#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
install_v25 — Pagina /v2/shows (calendario) refeita: minimalista, SEM SCROLL

- Calendario verificado (4 dias x 3 palcos x 4 shows = 48 actos)
- Tabs de dia (D1-D4). Desktop: 3 colunas dos palcos. Mobile: tabs de palco.
- Sem scroll: tudo em 100vh, overflow hidden, clamp() fluido.
- Inter, paleta v12, zero vermelho, zero vocabulario proibido.
- Headliner destacado (label + nome maiusculas verde escuro).
"""

import base64, os, shutil, subprocess, sys
from datetime import datetime
from pathlib import Path

os.environ["PATH"] = ":".join([
    "/usr/bin", "/bin", "/usr/sbin", "/sbin",
    "/usr/local/bin", "/opt/homebrew/bin",
    os.environ.get("PATH", ""),
])

SHOWS_B64 = (
    'J3VzZSBjbGllbnQnOwoKaW1wb3J0IHsgdXNlRWZmZWN0LCB1c2VTdGF0ZSB9IGZyb20gJ3JlYWN0'
    'JzsKCi8qIOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
    'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
    'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
    'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgAogICBDQUxFTkTDgVJJTyBWRVJJRklD'
    'QURPIMK3IFJvY2sgaW4gUmlvIExpc2JvYSAyMDI2IMK3IFBhcnF1ZSBUZWpvCiAgIOKUgOKUgOKU'
    'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
    'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
    'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
    'gOKUgOKUgOKUgOKUgOKUgOKUgCAqLwoKaW50ZXJmYWNlIFNob3cgewogIHRpbWU6IHN0cmluZzsK'
    'ICBhcnRpc3Q6IHN0cmluZzsKICBoZWFkbGluZXI/OiBib29sZWFuOwogIG5leHREYXk/OiBib29s'
    'ZWFuOyAvLyAwMTowMCBkbyBkaWEgc2VndWludGUKfQoKaW50ZXJmYWNlIERheSB7CiAgaWQ6IHN0'
    'cmluZzsKICBkYXRlOiBzdHJpbmc7ICAgICAgIC8vICdZWVlZLU1NLUREJwogIGRhdGVMYWJlbDog'
    'c3RyaW5nOyAgLy8gJzIwIEp1bmhvJwogIHdlZWtkYXk6IHN0cmluZzsKICB0aGVtZTogc3RyaW5n'
    'OwogIHN0YWdlczogewogICAgUE06IFNob3dbXTsKICAgIFBNVjogU2hvd1tdOwogICAgUFNCOiBT'
    'aG93W107CiAgfTsKfQoKY29uc3QgU1RBR0VfT1JERVIgPSBbJ1BNJywgJ1BNVicsICdQU0InXSBh'
    'cyBjb25zdDsKdHlwZSBTdGFnZUtleSA9ICh0eXBlb2YgU1RBR0VfT1JERVIpW251bWJlcl07Cgpj'
    'b25zdCBTVEFHRV9MQUJFTDogUmVjb3JkPFN0YWdlS2V5LCBzdHJpbmc+ID0gewogIFBNOiAnUGFs'
    'Y28gTXVuZG8nLAogIFBNVjogJ011c2ljIFZhbGxleScsCiAgUFNCOiAnU3VwZXIgQm9jaycsCn07'
    'Cgpjb25zdCBDQUxFTkRBUjogRGF5W10gPSBbCiAgewogICAgaWQ6ICdEMScsCiAgICBkYXRlOiAn'
    'MjAyNi0wNi0yMCcsCiAgICBkYXRlTGFiZWw6ICcyMCBKdW5obycsCiAgICB3ZWVrZGF5OiAnU8Oh'
    'YmFkbycsCiAgICB0aGVtZTogJ1BvcCDCtyBHbG9iYWwnLAogICAgc3RhZ2VzOiB7CiAgICAgIFBN'
    'OiBbCiAgICAgICAgeyB0aW1lOiAnMTc6MDAnLCBhcnRpc3Q6ICdDYWxlbWEnIH0sCiAgICAgICAg'
    'eyB0aW1lOiAnMTk6MDAnLCBhcnRpc3Q6ICdQZWRybyBTYW1wYWlvJyB9LAogICAgICAgIHsgdGlt'
    'ZTogJzIxOjE1JywgYXJ0aXN0OiAnQ2hhcmxpZSBQdXRoJyB9LAogICAgICAgIHsgdGltZTogJzIz'
    'OjE1JywgYXJ0aXN0OiAnS2F0eSBQZXJyeScsIGhlYWRsaW5lcjogdHJ1ZSB9LAogICAgICBdLAog'
    'ICAgICBQTVY6IFsKICAgICAgICB7IHRpbWU6ICcxODowMCcsIGFydGlzdDogJ01hbmluaG8nIH0s'
    'CiAgICAgICAgeyB0aW1lOiAnMjA6MTUnLCBhcnRpc3Q6ICdOZW5hJyB9LAogICAgICAgIHsgdGlt'
    'ZTogJzIyOjE1JywgYXJ0aXN0OiAnQXVkcmV5IE51bmEnIH0sCiAgICAgICAgeyB0aW1lOiAnMDE6'
    'MDAnLCBhcnRpc3Q6ICdBbG9rJywgaGVhZGxpbmVyOiB0cnVlLCBuZXh0RGF5OiB0cnVlIH0sCiAg'
    'ICAgIF0sCiAgICAgIFBTQjogWwogICAgICAgIHsgdGltZTogJzE2OjAwJywgYXJ0aXN0OiAnU29m'
    'aWEgQ2FtYXJhJyB9LAogICAgICAgIHsgdGltZTogJzE4OjAwJywgYXJ0aXN0OiAnTmFwYScgfSwK'
    'ICAgICAgICB7IHRpbWU6ICcyMDoxNScsIGFydGlzdDogJ0JlYmUgUmV4aGEnIH0sCiAgICAgICAg'
    'eyB0aW1lOiAnMjI6MTUnLCBhcnRpc3Q6ICdCw6FyYmFyYSBCYW5kZWlyYScsIGhlYWRsaW5lcjog'
    'dHJ1ZSB9LAogICAgICBdLAogICAgfSwKICB9LAogIHsKICAgIGlkOiAnRDInLAogICAgZGF0ZTog'
    'JzIwMjYtMDYtMjEnLAogICAgZGF0ZUxhYmVsOiAnMjEgSnVuaG8nLAogICAgd2Vla2RheTogJ0Rv'
    'bWluZ28nLAogICAgdGhlbWU6ICdSb2NrIMK3IFBlc2FkbycsCiAgICBzdGFnZXM6IHsKICAgICAg'
    'UE06IFsKICAgICAgICB7IHRpbWU6ICcxNzowMCcsIGFydGlzdDogJ0dyYW5kc29uJyB9LAogICAg'
    'ICAgIHsgdGltZTogJzE5OjAwJywgYXJ0aXN0OiAnVGhlIFByZXR0eSBSZWNrbGVzcycgfSwKICAg'
    'ICAgICB7IHRpbWU6ICcyMToxNScsIGFydGlzdDogJ0N5cHJlc3MgSGlsbCcgfSwKICAgICAgICB7'
    'IHRpbWU6ICcyMzoxNScsIGFydGlzdDogJ0xpbmtpbiBQYXJrJywgaGVhZGxpbmVyOiB0cnVlIH0s'
    'CiAgICAgIF0sCiAgICAgIFBNVjogWwogICAgICAgIHsgdGltZTogJzE2OjAwJywgYXJ0aXN0OiAn'
    'RGVhbGVtYScgfSwKICAgICAgICB7IHRpbWU6ICcxODowMCcsIGFydGlzdDogJ1NhbSB0aGUgS2lk'
    'ICsgT3JxdWVzdHJhICYgT3JlbGhhIE5lZ3JhJyB9LAogICAgICAgIHsgdGltZTogJzIwOjE1Jywg'
    'YXJ0aXN0OiAnUC5PLkQuJyB9LAogICAgICAgIHsgdGltZTogJzIyOjE1JywgYXJ0aXN0OiAnU2Vw'
    'dWx0dXJhJywgaGVhZGxpbmVyOiB0cnVlIH0sCiAgICAgIF0sCiAgICAgIFBTQjogWwogICAgICAg'
    'IHsgdGltZTogJzE2OjAwJywgYXJ0aXN0OiAnVGFyYSBQZXJkaWRhJyB9LAogICAgICAgIHsgdGlt'
    'ZTogJzE4OjAwJywgYXJ0aXN0OiAnQmxhc3RlZCBNZWNoYW5pc20nIH0sCiAgICAgICAgeyB0aW1l'
    'OiAnMjA6MTUnLCBhcnRpc3Q6ICdLYWlzZXIgQ2hpZWZzJyB9LAogICAgICAgIHsgdGltZTogJzIy'
    'OjE1JywgYXJ0aXN0OiAnSG9vYmFzdGFuaycsIGhlYWRsaW5lcjogdHJ1ZSB9LAogICAgICBdLAog'
    'ICAgfSwKICB9LAogIHsKICAgIGlkOiAnRDMnLAogICAgZGF0ZTogJzIwMjYtMDYtMjcnLAogICAg'
    'ZGF0ZUxhYmVsOiAnMjcgSnVuaG8nLAogICAgd2Vla2RheTogJ1PDoWJhZG8nLAogICAgdGhlbWU6'
    'ICdMZW5kYXMgwrcgQ2zDoXNzaWNvcycsCiAgICBzdGFnZXM6IHsKICAgICAgUE06IFsKICAgICAg'
    'ICB7IHRpbWU6ICcxNzowMCcsIGFydGlzdDogJzQgTm9uIEJsb25kZXMnIH0sCiAgICAgICAgeyB0'
    'aW1lOiAnMTk6MDAnLCBhcnRpc3Q6ICdTaGFnZ3knIH0sCiAgICAgICAgeyB0aW1lOiAnMjE6MTUn'
    'LCBhcnRpc3Q6ICdDeW5kaSBMYXVwZXInIH0sCiAgICAgICAgeyB0aW1lOiAnMjM6MTUnLCBhcnRp'
    'c3Q6ICdSb2QgU3Rld2FydCcsIGhlYWRsaW5lcjogdHJ1ZSB9LAogICAgICBdLAogICAgICBQTVY6'
    'IFsKICAgICAgICB7IHRpbWU6ICcxNjowMCcsIGFydGlzdDogJ0phZnVtZWdhJyB9LAogICAgICAg'
    'IHsgdGltZTogJzE4OjAwJywgYXJ0aXN0OiAnVUhGJyB9LAogICAgICAgIHsgdGltZTogJzIwOjE1'
    'JywgYXJ0aXN0OiAnR05SJyB9LAogICAgICAgIHsgdGltZTogJzIyOjE1JywgYXJ0aXN0OiAnWHV0'
    'b3MgJiBQb250YXDDqXMnLCBoZWFkbGluZXI6IHRydWUgfSwKICAgICAgXSwKICAgICAgUFNCOiBb'
    'CiAgICAgICAgeyB0aW1lOiAnMTU6MDAnLCBhcnRpc3Q6ICdTeXJvJyB9LAogICAgICAgIHsgdGlt'
    'ZTogJzE4OjAwJywgYXJ0aXN0OiAnVGhlIFdhaWxlcnMnIH0sCiAgICAgICAgeyB0aW1lOiAnMjA6'
    'MTUnLCBhcnRpc3Q6ICdKb3NzIFN0b25lJyB9LAogICAgICAgIHsgdGltZTogJzIyOjE1JywgYXJ0'
    'aXN0OiAnQmVsbycsIGhlYWRsaW5lcjogdHJ1ZSB9LAogICAgICBdLAogICAgfSwKICB9LAogIHsK'
    'ICAgIGlkOiAnRDQnLAogICAgZGF0ZTogJzIwMjYtMDYtMjgnLAogICAgZGF0ZUxhYmVsOiAnMjgg'
    'SnVuaG8nLAogICAgd2Vla2RheTogJ0RvbWluZ28nLAogICAgdGhlbWU6ICdVcmJhbm8gwrcgSGlw'
    'LUhvcCcsCiAgICBzdGFnZXM6IHsKICAgICAgUE06IFsKICAgICAgICB7IHRpbWU6ICcxNzowMCcs'
    'IGFydGlzdDogJ01hdHXDqicgfSwKICAgICAgICB7IHRpbWU6ICcxOTowMCcsIGFydGlzdDogJ1Jl'
    'bWEnIH0sCiAgICAgICAgeyB0aW1lOiAnMjE6MTUnLCBhcnRpc3Q6ICdDZW50cmFsIENlZScgfSwK'
    'ICAgICAgICB7IHRpbWU6ICcyMzoxNScsIGFydGlzdDogJzIxIFNhdmFnZScsIGhlYWRsaW5lcjog'
    'dHJ1ZSB9LAogICAgICBdLAogICAgICBQTVY6IFsKICAgICAgICB7IHRpbWU6ICcxODowMCcsIGFy'
    'dGlzdDogJ0lyaW5hIEJhcnJvcycgfSwKICAgICAgICB7IHRpbWU6ICcyMDoxNScsIGFydGlzdDog'
    'J0NhcmzDo28nIH0sCiAgICAgICAgeyB0aW1lOiAnMjI6MTUnLCBhcnRpc3Q6ICdGaWxpcGUgUmV0'
    'JyB9LAogICAgICAgIHsgdGltZTogJzAxOjAwJywgYXJ0aXN0OiAnRGVubmlzJywgaGVhZGxpbmVy'
    'OiB0cnVlLCBuZXh0RGF5OiB0cnVlIH0sCiAgICAgIF0sCiAgICAgIFBTQjogWwogICAgICAgIHsg'
    'dGltZTogJzE2OjAwJywgYXJ0aXN0OiAnS2FyZXR1cycgfSwKICAgICAgICB7IHRpbWU6ICcxODow'
    'MCcsIGFydGlzdDogJ1ZhbGV0ZScgfSwKICAgICAgICB7IHRpbWU6ICcyMDoxNScsIGFydGlzdDog'
    'J0xvbGEgw41uZGlnbycgfSwKICAgICAgICB7IHRpbWU6ICcyMjoxNScsIGFydGlzdDogJ0NlZUxv'
    'IEdyZWVuJywgaGVhZGxpbmVyOiB0cnVlIH0sCiAgICAgIF0sCiAgICB9LAogIH0sCl07CgovKiBE'
    'aWEgaW5pY2lhbDogbyBwcmltZWlybyBkaWEgPj0gaG9qZSwgc2Vuw6NvIG8gcHJpbWVpcm8uICov'
    'CmZ1bmN0aW9uIGluaXRpYWxEYXlJbmRleCgpOiBudW1iZXIgewogIGNvbnN0IHRvZGF5ID0gbmV3'
    'IERhdGUoKS50b0lTT1N0cmluZygpLnNsaWNlKDAsIDEwKTsKICBjb25zdCBpZHggPSBDQUxFTkRB'
    'Ui5maW5kSW5kZXgoKGQpID0+IGQuZGF0ZSA+PSB0b2RheSk7CiAgcmV0dXJuIGlkeCA9PT0gLTEg'
    'PyAwIDogaWR4Owp9CgpleHBvcnQgZGVmYXVsdCBmdW5jdGlvbiBTaG93c1BhZ2UoKSB7CiAgY29u'
    'c3QgW2RheUlkeCwgc2V0RGF5SWR4XSA9IHVzZVN0YXRlKDApOwogIGNvbnN0IFtzdGFnZUlkeCwg'
    'c2V0U3RhZ2VJZHhdID0gdXNlU3RhdGUoMCk7IC8vIHPDsyB1c2FkbyBlbSBtb2JpbGUKCiAgdXNl'
    'RWZmZWN0KCgpID0+IHsKICAgIHNldERheUlkeChpbml0aWFsRGF5SW5kZXgoKSk7CiAgfSwgW10p'
    'OwoKICBjb25zdCBkYXkgPSBDQUxFTkRBUltkYXlJZHhdOwogIGNvbnN0IG1vYmlsZVN0YWdlID0g'
    'U1RBR0VfT1JERVJbc3RhZ2VJZHhdOwoKICByZXR1cm4gKAogICAgPGRpdiBjbGFzc05hbWU9InNo'
    'b3dzLXJvb3QiPgogICAgICB7LyogQ2FiZcOnYWxobzogdGFicyBkZSBkaWEgKyB0ZW1hICovfQog'
    'ICAgICA8aGVhZGVyIGNsYXNzTmFtZT0ic2hvd3MtaGVhZGVyIj4KICAgICAgICA8ZGl2IGNsYXNz'
    'TmFtZT0ic2hvd3MtaGVhZC1yb3ciPgogICAgICAgICAgPGRpdj4KICAgICAgICAgICAgPGRpdiBj'
    'bGFzc05hbWU9InNob3dzLWV5ZWJyb3ciPlByb2dyYW1hIMK3IFJvY2sgaW4gUmlvIExpc2JvYSAy'
    'MDI2PC9kaXY+CiAgICAgICAgICAgIDxoMSBjbGFzc05hbWU9InNob3dzLXRpdGxlIj4KICAgICAg'
    'ICAgICAgICB7ZGF5LndlZWtkYXl9LCB7ZGF5LmRhdGVMYWJlbH0KICAgICAgICAgICAgPC9oMT4K'
    'ICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9InNob3dzLXRoZW1lIj57ZGF5LnRoZW1lfTwvZGl2'
    'PgogICAgICAgICAgPC9kaXY+CgogICAgICAgICAgPG5hdiBjbGFzc05hbWU9InNob3dzLWRheXRh'
    'YnMiIGFyaWEtbGFiZWw9IkRpYXMiPgogICAgICAgICAgICB7Q0FMRU5EQVIubWFwKChkLCBpKSA9'
    'PiAoCiAgICAgICAgICAgICAgPGJ1dHRvbgogICAgICAgICAgICAgICAga2V5PXtkLmlkfQogICAg'
    'ICAgICAgICAgICAgY2xhc3NOYW1lPXtgc2hvd3MtZGF5dGFiICR7aSA9PT0gZGF5SWR4ID8gJ2lz'
    'LWFjdGl2ZScgOiAnJ31gfQogICAgICAgICAgICAgICAgb25DbGljaz17KCkgPT4gc2V0RGF5SWR4'
    'KGkpfQogICAgICAgICAgICAgID4KICAgICAgICAgICAgICAgIDxzcGFuIGNsYXNzTmFtZT0ic2hv'
    'd3MtZGF5dGFiLWlkIj57ZC5pZH08L3NwYW4+CiAgICAgICAgICAgICAgICA8c3BhbiBjbGFzc05h'
    'bWU9InNob3dzLWRheXRhYi1kYXRlIj57ZC5kYXRlTGFiZWx9PC9zcGFuPgogICAgICAgICAgICAg'
    'IDwvYnV0dG9uPgogICAgICAgICAgICApKX0KICAgICAgICAgIDwvbmF2PgogICAgICAgIDwvZGl2'
    'PgoKICAgICAgICB7LyogVGFicyBkZSBwYWxjbyDigJQgc8OzIHZpc8OtdmVpcyBlbSBtb2JpbGUg'
    'Ki99CiAgICAgICAgPG5hdiBjbGFzc05hbWU9InNob3dzLXN0YWdldGFicyIgYXJpYS1sYWJlbD0i'
    'UGFsY29zIj4KICAgICAgICAgIHtTVEFHRV9PUkRFUi5tYXAoKHMsIGkpID0+ICgKICAgICAgICAg'
    'ICAgPGJ1dHRvbgogICAgICAgICAgICAgIGtleT17c30KICAgICAgICAgICAgICBjbGFzc05hbWU9'
    'e2BzaG93cy1zdGFnZXRhYiAke2kgPT09IHN0YWdlSWR4ID8gJ2lzLWFjdGl2ZScgOiAnJ31gfQog'
    'ICAgICAgICAgICAgIG9uQ2xpY2s9eygpID0+IHNldFN0YWdlSWR4KGkpfQogICAgICAgICAgICA+'
    'CiAgICAgICAgICAgICAge1NUQUdFX0xBQkVMW3NdfQogICAgICAgICAgICA8L2J1dHRvbj4KICAg'
    'ICAgICAgICkpfQogICAgICAgIDwvbmF2PgogICAgICA8L2hlYWRlcj4KCiAgICAgIHsvKiBHcmVs'
    'aGEgZG9zIDMgcGFsY29zICovfQogICAgICA8ZGl2IGNsYXNzTmFtZT0ic2hvd3MtZ3JpZCI+CiAg'
    'ICAgICAge1NUQUdFX09SREVSLm1hcCgoc3RhZ2UpID0+ICgKICAgICAgICAgIDxzZWN0aW9uCiAg'
    'ICAgICAgICAgIGtleT17c3RhZ2V9CiAgICAgICAgICAgIGNsYXNzTmFtZT17YHNob3dzLWNvbCAk'
    'e3N0YWdlID09PSBtb2JpbGVTdGFnZSA/ICdpcy1tb2JpbGUtYWN0aXZlJyA6ICcnfWB9CiAgICAg'
    'ICAgICAgIGFyaWEtbGFiZWw9e1NUQUdFX0xBQkVMW3N0YWdlXX0KICAgICAgICAgID4KICAgICAg'
    'ICAgICAgPGRpdiBjbGFzc05hbWU9InNob3dzLWNvbC1oZWFkIj57U1RBR0VfTEFCRUxbc3RhZ2Vd'
    'fTwvZGl2PgogICAgICAgICAgICA8b2wgY2xhc3NOYW1lPSJzaG93cy1saXN0Ij4KICAgICAgICAg'
    'ICAgICB7ZGF5LnN0YWdlc1tzdGFnZV0ubWFwKChzaG93LCBpKSA9PiAoCiAgICAgICAgICAgICAg'
    'ICA8bGkKICAgICAgICAgICAgICAgICAga2V5PXtgJHtzdGFnZX0tJHtpfWB9CiAgICAgICAgICAg'
    'ICAgICAgIGNsYXNzTmFtZT17YHNob3dzLWl0ZW0gJHtzaG93LmhlYWRsaW5lciA/ICdpcy1oZWFk'
    'bGluZXInIDogJyd9YH0KICAgICAgICAgICAgICAgID4KICAgICAgICAgICAgICAgICAgPGRpdiBj'
    'bGFzc05hbWU9InNob3dzLXRpbWUiPgogICAgICAgICAgICAgICAgICAgIHtzaG93LnRpbWV9CiAg'
    'ICAgICAgICAgICAgICAgICAge3Nob3cubmV4dERheSAmJiA8c3BhbiBjbGFzc05hbWU9InNob3dz'
    'LW5leHRkYXkiPisxPC9zcGFuPn0KICAgICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAg'
    'ICAgICAgIHtzaG93LmhlYWRsaW5lciAmJiA8ZGl2IGNsYXNzTmFtZT0ic2hvd3MtaGwtbGFiZWwi'
    'PkhlYWRsaW5lcjwvZGl2Pn0KICAgICAgICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9InNob3dz'
    'LWFydGlzdCI+e3Nob3cuYXJ0aXN0fTwvZGl2PgogICAgICAgICAgICAgICAgPC9saT4KICAgICAg'
    'ICAgICAgICApKX0KICAgICAgICAgICAgPC9vbD4KICAgICAgICAgIDwvc2VjdGlvbj4KICAgICAg'
    'ICApKX0KICAgICAgPC9kaXY+CgogICAgICA8c3R5bGUganN4PntgCiAgICAgICAgLnNob3dzLXJv'
    'b3QgewogICAgICAgICAgcG9zaXRpb246IGZpeGVkOwogICAgICAgICAgdG9wOiB2YXIoLS10b3Bi'
    'YXItaCwgNzJweCk7CiAgICAgICAgICBsZWZ0OiAwOwogICAgICAgICAgcmlnaHQ6IDA7CiAgICAg'
    'ICAgICBib3R0b206IDA7CiAgICAgICAgICBkaXNwbGF5OiBmbGV4OwogICAgICAgICAgZmxleC1k'
    'aXJlY3Rpb246IGNvbHVtbjsKICAgICAgICAgIGJhY2tncm91bmQ6ICNmZmZmZmY7CiAgICAgICAg'
    'ICBvdmVyZmxvdzogaGlkZGVuOwogICAgICAgICAgY29sb3I6ICMwZDFhMGY7CiAgICAgICAgfQoK'
    'ICAgICAgICAvKiDilIDilIAgSGVhZGVyIOKUgOKUgCAqLwogICAgICAgIC5zaG93cy1oZWFkZXIg'
    'ewogICAgICAgICAgZmxleC1zaHJpbms6IDA7CiAgICAgICAgICBwYWRkaW5nOiBjbGFtcCgxNnB4'
    'LCAyLjR2dywgMzBweCkgY2xhbXAoMThweCwgNHZ3LCA1NnB4KSBjbGFtcCgxMHB4LCAxLjR2dywg'
    'MThweCk7CiAgICAgICAgICBib3JkZXItYm90dG9tOiAxcHggc29saWQgI2VjZTdkNjsKICAgICAg'
    'ICB9CiAgICAgICAgLnNob3dzLWhlYWQtcm93IHsKICAgICAgICAgIGRpc3BsYXk6IGZsZXg7CiAg'
    'ICAgICAgICBqdXN0aWZ5LWNvbnRlbnQ6IHNwYWNlLWJldHdlZW47CiAgICAgICAgICBhbGlnbi1p'
    'dGVtczogZmxleC1zdGFydDsKICAgICAgICAgIGdhcDogMjBweDsKICAgICAgICAgIGZsZXgtd3Jh'
    'cDogd3JhcDsKICAgICAgICB9CiAgICAgICAgLnNob3dzLWV5ZWJyb3cgewogICAgICAgICAgZm9u'
    'dC1zaXplOiAxMHB4OwogICAgICAgICAgZm9udC13ZWlnaHQ6IDUwMDsKICAgICAgICAgIGxldHRl'
    'ci1zcGFjaW5nOiAwLjE2ZW07CiAgICAgICAgICB0ZXh0LXRyYW5zZm9ybTogdXBwZXJjYXNlOwog'
    'ICAgICAgICAgY29sb3I6ICNhNGE4OWM7CiAgICAgICAgfQogICAgICAgIC5zaG93cy10aXRsZSB7'
    'CiAgICAgICAgICBmb250LXNpemU6IGNsYW1wKDI2cHgsIDMuNnZ3LCA1MnB4KTsKICAgICAgICAg'
    'IGZvbnQtd2VpZ2h0OiAyMDA7CiAgICAgICAgICBsZXR0ZXItc3BhY2luZzogLTAuMDM1ZW07CiAg'
    'ICAgICAgICBsaW5lLWhlaWdodDogMTsKICAgICAgICAgIG1hcmdpbjogNnB4IDAgNHB4OwogICAg'
    'ICAgICAgY29sb3I6ICMwZDFhMGY7CiAgICAgICAgfQogICAgICAgIC5zaG93cy10aGVtZSB7CiAg'
    'ICAgICAgICBmb250LXNpemU6IGNsYW1wKDEzcHgsIDEuM3Z3LCAxNnB4KTsKICAgICAgICAgIGZv'
    'bnQtd2VpZ2h0OiA1MDA7CiAgICAgICAgICBjb2xvcjogIzRhN2M1OTsKICAgICAgICAgIGxldHRl'
    'ci1zcGFjaW5nOiAwLjAxZW07CiAgICAgICAgfQoKICAgICAgICAuc2hvd3MtZGF5dGFicyB7CiAg'
    'ICAgICAgICBkaXNwbGF5OiBmbGV4OwogICAgICAgICAgZ2FwOiA2cHg7CiAgICAgICAgfQogICAg'
    'ICAgIC5zaG93cy1kYXl0YWIgewogICAgICAgICAgZGlzcGxheTogZmxleDsKICAgICAgICAgIGZs'
    'ZXgtZGlyZWN0aW9uOiBjb2x1bW47CiAgICAgICAgICBhbGlnbi1pdGVtczogY2VudGVyOwogICAg'
    'ICAgICAgZ2FwOiAycHg7CiAgICAgICAgICBiYWNrZ3JvdW5kOiB0cmFuc3BhcmVudDsKICAgICAg'
    'ICAgIGJvcmRlcjogMXB4IHNvbGlkICNlY2U3ZDY7CiAgICAgICAgICBib3JkZXItcmFkaXVzOiAx'
    'MnB4OwogICAgICAgICAgcGFkZGluZzogY2xhbXAoOHB4LCAxdncsIDEycHgpIGNsYW1wKDEwcHgs'
    'IDEuNHZ3LCAxOHB4KTsKICAgICAgICAgIGN1cnNvcjogcG9pbnRlcjsKICAgICAgICAgIHRyYW5z'
    'aXRpb246IGJhY2tncm91bmQgMC4xNnMsIGJvcmRlci1jb2xvciAwLjE2cywgY29sb3IgMC4xNnM7'
    'CiAgICAgICAgICBmb250LWZhbWlseTogaW5oZXJpdDsKICAgICAgICAgIGNvbG9yOiAjMGQxYTBm'
    'OwogICAgICAgIH0KICAgICAgICAuc2hvd3MtZGF5dGFiOmhvdmVyIHsKICAgICAgICAgIGJvcmRl'
    'ci1jb2xvcjogIzRhN2M1OTsKICAgICAgICB9CiAgICAgICAgLnNob3dzLWRheXRhYi5pcy1hY3Rp'
    'dmUgewogICAgICAgICAgYmFja2dyb3VuZDogIzFiM2EyMTsKICAgICAgICAgIGJvcmRlci1jb2xv'
    'cjogIzFiM2EyMTsKICAgICAgICAgIGNvbG9yOiAjZmZmZmZmOwogICAgICAgIH0KICAgICAgICAu'
    'c2hvd3MtZGF5dGFiLWlkIHsKICAgICAgICAgIGZvbnQtc2l6ZTogY2xhbXAoMTNweCwgMS4ydncs'
    'IDE2cHgpOwogICAgICAgICAgZm9udC13ZWlnaHQ6IDYwMDsKICAgICAgICAgIGxldHRlci1zcGFj'
    'aW5nOiAtMC4wMWVtOwogICAgICAgIH0KICAgICAgICAuc2hvd3MtZGF5dGFiLWRhdGUgewogICAg'
    'ICAgICAgZm9udC1zaXplOiAxMHB4OwogICAgICAgICAgZm9udC13ZWlnaHQ6IDUwMDsKICAgICAg'
    'ICAgIGxldHRlci1zcGFjaW5nOiAwLjA0ZW07CiAgICAgICAgICBvcGFjaXR5OiAwLjc7CiAgICAg'
    'ICAgfQoKICAgICAgICAuc2hvd3Mtc3RhZ2V0YWJzIHsKICAgICAgICAgIGRpc3BsYXk6IG5vbmU7'
    'CiAgICAgICAgICBnYXA6IDZweDsKICAgICAgICAgIG1hcmdpbi10b3A6IDE0cHg7CiAgICAgICAg'
    'fQogICAgICAgIC5zaG93cy1zdGFnZXRhYiB7CiAgICAgICAgICBmbGV4OiAxOwogICAgICAgICAg'
    'YmFja2dyb3VuZDogdHJhbnNwYXJlbnQ7CiAgICAgICAgICBib3JkZXI6IDFweCBzb2xpZCAjZWNl'
    'N2Q2OwogICAgICAgICAgYm9yZGVyLXJhZGl1czogMTBweDsKICAgICAgICAgIHBhZGRpbmc6IDlw'
    'eCA4cHg7CiAgICAgICAgICBmb250LXNpemU6IDEycHg7CiAgICAgICAgICBmb250LXdlaWdodDog'
    'NTAwOwogICAgICAgICAgbGV0dGVyLXNwYWNpbmc6IDAuMDRlbTsKICAgICAgICAgIGN1cnNvcjog'
    'cG9pbnRlcjsKICAgICAgICAgIGZvbnQtZmFtaWx5OiBpbmhlcml0OwogICAgICAgICAgY29sb3I6'
    'ICMwZDFhMGY7CiAgICAgICAgICB0cmFuc2l0aW9uOiBiYWNrZ3JvdW5kIDAuMTZzLCBib3JkZXIt'
    'Y29sb3IgMC4xNnMsIGNvbG9yIDAuMTZzOwogICAgICAgIH0KICAgICAgICAuc2hvd3Mtc3RhZ2V0'
    'YWIuaXMtYWN0aXZlIHsKICAgICAgICAgIGJhY2tncm91bmQ6ICMxYjNhMjE7CiAgICAgICAgICBi'
    'b3JkZXItY29sb3I6ICMxYjNhMjE7CiAgICAgICAgICBjb2xvcjogI2ZmZmZmZjsKICAgICAgICB9'
    'CgogICAgICAgIC8qIOKUgOKUgCBHcmVsaGEg4pSA4pSAICovCiAgICAgICAgLnNob3dzLWdyaWQg'
    'ewogICAgICAgICAgZmxleDogMTsKICAgICAgICAgIG1pbi1oZWlnaHQ6IDA7CiAgICAgICAgICBk'
    'aXNwbGF5OiBncmlkOwogICAgICAgICAgZ3JpZC10ZW1wbGF0ZS1jb2x1bW5zOiByZXBlYXQoMywg'
    'MWZyKTsKICAgICAgICAgIGdhcDogMXB4OwogICAgICAgICAgYmFja2dyb3VuZDogI2VjZTdkNjsK'
    'ICAgICAgICB9CiAgICAgICAgLnNob3dzLWNvbCB7CiAgICAgICAgICBiYWNrZ3JvdW5kOiAjZmZm'
    'ZmZmOwogICAgICAgICAgcGFkZGluZzogY2xhbXAoMTRweCwgMS44dncsIDI2cHgpIGNsYW1wKDE2'
    'cHgsIDIuMnZ3LCAzNnB4KTsKICAgICAgICAgIGRpc3BsYXk6IGZsZXg7CiAgICAgICAgICBmbGV4'
    'LWRpcmVjdGlvbjogY29sdW1uOwogICAgICAgICAgbWluLWhlaWdodDogMDsKICAgICAgICAgIG92'
    'ZXJmbG93OiBoaWRkZW47CiAgICAgICAgfQogICAgICAgIC5zaG93cy1jb2wtaGVhZCB7CiAgICAg'
    'ICAgICBmb250LXNpemU6IDExcHg7CiAgICAgICAgICBmb250LXdlaWdodDogNjAwOwogICAgICAg'
    'ICAgbGV0dGVyLXNwYWNpbmc6IDAuMTRlbTsKICAgICAgICAgIHRleHQtdHJhbnNmb3JtOiB1cHBl'
    'cmNhc2U7CiAgICAgICAgICBjb2xvcjogI2E0YTg5YzsKICAgICAgICAgIHBhZGRpbmctYm90dG9t'
    'OiBjbGFtcCgxMHB4LCAxLjR2dywgMThweCk7CiAgICAgICAgICBtYXJnaW4tYm90dG9tOiBjbGFt'
    'cCg4cHgsIDEuMnZ3LCAxNnB4KTsKICAgICAgICAgIGJvcmRlci1ib3R0b206IDFweCBzb2xpZCAj'
    'ZWNlN2Q2OwogICAgICAgICAgZmxleC1zaHJpbms6IDA7CiAgICAgICAgfQogICAgICAgIC5zaG93'
    'cy1saXN0IHsKICAgICAgICAgIGxpc3Qtc3R5bGU6IG5vbmU7CiAgICAgICAgICBtYXJnaW46IDA7'
    'CiAgICAgICAgICBwYWRkaW5nOiAwOwogICAgICAgICAgZmxleDogMTsKICAgICAgICAgIGRpc3Bs'
    'YXk6IGZsZXg7CiAgICAgICAgICBmbGV4LWRpcmVjdGlvbjogY29sdW1uOwogICAgICAgICAganVz'
    'dGlmeS1jb250ZW50OiBzcGFjZS1iZXR3ZWVuOwogICAgICAgICAgbWluLWhlaWdodDogMDsKICAg'
    'ICAgICB9CiAgICAgICAgLnNob3dzLWl0ZW0gewogICAgICAgICAgcGFkZGluZzogY2xhbXAoNHB4'
    'LCAwLjZ2dywgOHB4KSAwOwogICAgICAgIH0KICAgICAgICAuc2hvd3MtdGltZSB7CiAgICAgICAg'
    'ICBmb250LXNpemU6IGNsYW1wKDEycHgsIDF2dywgMTRweCk7CiAgICAgICAgICBmb250LXdlaWdo'
    'dDogNTAwOwogICAgICAgICAgY29sb3I6ICNhNGE4OWM7CiAgICAgICAgICBmb250LXZhcmlhbnQt'
    'bnVtZXJpYzogdGFidWxhci1udW1zOwogICAgICAgICAgZm9udC1mZWF0dXJlLXNldHRpbmdzOiAn'
    'dG51bSc7CiAgICAgICAgICBsZXR0ZXItc3BhY2luZzogMC4wMmVtOwogICAgICAgICAgZGlzcGxh'
    'eTogZmxleDsKICAgICAgICAgIGFsaWduLWl0ZW1zOiBiYXNlbGluZTsKICAgICAgICAgIGdhcDog'
    'NnB4OwogICAgICAgIH0KICAgICAgICAuc2hvd3MtbmV4dGRheSB7CiAgICAgICAgICBmb250LXNp'
    'emU6IDlweDsKICAgICAgICAgIGZvbnQtd2VpZ2h0OiA2MDA7CiAgICAgICAgICBsZXR0ZXItc3Bh'
    'Y2luZzogMC4wOGVtOwogICAgICAgICAgY29sb3I6ICNjOWE5NjE7CiAgICAgICAgICBib3JkZXI6'
    'IDFweCBzb2xpZCAjYzlhOTYxOwogICAgICAgICAgYm9yZGVyLXJhZGl1czogNHB4OwogICAgICAg'
    'ICAgcGFkZGluZzogMCA0cHg7CiAgICAgICAgICBsaW5lLWhlaWdodDogMS40OwogICAgICAgIH0K'
    'ICAgICAgICAuc2hvd3MtaGwtbGFiZWwgewogICAgICAgICAgZm9udC1zaXplOiA5cHg7CiAgICAg'
    'ICAgICBmb250LXdlaWdodDogNjAwOwogICAgICAgICAgbGV0dGVyLXNwYWNpbmc6IDAuMTZlbTsK'
    'ICAgICAgICAgIHRleHQtdHJhbnNmb3JtOiB1cHBlcmNhc2U7CiAgICAgICAgICBjb2xvcjogIzRh'
    'N2M1OTsKICAgICAgICAgIG1hcmdpbi10b3A6IDRweDsKICAgICAgICB9CiAgICAgICAgLnNob3dz'
    'LWFydGlzdCB7CiAgICAgICAgICBmb250LXNpemU6IGNsYW1wKDE1cHgsIDEuNXZ3LCAyMnB4KTsK'
    'ICAgICAgICAgIGZvbnQtd2VpZ2h0OiA0MDA7CiAgICAgICAgICBsZXR0ZXItc3BhY2luZzogLTAu'
    'MDE1ZW07CiAgICAgICAgICBsaW5lLWhlaWdodDogMS4xNTsKICAgICAgICAgIGNvbG9yOiAjMGQx'
    'YTBmOwogICAgICAgICAgbWFyZ2luLXRvcDogM3B4OwogICAgICAgIH0KICAgICAgICAuc2hvd3Mt'
    'aXRlbS5pcy1oZWFkbGluZXIgLnNob3dzLWFydGlzdCB7CiAgICAgICAgICBmb250LXNpemU6IGNs'
    'YW1wKDIwcHgsIDIuMnZ3LCAzNHB4KTsKICAgICAgICAgIGZvbnQtd2VpZ2h0OiA2MDA7CiAgICAg'
    'ICAgICBsZXR0ZXItc3BhY2luZzogLTAuMDI1ZW07CiAgICAgICAgICB0ZXh0LXRyYW5zZm9ybTog'
    'dXBwZXJjYXNlOwogICAgICAgICAgY29sb3I6ICMxYjNhMjE7CiAgICAgICAgfQoKICAgICAgICAv'
    'KiDilIDilIAgTW9iaWxlOiAxIHBhbGNvIGRlIGNhZGEgdmV6IOKUgOKUgCAqLwogICAgICAgIEBt'
    'ZWRpYSAobWF4LXdpZHRoOiA3NjBweCkgewogICAgICAgICAgLnNob3dzLXN0YWdldGFicyB7CiAg'
    'ICAgICAgICAgIGRpc3BsYXk6IGZsZXg7CiAgICAgICAgICB9CiAgICAgICAgICAuc2hvd3MtZ3Jp'
    'ZCB7CiAgICAgICAgICAgIGdyaWQtdGVtcGxhdGUtY29sdW1uczogMWZyOwogICAgICAgICAgICBn'
    'YXA6IDA7CiAgICAgICAgICAgIGJhY2tncm91bmQ6ICNmZmZmZmY7CiAgICAgICAgICB9CiAgICAg'
    'ICAgICAuc2hvd3MtY29sIHsKICAgICAgICAgICAgZGlzcGxheTogbm9uZTsKICAgICAgICAgIH0K'
    'ICAgICAgICAgIC5zaG93cy1jb2wuaXMtbW9iaWxlLWFjdGl2ZSB7CiAgICAgICAgICAgIGRpc3Bs'
    'YXk6IGZsZXg7CiAgICAgICAgICB9CiAgICAgICAgICAuc2hvd3MtZGF5dGFiLWRhdGUgewogICAg'
    'ICAgICAgICBkaXNwbGF5OiBub25lOwogICAgICAgICAgfQogICAgICAgIH0KICAgICAgYH08L3N0'
    'eWxlPgogICAgPC9kaXY+CiAgKTsKfQo='
)


def run(cmd, cwd=None):
    print(f"$ {cmd}")
    r = subprocess.run(cmd, shell=True, cwd=cwd, capture_output=True, text=True)
    if r.stdout.strip(): print(r.stdout.rstrip())
    if r.stderr.strip(): print(r.stderr.rstrip(), file=sys.stderr)
    return r.returncode == 0


def main():
    root = Path.cwd()
    if not (root / "frontend").exists():
        print("ERRO: corre a partir de ~/planta_rock4")
        sys.exit(1)
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    shows = root / "frontend" / "app" / "v2" / "shows" / "page.tsx"
    shows.parent.mkdir(parents=True, exist_ok=True)
    if shows.exists():
        shutil.copy2(shows, shows.with_suffix(f".tsx.bak.v25.{stamp}"))
    d = base64.b64decode("".join(SHOWS_B64))
    shows.write_bytes(d)
    print(f"  OK frontend/app/v2/shows/page.tsx v25 ({len(d)} B)")

    run("git add frontend/app/v2/shows/page.tsx", cwd=str(root))
    run('git commit -m "feat(v25): pagina /shows calendario minimalista sem scroll (calendario verificado)"', cwd=str(root))
    run("git push", cwd=str(root))

    print()
    print("=" * 68)
    print("  PRONTO")
    print("=" * 68)
    print()
    print("  Aguarda ~90s e CMD+SHIFT+R em www.plantarockinrio.com/v2/shows")
    print()
    print("  - Tabs D1-D4 no topo. Clica para mudar de dia.")
    print("  - 3 colunas: Palco Mundo · Music Valley · Super Bock.")
    print("  - Headliner destacado (label + nome maiusculas).")
    print("  - SEM scroll. Tudo em 100vh.")
    print("  - Mobile: tabs de palco extra, 1 palco de cada vez.")


if __name__ == "__main__":
    main()
