#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
install_v18 — Singleton SSE provider + favicon Next.js convention + backend jitter
"""

import base64, os, re, shutil, subprocess, sys
from datetime import datetime
from pathlib import Path

os.environ["PATH"] = ":".join([
    "/usr/bin", "/bin", "/usr/sbin", "/sbin",
    "/usr/local/bin", "/opt/homebrew/bin",
    os.environ.get("PATH", ""),
])

FILES = {
    'frontend/components/v2/LiveContext.tsx': (
        'J3VzZSBjbGllbnQnOwoKLyoqCiAqIExpdmVDb250ZXh0IOKAlCBTSU5HTEUgU09VUkNFIE9GIFRS'
        'VVRIIHBhcmEgZGFkb3MgYW8gdml2byBkbyBQbGFudGFPUy4KICoKICogVU1BIGNvbmV4w6NvIFNT'
        'RSBwYXJhIHRvZG8gbyAvdjIuIFRvZGFzIGFzIHDDoWdpbmFzL2NvbXBvbmVudGVzIGNvbnNvbWVt'
        'CiAqIHZpYSB1c2VMaXZlKCkuIE1lc21vcyBuw7ptZXJvcyBlbSB0b2RvIG8gbGFkbywgc2VtcHJl'
        'LgogKgogKiBFbmRwb2ludDogR0VUIC9hcGkvdjEvdGVsZW1ldHJ5L2NsdXN0ZXJzL3N0cmVhbQog'
        'KiBQYXlsb2FkIChhIGNhZGEgc2VndW5kbyk6CiAqICAgeyBjbHVzdGVyczogWy4uLl0sIGtwaXM6'
        'IHtrcGlfMDEuLmtwaV8wNH0sIGNsdXN0ZXJfY291bnQsIGV4cGVjdGVkX2NsdXN0ZXJzIH0KICoK'
        'ICogRmFsbGJhY2s6IHNlIG8gRXZlbnRTb3VyY2UgY2FpciwgZmF6IHBvbGxpbmcgYSBjYWRhIDJz'
        'LgogKi8KCmltcG9ydCB7CiAgY3JlYXRlQ29udGV4dCwKICB1c2VDYWxsYmFjaywKICB1c2VDb250'
        'ZXh0LAogIHVzZUVmZmVjdCwKICB1c2VSZWYsCiAgdXNlU3RhdGUsCiAgdHlwZSBSZWFjdE5vZGUs'
        'Cn0gZnJvbSAncmVhY3QnOwoKY29uc3QgQVBJX0JBU0UgPQogIHByb2Nlc3MuZW52Lk5FWFRfUFVC'
        'TElDX0FQSV9CQVNFIHx8ICdodHRwczovL2FwaS5wbGFudGFyb2NraW5yaW8uY29tJzsKCmNvbnN0'
        'IFNUUkVBTV9VUkwgPSBgJHtBUElfQkFTRX0vYXBpL3YxL3RlbGVtZXRyeS9jbHVzdGVycy9zdHJl'
        'YW1gOwpjb25zdCBTTkFQU0hPVF9VUkwgPSBgJHtBUElfQkFTRX0vYXBpL3YxL3RlbGVtZXRyeS9j'
        'bHVzdGVycy9ub3dgOwpjb25zdCBQT0xMX0lOVEVSVkFMX01TID0gMjAwMDsKY29uc3QgUkVDT05O'
        'RUNUX0JBQ0tPRkZfTVMgPSBbMTAwMCwgMjAwMCwgNDAwMCwgODAwMF07CgpleHBvcnQgaW50ZXJm'
        'YWNlIENsdXN0ZXJQYXJhbXMgewogIHRlbGVtb3ZlaXNfZGV0ZWN0YWRvczogbnVtYmVyOwogIHBl'
        'c3NvYXNfZXN0aW1hZGFzOiBudW1iZXI7CiAgaG9tZW5zOiBudW1iZXIgfCBudWxsOwogIG11bGhl'
        'cmVzOiBudW1iZXIgfCBudWxsOwogIGVudHJhZGFzX2lyOiBudW1iZXI7CiAgc2FpZGFzX2lyOiBu'
        'dW1iZXI7CiAgb2N1cGFjYW9faW5zdGFudGFuZWE6IG51bWJlcjsKICBjb250YWdlbV9wcm9zZWd1'
        'cjogbnVtYmVyOwogIGNvbmZpYW5jYV9jcnV6YWRhOiBudW1iZXI7CiAgZXN0YWRvX3NlbnNvcjog'
        'c3RyaW5nOwogIGZpbGFfYXR1YWw6IG51bWJlcjsKICB0ZW1wb19lc3BlcmFfbWluOiBudW1iZXI7'
        'CiAgaXNfdW5pc3NleDogYm9vbGVhbjsKICBjYXBhY2lkYWRlX3RvdGFsOiBudW1iZXI7Cn0KCmV4'
        'cG9ydCBpbnRlcmZhY2UgQ2x1c3RlclBheWxvYWQgewogIGNsdXN0ZXJfaWQ6IHN0cmluZzsKICB0'
        'czogbnVtYmVyOwogIHBhcmFtczogQ2x1c3RlclBhcmFtczsKfQoKZXhwb3J0IGludGVyZmFjZSBL'
        'cGlzIHsKICBrcGlfMDE6IG51bWJlcjsKICBrcGlfMDI6IG51bWJlcjsKICBrcGlfMDM6IG51bWJl'
        'cjsKICBrcGlfMDQ6IG51bWJlcjsKfQoKZXhwb3J0IGludGVyZmFjZSBMaXZlU25hcHNob3Qgewog'
        'IGNsdXN0ZXJzOiBDbHVzdGVyUGF5bG9hZFtdOwogIGtwaXM6IEtwaXM7CiAgY2x1c3Rlcl9jb3Vu'
        'dDogbnVtYmVyOwogIGV4cGVjdGVkX2NsdXN0ZXJzOiBzdHJpbmdbXTsKfQoKdHlwZSBDb25uZWN0'
        'aW9uID0gJ2Nvbm5lY3RpbmcnIHwgJ3NzZScgfCAncG9sbGluZycgfCAnb2ZmbGluZSc7CgpleHBv'
        'cnQgaW50ZXJmYWNlIExpdmVTdGF0ZSB7CiAgc25hcHNob3Q6IExpdmVTbmFwc2hvdCB8IG51bGw7'
        'CiAgY29ubmVjdGlvbjogQ29ubmVjdGlvbjsKICB0aWNrOiBudW1iZXI7ICAgICAgICAgICAgLy8g'
        'aW5jcmVtZW50YSBwb3IgY2FkYSB1cGRhdGUgcmVjZWJpZG8KICBsYXN0VXBkYXRlTXM6IG51bWJl'
        'cjsgICAgLy8gdGltZXN0YW1wIGxvY2FsIGRhIMO6bHRpbWEgYWN0dWFsaXphw6fDo28KICAvLyBE'
        'ZXJpdmVkIGhlbHBlcnMg4oCUIGNhbGN1bGFkb3MgbmEgaG9yYSBhIHBhcnRpciBkbyBzbmFwc2hv'
        'dAogIHRvdGFsUGVzc29hczogbnVtYmVyOwogIGF2Z09jYzogbnVtYmVyOwogIGNyaXRpY29zOiBu'
        'dW1iZXI7Cn0KCmNvbnN0IERFRkFVTFQ6IExpdmVTdGF0ZSA9IHsKICBzbmFwc2hvdDogbnVsbCwK'
        'ICBjb25uZWN0aW9uOiAnY29ubmVjdGluZycsCiAgdGljazogMCwKICBsYXN0VXBkYXRlTXM6IDAs'
        'CiAgdG90YWxQZXNzb2FzOiAwLAogIGF2Z09jYzogMCwKICBjcml0aWNvczogMCwKfTsKCmNvbnN0'
        'IExpdmVDdHggPSBjcmVhdGVDb250ZXh0PExpdmVTdGF0ZT4oREVGQVVMVCk7CgpmdW5jdGlvbiBk'
        'ZXJpdmVUb3RhbHMoc25hcDogTGl2ZVNuYXBzaG90IHwgbnVsbCkgewogIGlmICghc25hcCB8fCAh'
        'c25hcC5jbHVzdGVycz8ubGVuZ3RoKSB7CiAgICByZXR1cm4geyB0b3RhbFBlc3NvYXM6IDAsIGF2'
        'Z09jYzogMCwgY3JpdGljb3M6IDAgfTsKICB9CiAgY29uc3QgdG90YWxQZXNzb2FzID0gc25hcC5j'
        'bHVzdGVycy5yZWR1Y2UoCiAgICAoYSwgYykgPT4gYSArIChjLnBhcmFtcz8ucGVzc29hc19lc3Rp'
        'bWFkYXMgfHwgMCksCiAgICAwLAogICk7CiAgY29uc3QgYXZnT2NjID0gc25hcC5rcGlzPy5rcGlf'
        'MDIgPz8gMDsKICBjb25zdCBjcml0aWNvcyA9IHNuYXAua3Bpcz8ua3BpXzAzID8/IDA7CiAgcmV0'
        'dXJuIHsgdG90YWxQZXNzb2FzLCBhdmdPY2MsIGNyaXRpY29zIH07Cn0KCmV4cG9ydCBmdW5jdGlv'
        'biBMaXZlUHJvdmlkZXIoeyBjaGlsZHJlbiB9OiB7IGNoaWxkcmVuOiBSZWFjdE5vZGUgfSkgewog'
        'IGNvbnN0IFtzdGF0ZSwgc2V0U3RhdGVdID0gdXNlU3RhdGU8TGl2ZVN0YXRlPihERUZBVUxUKTsK'
        'CiAgLy8gUmVmcyBwYXJhIGNvbmV4w6NvIChuw6NvIGNhdXNhbSByZS1yZW5kZXIpCiAgY29uc3Qg'
        'ZXNSZWYgPSB1c2VSZWY8RXZlbnRTb3VyY2UgfCBudWxsPihudWxsKTsKICBjb25zdCBwb2xsUmVm'
        'ID0gdXNlUmVmPFJldHVyblR5cGU8dHlwZW9mIHNldEludGVydmFsPiB8IG51bGw+KG51bGwpOwog'
        'IGNvbnN0IHJlY29ubmVjdFJlZiA9IHVzZVJlZjxSZXR1cm5UeXBlPHR5cGVvZiBzZXRUaW1lb3V0'
        'PiB8IG51bGw+KG51bGwpOwogIGNvbnN0IHJlY29ubmVjdEF0dGVtcHQgPSB1c2VSZWYoMCk7CiAg'
        'Y29uc3QgY2FuY2VsbGVkUmVmID0gdXNlUmVmKGZhbHNlKTsKCiAgY29uc3QgaW5nZXN0ID0gdXNl'
        'Q2FsbGJhY2soKHNuYXA6IExpdmVTbmFwc2hvdCwgY29ubjogQ29ubmVjdGlvbikgPT4gewogICAg'
        'Y29uc3QgZGVyaXZlZCA9IGRlcml2ZVRvdGFscyhzbmFwKTsKICAgIHNldFN0YXRlKChwcmV2KSA9'
        'PiAoewogICAgICBzbmFwc2hvdDogc25hcCwKICAgICAgY29ubmVjdGlvbjogY29ubiwKICAgICAg'
        'dGljazogcHJldi50aWNrICsgMSwKICAgICAgbGFzdFVwZGF0ZU1zOiBEYXRlLm5vdygpLAogICAg'
        'ICAuLi5kZXJpdmVkLAogICAgfSkpOwogIH0sIFtdKTsKCiAgLy8gUG9sbGluZyDigJQgZmFsbGJh'
        'Y2sgc2UgU1NFIGluZGlzcG9uw612ZWwKICBjb25zdCBzdGFydFBvbGxpbmcgPSB1c2VDYWxsYmFj'
        'aygoKSA9PiB7CiAgICBpZiAocG9sbFJlZi5jdXJyZW50KSBjbGVhckludGVydmFsKHBvbGxSZWYu'
        'Y3VycmVudCk7CiAgICBjb25zdCBmZXRjaE9uY2UgPSBhc3luYyAoKSA9PiB7CiAgICAgIGlmIChj'
        'YW5jZWxsZWRSZWYuY3VycmVudCkgcmV0dXJuOwogICAgICB0cnkgewogICAgICAgIGNvbnN0IHIg'
        'PSBhd2FpdCBmZXRjaChTTkFQU0hPVF9VUkwsIHsgY2FjaGU6ICduby1zdG9yZScgfSk7CiAgICAg'
        'ICAgaWYgKCFyLm9rKSB0aHJvdyBuZXcgRXJyb3IoYHN0YXR1cyAke3Iuc3RhdHVzfWApOwogICAg'
        'ICAgIGNvbnN0IGo6IExpdmVTbmFwc2hvdCA9IGF3YWl0IHIuanNvbigpOwogICAgICAgIGlmIChj'
        'YW5jZWxsZWRSZWYuY3VycmVudCkgcmV0dXJuOwogICAgICAgIGluZ2VzdChqLCAncG9sbGluZycp'
        'OwogICAgICB9IGNhdGNoIHsKICAgICAgICBpZiAoY2FuY2VsbGVkUmVmLmN1cnJlbnQpIHJldHVy'
        'bjsKICAgICAgICBzZXRTdGF0ZSgocHJldikgPT4gKHsgLi4ucHJldiwgY29ubmVjdGlvbjogJ29m'
        'ZmxpbmUnIH0pKTsKICAgICAgfQogICAgfTsKICAgIGZldGNoT25jZSgpOwogICAgcG9sbFJlZi5j'
        'dXJyZW50ID0gc2V0SW50ZXJ2YWwoZmV0Y2hPbmNlLCBQT0xMX0lOVEVSVkFMX01TKTsKICB9LCBb'
        'aW5nZXN0XSk7CgogIC8vIFNTRSDigJQgcHJlZmVyaWRvCiAgY29uc3Qgc3RhcnRTU0UgPSB1c2VD'
        'YWxsYmFjaygoKSA9PiB7CiAgICBpZiAodHlwZW9mIHdpbmRvdyA9PT0gJ3VuZGVmaW5lZCcpIHJl'
        'dHVybjsKICAgIGlmIChlc1JlZi5jdXJyZW50KSB7CiAgICAgIHRyeSB7IGVzUmVmLmN1cnJlbnQu'
        'Y2xvc2UoKTsgfSBjYXRjaCB7fQogICAgICBlc1JlZi5jdXJyZW50ID0gbnVsbDsKICAgIH0KCiAg'
        'ICBsZXQgZXM6IEV2ZW50U291cmNlOwogICAgdHJ5IHsKICAgICAgZXMgPSBuZXcgRXZlbnRTb3Vy'
        'Y2UoU1RSRUFNX1VSTCk7CiAgICB9IGNhdGNoIHsKICAgICAgLy8gQnJvd3NlciBzZW0gc3Vwb3J0'
        'ZSDihpIgcG9sbGluZwogICAgICBzdGFydFBvbGxpbmcoKTsKICAgICAgcmV0dXJuOwogICAgfQog'
        'ICAgZXNSZWYuY3VycmVudCA9IGVzOwoKICAgIGVzLm9ub3BlbiA9ICgpID0+IHsKICAgICAgcmVj'
        'b25uZWN0QXR0ZW1wdC5jdXJyZW50ID0gMDsKICAgICAgLy8gU2UgZXN0YXZhIGVtIHBvbGxpbmcs'
        'IGZlY2hhLW8KICAgICAgaWYgKHBvbGxSZWYuY3VycmVudCkgewogICAgICAgIGNsZWFySW50ZXJ2'
        'YWwocG9sbFJlZi5jdXJyZW50KTsKICAgICAgICBwb2xsUmVmLmN1cnJlbnQgPSBudWxsOwogICAg'
        'ICB9CiAgICAgIHNldFN0YXRlKChwcmV2KSA9PiAoeyAuLi5wcmV2LCBjb25uZWN0aW9uOiAnc3Nl'
        'JyB9KSk7CiAgICB9OwoKICAgIGVzLm9ubWVzc2FnZSA9IChldikgPT4gewogICAgICBpZiAoY2Fu'
        'Y2VsbGVkUmVmLmN1cnJlbnQpIHJldHVybjsKICAgICAgdHJ5IHsKICAgICAgICBjb25zdCBqOiBM'
        'aXZlU25hcHNob3QgPSBKU09OLnBhcnNlKGV2LmRhdGEpOwogICAgICAgIGluZ2VzdChqLCAnc3Nl'
        'Jyk7CiAgICAgIH0gY2F0Y2ggewogICAgICAgIC8vIGlnbm9yYSBtZW5zYWdlbSBtYWwtZm9ybWFk'
        'YQogICAgICB9CiAgICB9OwoKICAgIGVzLm9uZXJyb3IgPSAoKSA9PiB7CiAgICAgIGlmIChjYW5j'
        'ZWxsZWRSZWYuY3VycmVudCkgcmV0dXJuOwogICAgICB0cnkgeyBlcy5jbG9zZSgpOyB9IGNhdGNo'
        'IHt9CiAgICAgIGVzUmVmLmN1cnJlbnQgPSBudWxsOwoKICAgICAgLy8gQmFja29mZiBleHBvbmVu'
        'Y2lhbDsgYXDDs3MgNCB0ZW50YXRpdmFzIGZhbGhhZGFzLCBjYWkgcGFyYSBwb2xsaW5nCiAgICAg'
        'IGNvbnN0IGF0dGVtcHQgPSByZWNvbm5lY3RBdHRlbXB0LmN1cnJlbnQ7CiAgICAgIGlmIChhdHRl'
        'bXB0IDwgUkVDT05ORUNUX0JBQ0tPRkZfTVMubGVuZ3RoKSB7CiAgICAgICAgY29uc3QgZGVsYXkg'
        'PSBSRUNPTk5FQ1RfQkFDS09GRl9NU1thdHRlbXB0XTsKICAgICAgICByZWNvbm5lY3RBdHRlbXB0'
        'LmN1cnJlbnQgKz0gMTsKICAgICAgICBzZXRTdGF0ZSgocHJldikgPT4gKHsgLi4ucHJldiwgY29u'
        'bmVjdGlvbjogJ2Nvbm5lY3RpbmcnIH0pKTsKICAgICAgICByZWNvbm5lY3RSZWYuY3VycmVudCA9'
        'IHNldFRpbWVvdXQoKCkgPT4gewogICAgICAgICAgaWYgKCFjYW5jZWxsZWRSZWYuY3VycmVudCkg'
        'c3RhcnRTU0UoKTsKICAgICAgICB9LCBkZWxheSk7CiAgICAgIH0gZWxzZSB7CiAgICAgICAgc3Rh'
        'cnRQb2xsaW5nKCk7CiAgICAgIH0KICAgIH07CiAgfSwgW2luZ2VzdCwgc3RhcnRQb2xsaW5nXSk7'
        'CgogIHVzZUVmZmVjdCgoKSA9PiB7CiAgICBjYW5jZWxsZWRSZWYuY3VycmVudCA9IGZhbHNlOwog'
        'ICAgc3RhcnRTU0UoKTsKICAgIHJldHVybiAoKSA9PiB7CiAgICAgIGNhbmNlbGxlZFJlZi5jdXJy'
        'ZW50ID0gdHJ1ZTsKICAgICAgaWYgKGVzUmVmLmN1cnJlbnQpIHsKICAgICAgICB0cnkgeyBlc1Jl'
        'Zi5jdXJyZW50LmNsb3NlKCk7IH0gY2F0Y2gge30KICAgICAgICBlc1JlZi5jdXJyZW50ID0gbnVs'
        'bDsKICAgICAgfQogICAgICBpZiAocG9sbFJlZi5jdXJyZW50KSB7CiAgICAgICAgY2xlYXJJbnRl'
        'cnZhbChwb2xsUmVmLmN1cnJlbnQpOwogICAgICAgIHBvbGxSZWYuY3VycmVudCA9IG51bGw7CiAg'
        'ICAgIH0KICAgICAgaWYgKHJlY29ubmVjdFJlZi5jdXJyZW50KSB7CiAgICAgICAgY2xlYXJUaW1l'
        'b3V0KHJlY29ubmVjdFJlZi5jdXJyZW50KTsKICAgICAgICByZWNvbm5lY3RSZWYuY3VycmVudCA9'
        'IG51bGw7CiAgICAgIH0KICAgIH07CiAgfSwgW3N0YXJ0U1NFXSk7CgogIHJldHVybiA8TGl2ZUN0'
        'eC5Qcm92aWRlciB2YWx1ZT17c3RhdGV9PntjaGlsZHJlbn08L0xpdmVDdHguUHJvdmlkZXI+Owp9'
        'CgpleHBvcnQgZnVuY3Rpb24gdXNlTGl2ZSgpOiBMaXZlU3RhdGUgewogIHJldHVybiB1c2VDb250'
        'ZXh0KExpdmVDdHgpOwp9CgovLyBIZWxwZXIgcGFyYSBvYnRlciBjbHVzdGVyIGVzcGVjw61maWNv'
        'CmV4cG9ydCBmdW5jdGlvbiB1c2VDbHVzdGVyKGNsdXN0ZXJJZDogc3RyaW5nKTogQ2x1c3RlclBh'
        'eWxvYWQgfCBudWxsIHsKICBjb25zdCB7IHNuYXBzaG90IH0gPSB1c2VMaXZlKCk7CiAgaWYgKCFz'
        'bmFwc2hvdCkgcmV0dXJuIG51bGw7CiAgcmV0dXJuIHNuYXBzaG90LmNsdXN0ZXJzLmZpbmQoKGMp'
        'ID0+IGMuY2x1c3Rlcl9pZCA9PT0gY2x1c3RlcklkKSB8fCBudWxsOwp9Cg=='
    ),
    'frontend/app/v2/layout.tsx': (
        'aW1wb3J0IHR5cGUgeyBNZXRhZGF0YSB9IGZyb20gJ25leHQnOwppbXBvcnQgeyBDb3Jtb3JhbnRf'
        'R2FyYW1vbmQsIERNX1NhbnMsIERNX01vbm8gfSBmcm9tICduZXh0L2ZvbnQvZ29vZ2xlJzsKaW1w'
        'b3J0IFRvcEJhciBmcm9tICdAL2NvbXBvbmVudHMvdjIvVG9wQmFyJzsKaW1wb3J0IFBsYW50YVNl'
        'YXJjaEJhciBmcm9tICdAL2NvbXBvbmVudHMvdjIvUGxhbnRhU2VhcmNoQmFyJzsKaW1wb3J0IHsg'
        'TGl2ZVByb3ZpZGVyIH0gZnJvbSAnQC9jb21wb25lbnRzL3YyL0xpdmVDb250ZXh0JzsKaW1wb3J0'
        'ICcuL3YyLmNzcyc7CgovLyBNYW50ZW1vcyBhcyBmb250ZXMgY2FycmVnYWRhcyAoRE1fTW9ubyBh'
        'aW5kYSDDqSB1c2FkYSBjb21vIC0tZm9udC1kbS1tb25vKQovLyBtYXMgYSB0aXBvZ3JhZmlhIHZp'
        'c8OtdmVsIMOpIEludGVyIChjYXJyZWdhZGEgdmlhIEBpbXBvcnQgZW0gdjIuY3NzKS4KY29uc3Qg'
        'Y29ybW9yYW50ID0gQ29ybW9yYW50X0dhcmFtb25kKHsKICBzdWJzZXRzOiBbJ2xhdGluJ10sCiAg'
        'd2VpZ2h0OiBbJzMwMCcsICc0MDAnLCAnNTAwJywgJzYwMCcsICc3MDAnXSwKICB2YXJpYWJsZTog'
        'Jy0tZm9udC1zZXJpZicsCiAgZGlzcGxheTogJ3N3YXAnLAp9KTsKCmNvbnN0IGRtU2FucyA9IERN'
        'X1NhbnMoewogIHN1YnNldHM6IFsnbGF0aW4nXSwKICB3ZWlnaHQ6IFsnNDAwJywgJzUwMCcsICc2'
        'MDAnLCAnNzAwJ10sCiAgdmFyaWFibGU6ICctLWZvbnQtdWknLAogIGRpc3BsYXk6ICdzd2FwJywK'
        'fSk7Cgpjb25zdCBkbU1vbm8gPSBETV9Nb25vKHsKICBzdWJzZXRzOiBbJ2xhdGluJ10sCiAgd2Vp'
        'Z2h0OiBbJzQwMCcsICc1MDAnXSwKICB2YXJpYWJsZTogJy0tZm9udC1kbS1tb25vJywKICBkaXNw'
        'bGF5OiAnc3dhcCcsCn0pOwoKZXhwb3J0IGNvbnN0IG1ldGFkYXRhOiBNZXRhZGF0YSA9IHsKICB0'
        'aXRsZTogJ1BsYW50YU9TIMK3IFJvY2sgaW4gUmlvIExpc2JvYSAyMDI2JywKICBkZXNjcmlwdGlv'
        'bjoKICAgICdJbnRlbGlnw6puY2lhIGRlIGZsdXhvcyBlbSB0ZW1wbyByZWFsIOKAlCA4IGNsdXN0'
        'ZXJzIFdDLCAxIDEzNyBsdWdhcmVzLCBQYXJxdWUgVGVqbywgMjDigJMyOCBKdW5obyAyMDI2Lics'
        'Cn07CgpleHBvcnQgZGVmYXVsdCBmdW5jdGlvbiBWMkxheW91dCh7IGNoaWxkcmVuIH06IHsgY2hp'
        'bGRyZW46IFJlYWN0LlJlYWN0Tm9kZSB9KSB7CiAgcmV0dXJuICgKICAgIDxkaXYKICAgICAgY2xh'
        'c3NOYW1lPXtgJHtjb3Jtb3JhbnQudmFyaWFibGV9ICR7ZG1TYW5zLnZhcmlhYmxlfSAke2RtTW9u'
        'by52YXJpYWJsZX0gdjItcm9vdGB9CiAgICA+CiAgICAgIDxMaXZlUHJvdmlkZXI+CiAgICAgICAg'
        'PFRvcEJhciAvPgogICAgICAgIDxtYWluIGNsYXNzTmFtZT0idjItY29udGVudCI+CiAgICAgICAg'
        'ICB7Y2hpbGRyZW59CiAgICAgICAgICA8UGxhbnRhU2VhcmNoQmFyIC8+CiAgICAgICAgPC9tYWlu'
        'PgogICAgICA8L0xpdmVQcm92aWRlcj4KICAgIDwvZGl2PgogICk7Cn0K'
    ),
    'frontend/app/v2/page.tsx': (
        'J3VzZSBjbGllbnQnOwoKaW1wb3J0IExpbmsgZnJvbSAnbmV4dC9saW5rJzsKaW1wb3J0IHsgdXNl'
        'TGl2ZSB9IGZyb20gJ0AvY29tcG9uZW50cy92Mi9MaXZlQ29udGV4dCc7Cgpjb25zdCBDTFVTVEVS'
        'X09SREVSID0gWyd3Yy0wMScsICd3Yy0wMicsICd3Yy0wMycsICd3Yy0wNCcsICd3Yy0wNScsICd3'
        'Yy0wNicsICd3Yy0wNycsICd3Yy0wOCddOwpjb25zdCBVTklTRVggPSBuZXcgU2V0KFsnd2MtMDUn'
        'LCAnd2MtMDYnXSk7CgpleHBvcnQgZGVmYXVsdCBmdW5jdGlvbiBIb21lUGFnZSgpIHsKICBjb25z'
        'dCB7IHNuYXBzaG90LCBjb25uZWN0aW9uLCB0aWNrLCB0b3RhbFBlc3NvYXMsIGF2Z09jYywgY3Jp'
        'dGljb3MgfSA9IHVzZUxpdmUoKTsKCiAgY29uc3QgY2x1c3RlcnMgPSAoKCkgPT4gewogICAgaWYg'
        'KCFzbmFwc2hvdCkgcmV0dXJuIFtdOwogICAgY29uc3QgbSA9IG5ldyBNYXAoc25hcHNob3QuY2x1'
        'c3RlcnMubWFwKChjKSA9PiBbYy5jbHVzdGVyX2lkLCBjXSkpOwogICAgcmV0dXJuIENMVVNURVJf'
        'T1JERVIubWFwKChpZCkgPT4gbS5nZXQoaWQpKS5maWx0ZXIoQm9vbGVhbikgYXMgTm9uTnVsbGFi'
        'bGU8UmV0dXJuVHlwZTx0eXBlb2YgbS5nZXQ+PltdOwogIH0pKCk7CgogIGNvbnN0IGZsb3dJZHgg'
        'PSBzbmFwc2hvdD8ua3Bpcz8ua3BpXzAxID8/IDA7CiAgY29uc3QgaXNTdHJlYW1pbmcgPSBjb25u'
        'ZWN0aW9uID09PSAnc3NlJzsKCiAgcmV0dXJuICgKICAgIDxkaXYgY2xhc3NOYW1lPSJwYWdlLWZ1'
        'bGwiPgogICAgICA8c2VjdGlvbiBzdHlsZT17eyBtYXJnaW5Cb3R0b206ICdjbGFtcCgyMHB4LCAz'
        'dncsIDM2cHgpJyB9fT4KICAgICAgICA8ZGl2CiAgICAgICAgICBzdHlsZT17ewogICAgICAgICAg'
        'ICBkaXNwbGF5OiAnZmxleCcsCiAgICAgICAgICAgIGp1c3RpZnlDb250ZW50OiAnc3BhY2UtYmV0'
        'd2VlbicsCiAgICAgICAgICAgIGFsaWduSXRlbXM6ICdmbGV4LWVuZCcsCiAgICAgICAgICAgIGdh'
        'cDogMTYsCiAgICAgICAgICAgIGZsZXhXcmFwOiAnd3JhcCcsCiAgICAgICAgICAgIG1hcmdpbkJv'
        'dHRvbTogMjQsCiAgICAgICAgICB9fQogICAgICAgID4KICAgICAgICAgIDxkaXY+CiAgICAgICAg'
        'ICAgIDxkaXYgY2xhc3NOYW1lPSJzZWN0aW9uLWxhYmVsIj5Sb2NrIGluIFJpbyBMaXNib2Egwrcg'
        'UGFycXVlIFRlam8gwrcgMjDigJMyOCBKdW4gMjAyNjwvZGl2PgogICAgICAgICAgICA8aDEKICAg'
        'ICAgICAgICAgICBjbGFzc05hbWU9ImRpc3BsYXkiCiAgICAgICAgICAgICAgc3R5bGU9e3sKICAg'
        'ICAgICAgICAgICAgIGZvbnRGYW1pbHk6ICd2YXIoLS1mb250LWRpc3BsYXkpJywKICAgICAgICAg'
        'ICAgICAgIGZvbnRTaXplOiAnY2xhbXAoNDBweCwgNnZ3LCA4NHB4KScsCiAgICAgICAgICAgICAg'
        'ICBsaW5lSGVpZ2h0OiAwLjk1LAogICAgICAgICAgICAgICAgbGV0dGVyU3BhY2luZzogJy0wLjAz'
        'NWVtJywKICAgICAgICAgICAgICAgIGZvbnRXZWlnaHQ6IDUwMCwKICAgICAgICAgICAgICAgIG1h'
        'cmdpblRvcDogNCwKICAgICAgICAgICAgICB9fQogICAgICAgICAgICA+CiAgICAgICAgICAgICAg'
        'RW0gdGVtcG8gcmVhbC4KICAgICAgICAgICAgPC9oMT4KICAgICAgICAgIDwvZGl2PgogICAgICAg'
        'ICAgPHNwYW4gY2xhc3NOYW1lPXtpc1N0cmVhbWluZyA/ICdwaWxsIHBpbGwtbGl2ZScgOiAncGls'
        'bCBwaWxsLXNpbSd9PgogICAgICAgICAgICB7Y29ubmVjdGlvbiA9PT0gJ3NzZScgPyAnU1RSRUFN'
        'IEFPIFNFR1VORE8nIDoKICAgICAgICAgICAgIGNvbm5lY3Rpb24gPT09ICdwb2xsaW5nJyA/ICdG'
        'QUxMQkFDSyDCtyAycycgOgogICAgICAgICAgICAgY29ubmVjdGlvbiA9PT0gJ29mZmxpbmUnID8g'
        'J09GRkxJTkUnIDogJ0EgTElHQVInfQogICAgICAgICAgPC9zcGFuPgogICAgICAgIDwvZGl2PgoK'
        'ICAgICAgICA8ZGl2CiAgICAgICAgICBzdHlsZT17ewogICAgICAgICAgICBkaXNwbGF5OiAnZ3Jp'
        'ZCcsCiAgICAgICAgICAgIGdyaWRUZW1wbGF0ZUNvbHVtbnM6ICdyZXBlYXQoNCwgMWZyKScsCiAg'
        'ICAgICAgICAgIGdhcDogJ2NsYW1wKDEycHgsIDJ2dywgMjhweCknLAogICAgICAgICAgICBib3Jk'
        'ZXJUb3A6ICcxcHggc29saWQgdmFyKC0tYm9yZGVyKScsCiAgICAgICAgICAgIHBhZGRpbmdUb3A6'
        'ICdjbGFtcCgxNHB4LCAydncsIDIycHgpJywKICAgICAgICAgIH19CiAgICAgICAgPgogICAgICAg'
        'ICAgPEtwaSBsYWJlbD0iUGVzc29hcyBlc3RpbWFkYXMiIHZhbHVlPXt0b3RhbFBlc3NvYXN9IGFj'
        'Y2VudCAvPgogICAgICAgICAgPEtwaSBsYWJlbD0iT2N1cGHDp8OjbyBtw6lkaWEiIHZhbHVlPXtg'
        'JHthdmdPY2MudG9GaXhlZCgwKX0lYH0gLz4KICAgICAgICAgIDxLcGkgbGFiZWw9IsONbmRpY2Ug'
        'ZGUgZmx1eG8iIHZhbHVlPXtmbG93SWR4fSAvPgogICAgICAgICAgPEtwaSBsYWJlbD0iQ3LDrXRp'
        'Y29zIiB2YWx1ZT17Y3JpdGljb3N9IGFsZXJ0PXtjcml0aWNvcyA+IDB9IC8+CiAgICAgICAgPC9k'
        'aXY+CiAgICAgIDwvc2VjdGlvbj4KCiAgICAgIDxzZWN0aW9uIHN0eWxlPXt7IGZsZXg6IDEsIGRp'
        'c3BsYXk6ICdmbGV4JywgZmxleERpcmVjdGlvbjogJ2NvbHVtbicgfX0+CiAgICAgICAgPGRpdgog'
        'ICAgICAgICAgc3R5bGU9e3sKICAgICAgICAgICAgZGlzcGxheTogJ2ZsZXgnLAogICAgICAgICAg'
        'ICBqdXN0aWZ5Q29udGVudDogJ3NwYWNlLWJldHdlZW4nLAogICAgICAgICAgICBhbGlnbkl0ZW1z'
        'OiAnYmFzZWxpbmUnLAogICAgICAgICAgICBtYXJnaW5Cb3R0b206IDEyLAogICAgICAgICAgfX0K'
        'ICAgICAgICA+CiAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT0ic2VjdGlvbi1sYWJlbCI+OCBjbHVz'
        'dGVycyDCtyAxIDEzNyBsdWdhcmVzPC9kaXY+CiAgICAgICAgICA8c3BhbgogICAgICAgICAgICBj'
        'bGFzc05hbWU9Im1vbm8iCiAgICAgICAgICAgIHN0eWxlPXt7IGZvbnRTaXplOiAxMSwgY29sb3I6'
        'ICd2YXIoLS1mYWludCknIH19CiAgICAgICAgICA+CiAgICAgICAgICAgIHRpY2sgI3t0aWNrfQog'
        'ICAgICAgICAgPC9zcGFuPgogICAgICAgIDwvZGl2PgoKICAgICAgICA8ZGl2IGNsYXNzTmFtZT0i'
        'Z3JpZCBncmlkLTgiIHN0eWxlPXt7IGFsaWduQ29udGVudDogJ3N0YXJ0JyB9fT4KICAgICAgICAg'
        'IHtjbHVzdGVycy5sZW5ndGggPT09IDAgJiYKICAgICAgICAgICAgQ0xVU1RFUl9PUkRFUi5tYXAo'
        'KGlkKSA9PiAoCiAgICAgICAgICAgICAgPGRpdgogICAgICAgICAgICAgICAga2V5PXtpZH0KICAg'
        'ICAgICAgICAgICAgIHN0eWxlPXt7CiAgICAgICAgICAgICAgICAgIGJhY2tncm91bmQ6ICd2YXIo'
        'LS1iZy1zb2Z0KScsCiAgICAgICAgICAgICAgICAgIGJvcmRlcjogJzFweCBzb2xpZCB2YXIoLS1i'
        'b3JkZXIpJywKICAgICAgICAgICAgICAgICAgYm9yZGVyUmFkaXVzOiAndmFyKC0tcmFkaXVzKScs'
        'CiAgICAgICAgICAgICAgICAgIHBhZGRpbmc6IDE4LAogICAgICAgICAgICAgICAgICBtaW5IZWln'
        'aHQ6IDkwLAogICAgICAgICAgICAgICAgfX0KICAgICAgICAgICAgICAvPgogICAgICAgICAgICAp'
        'KX0KICAgICAgICAgIHtjbHVzdGVycy5tYXAoKGMpID0+IHsKICAgICAgICAgICAgY29uc3QgaXNV'
        'bmkgPSBVTklTRVguaGFzKGMuY2x1c3Rlcl9pZCk7CiAgICAgICAgICAgIGNvbnN0IG9jYyA9IGMu'
        'cGFyYW1zLm9jdXBhY2FvX2luc3RhbnRhbmVhID8/IDA7CiAgICAgICAgICAgIGNvbnN0IG9jY0Nv'
        'bG9yID0KICAgICAgICAgICAgICBvY2MgPj0gODAgPyAndmFyKC0tYW1iZXIpJyA6IG9jYyA+PSA2'
        'MCA/ICcjQTg1RDAwJyA6ICd2YXIoLS1ncmVlbi1kYXJrKSc7CiAgICAgICAgICAgIHJldHVybiAo'
        'CiAgICAgICAgICAgICAgPExpbmsKICAgICAgICAgICAgICAgIGtleT17Yy5jbHVzdGVyX2lkfQog'
        'ICAgICAgICAgICAgICAgaHJlZj17YC92Mi9zY29yYH0KICAgICAgICAgICAgICAgIHN0eWxlPXt7'
        'CiAgICAgICAgICAgICAgICAgIGJhY2tncm91bmQ6ICd3aGl0ZScsCiAgICAgICAgICAgICAgICAg'
        'IGJvcmRlcjogJzFweCBzb2xpZCB2YXIoLS1ib3JkZXIpJywKICAgICAgICAgICAgICAgICAgYm9y'
        'ZGVyTGVmdDogYDNweCBzb2xpZCAke2lzVW5pID8gJyM3QTRBOEUnIDogJ3ZhcigtLWdyZWVuLWRh'
        'cmspJ31gLAogICAgICAgICAgICAgICAgICBib3JkZXJSYWRpdXM6ICd2YXIoLS1yYWRpdXMpJywK'
        'ICAgICAgICAgICAgICAgICAgcGFkZGluZzogJzE0cHggMTZweCcsCiAgICAgICAgICAgICAgICAg'
        'IGRpc3BsYXk6ICdmbGV4JywKICAgICAgICAgICAgICAgICAgZmxleERpcmVjdGlvbjogJ2NvbHVt'
        'bicsCiAgICAgICAgICAgICAgICAgIGdhcDogOCwKICAgICAgICAgICAgICAgICAgdGV4dERlY29y'
        'YXRpb246ICdub25lJywKICAgICAgICAgICAgICAgICAgY29sb3I6ICdpbmhlcml0JywKICAgICAg'
        'ICAgICAgICAgICAgdHJhbnNpdGlvbjogJ2JvcmRlci1jb2xvciAwLjE4cywgYm94LXNoYWRvdyAw'
        'LjE4cywgdHJhbnNmb3JtIDAuMThzJywKICAgICAgICAgICAgICAgIH19CiAgICAgICAgICAgICAg'
        'ICBvbk1vdXNlRW50ZXI9eyhlKSA9PiB7CiAgICAgICAgICAgICAgICAgIGUuY3VycmVudFRhcmdl'
        'dC5zdHlsZS5ib3hTaGFkb3cgPSAndmFyKC0tc2hhZG93LW1kKSc7CiAgICAgICAgICAgICAgICAg'
        'IGUuY3VycmVudFRhcmdldC5zdHlsZS50cmFuc2Zvcm0gPSAndHJhbnNsYXRlWSgtMXB4KSc7CiAg'
        'ICAgICAgICAgICAgICB9fQogICAgICAgICAgICAgICAgb25Nb3VzZUxlYXZlPXsoZSkgPT4gewog'
        'ICAgICAgICAgICAgICAgICBlLmN1cnJlbnRUYXJnZXQuc3R5bGUuYm94U2hhZG93ID0gJ25vbmUn'
        'OwogICAgICAgICAgICAgICAgICBlLmN1cnJlbnRUYXJnZXQuc3R5bGUudHJhbnNmb3JtID0gJ3Ry'
        'YW5zbGF0ZVkoMCknOwogICAgICAgICAgICAgICAgfX0KICAgICAgICAgICAgICA+CiAgICAgICAg'
        'ICAgICAgICA8ZGl2CiAgICAgICAgICAgICAgICAgIHN0eWxlPXt7CiAgICAgICAgICAgICAgICAg'
        'ICAgZGlzcGxheTogJ2ZsZXgnLAogICAgICAgICAgICAgICAgICAgIGp1c3RpZnlDb250ZW50OiAn'
        'c3BhY2UtYmV0d2VlbicsCiAgICAgICAgICAgICAgICAgICAgYWxpZ25JdGVtczogJ2ZsZXgtc3Rh'
        'cnQnLAogICAgICAgICAgICAgICAgICB9fQogICAgICAgICAgICAgICAgPgogICAgICAgICAgICAg'
        'ICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgIDxkaXYKICAgICAgICAgICAgICAgICAgICAg'
        'IHN0eWxlPXt7CiAgICAgICAgICAgICAgICAgICAgICAgIGZvbnRTaXplOiAnY2xhbXAoMTVweCwg'
        'MS40dncsIDE4cHgpJywKICAgICAgICAgICAgICAgICAgICAgICAgZm9udFdlaWdodDogNjAwLAog'
        'ICAgICAgICAgICAgICAgICAgICAgICBsZXR0ZXJTcGFjaW5nOiAnLTAuMDE1ZW0nLAogICAgICAg'
        'ICAgICAgICAgICAgICAgICBjb2xvcjogJ3ZhcigtLWluayknLAogICAgICAgICAgICAgICAgICAg'
        'ICAgfX0KICAgICAgICAgICAgICAgICAgICA+CiAgICAgICAgICAgICAgICAgICAgICB7Yy5jbHVz'
        'dGVyX2lkLnRvVXBwZXJDYXNlKCl9CiAgICAgICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAg'
        'ICAgICAgICAgICAgPGRpdgogICAgICAgICAgICAgICAgICAgICAgY2xhc3NOYW1lPSJtb25vIgog'
        'ICAgICAgICAgICAgICAgICAgICAgc3R5bGU9e3sKICAgICAgICAgICAgICAgICAgICAgICAgZm9u'
        'dFNpemU6IDksCiAgICAgICAgICAgICAgICAgICAgICAgIGNvbG9yOiAndmFyKC0tbXV0ZWQpJywK'
        'ICAgICAgICAgICAgICAgICAgICAgICAgbGV0dGVyU3BhY2luZzogJzAuMWVtJywKICAgICAgICAg'
        'ICAgICAgICAgICAgICAgdGV4dFRyYW5zZm9ybTogJ3VwcGVyY2FzZScsCiAgICAgICAgICAgICAg'
        'ICAgICAgICAgIG1hcmdpblRvcDogMSwKICAgICAgICAgICAgICAgICAgICAgIH19CiAgICAgICAg'
        'ICAgICAgICAgICAgPgogICAgICAgICAgICAgICAgICAgICAge2lzVW5pID8gJ3VuaXNzZXgnIDog'
        'J21hc2MgKyBmZW0nfQogICAgICAgICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICAgICAg'
        'ICA8L2Rpdj4KICAgICAgICAgICAgICAgICAgPGRpdgogICAgICAgICAgICAgICAgICAgIHN0eWxl'
        'PXt7CiAgICAgICAgICAgICAgICAgICAgICBmb250U2l6ZTogJ2NsYW1wKDE4cHgsIDJ2dywgMjRw'
        'eCknLAogICAgICAgICAgICAgICAgICAgICAgZm9udFdlaWdodDogNjAwLAogICAgICAgICAgICAg'
        'ICAgICAgICAgbGV0dGVyU3BhY2luZzogJy0wLjAyZW0nLAogICAgICAgICAgICAgICAgICAgICAg'
        'Y29sb3I6IG9jY0NvbG9yLAogICAgICAgICAgICAgICAgICAgICAgbGluZUhlaWdodDogMSwKICAg'
        'ICAgICAgICAgICAgICAgICB9fQogICAgICAgICAgICAgICAgICA+CiAgICAgICAgICAgICAgICAg'
        'ICAge29jY30KICAgICAgICAgICAgICAgICAgICA8c3BhbiBzdHlsZT17eyBmb250U2l6ZTogJzAu'
        'NTVlbScsIG1hcmdpbkxlZnQ6IDEsIGNvbG9yOiAndmFyKC0tbXV0ZWQpJyB9fT4lPC9zcGFuPgog'
        'ICAgICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgICAgIDwvZGl2PgoKICAgICAgICAg'
        'ICAgICAgIDxkaXYKICAgICAgICAgICAgICAgICAgc3R5bGU9e3sKICAgICAgICAgICAgICAgICAg'
        'ICBoZWlnaHQ6IDQsCiAgICAgICAgICAgICAgICAgICAgYmFja2dyb3VuZDogJ3ZhcigtLWJnLXNv'
        'ZnQpJywKICAgICAgICAgICAgICAgICAgICBib3JkZXJSYWRpdXM6IDk5OSwKICAgICAgICAgICAg'
        'ICAgICAgICBvdmVyZmxvdzogJ2hpZGRlbicsCiAgICAgICAgICAgICAgICAgIH19CiAgICAgICAg'
        'ICAgICAgICA+CiAgICAgICAgICAgICAgICAgIDxkaXYKICAgICAgICAgICAgICAgICAgICBzdHls'
        'ZT17ewogICAgICAgICAgICAgICAgICAgICAgd2lkdGg6IGAke01hdGgubWluKDEwMCwgb2NjKX0l'
        'YCwKICAgICAgICAgICAgICAgICAgICAgIGhlaWdodDogJzEwMCUnLAogICAgICAgICAgICAgICAg'
        'ICAgICAgYmFja2dyb3VuZDogb2NjQ29sb3IsCiAgICAgICAgICAgICAgICAgICAgICB0cmFuc2l0'
        'aW9uOiAnd2lkdGggMC41cyBlYXNlJywKICAgICAgICAgICAgICAgICAgICB9fQogICAgICAgICAg'
        'ICAgICAgICAvPgogICAgICAgICAgICAgICAgPC9kaXY+CgogICAgICAgICAgICAgICAgPGRpdgog'
        'ICAgICAgICAgICAgICAgICBzdHlsZT17ewogICAgICAgICAgICAgICAgICAgIGRpc3BsYXk6ICdm'
        'bGV4JywKICAgICAgICAgICAgICAgICAgICBqdXN0aWZ5Q29udGVudDogJ3NwYWNlLWJldHdlZW4n'
        'LAogICAgICAgICAgICAgICAgICAgIGZvbnRTaXplOiAxMSwKICAgICAgICAgICAgICAgICAgICBj'
        'b2xvcjogJ3ZhcigtLW11dGVkKScsCiAgICAgICAgICAgICAgICAgICAgZm9udEZhbWlseTogJ3Zh'
        'cigtLWZvbnQtbW9ubyknLAogICAgICAgICAgICAgICAgICB9fQogICAgICAgICAgICAgICAgPgog'
        'ICAgICAgICAgICAgICAgICA8c3Bhbj57Yy5wYXJhbXMucGVzc29hc19lc3RpbWFkYXN9IHBlc3Nv'
        'YXM8L3NwYW4+CiAgICAgICAgICAgICAgICAgIHtjLnBhcmFtcy5maWxhX2F0dWFsICE9PSB1bmRl'
        'ZmluZWQgJiYgKAogICAgICAgICAgICAgICAgICAgIDxzcGFuPmZpbGEge2MucGFyYW1zLmZpbGFf'
        'YXR1YWx9PC9zcGFuPgogICAgICAgICAgICAgICAgICApfQogICAgICAgICAgICAgICAgPC9kaXY+'
        'CiAgICAgICAgICAgICAgPC9MaW5rPgogICAgICAgICAgICApOwogICAgICAgICAgfSl9CiAgICAg'
        'ICAgPC9kaXY+CiAgICAgIDwvc2VjdGlvbj4KCiAgICAgIDxmb290ZXIKICAgICAgICBzdHlsZT17'
        'ewogICAgICAgICAgbWFyZ2luVG9wOiAnY2xhbXAoMTZweCwgMnZ3LCAyOHB4KScsCiAgICAgICAg'
        'ICBwYWRkaW5nVG9wOiAxNCwKICAgICAgICAgIGJvcmRlclRvcDogJzFweCBzb2xpZCB2YXIoLS1i'
        'b3JkZXIpJywKICAgICAgICAgIGRpc3BsYXk6ICdmbGV4JywKICAgICAgICAgIGp1c3RpZnlDb250'
        'ZW50OiAnc3BhY2UtYmV0d2VlbicsCiAgICAgICAgICBhbGlnbkl0ZW1zOiAnY2VudGVyJywKICAg'
        'ICAgICAgIGdhcDogMTQsCiAgICAgICAgICBmb250U2l6ZTogMTIsCiAgICAgICAgICBjb2xvcjog'
        'J3ZhcigtLW11dGVkKScsCiAgICAgICAgICBmbGV4V3JhcDogJ3dyYXAnLAogICAgICAgIH19CiAg'
        'ICAgID4KICAgICAgICA8ZGl2IGNsYXNzTmFtZT0ibW9ubyIgc3R5bGU9e3sgZm9udFNpemU6IDEw'
        'LjUsIGxldHRlclNwYWNpbmc6ICcwLjEyZW0nLCB0ZXh0VHJhbnNmb3JtOiAndXBwZXJjYXNlJyB9'
        'fT4KICAgICAgICAgIEZDVCAyMDI1LjAwMDIwLkFJVkxBQi5ERVVDQUxJT04KICAgICAgICA8L2Rp'
        'dj4KICAgICAgICA8ZGl2IHN0eWxlPXt7IGRpc3BsYXk6ICdmbGV4JywgZ2FwOiAxOCwgZm9udFNp'
        'emU6IDEyIH19PgogICAgICAgICAgPExpbmsgaHJlZj0iL3YyL3R3aW4iIHN0eWxlPXt7IGNvbG9y'
        'OiAndmFyKC0tbXV0ZWQpJyB9fT5EaWdpdGFsIHR3aW4g4oaSPC9MaW5rPgogICAgICAgICAgPExp'
        'bmsgaHJlZj0iL3YyL3Njb3IiIHN0eWxlPXt7IGNvbG9yOiAndmFyKC0tbXV0ZWQpJyB9fT5TQ09S'
        'IGxpdmUg4oaSPC9MaW5rPgogICAgICAgICAgPExpbmsgaHJlZj0iL3YyL2NsZWFuaW5nIiBzdHls'
        'ZT17eyBjb2xvcjogJ3ZhcigtLW11dGVkKScgfX0+TGltcGV6YSDihpI8L0xpbms+CiAgICAgICAg'
        'PC9kaXY+CiAgICAgIDwvZm9vdGVyPgogICAgPC9kaXY+CiAgKTsKfQoKZnVuY3Rpb24gS3BpKHsg'
        'bGFiZWwsIHZhbHVlLCBhY2NlbnQsIGFsZXJ0IH06IHsKICBsYWJlbDogc3RyaW5nOwogIHZhbHVl'
        'OiBudW1iZXIgfCBzdHJpbmc7CiAgYWNjZW50PzogYm9vbGVhbjsKICBhbGVydD86IGJvb2xlYW47'
        'Cn0pIHsKICByZXR1cm4gKAogICAgPGRpdj4KICAgICAgPGRpdiBjbGFzc05hbWU9ImtwaS1sYWJl'
        'bCI+e2xhYmVsfTwvZGl2PgogICAgICA8ZGl2CiAgICAgICAgY2xhc3NOYW1lPSJrcGktdmFsdWUi'
        'CiAgICAgICAgc3R5bGU9e3sKICAgICAgICAgIGNvbG9yOiBhbGVydCA/ICd2YXIoLS1hbWJlcikn'
        'IDogYWNjZW50ID8gJ3ZhcigtLWdyZWVuLWRhcmspJyA6ICd2YXIoLS1pbmspJywKICAgICAgICAg'
        'IG1hcmdpblRvcDogNCwKICAgICAgICB9fQogICAgICA+CiAgICAgICAge3R5cGVvZiB2YWx1ZSA9'
        'PT0gJ251bWJlcicgPyB2YWx1ZS50b0xvY2FsZVN0cmluZygncHQtUFQnKSA6IHZhbHVlfQogICAg'
        'ICA8L2Rpdj4KICAgIDwvZGl2PgogICk7Cn0K'
    ),
    'frontend/components/v2/TopBar.tsx': (
        'J3VzZSBjbGllbnQnOwoKaW1wb3J0IExpbmsgZnJvbSAnbmV4dC9saW5rJzsKaW1wb3J0IHsgdXNl'
        'UGF0aG5hbWUgfSBmcm9tICduZXh0L25hdmlnYXRpb24nOwppbXBvcnQgeyB1c2VDYWxsYmFjaywg'
        'dXNlRWZmZWN0LCB1c2VNZW1vLCB1c2VSZWYsIHVzZVN0YXRlIH0gZnJvbSAncmVhY3QnOwppbXBv'
        'cnQgeyB1c2VMaXZlIH0gZnJvbSAnLi9MaXZlQ29udGV4dCc7Cgpjb25zdCBBUElfQkFTRSA9IHBy'
        'b2Nlc3MuZW52Lk5FWFRfUFVCTElDX0FQSV9CQVNFIHx8ICdodHRwczovL2FwaS5wbGFudGFyb2Nr'
        'aW5yaW8uY29tJzsKY29uc3QgUkVDRU5UU19LRVkgPSAncGxhbnRhLXJlY2VudC1wYXRocy12MSc7'
        'CgppbnRlcmZhY2UgTmF2SXRlbSB7CiAgaHJlZjogc3RyaW5nOwogIGxhYmVsOiBzdHJpbmc7CiAg'
        'aGludDogc3RyaW5nOwp9Cgpjb25zdCBOQVY6IE5hdkl0ZW1bXSA9IFsKICB7IGhyZWY6ICcvdjIn'
        'LCAgICAgICAgICAgbGFiZWw6ICdJbsOtY2lvJywgICAgIGhpbnQ6ICdHIEgnIH0sCiAgeyBocmVm'
        'OiAnL3YyL3R3aW4nLCAgICAgIGxhYmVsOiAnVHdpbicsICAgICAgIGhpbnQ6ICdHIFQnIH0sCiAg'
        'eyBocmVmOiAnL3YyL3NlbnNvcnMnLCAgIGxhYmVsOiAnU2Vuc29yZXMnLCAgIGhpbnQ6ICdHIFMn'
        'IH0sCiAgeyBocmVmOiAnL3YyL3Nob3dzJywgICAgIGxhYmVsOiAnU2hvd3MnLCAgICAgIGhpbnQ6'
        'ICdHIFcnIH0sCiAgeyBocmVmOiAnL3YyL29wZXJhdGlvbnMnLGxhYmVsOiAnT3BlcmHDp8O1ZXMn'
        'LCAgaGludDogJ0cgTycgfSwKICB7IGhyZWY6ICcvdjIvY2xlYW5pbmcnLCAgbGFiZWw6ICdMaW1w'
        'ZXphJywgICAgaGludDogJ0cgTCcgfSwKICB7IGhyZWY6ICcvdjIvaW5jaWRlbnRzJywgbGFiZWw6'
        'ICdJbmNpZGVudGVzJywgaGludDogJ0cgSScgfSwKICB7IGhyZWY6ICcvdjIvc2NvcicsICAgICAg'
        'bGFiZWw6ICdTQ09SJywgICAgICAgaGludDogJ0cgQycgfSwKICB7IGhyZWY6ICcvdjIvcGlwZWxp'
        'bmVzJywgbGFiZWw6ICdQaXBlbGluZXMnLCAgaGludDogJ0cgUCcgfSwKICB7IGhyZWY6ICcvdjIv'
        'Y2hhdCcsICAgICAgbGFiZWw6ICdDaGF0JywgICAgICAgaGludDogJ0cgPycgfSwKXTsKCmZ1bmN0'
        'aW9uIHJlYWRSZWNlbnRzKCk6IHN0cmluZ1tdIHsKICBpZiAodHlwZW9mIHdpbmRvdyA9PT0gJ3Vu'
        'ZGVmaW5lZCcpIHJldHVybiBbXTsKICB0cnkgewogICAgY29uc3QgcmF3ID0gbG9jYWxTdG9yYWdl'
        'LmdldEl0ZW0oUkVDRU5UU19LRVkpOwogICAgcmV0dXJuIHJhdyA/IEpTT04ucGFyc2UocmF3KSA6'
        'IFtdOwogIH0gY2F0Y2ggeyByZXR1cm4gW107IH0KfQoKZnVuY3Rpb24gcHVzaFJlY2VudChwYXRo'
        'OiBzdHJpbmcpIHsKICBpZiAodHlwZW9mIHdpbmRvdyA9PT0gJ3VuZGVmaW5lZCcpIHJldHVybjsK'
        'ICB0cnkgewogICAgY29uc3QgY3VyID0gcmVhZFJlY2VudHMoKS5maWx0ZXIoKHApID0+IHAgIT09'
        'IHBhdGgpOwogICAgY3VyLnVuc2hpZnQocGF0aCk7CiAgICBsb2NhbFN0b3JhZ2Uuc2V0SXRlbShS'
        'RUNFTlRTX0tFWSwgSlNPTi5zdHJpbmdpZnkoY3VyLnNsaWNlKDAsIDQpKSk7CiAgfSBjYXRjaCB7'
        'fQp9CgpleHBvcnQgZGVmYXVsdCBmdW5jdGlvbiBUb3BCYXIoKSB7CiAgY29uc3QgcGF0aG5hbWUg'
        'PSB1c2VQYXRobmFtZSgpIHx8ICcvdjInOwogIGNvbnN0IFt0aW1lLCBzZXRUaW1lXSA9IHVzZVN0'
        'YXRlKCcnKTsKICBjb25zdCBbb3Blbiwgc2V0T3Blbl0gPSB1c2VTdGF0ZShmYWxzZSk7CiAgY29u'
        'c3QgW3NlYXJjaCwgc2V0U2VhcmNoXSA9IHVzZVN0YXRlKCcnKTsKICBjb25zdCBbcmVjZW50cywg'
        'c2V0UmVjZW50c10gPSB1c2VTdGF0ZTxzdHJpbmdbXT4oW10pOwogIC8vIEtQSXMgbGl2ZSB2aWEg'
        'dXNlTGl2ZSgpIOKAlCBzaW5nbGUgc291cmNlIG9mIHRydXRoIGRvIHYyL2xheW91dCBMaXZlUHJv'
        'dmlkZXIKICBjb25zdCB7IHRvdGFsUGVzc29hczogbGl2ZVBlb3BsZSwgYXZnT2NjOiBsaXZlT2Nj'
        'LCBjb25uZWN0aW9uIH0gPSB1c2VMaXZlKCk7CiAgY29uc3Qgc2VhcmNoUmVmID0gdXNlUmVmPEhU'
        'TUxJbnB1dEVsZW1lbnQ+KG51bGwpOwoKICB1c2VFZmZlY3QoKCkgPT4gewogICAgY29uc3QgdGlj'
        'ayA9ICgpID0+IHsKICAgICAgY29uc3QgZCA9IG5ldyBEYXRlKCk7CiAgICAgIHNldFRpbWUoYCR7'
        'U3RyaW5nKGQuZ2V0SG91cnMoKSkucGFkU3RhcnQoMiwnMCcpfToke1N0cmluZyhkLmdldE1pbnV0'
        'ZXMoKSkucGFkU3RhcnQoMiwnMCcpfToke1N0cmluZyhkLmdldFNlY29uZHMoKSkucGFkU3RhcnQo'
        'MiwnMCcpfWApOwogICAgfTsKICAgIHRpY2soKTsKICAgIGNvbnN0IGl2ID0gc2V0SW50ZXJ2YWwo'
        'dGljaywgMTAwMCk7CiAgICByZXR1cm4gKCkgPT4gY2xlYXJJbnRlcnZhbChpdik7CiAgfSwgW10p'
        'OwoKICB1c2VFZmZlY3QoKCkgPT4gewogICAgaWYgKHBhdGhuYW1lICYmIHBhdGhuYW1lICE9PSAn'
        'L3YyJykgcHVzaFJlY2VudChwYXRobmFtZSk7CiAgICBzZXRSZWNlbnRzKHJlYWRSZWNlbnRzKCkp'
        'OwogIH0sIFtwYXRobmFtZV0pOwoKICB1c2VFZmZlY3QoKCkgPT4gewogICAgc2V0T3BlbihmYWxz'
        'ZSk7CiAgICBzZXRTZWFyY2goJycpOwogIH0sIFtwYXRobmFtZV0pOwoKICB1c2VFZmZlY3QoKCkg'
        'PT4gewogICAgaWYgKG9wZW4pIHsKICAgICAgZG9jdW1lbnQuYm9keS5zdHlsZS5vdmVyZmxvdyA9'
        'ICdoaWRkZW4nOwogICAgICBzZXRUaW1lb3V0KCgpID0+IHNlYXJjaFJlZi5jdXJyZW50Py5mb2N1'
        'cygpLCAyMjApOwogICAgfSBlbHNlIHsKICAgICAgZG9jdW1lbnQuYm9keS5zdHlsZS5vdmVyZmxv'
        'dyA9ICcnOwogICAgfQogICAgcmV0dXJuICgpID0+IHsgZG9jdW1lbnQuYm9keS5zdHlsZS5vdmVy'
        'ZmxvdyA9ICcnOyB9OwogIH0sIFtvcGVuXSk7CgogIHVzZUVmZmVjdCgoKSA9PiB7CiAgICBpZiAo'
        'IW9wZW4pIHJldHVybjsKICAgIGNvbnN0IG9uS2V5ID0gKGU6IEtleWJvYXJkRXZlbnQpID0+IHsK'
        'ICAgICAgaWYgKGUua2V5ID09PSAnRXNjYXBlJykgc2V0T3BlbihmYWxzZSk7CiAgICB9OwogICAg'
        'd2luZG93LmFkZEV2ZW50TGlzdGVuZXIoJ2tleWRvd24nLCBvbktleSk7CiAgICByZXR1cm4gKCkg'
        'PT4gd2luZG93LnJlbW92ZUV2ZW50TGlzdGVuZXIoJ2tleWRvd24nLCBvbktleSk7CiAgfSwgW29w'
        'ZW5dKTsKCiAgY29uc3QgaXNBY3RpdmUgPSB1c2VDYWxsYmFjaygoaHJlZjogc3RyaW5nKSA9Pgog'
        'ICAgaHJlZiA9PT0gJy92MicgPyBwYXRobmFtZSA9PT0gJy92MicgOiBwYXRobmFtZS5zdGFydHNX'
        'aXRoKGhyZWYpLAogIFtwYXRobmFtZV0pOwoKICBjb25zdCBmaWx0ZXJlZCA9IHVzZU1lbW8oKCkg'
        'PT4gewogICAgY29uc3QgcSA9IHNlYXJjaC50cmltKCkudG9Mb3dlckNhc2UoKTsKICAgIGlmICgh'
        'cSkgcmV0dXJuIE5BVjsKICAgIHJldHVybiBOQVYuZmlsdGVyKChuKSA9PgogICAgICBuLmxhYmVs'
        'LnRvTG93ZXJDYXNlKCkuaW5jbHVkZXMocSkgfHwgbi5ocmVmLnRvTG93ZXJDYXNlKCkuaW5jbHVk'
        'ZXMocSkKICAgICk7CiAgfSwgW3NlYXJjaF0pOwoKICBjb25zdCByZWNlbnRJdGVtcyA9IHVzZU1l'
        'bW8oKCkgPT4gewogICAgcmV0dXJuIHJlY2VudHMKICAgICAgLm1hcCgocGF0aCkgPT4gTkFWLmZp'
        'bmQoKG4pID0+IG4uaHJlZiA9PT0gcGF0aCkpCiAgICAgIC5maWx0ZXIoQm9vbGVhbikgYXMgTmF2'
        'SXRlbVtdOwogIH0sIFtyZWNlbnRzXSk7CgogIHJldHVybiAoCiAgICA8PgogICAgICA8aGVhZGVy'
        'CiAgICAgICAgc3R5bGU9e3sKICAgICAgICAgIHBvc2l0aW9uOiAnZml4ZWQnLCB0b3A6IDAsIGxl'
        'ZnQ6IDAsIHJpZ2h0OiAwLAogICAgICAgICAgaGVpZ2h0OiAndmFyKC0taGVhZGVyLWgsIDcycHgp'
        'JywKICAgICAgICAgIGJhY2tncm91bmQ6ICdyZ2JhKDI1NSwgMjU1LCAyNTUsIDAuOTQpJywKICAg'
        'ICAgICAgIGJhY2tkcm9wRmlsdGVyOiAnYmx1cigxNnB4KSBzYXR1cmF0ZSgxNDAlKScsCiAgICAg'
        'ICAgICBXZWJraXRCYWNrZHJvcEZpbHRlcjogJ2JsdXIoMTZweCkgc2F0dXJhdGUoMTQwJSknLAog'
        'ICAgICAgICAgYm9yZGVyQm90dG9tOiAnMXB4IHNvbGlkIHZhcigtLWJvcmRlciknLAogICAgICAg'
        'ICAgekluZGV4OiAxMDAsCiAgICAgICAgICBkaXNwbGF5OiAnZmxleCcsCiAgICAgICAgICBhbGln'
        'bkl0ZW1zOiAnY2VudGVyJywKICAgICAgICAgIHBhZGRpbmc6ICcwIGNsYW1wKDE0cHgsIDN2dywg'
        'MzJweCknLAogICAgICAgICAgZ2FwOiAnY2xhbXAoMTBweCwgMnZ3LCAyNHB4KScsCiAgICAgICAg'
        'fX0KICAgICAgPgogICAgICAgIHsvKiBMT0dPICsgQlJBTkQg4oCUIHNlbXByZSDDoCBlc3F1ZXJk'
        'YSAqL30KICAgICAgICA8TGluawogICAgICAgICAgaHJlZj0iL3YyIgogICAgICAgICAgc3R5bGU9'
        'e3sKICAgICAgICAgICAgZGlzcGxheTogJ2ZsZXgnLCBhbGlnbkl0ZW1zOiAnY2VudGVyJywgZ2Fw'
        'OiAxMCwKICAgICAgICAgICAgdGV4dERlY29yYXRpb246ICdub25lJywgZmxleFNocmluazogMCwg'
        'bWluV2lkdGg6IDAsCiAgICAgICAgICB9fQogICAgICAgID4KICAgICAgICAgIDxpbWcKICAgICAg'
        'ICAgICAgc3JjPSIvcGxhbnRhLWxvZ28uc3ZnIgogICAgICAgICAgICBhbHQ9IlBsYW50YSBTbWFy'
        'dCBIb21lcyIKICAgICAgICAgICAgc3R5bGU9e3sKICAgICAgICAgICAgICB3aWR0aDogJ2NsYW1w'
        'KDM2cHgsIDR2dywgNDRweCknLAogICAgICAgICAgICAgIGhlaWdodDogJ2NsYW1wKDM2cHgsIDR2'
        'dywgNDRweCknLAogICAgICAgICAgICAgIGRpc3BsYXk6ICdibG9jaycsIG9iamVjdEZpdDogJ2Nv'
        'bnRhaW4nLCBmbGV4U2hyaW5rOiAwLAogICAgICAgICAgICB9fQogICAgICAgICAgLz4KICAgICAg'
        'ICAgIDxzcGFuCiAgICAgICAgICAgIGNsYXNzTmFtZT0idG9wYmFyLWJyYW5kIgogICAgICAgICAg'
        'ICBzdHlsZT17ewogICAgICAgICAgICAgIGZvbnRTaXplOiAnY2xhbXAoMTRweCwgMS40dncsIDE4'
        'cHgpJywKICAgICAgICAgICAgICBmb250V2VpZ2h0OiA2MDAsCiAgICAgICAgICAgICAgY29sb3I6'
        'ICd2YXIoLS1pbmspJywKICAgICAgICAgICAgICBsZXR0ZXJTcGFjaW5nOiAnLTAuMDJlbScsCiAg'
        'ICAgICAgICAgICAgd2hpdGVTcGFjZTogJ25vd3JhcCcsCiAgICAgICAgICAgICAgZm9udEZhbWls'
        'eTogJ3ZhcigtLWZvbnQtZGlzcGxheSwgSW50ZXIsIHNhbnMtc2VyaWYpJywKICAgICAgICAgICAg'
        'ICBvdmVyZmxvdzogJ2hpZGRlbicsIHRleHRPdmVyZmxvdzogJ2VsbGlwc2lzJywKICAgICAgICAg'
        'ICAgfX0KICAgICAgICAgID4KICAgICAgICAgICAgUGxhbnRhIFNtYXJ0IEhvbWVzCiAgICAgICAg'
        'ICA8L3NwYW4+CiAgICAgICAgPC9MaW5rPgoKICAgICAgICB7LyogTmF2IGRlc2t0b3AgT1Ugc3Bh'
        'Y2VyIGZsZXggZW0gbW9iaWxlICovfQogICAgICAgIDxuYXYKICAgICAgICAgIGNsYXNzTmFtZT0i'
        'dG9wYmFyLW5hdi1kZXNrdG9wIgogICAgICAgICAgc3R5bGU9e3sKICAgICAgICAgICAgZGlzcGxh'
        'eTogJ2ZsZXgnLCBnYXA6IDIsIGZsZXg6IDEsCiAgICAgICAgICAgIG92ZXJmbG93WDogJ2F1dG8n'
        'LAogICAgICAgICAgICBzY3JvbGxiYXJXaWR0aDogJ25vbmUnLAogICAgICAgICAgICBtc092ZXJm'
        'bG93U3R5bGU6ICdub25lJywKICAgICAgICAgICAganVzdGlmeUNvbnRlbnQ6ICdmbGV4LWVuZCcs'
        'CiAgICAgICAgICB9fQogICAgICAgID4KICAgICAgICAgIHtOQVYuc2xpY2UoMCwgOSkubWFwKChp'
        'dGVtKSA9PiB7CiAgICAgICAgICAgIGNvbnN0IGFjdGl2ZSA9IGlzQWN0aXZlKGl0ZW0uaHJlZik7'
        'CiAgICAgICAgICAgIHJldHVybiAoCiAgICAgICAgICAgICAgPExpbmsKICAgICAgICAgICAgICAg'
        'IGtleT17aXRlbS5ocmVmfQogICAgICAgICAgICAgICAgaHJlZj17aXRlbS5ocmVmfQogICAgICAg'
        'ICAgICAgICAgc3R5bGU9e3sKICAgICAgICAgICAgICAgICAgcGFkZGluZzogJzZweCAxMnB4JywK'
        'ICAgICAgICAgICAgICAgICAgYm9yZGVyUmFkaXVzOiA4LAogICAgICAgICAgICAgICAgICB0ZXh0'
        'RGVjb3JhdGlvbjogJ25vbmUnLAogICAgICAgICAgICAgICAgICBmb250U2l6ZTogMTMuNSwKICAg'
        'ICAgICAgICAgICAgICAgZm9udFdlaWdodDogYWN0aXZlID8gNjAwIDogNTAwLAogICAgICAgICAg'
        'ICAgICAgICBjb2xvcjogYWN0aXZlID8gJ3ZhcigtLWluayknIDogJ3ZhcigtLW11dGVkKScsCiAg'
        'ICAgICAgICAgICAgICAgIGJhY2tncm91bmQ6IGFjdGl2ZSA/ICd2YXIoLS1iZy1zb2Z0KScgOiAn'
        'dHJhbnNwYXJlbnQnLAogICAgICAgICAgICAgICAgICB3aGl0ZVNwYWNlOiAnbm93cmFwJywKICAg'
        'ICAgICAgICAgICAgICAgbGV0dGVyU3BhY2luZzogJy0wLjAwNWVtJywKICAgICAgICAgICAgICAg'
        'ICAgdHJhbnNpdGlvbjogJ2NvbG9yIDAuMTRzLCBiYWNrZ3JvdW5kIDAuMTRzJywKICAgICAgICAg'
        'ICAgICAgIH19CiAgICAgICAgICAgICAgPgogICAgICAgICAgICAgICAge2l0ZW0ubGFiZWx9CiAg'
        'ICAgICAgICAgICAgPC9MaW5rPgogICAgICAgICAgICApOwogICAgICAgICAgfSl9CiAgICAgICAg'
        'PC9uYXY+CgogICAgICAgIHsvKiBTcGFjZXIgYXBlbmFzIGVtIG1vYmlsZSDigJQgZW1wdXJyYSBo'
        'YW1idXJnZXIgcGFyYSBhIGRpcmVpdGEgKi99CiAgICAgICAgPHNwYW4KICAgICAgICAgIGNsYXNz'
        'TmFtZT0idG9wYmFyLW1vYmlsZS1zcGFjZXIiCiAgICAgICAgICBzdHlsZT17eyBkaXNwbGF5OiAn'
        'bm9uZScsIGZsZXg6IDEgfX0KICAgICAgICAgIGFyaWEtaGlkZGVuPSJ0cnVlIgogICAgICAgIC8+'
        'CgogICAgICAgIHsvKiBSaWdodCBjbHVzdGVyIGRlc2t0b3AgKi99CiAgICAgICAgPGRpdgogICAg'
        'ICAgICAgY2xhc3NOYW1lPSJ0b3BiYXItcmlnaHQtZGVza3RvcCIKICAgICAgICAgIHN0eWxlPXt7'
        'IGRpc3BsYXk6ICdmbGV4JywgYWxpZ25JdGVtczogJ2NlbnRlcicsIGdhcDogMTAsIGZsZXhTaHJp'
        'bms6IDAgfX0KICAgICAgICA+CiAgICAgICAgICA8c3BhbiBjbGFzc05hbWU9InBpbGwgcGlsbC1z'
        'aW0iIHRpdGxlPSJTaW11bGFkbyDCtyBzZW5zb3JlcyAxMeKAkzEyIEp1biI+U0lNVUxBRE88L3Nw'
        'YW4+CiAgICAgICAgICA8c3BhbgogICAgICAgICAgICBjbGFzc05hbWU9Im1vbm8iCiAgICAgICAg'
        'ICAgIHN0eWxlPXt7CiAgICAgICAgICAgICAgZm9udFNpemU6IDExLjUsCiAgICAgICAgICAgICAg'
        'Y29sb3I6ICd2YXIoLS1mYWludCknLAogICAgICAgICAgICAgIG1pbldpZHRoOiA2NCwKICAgICAg'
        'ICAgICAgICB0ZXh0QWxpZ246ICdyaWdodCcsCiAgICAgICAgICAgICAgZm9udFZhcmlhbnROdW1l'
        'cmljOiAndGFidWxhci1udW1zJywKICAgICAgICAgICAgfX0KICAgICAgICAgID4KICAgICAgICAg'
        'ICAge3RpbWV9CiAgICAgICAgICA8L3NwYW4+CiAgICAgICAgPC9kaXY+CgogICAgICAgIHsvKiBI'
        'QU1CVVJHRVIgVkVHR0lFIOKAlCB2ZXJkZSBlc2N1cm8gUGxhbnRhIGNvbSBsaW5oYXMgY3JlbWUg'
        '4oCUIMOgIERJUkVJVEEgKi99CiAgICAgICAgPGJ1dHRvbgogICAgICAgICAgY2xhc3NOYW1lPSJ0'
        'b3BiYXItYnVyZ2VyIgogICAgICAgICAgb25DbGljaz17KCkgPT4gc2V0T3BlbigodikgPT4gIXYp'
        'fQogICAgICAgICAgYXJpYS1sYWJlbD17b3BlbiA/ICdGZWNoYXIgbWVudScgOiAnQWJyaXIgbWVu'
        'dSd9CiAgICAgICAgICBhcmlhLWV4cGFuZGVkPXtvcGVufQogICAgICAgICAgc3R5bGU9e3sKICAg'
        'ICAgICAgICAgZGlzcGxheTogJ25vbmUnLAogICAgICAgICAgICB3aWR0aDogNDQsIGhlaWdodDog'
        'NDQsCiAgICAgICAgICAgIGJhY2tncm91bmQ6IG9wZW4gPyAndmFyKC0taW5rLCAjMEQxQTBGKScg'
        'OiAndmFyKC0tZ3JlZW4tZGFyaywgIzFCM0EyMSknLAogICAgICAgICAgICBib3JkZXI6ICdub25l'
        'JywKICAgICAgICAgICAgYm9yZGVyUmFkaXVzOiAxMiwKICAgICAgICAgICAgY3Vyc29yOiAncG9p'
        'bnRlcicsCiAgICAgICAgICAgIGNvbG9yOiAnI0Y1RjNFQycsCiAgICAgICAgICAgIGFsaWduSXRl'
        'bXM6ICdjZW50ZXInLAogICAgICAgICAgICBqdXN0aWZ5Q29udGVudDogJ2NlbnRlcicsCiAgICAg'
        'ICAgICAgIGZsZXhTaHJpbms6IDAsCiAgICAgICAgICAgIHBhZGRpbmc6IDAsCiAgICAgICAgICAg'
        'IHBvc2l0aW9uOiAncmVsYXRpdmUnLAogICAgICAgICAgICBib3hTaGFkb3c6IG9wZW4KICAgICAg'
        'ICAgICAgICA/ICcwIDRweCAxNHB4IHJnYmEoMTMsIDI2LCAxNSwgMC4yOCknCiAgICAgICAgICAg'
        'ICAgOiAnMCAycHggMTBweCByZ2JhKDI3LCA1OCwgMzMsIDAuMjIpJywKICAgICAgICAgICAgdHJh'
        'bnNpdGlvbjogJ2JhY2tncm91bmQgMC4yNHMsIGJveC1zaGFkb3cgMC4yNHMsIHRyYW5zZm9ybSAw'
        'LjE4cycsCiAgICAgICAgICB9fQogICAgICAgICAgb25Nb3VzZURvd249eyhlKSA9PiB7IGUuY3Vy'
        'cmVudFRhcmdldC5zdHlsZS50cmFuc2Zvcm0gPSAnc2NhbGUoMC45NCknOyB9fQogICAgICAgICAg'
        'b25Nb3VzZVVwPXsoZSkgPT4geyBlLmN1cnJlbnRUYXJnZXQuc3R5bGUudHJhbnNmb3JtID0gJ3Nj'
        'YWxlKDEpJzsgfX0KICAgICAgICAgIG9uTW91c2VMZWF2ZT17KGUpID0+IHsgZS5jdXJyZW50VGFy'
        'Z2V0LnN0eWxlLnRyYW5zZm9ybSA9ICdzY2FsZSgxKSc7IH19CiAgICAgICAgPgogICAgICAgICAg'
        'PEJ1cmdlckljb24gb3Blbj17b3Blbn0gLz4KICAgICAgICA8L2J1dHRvbj4KICAgICAgPC9oZWFk'
        'ZXI+CgogICAgICB7LyogQkFDS0RST1AgKi99CiAgICAgIDxkaXYKICAgICAgICBjbGFzc05hbWU9'
        'InRvcGJhci1iYWNrZHJvcCIKICAgICAgICBvbkNsaWNrPXsoKSA9PiBzZXRPcGVuKGZhbHNlKX0K'
        'ICAgICAgICBzdHlsZT17ewogICAgICAgICAgcG9zaXRpb246ICdmaXhlZCcsIGluc2V0OiAwLAog'
        'ICAgICAgICAgYmFja2dyb3VuZDogJ3JnYmEoMTMsIDI2LCAxNSwgMC40MiknLAogICAgICAgICAg'
        'YmFja2Ryb3BGaWx0ZXI6ICdibHVyKDhweCknLAogICAgICAgICAgV2Via2l0QmFja2Ryb3BGaWx0'
        'ZXI6ICdibHVyKDhweCknLAogICAgICAgICAgekluZGV4OiA5OCwKICAgICAgICAgIG9wYWNpdHk6'
        'IG9wZW4gPyAxIDogMCwKICAgICAgICAgIHBvaW50ZXJFdmVudHM6IG9wZW4gPyAnYXV0bycgOiAn'
        'bm9uZScsCiAgICAgICAgICB0cmFuc2l0aW9uOiAnb3BhY2l0eSAwLjI4cyBjdWJpYy1iZXppZXIo'
        'MC4zMiwgMC43MiwgMCwgMSknLAogICAgICAgIH19CiAgICAgICAgYXJpYS1oaWRkZW49InRydWUi'
        'CiAgICAgIC8+CgogICAgICB7LyogRFJBV0VSIOKAlCBhZ29yYSB2ZW0gZGEgRElSRUlUQSBwb3Jx'
        'dWUgbyBoYW1idXJnZXIgZXN0w6Egw6AgZGlyZWl0YSAqL30KICAgICAgPGFzaWRlCiAgICAgICAg'
        'Y2xhc3NOYW1lPSJ0b3BiYXItZHJhd2VyIgogICAgICAgIHJvbGU9ImRpYWxvZyIKICAgICAgICBh'
        'cmlhLW1vZGFsPSJ0cnVlIgogICAgICAgIGFyaWEtbGFiZWw9Ik1lbnUgZGUgbmF2ZWdhw6fDo28i'
        'CiAgICAgICAgc3R5bGU9e3sKICAgICAgICAgIHBvc2l0aW9uOiAnZml4ZWQnLAogICAgICAgICAg'
        'dG9wOiAwLCByaWdodDogMCwgYm90dG9tOiAwLAogICAgICAgICAgd2lkdGg6ICdtaW4oMzYwcHgs'
        'IDkwdncpJywKICAgICAgICAgIGJhY2tncm91bmQ6ICd3aGl0ZScsCiAgICAgICAgICB6SW5kZXg6'
        'IDk5LAogICAgICAgICAgYm94U2hhZG93OiBvcGVuID8gJy0xMHB4IDAgNjBweCByZ2JhKDEzLCAy'
        'NiwgMTUsIDAuMTgpJyA6ICdub25lJywKICAgICAgICAgIHRyYW5zZm9ybTogb3BlbiA/ICd0cmFu'
        'c2xhdGVYKDApJyA6ICd0cmFuc2xhdGVYKDEwMCUpJywKICAgICAgICAgIHRyYW5zaXRpb246ICd0'
        'cmFuc2Zvcm0gMC4zMnMgY3ViaWMtYmV6aWVyKDAuMzIsIDAuNzIsIDAsIDEpJywKICAgICAgICAg'
        'IGRpc3BsYXk6ICdmbGV4JywKICAgICAgICAgIGZsZXhEaXJlY3Rpb246ICdjb2x1bW4nLAogICAg'
        'ICAgICAgb3ZlcmZsb3c6ICdoaWRkZW4nLAogICAgICAgIH19CiAgICAgID4KICAgICAgICB7Lyog'
        'VE9QTyDigJQgbG9nbyArIGNsb3NlICovfQogICAgICAgIDxkaXYgc3R5bGU9e3sKICAgICAgICAg'
        'IGRpc3BsYXk6ICdmbGV4JywKICAgICAgICAgIGFsaWduSXRlbXM6ICdjZW50ZXInLAogICAgICAg'
        'ICAganVzdGlmeUNvbnRlbnQ6ICdzcGFjZS1iZXR3ZWVuJywKICAgICAgICAgIHBhZGRpbmc6ICcx'
        'OHB4IDIwcHggMTRweCcsCiAgICAgICAgICBib3JkZXJCb3R0b206ICcxcHggc29saWQgdmFyKC0t'
        'Ym9yZGVyKScsCiAgICAgICAgfX0+CiAgICAgICAgICA8ZGl2IHN0eWxlPXt7IGRpc3BsYXk6ICdm'
        'bGV4JywgYWxpZ25JdGVtczogJ2NlbnRlcicsIGdhcDogMTAgfX0+CiAgICAgICAgICAgIDxpbWcg'
        'c3JjPSIvcGxhbnRhLWxvZ28uc3ZnIiBhbHQ9IiIgc3R5bGU9e3sgd2lkdGg6IDMyLCBoZWlnaHQ6'
        'IDMyIH19IC8+CiAgICAgICAgICAgIDxkaXYgc3R5bGU9e3sgZGlzcGxheTogJ2ZsZXgnLCBmbGV4'
        'RGlyZWN0aW9uOiAnY29sdW1uJywgbGluZUhlaWdodDogMS4xIH19PgogICAgICAgICAgICAgIDxz'
        'cGFuIHN0eWxlPXt7CiAgICAgICAgICAgICAgICBmb250U2l6ZTogMTQsIGZvbnRXZWlnaHQ6IDYw'
        'MCwgbGV0dGVyU3BhY2luZzogJy0wLjAxZW0nLAogICAgICAgICAgICAgICAgZm9udEZhbWlseTog'
        'J3ZhcigtLWZvbnQtZGlzcGxheSknLAogICAgICAgICAgICAgIH19PlBsYW50YTwvc3Bhbj4KICAg'
        'ICAgICAgICAgICA8c3BhbiBzdHlsZT17ewogICAgICAgICAgICAgICAgZm9udFNpemU6IDEwLjUs'
        'CiAgICAgICAgICAgICAgICBjb2xvcjogJ3ZhcigtLW11dGVkKScsCiAgICAgICAgICAgICAgICBm'
        'b250RmFtaWx5OiAndmFyKC0tZm9udC1tb25vKScsCiAgICAgICAgICAgICAgICBsZXR0ZXJTcGFj'
        'aW5nOiAnMC4xZW0nLAogICAgICAgICAgICAgICAgdGV4dFRyYW5zZm9ybTogJ3VwcGVyY2FzZScs'
        'CiAgICAgICAgICAgICAgfX0+U21hcnQgSG9tZXM8L3NwYW4+CiAgICAgICAgICAgIDwvZGl2Pgog'
        'ICAgICAgICAgPC9kaXY+CiAgICAgICAgICA8YnV0dG9uCiAgICAgICAgICAgIG9uQ2xpY2s9eygp'
        'ID0+IHNldE9wZW4oZmFsc2UpfQogICAgICAgICAgICBhcmlhLWxhYmVsPSJGZWNoYXIiCiAgICAg'
        'ICAgICAgIHN0eWxlPXt7CiAgICAgICAgICAgICAgd2lkdGg6IDMyLCBoZWlnaHQ6IDMyLAogICAg'
        'ICAgICAgICAgIGJhY2tncm91bmQ6ICd0cmFuc3BhcmVudCcsCiAgICAgICAgICAgICAgYm9yZGVy'
        'OiAnMXB4IHNvbGlkIHZhcigtLWJvcmRlciknLAogICAgICAgICAgICAgIGJvcmRlclJhZGl1czog'
        'OCwKICAgICAgICAgICAgICBjdXJzb3I6ICdwb2ludGVyJywKICAgICAgICAgICAgICBjb2xvcjog'
        'J3ZhcigtLW11dGVkKScsCiAgICAgICAgICAgICAgZGlzcGxheTogJ2ZsZXgnLAogICAgICAgICAg'
        'ICAgIGFsaWduSXRlbXM6ICdjZW50ZXInLAogICAgICAgICAgICAgIGp1c3RpZnlDb250ZW50OiAn'
        'Y2VudGVyJywKICAgICAgICAgICAgICBwYWRkaW5nOiAwLAogICAgICAgICAgICB9fQogICAgICAg'
        'ICAgPgogICAgICAgICAgICA8c3ZnIHdpZHRoPSIxNCIgaGVpZ2h0PSIxNCIgdmlld0JveD0iMCAw'
        'IDI0IDI0IiBmaWxsPSJub25lIiBzdHJva2U9ImN1cnJlbnRDb2xvciIgc3Ryb2tlV2lkdGg9IjIi'
        'IHN0cm9rZUxpbmVjYXA9InJvdW5kIiBzdHJva2VMaW5lam9pbj0icm91bmQiPgogICAgICAgICAg'
        'ICAgIDxsaW5lIHgxPSIxOCIgeTE9IjYiIHgyPSI2IiB5Mj0iMTgiLz48bGluZSB4MT0iNiIgeTE9'
        'IjYiIHgyPSIxOCIgeTI9IjE4Ii8+CiAgICAgICAgICAgIDwvc3ZnPgogICAgICAgICAgPC9idXR0'
        'b24+CiAgICAgICAgPC9kaXY+CgogICAgICAgIHsvKiBLUElzIExJVkUgKi99CiAgICAgICAgPGRp'
        'diBzdHlsZT17ewogICAgICAgICAgcGFkZGluZzogJzE0cHggMjBweCcsCiAgICAgICAgICBib3Jk'
        'ZXJCb3R0b206ICcxcHggc29saWQgdmFyKC0tYm9yZGVyKScsCiAgICAgICAgICBiYWNrZ3JvdW5k'
        'OiAndmFyKC0tYmctc29mdCknLAogICAgICAgIH19PgogICAgICAgICAgPGRpdiBjbGFzc05hbWU9'
        'Im1vbm8iIHN0eWxlPXt7CiAgICAgICAgICAgIGZvbnRTaXplOiA5LjUsIGxldHRlclNwYWNpbmc6'
        'ICcwLjE4ZW0nLAogICAgICAgICAgICB0ZXh0VHJhbnNmb3JtOiAndXBwZXJjYXNlJywgY29sb3I6'
        'ICd2YXIoLS1tdXRlZCknLAogICAgICAgICAgICBtYXJnaW5Cb3R0b206IDgsCiAgICAgICAgICB9'
        'fT4KICAgICAgICAgICAgQWdvcmEgwrcgYW8gc2VndW5kbwogICAgICAgICAgPC9kaXY+CiAgICAg'
        'ICAgICA8ZGl2IHN0eWxlPXt7IGRpc3BsYXk6ICdmbGV4JywgZ2FwOiAxOCwgYWxpZ25JdGVtczog'
        'J2Jhc2VsaW5lJyB9fT4KICAgICAgICAgICAgPGRpdj4KICAgICAgICAgICAgICA8ZGl2IHN0eWxl'
        'PXt7CiAgICAgICAgICAgICAgICBmb250U2l6ZTogMjQsIGZvbnRXZWlnaHQ6IDYwMCwKICAgICAg'
        'ICAgICAgICAgIGxldHRlclNwYWNpbmc6ICctMC4wMjVlbScsCiAgICAgICAgICAgICAgICBsaW5l'
        'SGVpZ2h0OiAxLAogICAgICAgICAgICAgICAgY29sb3I6ICd2YXIoLS1pbmspJywKICAgICAgICAg'
        'ICAgICAgIGZvbnRGYW1pbHk6ICd2YXIoLS1mb250LWRpc3BsYXkpJywKICAgICAgICAgICAgICAg'
        'IGZvbnRWYXJpYW50TnVtZXJpYzogJ3RhYnVsYXItbnVtcycsCiAgICAgICAgICAgICAgfX0+CiAg'
        'ICAgICAgICAgICAgICB7bGl2ZVBlb3BsZSA+IDAgPyBsaXZlUGVvcGxlLnRvTG9jYWxlU3RyaW5n'
        'KCdwdC1QVCcpIDogJ+KAlCd9CiAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICAgPGRp'
        'diBzdHlsZT17eyBmb250U2l6ZTogMTAuNSwgY29sb3I6ICd2YXIoLS1tdXRlZCknLCBtYXJnaW5U'
        'b3A6IDIsIGZvbnRGYW1pbHk6ICd2YXIoLS1mb250LW1vbm8pJywgbGV0dGVyU3BhY2luZzogJzAu'
        'MDhlbScsIHRleHRUcmFuc2Zvcm06ICd1cHBlcmNhc2UnIH19PgogICAgICAgICAgICAgICAgcGVz'
        'c29hcwogICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAg'
        'PGRpdj4KICAgICAgICAgICAgICA8ZGl2IHN0eWxlPXt7CiAgICAgICAgICAgICAgICBmb250U2l6'
        'ZTogMjQsIGZvbnRXZWlnaHQ6IDYwMCwKICAgICAgICAgICAgICAgIGxldHRlclNwYWNpbmc6ICct'
        'MC4wMjVlbScsCiAgICAgICAgICAgICAgICBsaW5lSGVpZ2h0OiAxLAogICAgICAgICAgICAgICAg'
        'Y29sb3I6ICd2YXIoLS1ncmVlbi1kYXJrKScsCiAgICAgICAgICAgICAgICBmb250RmFtaWx5OiAn'
        'dmFyKC0tZm9udC1kaXNwbGF5KScsCiAgICAgICAgICAgICAgICBmb250VmFyaWFudE51bWVyaWM6'
        'ICd0YWJ1bGFyLW51bXMnLAogICAgICAgICAgICAgIH19PgogICAgICAgICAgICAgICAge2xpdmVP'
        'Y2MgPiAwID8gYCR7bGl2ZU9jYy50b0ZpeGVkKDApfSVgIDogJ+KAlCd9CiAgICAgICAgICAgICAg'
        'PC9kaXY+CiAgICAgICAgICAgICAgPGRpdiBzdHlsZT17eyBmb250U2l6ZTogMTAuNSwgY29sb3I6'
        'ICd2YXIoLS1tdXRlZCknLCBtYXJnaW5Ub3A6IDIsIGZvbnRGYW1pbHk6ICd2YXIoLS1mb250LW1v'
        'bm8pJywgbGV0dGVyU3BhY2luZzogJzAuMDhlbScsIHRleHRUcmFuc2Zvcm06ICd1cHBlcmNhc2Un'
        'IH19PgogICAgICAgICAgICAgICAgb2N1cAogICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAg'
        'ICA8L2Rpdj4KICAgICAgICAgICAgPGRpdiBzdHlsZT17eyBtYXJnaW5MZWZ0OiAnYXV0bycgfX0+'
        'CiAgICAgICAgICAgICAgPHNwYW4gY2xhc3NOYW1lPXtjb25uZWN0aW9uID09PSAic3NlIiA/ICJw'
        'aWxsIHBpbGwtbGl2ZSIgOiAicGlsbCBwaWxsLXNpbSJ9IHN0eWxlPXt7IGZvbnRTaXplOiA5IH19'
        'Pntjb25uZWN0aW9uID09PSAic3NlIiA/ICJMSVZFIiA6IGNvbm5lY3Rpb24gPT09ICJwb2xsaW5n'
        'IiA/ICIycyIgOiAiLi4uIn08L3NwYW4+CiAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgPC9k'
        'aXY+CiAgICAgICAgPC9kaXY+CgogICAgICAgIHsvKiBTRUFSQ0ggKi99CiAgICAgICAgPGRpdiBz'
        'dHlsZT17ewogICAgICAgICAgcGFkZGluZzogJzEycHggMjBweCcsCiAgICAgICAgICBib3JkZXJC'
        'b3R0b206ICcxcHggc29saWQgdmFyKC0tYm9yZGVyKScsCiAgICAgICAgfX0+CiAgICAgICAgICA8'
        'ZGl2IHN0eWxlPXt7CiAgICAgICAgICAgIGRpc3BsYXk6ICdmbGV4JywgYWxpZ25JdGVtczogJ2Nl'
        'bnRlcicsIGdhcDogOCwKICAgICAgICAgICAgYmFja2dyb3VuZDogJ3ZhcigtLWJnLXNvZnQpJywK'
        'ICAgICAgICAgICAgYm9yZGVyOiAnMXB4IHNvbGlkIHZhcigtLWJvcmRlciknLAogICAgICAgICAg'
        'ICBib3JkZXJSYWRpdXM6IDEwLAogICAgICAgICAgICBwYWRkaW5nOiAnOHB4IDEycHgnLAogICAg'
        'ICAgICAgfX0+CiAgICAgICAgICAgIDxzdmcgd2lkdGg9IjE0IiBoZWlnaHQ9IjE0IiB2aWV3Qm94'
        'PSIwIDAgMjQgMjQiIGZpbGw9Im5vbmUiIHN0cm9rZT0idmFyKC0tbXV0ZWQpIiBzdHJva2VXaWR0'
        'aD0iMiIgc3Ryb2tlTGluZWNhcD0icm91bmQiIHN0cm9rZUxpbmVqb2luPSJyb3VuZCI+CiAgICAg'
        'ICAgICAgICAgPGNpcmNsZSBjeD0iMTEiIGN5PSIxMSIgcj0iOCIvPjxsaW5lIHgxPSIyMSIgeTE9'
        'IjIxIiB4Mj0iMTYuNjUiIHkyPSIxNi42NSIvPgogICAgICAgICAgICA8L3N2Zz4KICAgICAgICAg'
        'ICAgPGlucHV0CiAgICAgICAgICAgICAgcmVmPXtzZWFyY2hSZWZ9CiAgICAgICAgICAgICAgdHlw'
        'ZT0idGV4dCIKICAgICAgICAgICAgICB2YWx1ZT17c2VhcmNofQogICAgICAgICAgICAgIG9uQ2hh'
        'bmdlPXsoZSkgPT4gc2V0U2VhcmNoKGUudGFyZ2V0LnZhbHVlKX0KICAgICAgICAgICAgICBwbGFj'
        'ZWhvbGRlcj0iUHJvY3VyYXLigKYiCiAgICAgICAgICAgICAgc3R5bGU9e3sKICAgICAgICAgICAg'
        'ICAgIGZsZXg6IDEsCiAgICAgICAgICAgICAgICBib3JkZXI6ICdub25lJywKICAgICAgICAgICAg'
        'ICAgIG91dGxpbmU6ICdub25lJywKICAgICAgICAgICAgICAgIGJhY2tncm91bmQ6ICd0cmFuc3Bh'
        'cmVudCcsCiAgICAgICAgICAgICAgICBmb250U2l6ZTogMTQsCiAgICAgICAgICAgICAgICBmb250'
        'RmFtaWx5OiAnaW5oZXJpdCcsCiAgICAgICAgICAgICAgICBwYWRkaW5nOiAwLAogICAgICAgICAg'
        'ICAgICAgY29sb3I6ICd2YXIoLS1pbmspJywKICAgICAgICAgICAgICAgIG1pbldpZHRoOiAwLAog'
        'ICAgICAgICAgICAgIH19CiAgICAgICAgICAgIC8+CiAgICAgICAgICAgIHtzZWFyY2ggJiYgKAog'
        'ICAgICAgICAgICAgIDxidXR0b24KICAgICAgICAgICAgICAgIG9uQ2xpY2s9eygpID0+IHNldFNl'
        'YXJjaCgnJyl9CiAgICAgICAgICAgICAgICBhcmlhLWxhYmVsPSJMaW1wYXIiCiAgICAgICAgICAg'
        'ICAgICBzdHlsZT17ewogICAgICAgICAgICAgICAgICBiYWNrZ3JvdW5kOiAndHJhbnNwYXJlbnQn'
        'LCBib3JkZXI6ICdub25lJywKICAgICAgICAgICAgICAgICAgY3Vyc29yOiAncG9pbnRlcicsIGNv'
        'bG9yOiAndmFyKC0tbXV0ZWQpJywKICAgICAgICAgICAgICAgICAgZm9udFNpemU6IDExLCBwYWRk'
        'aW5nOiAwLAogICAgICAgICAgICAgICAgICBmb250RmFtaWx5OiAndmFyKC0tZm9udC1tb25vKScs'
        'CiAgICAgICAgICAgICAgICB9fQogICAgICAgICAgICAgID4KICAgICAgICAgICAgICAgIOKclQog'
        'ICAgICAgICAgICAgIDwvYnV0dG9uPgogICAgICAgICAgICApfQogICAgICAgICAgPC9kaXY+CiAg'
        'ICAgICAgPC9kaXY+CgogICAgICAgIHsvKiBMSVNUQSBuYXZlZ8OhdmVsICovfQogICAgICAgIDxk'
        'aXYgc3R5bGU9e3sKICAgICAgICAgIGZsZXg6IDEsCiAgICAgICAgICBvdmVyZmxvd1k6ICdhdXRv'
        'JywKICAgICAgICAgIHBhZGRpbmc6ICcxMnB4IDEycHggMjBweCcsCiAgICAgICAgfX0+CiAgICAg'
        'ICAgICB7IXNlYXJjaCAmJiByZWNlbnRJdGVtcy5sZW5ndGggPiAwICYmICgKICAgICAgICAgICAg'
        'PGRpdiBzdHlsZT17eyBtYXJnaW5Cb3R0b206IDEyLCBwYWRkaW5nOiAnMCA4cHgnIH19PgogICAg'
        'ICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJtb25vIiBzdHlsZT17ewogICAgICAgICAgICAgICAg'
        'Zm9udFNpemU6IDkuNSwgbGV0dGVyU3BhY2luZzogJzAuMThlbScsCiAgICAgICAgICAgICAgICB0'
        'ZXh0VHJhbnNmb3JtOiAndXBwZXJjYXNlJywgY29sb3I6ICd2YXIoLS1tdXRlZCknLAogICAgICAg'
        'ICAgICAgICAgbWFyZ2luOiAnNnB4IDAgNnB4JywKICAgICAgICAgICAgICB9fT4KICAgICAgICAg'
        'ICAgICAgIFJlY2VudGVzCiAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICAge3JlY2Vu'
        'dEl0ZW1zLnNsaWNlKDAsIDMpLm1hcCgoaXRlbSkgPT4gKAogICAgICAgICAgICAgICAgPERyYXdl'
        'ckxpbmsga2V5PXtgci0ke2l0ZW0uaHJlZn1gfSBpdGVtPXtpdGVtfSBhY3RpdmU9e2lzQWN0aXZl'
        'KGl0ZW0uaHJlZil9IHNtYWxsIC8+CiAgICAgICAgICAgICAgKSl9CiAgICAgICAgICAgIDwvZGl2'
        'PgogICAgICAgICAgKX0KCiAgICAgICAgICB7IXNlYXJjaCAmJiByZWNlbnRJdGVtcy5sZW5ndGgg'
        'PiAwICYmICgKICAgICAgICAgICAgPGRpdiBjbGFzc05hbWU9Im1vbm8iIHN0eWxlPXt7CiAgICAg'
        'ICAgICAgICAgZm9udFNpemU6IDkuNSwgbGV0dGVyU3BhY2luZzogJzAuMThlbScsCiAgICAgICAg'
        'ICAgICAgdGV4dFRyYW5zZm9ybTogJ3VwcGVyY2FzZScsIGNvbG9yOiAndmFyKC0tbXV0ZWQpJywK'
        'ICAgICAgICAgICAgICBwYWRkaW5nOiAnNnB4IDE2cHggNnB4JywKICAgICAgICAgICAgfX0+CiAg'
        'ICAgICAgICAgICAgVHVkbwogICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICl9CgogICAgICAg'
        'ICAge2ZpbHRlcmVkLmxlbmd0aCA9PT0gMCAmJiAoCiAgICAgICAgICAgIDxkaXYgc3R5bGU9e3sK'
        'ICAgICAgICAgICAgICBwYWRkaW5nOiAnNDBweCAyMHB4JywKICAgICAgICAgICAgICB0ZXh0QWxp'
        'Z246ICdjZW50ZXInLAogICAgICAgICAgICAgIGNvbG9yOiAndmFyKC0tbXV0ZWQpJywKICAgICAg'
        'ICAgICAgICBmb250U2l6ZTogMTMsCiAgICAgICAgICAgIH19PgogICAgICAgICAgICAgIFNlbSBy'
        'ZXN1bHRhZG9zIHBhcmEgIntzZWFyY2h9IgogICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICl9'
        'CgogICAgICAgICAge2ZpbHRlcmVkLm1hcCgoaXRlbSkgPT4gKAogICAgICAgICAgICA8RHJhd2Vy'
        'TGluayBrZXk9e2l0ZW0uaHJlZn0gaXRlbT17aXRlbX0gYWN0aXZlPXtpc0FjdGl2ZShpdGVtLmhy'
        'ZWYpfSAvPgogICAgICAgICAgKSl9CiAgICAgICAgPC9kaXY+CgogICAgICAgIHsvKiBGT09URVIg'
        'Ki99CiAgICAgICAgPGRpdiBzdHlsZT17ewogICAgICAgICAgcGFkZGluZzogJzEycHggMjBweCcs'
        'CiAgICAgICAgICBib3JkZXJUb3A6ICcxcHggc29saWQgdmFyKC0tYm9yZGVyKScsCiAgICAgICAg'
        'ICBiYWNrZ3JvdW5kOiAndmFyKC0tYmctc29mdCknLAogICAgICAgICAgZGlzcGxheTogJ2ZsZXgn'
        'LAogICAgICAgICAganVzdGlmeUNvbnRlbnQ6ICdzcGFjZS1iZXR3ZWVuJywKICAgICAgICAgIGFs'
        'aWduSXRlbXM6ICdjZW50ZXInLAogICAgICAgICAgZm9udFNpemU6IDExLAogICAgICAgICAgY29s'
        'b3I6ICd2YXIoLS1tdXRlZCknLAogICAgICAgICAgZm9udEZhbWlseTogJ3ZhcigtLWZvbnQtbW9u'
        'byknLAogICAgICAgIH19PgogICAgICAgICAgPHNwYW4gc3R5bGU9e3sgbGV0dGVyU3BhY2luZzog'
        'JzAuMDRlbScgfX0+CiAgICAgICAgICAgIEVTQyBmZWNoYSDCtyB7dGltZX0KICAgICAgICAgIDwv'
        'c3Bhbj4KICAgICAgICAgIDxzcGFuIGNsYXNzTmFtZT0icGlsbCBwaWxsLXNpbSIgc3R5bGU9e3sg'
        'Zm9udFNpemU6IDkgfX0+U0lNPC9zcGFuPgogICAgICAgIDwvZGl2PgogICAgICA8L2FzaWRlPgoK'
        'ICAgICAgPHN0eWxlIGpzeCBnbG9iYWw+e2AKICAgICAgICAudG9wYmFyLW5hdi1kZXNrdG9wOjot'
        'd2Via2l0LXNjcm9sbGJhciB7IGRpc3BsYXk6IG5vbmU7IH0KCiAgICAgICAgQG1lZGlhIChtYXgt'
        'd2lkdGg6IDkyMHB4KSB7CiAgICAgICAgICAudG9wYmFyLW5hdi1kZXNrdG9wIHsgZGlzcGxheTog'
        'bm9uZSAhaW1wb3J0YW50OyB9CiAgICAgICAgICAudG9wYmFyLXJpZ2h0LWRlc2t0b3AgeyBkaXNw'
        'bGF5OiBub25lICFpbXBvcnRhbnQ7IH0KICAgICAgICAgIC50b3BiYXItbW9iaWxlLXNwYWNlciB7'
        'IGRpc3BsYXk6IGJsb2NrICFpbXBvcnRhbnQ7IH0KICAgICAgICAgIC50b3BiYXItYnVyZ2VyIHsg'
        'ZGlzcGxheTogZmxleCAhaW1wb3J0YW50OyB9CiAgICAgICAgfQoKICAgICAgICBAbWVkaWEgKG1h'
        'eC13aWR0aDogMzgwcHgpIHsKICAgICAgICAgIC50b3BiYXItYnJhbmQgewogICAgICAgICAgICBm'
        'b250LXNpemU6IDEzcHggIWltcG9ydGFudDsKICAgICAgICAgICAgbWF4LXdpZHRoOiAxNDBweCAh'
        'aW1wb3J0YW50OwogICAgICAgICAgfQogICAgICAgIH0KCiAgICAgICAgQGtleWZyYW1lcyBwdWxz'
        'ZS1zb2Z0IHsKICAgICAgICAgIDAlLCAxMDAlIHsgb3BhY2l0eTogMTsgdHJhbnNmb3JtOiBzY2Fs'
        'ZSgxKTsgfQogICAgICAgICAgNTAlIHsgb3BhY2l0eTogMC42OyB0cmFuc2Zvcm06IHNjYWxlKDAu'
        'ODUpOyB9CiAgICAgICAgfQogICAgICBgfTwvc3R5bGU+CiAgICA8Lz4KICApOwp9CgovKiDilIDi'
        'lIDilIDilIAgSGFtYnVyZ2VyIFZlZ2dpZSDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDi'
        'lIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDi'
        'lIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAKICAgMyBsaW5o'
        'YXMgY3JlbWUgKCNGNUYzRUMpIHNvYnJlIGZ1bmRvIHZlcmRlIGVzY3VybyBQbGFudGEuCiAgIENh'
        'ZGEgbGluaGEgY29tIGxhcmd1cmEgZGlmZXJlbnRlOiAxOHB4LCAxNHB4LCAxOHB4IOKAlCB0b3F1'
        'ZSBvcmfDom5pY28uCiAgIEFvIGFicmlyLCBhbmltYcOnw6NvIGZsdWlkYSBwYXJhIFguCiAgIOKU'
        'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
        'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
        'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
        'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgCAqLwpmdW5jdGlvbiBCdXJnZXJJY29uKHsgb3Bl'
        'biB9OiB7IG9wZW46IGJvb2xlYW4gfSkgewogIGNvbnN0IGJhc2VMaW5lOiBSZWFjdC5DU1NQcm9w'
        'ZXJ0aWVzID0gewogICAgcG9zaXRpb246ICdhYnNvbHV0ZScsCiAgICBoZWlnaHQ6IDIsCiAgICBi'
        'YWNrZ3JvdW5kOiAnI0Y1RjNFQycsCiAgICBib3JkZXJSYWRpdXM6IDIsCiAgICB0cmFuc2l0aW9u'
        'OiAnYWxsIDAuMzRzIGN1YmljLWJlemllcigwLjMyLCAwLjcyLCAwLCAxKScsCiAgICB0cmFuc2Zv'
        'cm1PcmlnaW46ICdjZW50ZXInLAogIH07CiAgcmV0dXJuICgKICAgIDxzcGFuIHN0eWxlPXt7IHBv'
        'c2l0aW9uOiAncmVsYXRpdmUnLCB3aWR0aDogMjIsIGhlaWdodDogMTQsIGRpc3BsYXk6ICdpbmxp'
        'bmUtYmxvY2snIH19PgogICAgICB7LyogTGluaGEgZGUgY2ltYSAqL30KICAgICAgPHNwYW4gc3R5'
        'bGU9e3sKICAgICAgICAuLi5iYXNlTGluZSwKICAgICAgICB0b3A6IG9wZW4gPyA2IDogMCwKICAg'
        'ICAgICBsZWZ0OiBvcGVuID8gMCA6IDAsCiAgICAgICAgd2lkdGg6IG9wZW4gPyAyMiA6IDE4LAog'
        'ICAgICAgIHRyYW5zZm9ybTogb3BlbiA/ICdyb3RhdGUoNDVkZWcpJyA6ICdyb3RhdGUoMCknLAog'
        'ICAgICB9fSAvPgogICAgICB7LyogTGluaGEgZG8gbWVpbyDigJQgbWFpcyBjdXJ0YSAodG9xdWUg'
        'b3Jnw6JuaWNvKSAqL30KICAgICAgPHNwYW4gc3R5bGU9e3sKICAgICAgICAuLi5iYXNlTGluZSwK'
        'ICAgICAgICB0b3A6IDYsCiAgICAgICAgbGVmdDogb3BlbiA/IDAgOiA0LAogICAgICAgIHdpZHRo'
        'OiBvcGVuID8gMCA6IDE0LAogICAgICAgIG9wYWNpdHk6IG9wZW4gPyAwIDogMSwKICAgICAgfX0g'
        'Lz4KICAgICAgey8qIExpbmhhIGRlIGJhaXhvICovfQogICAgICA8c3BhbiBzdHlsZT17ewogICAg'
        'ICAgIC4uLmJhc2VMaW5lLAogICAgICAgIHRvcDogb3BlbiA/IDYgOiAxMiwKICAgICAgICBsZWZ0'
        'OiBvcGVuID8gMCA6IDAsCiAgICAgICAgd2lkdGg6IG9wZW4gPyAyMiA6IDE4LAogICAgICAgIHRy'
        'YW5zZm9ybTogb3BlbiA/ICdyb3RhdGUoLTQ1ZGVnKScgOiAncm90YXRlKDApJywKICAgICAgfX0g'
        'Lz4KICAgIDwvc3Bhbj4KICApOwp9CgpmdW5jdGlvbiBEcmF3ZXJMaW5rKHsgaXRlbSwgYWN0aXZl'
        'LCBzbWFsbCB9OiB7IGl0ZW06IE5hdkl0ZW07IGFjdGl2ZTogYm9vbGVhbjsgc21hbGw/OiBib29s'
        'ZWFuIH0pIHsKICByZXR1cm4gKAogICAgPExpbmsKICAgICAgaHJlZj17aXRlbS5ocmVmfQogICAg'
        'ICBzdHlsZT17ewogICAgICAgIGRpc3BsYXk6ICdmbGV4JywKICAgICAgICBhbGlnbkl0ZW1zOiAn'
        'Y2VudGVyJywKICAgICAgICBqdXN0aWZ5Q29udGVudDogJ3NwYWNlLWJldHdlZW4nLAogICAgICAg'
        'IGdhcDogMTIsCiAgICAgICAgcGFkZGluZzogc21hbGwgPyAnOHB4IDhweCcgOiAnMTJweCA4cHgn'
        'LAogICAgICAgIGJvcmRlclJhZGl1czogOCwKICAgICAgICB0ZXh0RGVjb3JhdGlvbjogJ25vbmUn'
        'LAogICAgICAgIGJhY2tncm91bmQ6IGFjdGl2ZSA/ICd2YXIoLS1ncmVlbi1wYWxlKScgOiAndHJh'
        'bnNwYXJlbnQnLAogICAgICAgIHRyYW5zaXRpb246ICdiYWNrZ3JvdW5kIDAuMTRzJywKICAgICAg'
        'ICBtYXJnaW5Cb3R0b206IDEsCiAgICAgIH19CiAgICAgIG9uTW91c2VFbnRlcj17KGUpID0+IHsK'
        'ICAgICAgICBpZiAoIWFjdGl2ZSkgZS5jdXJyZW50VGFyZ2V0LnN0eWxlLmJhY2tncm91bmQgPSAn'
        'dmFyKC0tYmctc29mdCknOwogICAgICB9fQogICAgICBvbk1vdXNlTGVhdmU9eyhlKSA9PiB7CiAg'
        'ICAgICAgaWYgKCFhY3RpdmUpIGUuY3VycmVudFRhcmdldC5zdHlsZS5iYWNrZ3JvdW5kID0gJ3Ry'
        'YW5zcGFyZW50JzsKICAgICAgfX0KICAgID4KICAgICAgPGRpdiBzdHlsZT17eyBkaXNwbGF5OiAn'
        'ZmxleCcsIGFsaWduSXRlbXM6ICdjZW50ZXInLCBnYXA6IDEwLCBtaW5XaWR0aDogMCB9fT4KICAg'
        'ICAgICA8c3BhbiBzdHlsZT17ewogICAgICAgICAgd2lkdGg6IDYsIGhlaWdodDogNiwgYm9yZGVy'
        'UmFkaXVzOiAnNTAlJywKICAgICAgICAgIGJhY2tncm91bmQ6IGFjdGl2ZSA/ICd2YXIoLS1ncmVl'
        'bi1kYXJrKScgOiAndmFyKC0tZmFpbnQpJywKICAgICAgICAgIGZsZXhTaHJpbms6IDAsCiAgICAg'
        'ICAgICBvcGFjaXR5OiBhY3RpdmUgPyAxIDogMC40LAogICAgICAgICAgYW5pbWF0aW9uOiBhY3Rp'
        'dmUgPyAncHVsc2Utc29mdCAxLjZzIGVhc2UtaW4tb3V0IGluZmluaXRlJyA6ICdub25lJywKICAg'
        'ICAgICB9fSAvPgogICAgICAgIDxzcGFuIHN0eWxlPXt7CiAgICAgICAgICBmb250U2l6ZTogc21h'
        'bGwgPyAxNCA6IDE2LAogICAgICAgICAgZm9udFdlaWdodDogYWN0aXZlID8gNjAwIDogNTAwLAog'
        'ICAgICAgICAgY29sb3I6ICd2YXIoLS1pbmspJywKICAgICAgICAgIGxldHRlclNwYWNpbmc6ICct'
        'MC4wMWVtJywKICAgICAgICAgIGZvbnRGYW1pbHk6ICd2YXIoLS1mb250LWRpc3BsYXkpJywKICAg'
        'ICAgICB9fT4KICAgICAgICAgIHtpdGVtLmxhYmVsfQogICAgICAgIDwvc3Bhbj4KICAgICAgPC9k'
        'aXY+CiAgICAgIDxzcGFuIHN0eWxlPXt7CiAgICAgICAgZm9udFNpemU6IDEwLAogICAgICAgIGNv'
        'bG9yOiAndmFyKC0tZmFpbnQpJywKICAgICAgICBmb250RmFtaWx5OiAndmFyKC0tZm9udC1tb25v'
        'KScsCiAgICAgICAgbGV0dGVyU3BhY2luZzogJzAuMDZlbScsCiAgICAgICAgcGFkZGluZzogJzJw'
        'eCA2cHgnLAogICAgICAgIGJvcmRlclJhZGl1czogNCwKICAgICAgICBib3JkZXI6ICcxcHggc29s'
        'aWQgdmFyKC0tYm9yZGVyKScsCiAgICAgICAgYmFja2dyb3VuZDogJ3doaXRlJywKICAgICAgICBm'
        'bGV4U2hyaW5rOiAwLAogICAgICB9fT4KICAgICAgICB7aXRlbS5oaW50fQogICAgICA8L3NwYW4+'
        'CiAgICA8L0xpbms+CiAgKTsKfQo='
    ),
}


def sec(m):
    print()
    print("=" * 68)
    print("  " + m)
    print("=" * 68)


def run(cmd, cwd=None):
    print(f"$ {cmd}")
    r = subprocess.run(cmd, shell=True, cwd=cwd, capture_output=True, text=True)
    if r.stdout.strip(): print(r.stdout.rstrip())
    if r.stderr.strip(): print(r.stderr.rstrip(), file=sys.stderr)
    return r.returncode == 0


def setup_favicon_v18(root, stamp):
    """Cria frontend/app/icon.svg (Next.js convention) a partir de LOGO/MAIN LOGO.svg."""
    src = None
    candidates = [
        root / "LOGO" / "MAIN LOGO.svg",
        root / "LOGO" / "MAIN_LOGO.svg",
        root / "LOGO" / "main logo.svg",
        root / "LOGO" / "Main Logo.svg",
    ]
    for cand in candidates:
        if cand.exists():
            src = cand
            break
    if not src:
        existing = root / "frontend" / "public" / "planta-logo.svg"
        if existing.exists():
            src = existing
            print(f"  i LOGO/MAIN LOGO.svg nao encontrado, uso planta-logo.svg")
        else:
            print("  WARN: nenhum SVG encontrado para favicon")
            return False

    svg = src.read_text(encoding="utf-8", errors="ignore")

    # Remover <rect ... fill="white"/> e variantes
    rect_pattern_self = re.compile(
        r'<rect[^>]*fill\s*=\s*["\']\s*(?:#fff(?:fff)?|white)\s*["\'][^>]*/>',
        re.IGNORECASE,
    )
    rect_pattern_pair = re.compile(
        r'<rect[^>]*fill\s*=\s*["\']\s*(?:#fff(?:fff)?|white)\s*["\'][^>]*>.*?</rect>',
        re.IGNORECASE | re.DOTALL,
    )
    svg2 = rect_pattern_self.sub("", svg)
    svg2 = rect_pattern_pair.sub("", svg2)

    if len(svg2) != len(svg):
        print(f"  Removidos elementos de fundo branco ({len(svg) - len(svg2)} B)")

    # Next.js 14 convention: app/icon.svg (auto-discovered)
    icon = root / "frontend" / "app" / "icon.svg"
    if icon.exists():
        shutil.copy2(icon, icon.with_suffix(f".svg.bak.v18.{stamp}"))
    icon.write_text(svg2, encoding="utf-8")
    print(f"  OK frontend/app/icon.svg ({len(svg2)} B)")

    # Tambem actualizar public/favicon.svg por compat
    pub = root / "frontend" / "public" / "favicon.svg"
    pub.parent.mkdir(parents=True, exist_ok=True)
    if pub.exists():
        shutil.copy2(pub, pub.with_suffix(f".svg.bak.v18.{stamp}"))
    pub.write_text(svg2, encoding="utf-8")
    print(f"  OK frontend/public/favicon.svg ({len(svg2)} B)")
    return True


def jitter_backend(root, stamp):
    """Patch leve no cluster_telemetry.py para variar occ_pct +/- 3%."""
    f = root / "app" / "services" / "cluster_telemetry.py"
    if not f.exists():
        print("  i cluster_telemetry.py nao encontrado, skip jitter")
        return False
    c = f.read_text()
    if "v18-jitter" in c:
        print("  i jitter ja aplicado, skip")
        return True
    shutil.copy2(f, f.with_suffix(f".py.bak.v18.{stamp}"))

    if "import random" not in c:
        c = c.replace("import time\n", "import time\nimport random  # v18-jitter\n", 1)

    pattern = 'occ_pct = float(sec.get("ocupacao_pct", 0))'
    if pattern in c:
        jitter_code = (
            'occ_pct = float(sec.get("ocupacao_pct", 0))\n'
            '        # v18-jitter: +/- 3% para evitar steady state visual\n'
            '        occ_pct = max(0.0, min(100.0, occ_pct * (1 + random.uniform(-0.03, 0.03))))'
        )
        c = c.replace(pattern, jitter_code, 1)
        f.write_text(c)
        print("  OK jitter +/-3% aplicado a occ_pct")
        return True
    print("  i pattern nao encontrado, skip jitter")
    return False


def main():
    root = Path.cwd()
    if not (root / "frontend").exists():
        print("ERRO: corre a partir de ~/planta_rock4")
        sys.exit(1)
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    sec("1. ESCREVER 4 FICHEIROS FRONTEND")
    for rel, chunks in FILES.items():
        t = root / rel
        t.parent.mkdir(parents=True, exist_ok=True)
        if t.exists():
            shutil.copy2(t, t.with_suffix(f"{t.suffix}.bak.v18.{stamp}"))
        d = base64.b64decode("".join(chunks))
        t.write_bytes(d)
        print(f"  OK {rel}  ({len(d)} B)")

    sec("2. FAVICON Next.js convention")
    setup_favicon_v18(root, stamp)

    sec("3. BACKEND JITTER (opcional)")
    jitter_backend(root, stamp)

    sec("4. GIT FORCAR ADD + COMMIT + PUSH")
    run("git add -f frontend/components/v2/LiveContext.tsx frontend/components/v2/TopBar.tsx frontend/app/v2/layout.tsx frontend/app/v2/page.tsx frontend/app/icon.svg frontend/public/favicon.svg app/services/cluster_telemetry.py", cwd=str(root))
    run("git add -f CLAUDE.md README.md docs/ 2>/dev/null || true", cwd=str(root))
    print("")
    print("Status pendente:")
    run("git status --short | grep -vE '\\.bak|install_v|\\.DS_Store|LOGO/|Sensors/|infrastructure/|check\\.sh' | head -20", cwd=str(root))
    run('git commit -m "feat(v18): singleton SSE LiveProvider + favicon Next convention + jitter"', cwd=str(root))
    run("git push", cwd=str(root))

    sec("5. PRONTO")
    print("")
    print("  Singleton SSE ACTIVO em /v2.")
    print("  /v2 (home) e o drawer do TopBar mostram os MESMOS numeros, mesmo tick.")
    print("")
    print("  Aguarda ~90s e CMD+SHIFT+R em www.plantarockinrio.com/v2")
    print("")
    print("  Teste:")
    print("    1. /v2: ve total de pessoas (ex: 381)")
    print("    2. Click no hamburger: drawer abre, ve KPI 'pessoas'")
    print("    3. Esse numero TEM que ser exactamente o mesmo (381).")
    print("")


if __name__ == "__main__":
    main()
