#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
install_v24 — JAMAIS resposta estupida do Gemini + chat estilo WhatsApp
"""

import base64, os, re, shutil, subprocess, sys
from datetime import datetime
from pathlib import Path

os.environ["PATH"] = ":".join([
    "/usr/bin", "/bin", "/usr/sbin", "/sbin",
    "/usr/local/bin", "/opt/homebrew/bin",
    os.environ.get("PATH", ""),
])

CHAT_PAGE_B64 = (
    'J3VzZSBjbGllbnQnOwoKaW1wb3J0IHsgU3VzcGVuc2UsIHVzZUVmZmVjdCwgdXNlUmVmLCB1c2VT'
    'dGF0ZSB9IGZyb20gJ3JlYWN0JzsKaW1wb3J0IHsgdXNlUm91dGVyLCB1c2VTZWFyY2hQYXJhbXMg'
    'fSBmcm9tICduZXh0L25hdmlnYXRpb24nOwppbXBvcnQgeyB1c2VMaXZlLCB0eXBlIExpdmVTbmFw'
    'c2hvdCB9IGZyb20gJ0AvY29tcG9uZW50cy92Mi9MaXZlQ29udGV4dCc7Cgpjb25zdCBBUElfQkFT'
    'RSA9IHByb2Nlc3MuZW52Lk5FWFRfUFVCTElDX0FQSV9CQVNFIHx8ICdodHRwczovL2FwaS5wbGFu'
    'dGFyb2NraW5yaW8uY29tJzsKY29uc3QgU1RPUkFHRV9LRVkgPSAncGxhbnRhLWNoYXQtaGlzdG9y'
    'eS12MSc7CmNvbnN0IEFUVEFDSF9LRVkgPSAncGxhbnRhLXBlbmRpbmctaW1hZ2UnOwoKaW50ZXJm'
    'YWNlIE1zZyB7CiAgcm9sZTogJ3VzZXInIHwgJ2Fzc2lzdGFudCc7CiAgY29udGVudDogc3RyaW5n'
    'OwogIHRzOiBudW1iZXI7Cn0KCi8qIOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
    'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
    'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
    'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgAogICBMT0NB'
    'TCBST1VUSU5HIOKAlCBkZXRlcm1pbsOtc3RpY28sIG51bmNhIGRlcGVuZGVudGUgZG8gTExNCiAg'
    'IOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
    'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
    'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
    'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgCAqLwoKLy8gQ2VudHJvaWQgYXByb3hpbWFkbyBk'
    'byBQYXJxdWUgVGVqbyAoTGlzYm9hKQpjb25zdCBWRU5VRV9DRU5UUk9JRCA9IHsgbGF0OiAzOC43'
    'NjM2LCBsbmc6IC05LjA5NTYgfTsKCi8vIENvbnZlcnPDo28gbWV0cm9zIOKGlCBncmF1cywgYmFz'
    'ZWFkYSBlbSBQYWxjbyBNdW5kbyBjb21vIG9yaWdlbQpjb25zdCBNRVRFUl9QRVJfREVHX0xBVCA9'
    'IDExMTMyMDsKY29uc3QgTUVURVJfUEVSX0RFR19MTkcgPSAxMTEzMjAgKiBNYXRoLmNvcygoVkVO'
    'VUVfQ0VOVFJPSUQubGF0ICogTWF0aC5QSSkgLyAxODApOwoKLy8gUG9zacOnw7VlcyBkb3MgOCBj'
    'bHVzdGVycyByZWxhdGl2YXMgYW8gUGFsY28gTXVuZG8gKGVtIG1ldHJvcykKY29uc3QgQ0xVU1RF'
    'UlM6IFJlY29yZDxzdHJpbmcsIHsgeF9tOiBudW1iZXI7IHlfbTogbnVtYmVyOyB6b25lOiBzdHJp'
    'bmcgfT4gPSB7CiAgJ3djLTAxJzogeyB4X206IC0zODAsIHlfbTogMTIwLCAgem9uZTogJ0VudHJh'
    'ZGEgTlcnIH0sCiAgJ3djLTAyJzogeyB4X206IDgwLCAgIHlfbTogLTMwLCAgem9uZTogJ0p1bnRv'
    'IGFvIHBhbGNvJyB9LAogICd3Yy0wMyc6IHsgeF9tOiAtMTAwLCB5X206IDgwLCAgIHpvbmU6ICdD'
    'ZW50cmFsJyB9LAogICd3Yy0wNCc6IHsgeF9tOiAtMjAwLCB5X206IDIwMCwgIHpvbmU6ICdFbGV2'
    'YWRvIG1pZCcgfSwKICAnd2MtMDUnOiB7IHhfbTogMjUwLCAgeV9tOiAxODAsICB6b25lOiAnRWxl'
    'dmFkbyBsZXN0ZSAodW5pc3NleCknIH0sCiAgJ3djLTA2JzogeyB4X206IC01MCwgIHlfbTogMjUw'
    'LCAgem9uZTogJ0NlbnRyYWwgbm9ydGUgKHVuaXNzZXggZ3JhbmRlKScgfSwKICAnd2MtMDcnOiB7'
    'IHhfbTogLTMwMCwgeV9tOiAtODAsICB6b25lOiAnTlcgwrcgbG9ja2VycycgfSwKICAnd2MtMDgn'
    'OiB7IHhfbTogMzUwLCAgeV9tOiAzMDAsICB6b25lOiAnT3V0ZXIgbGVzdGUnIH0sCn07Cgpjb25z'
    'dCBDT09SRFNfUkVHRVggPSAvKC0/XGR7MSwzfVwuXGR7Miw4fSlccyosXHMqKC0/XGR7MSwzfVwu'
    'XGR7Miw4fSkvOwoKZnVuY3Rpb24gZGV0ZWN0Q29vcmRzKHRleHQ6IHN0cmluZyk6IHsgbGF0OiBu'
    'dW1iZXI7IGxuZzogbnVtYmVyIH0gfCBudWxsIHsKICBjb25zdCBtID0gdGV4dC5tYXRjaChDT09S'
    'RFNfUkVHRVgpOwogIGlmICghbSkgcmV0dXJuIG51bGw7CiAgY29uc3QgbGF0ID0gcGFyc2VGbG9h'
    'dChtWzFdKTsKICBjb25zdCBsbmcgPSBwYXJzZUZsb2F0KG1bMl0pOwogIGlmIChOdW1iZXIuaXNO'
    'YU4obGF0KSB8fCBOdW1iZXIuaXNOYU4obG5nKSkgcmV0dXJuIG51bGw7CiAgaWYgKE1hdGguYWJz'
    'KGxhdCkgPiA5MCB8fCBNYXRoLmFicyhsbmcpID4gMTgwKSByZXR1cm4gbnVsbDsKICByZXR1cm4g'
    'eyBsYXQsIGxuZyB9Owp9CgpmdW5jdGlvbiBjbHVzdGVyUG9zKGNpZDogc3RyaW5nKTogeyBsYXQ6'
    'IG51bWJlcjsgbG5nOiBudW1iZXIgfSB7CiAgY29uc3QgYyA9IENMVVNURVJTW2NpZF07CiAgaWYg'
    'KCFjKSByZXR1cm4gVkVOVUVfQ0VOVFJPSUQ7CiAgcmV0dXJuIHsKICAgIGxhdDogVkVOVUVfQ0VO'
    'VFJPSUQubGF0ICsgYy55X20gLyBNRVRFUl9QRVJfREVHX0xBVCwKICAgIGxuZzogVkVOVUVfQ0VO'
    'VFJPSUQubG5nICsgYy54X20gLyBNRVRFUl9QRVJfREVHX0xORywKICB9Owp9CgpmdW5jdGlvbiBo'
    'YXZlcnNpbmUoYTogeyBsYXQ6IG51bWJlcjsgbG5nOiBudW1iZXIgfSwgYjogeyBsYXQ6IG51bWJl'
    'cjsgbG5nOiBudW1iZXIgfSk6IG51bWJlciB7CiAgY29uc3QgUiA9IDYzNzEwMDA7CiAgY29uc3Qg'
    'dG9SYWQgPSAoZDogbnVtYmVyKSA9PiAoZCAqIE1hdGguUEkpIC8gMTgwOwogIGNvbnN0IGRMYXQg'
    'PSB0b1JhZChiLmxhdCAtIGEubGF0KTsKICBjb25zdCBkTG5nID0gdG9SYWQoYi5sbmcgLSBhLmxu'
    'Zyk7CiAgY29uc3QgbGF0MSA9IHRvUmFkKGEubGF0KTsKICBjb25zdCBsYXQyID0gdG9SYWQoYi5s'
    'YXQpOwogIGNvbnN0IHggPQogICAgTWF0aC5zaW4oZExhdCAvIDIpICoqIDIgKwogICAgTWF0aC5j'
    'b3MobGF0MSkgKiBNYXRoLmNvcyhsYXQyKSAqIE1hdGguc2luKGRMbmcgLyAyKSAqKiAyOwogIHJl'
    'dHVybiAyICogUiAqIE1hdGguYXRhbjIoTWF0aC5zcXJ0KHgpLCBNYXRoLnNxcnQoMSAtIHgpKTsK'
    'fQoKaW50ZXJmYWNlIFJhbmtpbmcgewogIGNpZDogc3RyaW5nOwogIGRpc3RNZXRlcnM6IG51bWJl'
    'cjsgICAgICAgLy8gZGlzdMOibmNpYSByZWFsIHVzZXIg4oaSIGNsdXN0ZXIgKHPDsyDDunRpbCBz'
    'ZSBkZW50cm8pCiAgd2Fsa1NlY29uZHM6IG51bWJlcjsgICAgICAvLyB0ZW1wbyBhIHDDqSByZWFs'
    'IChzw7Mgw7p0aWwgc2UgZGVudHJvKQogIGludHJhVmVudWVEaXN0OiBudW1iZXI7ICAgLy8gZGlz'
    'dMOibmNpYSBjbHVzdGVyIOKGkiBjZW50cm9pZCAoY2VudHJhbGlkYWRlKQogIG9jYzogbnVtYmVy'
    'OwogIGZpbGE6IG51bWJlcjsKICB3YWl0U2VjOiBudW1iZXI7CiAgdG90YWxDb3N0OiBudW1iZXI7'
    'Cn0KCmZ1bmN0aW9uIHJlY29tbWVuZENsdXN0ZXIoCiAgdXNlckxhdDogbnVtYmVyLAogIHVzZXJM'
    'bmc6IG51bWJlciwKICBzbmFwc2hvdDogTGl2ZVNuYXBzaG90IHwgbnVsbCwKKTogeyBiZXN0OiBS'
    'YW5raW5nOyBhbHQ6IFJhbmtpbmcgfCBudWxsOyBpc091dHNpZGU6IGJvb2xlYW47IHZlbnVlRGlz'
    'dDogbnVtYmVyIH0gfCBudWxsIHsKICBjb25zdCB1c2VyID0geyBsYXQ6IHVzZXJMYXQsIGxuZzog'
    'dXNlckxuZyB9OwogIGNvbnN0IHZlbnVlRGlzdCA9IGhhdmVyc2luZSh1c2VyLCBWRU5VRV9DRU5U'
    'Uk9JRCk7CiAgY29uc3QgaXNPdXRzaWRlID0gdmVudWVEaXN0ID4gODAwOyAvLyA+IDgwMG0gZG8g'
    'Y2VudHJvaWQgPSBmb3JhIGRvIHJlY2ludG8KCiAgY29uc3Qgc291cmNlQ2x1c3RlcnMgPSBPYmpl'
    'Y3Qua2V5cyhDTFVTVEVSUyk7CiAgY29uc3QgbGl2ZU1hcCA9IG5ldyBNYXAoCiAgICAoc25hcHNo'
    'b3Q/LmNsdXN0ZXJzID8/IFtdKS5tYXAoKGMpID0+IFtjLmNsdXN0ZXJfaWQsIGNdKSwKICApOwoK'
    'ICAvLyBTZSBlc3TDoXMgRk9SQSBkbyB2ZW51ZSwgbyB0ZW1wbyBhIHDDqSDDqSBERU5UUk8gZG8g'
    'cmVjaW50byAoZGEgZW50cmFkYS9jZW50cm8KICAvLyBhbyBXQyksIG7Do28gZGVzZGUgYSB0dWEg'
    'cG9zacOnw6NvIGEgY2VudGVuYXMgZGUga20uIFNlIGVzdMOhcyBERU5UUk8sIMOpIHJlYWwuCiAg'
    'Y29uc3QgcmVmUG9pbnQgPSBpc091dHNpZGUgPyBWRU5VRV9DRU5UUk9JRCA6IHVzZXI7CgogIGNv'
    'bnN0IHJhbmtlZDogUmFua2luZ1tdID0gc291cmNlQ2x1c3RlcnMKICAgIC5tYXAoKGNpZCkgPT4g'
    'ewogICAgICBjb25zdCBwb3MgPSBjbHVzdGVyUG9zKGNpZCk7CiAgICAgIGNvbnN0IGRpc3RNZXRl'
    'cnMgPSBoYXZlcnNpbmUocmVmUG9pbnQsIHBvcyk7CiAgICAgIGNvbnN0IHdhbGtTZWNvbmRzID0g'
    'ZGlzdE1ldGVycyAvIDEuNDsgLy8gfjEuNCBtL3MKICAgICAgY29uc3QgaW50cmFWZW51ZURpc3Qg'
    'PSBoYXZlcnNpbmUocG9zLCBWRU5VRV9DRU5UUk9JRCk7CiAgICAgIGNvbnN0IGxpdmUgPSBsaXZl'
    'TWFwLmdldChjaWQpOwogICAgICBjb25zdCBvY2MgPSBsaXZlPy5wYXJhbXM/Lm9jdXBhY2FvX2lu'
    'c3RhbnRhbmVhID8/IDA7CiAgICAgIGNvbnN0IGZpbGEgPSBsaXZlPy5wYXJhbXM/LmZpbGFfYXR1'
    'YWwgPz8gMDsKICAgICAgY29uc3Qgd2FpdFNlYyA9IChsaXZlPy5wYXJhbXM/LnRlbXBvX2VzcGVy'
    'YV9taW4gPz8gMCkgKiA2MDsKICAgICAgY29uc3QgY29uZ2VzdGlvblBlbmFsdHkgPSBvY2MgPj0g'
    'ODAgPyA5MCA6IG9jYyA+PSA2MCA/IDI1IDogMDsKCiAgICAgIC8vIFJFR1JBIENSw41USUNBOgog'
    'ICAgICAvLyAtIERFTlRSTyBkbyByZWNpbnRvOiBhIGRpc3TDom5jaWEgYXTDqSB0aSBjb250YSAo'
    'd2Fsa190aW1lICsgcXVldWUgKyBjb25nZXN0aW9uKS4KICAgICAgLy8gLSBGT1JBOiBhIGRpc3TD'
    'om5jaWEgZGUgMjAwKyBrbSDDqSBpcnJlbGV2YW50ZS4gUmFua2VhbW9zIHPDsyBwZWxvIGVzdGFk'
    'byBhbwogICAgICAvLyAgIHZpdm8gKG9jdXBhw6fDo28sIGZpbGEsIGVzcGVyYSkgKyB1bWEgcGVx'
    'dWVuYSBwcmVmZXLDqm5jaWEgcG9yIGNsdXN0ZXJzCiAgICAgIC8vICAgY2VudHJhaXMgKGbDoWNl'
    'aXMgZGUgZW5jb250cmFyKS4gTlVOQ0EgcG9yIHdhbGtTZWNvbmRzIOKAlCBzZW7Do28gZXNjb2xo'
    'ZS1zZQogICAgICAvLyAgIG8gY2x1c3RlciBtYXJnaW5hbG1lbnRlIG1haXMgcGVydG8gZGEgdHVh'
    'IGNpZGFkZSwgbyBxdWUgw6kgYWJzdXJkby4KICAgICAgY29uc3QgdG90YWxDb3N0ID0gaXNPdXRz'
    'aWRlCiAgICAgICAgPyB3YWl0U2VjICsgY29uZ2VzdGlvblBlbmFsdHkgKyBvY2MgKiAyICsgKGlu'
    'dHJhVmVudWVEaXN0IC8gMS40KSAqIDAuMwogICAgICAgIDogd2Fsa1NlY29uZHMgKyB3YWl0U2Vj'
    'ICsgY29uZ2VzdGlvblBlbmFsdHk7CgogICAgICByZXR1cm4geyBjaWQsIGRpc3RNZXRlcnMsIHdh'
    'bGtTZWNvbmRzLCBpbnRyYVZlbnVlRGlzdCwgb2NjLCBmaWxhLCB3YWl0U2VjLCB0b3RhbENvc3Qg'
    'fTsKICAgIH0pCiAgICAuc29ydCgoYSwgYikgPT4gYS50b3RhbENvc3QgLSBiLnRvdGFsQ29zdCk7'
    'CgogIGlmICghcmFua2VkLmxlbmd0aCkgcmV0dXJuIG51bGw7CiAgcmV0dXJuIHsgYmVzdDogcmFu'
    'a2VkWzBdLCBhbHQ6IHJhbmtlZFsxXSB8fCBudWxsLCBpc091dHNpZGUsIHZlbnVlRGlzdCB9Owp9'
    'CgpmdW5jdGlvbiBmbXREaXN0KG06IG51bWJlcik6IHN0cmluZyB7CiAgaWYgKG0gPCAxMDAwKSBy'
    'ZXR1cm4gYCR7TWF0aC5yb3VuZChtKX0gbWA7CiAgaWYgKG0gPCAxMDAwMCkgcmV0dXJuIGAkeyht'
    'IC8gMTAwMCkudG9GaXhlZCgxKX0ga21gOwogIHJldHVybiBgJHtNYXRoLnJvdW5kKG0gLyAxMDAw'
    'KX0ga21gOwp9CgpmdW5jdGlvbiBmbXRXYWxrTWluKHNlY29uZHM6IG51bWJlcik6IHN0cmluZyB7'
    'CiAgY29uc3QgbSA9IE1hdGgubWF4KDEsIE1hdGgucm91bmQoc2Vjb25kcyAvIDYwKSk7CiAgaWYg'
    'KG0gPiA5MCkgewogICAgLy8gU2FsdmFndWFyZGE6IGRpc3TDom5jaWEgYWJzdXJkYSDihpIgcGlh'
    'ZGEsIG51bmNhIHVtIG7Dum1lcm8gcmlkw61jdWxvCiAgICByZXR1cm4gYCR7bX0gbWluIPCfmIUg'
    '4oCUIG9zIG5vc3NvcyBXQyBzw6NvIGludGVsaWdlbnRlcywgbWFzIG7Do28gdMOjbyBhdmVudHVy'
    'ZWlyb3MhYDsKICB9CiAgcmV0dXJuIGAke219IG1pbmA7Cn0KCmZ1bmN0aW9uIGZvcm1hdFJlY29t'
    'bWVuZGF0aW9uKAogIHJlYzogUmV0dXJuVHlwZTx0eXBlb2YgcmVjb21tZW5kQ2x1c3Rlcj4sCik6'
    'IHN0cmluZyB7CiAgaWYgKCFyZWMpIHsKICAgIHJldHVybiAnQWluZGEgbsOjbyB0ZW5obyBkYWRv'
    'cyBhbyB2aXZvLiBUZW50YSBlbSBwb3Vjb3Mgc2VndW5kb3MuJzsKICB9CiAgY29uc3QgeyBiZXN0'
    'LCBhbHQsIGlzT3V0c2lkZSwgdmVudWVEaXN0IH0gPSByZWM7CiAgY29uc3QgY2lkVXBwZXIgPSBi'
    'ZXN0LmNpZC50b1VwcGVyQ2FzZSgpOwogIGNvbnN0IHpvbmUgPSBDTFVTVEVSU1tiZXN0LmNpZF0/'
    'LnpvbmUgPz8gJyc7CiAgY29uc3Qgb2NjTGFiZWwgPSBgJHtNYXRoLnJvdW5kKGJlc3Qub2NjKX0l'
    'IG9jdXBhw6fDo29gOwogIGNvbnN0IGZpbGFMYWJlbCA9IGJlc3QuZmlsYSA+IDAgPyBgIMK3ICR7'
    'YmVzdC5maWxhfSBuYSBmaWxhYCA6ICcgwrcgc2VtIGZpbGEnOwogIGNvbnN0IHdhaXRMYWJlbCA9'
    'IGJlc3Qud2FpdFNlYyA+IDMwID8gYCDCtyB+JHtNYXRoLnJvdW5kKGJlc3Qud2FpdFNlYyAvIDYw'
    'KX0gbWluIGVzcGVyYWAgOiAnJzsKCiAgaWYgKGlzT3V0c2lkZSkgewogICAgLy8gRk9SQSBkbyBy'
    'ZWNpbnRvOiBuYWRhIGRlIHRlbXBvIGEgcMOpIGFic3VyZG8uIE1vc3RyYSBlc3RhZG8gKyB6b25h'
    'LgogICAgbGV0IHR4dCA9IGBFc3TDoXMgYSAke2ZtdERpc3QodmVudWVEaXN0KX0gZG8gUGFycXVl'
    'IFRlam8uIFF1YW5kbyBjaGVnYXJlcywgYSBvcMOnw6NvIG1haXMgZGVzYWZvZ2FkYSBhZ29yYSDD'
    'qTpcblxuYDsKICAgIHR4dCArPSBgKioke2NpZFVwcGVyfSoqIMK3ICR7em9uZX1cbmA7CiAgICB0'
    'eHQgKz0gYCR7b2NjTGFiZWx9JHtmaWxhTGFiZWx9JHt3YWl0TGFiZWx9YDsKICAgIGlmIChhbHQg'
    'JiYgYWx0LmNpZCAhPT0gYmVzdC5jaWQpIHsKICAgICAgdHh0ICs9IGBcblxuRW0gc2VndW5kbzog'
    'Kioke2FsdC5jaWQudG9VcHBlckNhc2UoKX0qKiDigJQgJHtNYXRoLnJvdW5kKGFsdC5vY2MpfSUg'
    'b2N1cGHDp8Ojby5gOwogICAgfQogICAgdHh0ICs9IGBcblxuUXVhbmRvIGVudHJhcmVzIG5vIHJl'
    'Y2ludG8sIHBhcnRpbGhhIGEgbG9jYWxpemHDp8OjbyBvdXRyYSB2ZXogZSBkb3UtdGUgbyBjYW1p'
    'bmhvIGEgcMOpIGV4YWN0by5gOwogICAgcmV0dXJuIHR4dDsKICB9CgogIC8vIERFTlRSTzogY2Ft'
    'aW5obyByZWFsCiAgbGV0IHR4dCA9IGAqKiR7Y2lkVXBwZXJ9KiogwrcgJHt6b25lfVxuYDsKICB0'
    'eHQgKz0gYCR7Zm10RGlzdChiZXN0LmRpc3RNZXRlcnMpfSDCtyB+JHtmbXRXYWxrTWluKGJlc3Qu'
    'd2Fsa1NlY29uZHMpfSBhIHDDqVxuYDsKICB0eHQgKz0gYCR7b2NjTGFiZWx9JHtmaWxhTGFiZWx9'
    'JHt3YWl0TGFiZWx9YDsKICBpZiAoYWx0ICYmIGFsdC5jaWQgIT09IGJlc3QuY2lkKSB7CiAgICB0'
    'eHQgKz0gYFxuXG5BbHRlcm5hdGl2YTogKioke2FsdC5jaWQudG9VcHBlckNhc2UoKX0qKiDigJQg'
    'JHtmbXRXYWxrTWluKGFsdC53YWxrU2Vjb25kcyl9IGEgcMOpLCAke01hdGgucm91bmQoYWx0Lm9j'
    'Yyl9JSBvY3VwYcOnw6NvLmA7CiAgfQogIHJldHVybiB0eHQ7Cn0KCi8qIOKUgOKUgOKUgOKUgOKU'
    'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
    'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
    'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
    'gOKUgOKUgOKUgOKUgAogICBISVNUw5NSSUNPIExPQ0FMCiAgIOKUgOKUgOKUgOKUgOKUgOKUgOKU'
    'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
    'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
    'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
    'gOKUgOKUgCAqLwoKZnVuY3Rpb24gbG9hZEhpc3RvcnkoKTogTXNnW10gewogIGlmICh0eXBlb2Yg'
    'd2luZG93ID09PSAndW5kZWZpbmVkJykgcmV0dXJuIFtdOwogIHRyeSB7CiAgICBjb25zdCByYXcg'
    'PSBsb2NhbFN0b3JhZ2UuZ2V0SXRlbShTVE9SQUdFX0tFWSk7CiAgICBpZiAoIXJhdykgcmV0dXJu'
    'IFtdOwogICAgY29uc3QgcGFyc2VkID0gSlNPTi5wYXJzZShyYXcpOwogICAgaWYgKEFycmF5Lmlz'
    'QXJyYXkocGFyc2VkKSkgcmV0dXJuIHBhcnNlZDsKICAgIHJldHVybiBbXTsKICB9IGNhdGNoIHsK'
    'ICAgIHJldHVybiBbXTsKICB9Cn0KCmZ1bmN0aW9uIHNhdmVIaXN0b3J5KG1zZ3M6IE1zZ1tdKSB7'
    'CiAgaWYgKHR5cGVvZiB3aW5kb3cgPT09ICd1bmRlZmluZWQnKSByZXR1cm47CiAgdHJ5IHsKICAg'
    'IGxvY2FsU3RvcmFnZS5zZXRJdGVtKFNUT1JBR0VfS0VZLCBKU09OLnN0cmluZ2lmeShtc2dzLnNs'
    'aWNlKC0yMDApKSk7CiAgfSBjYXRjaCB7fQp9CgpmdW5jdGlvbiBpc0ltYWdlRGF0YVVybChzOiBz'
    'dHJpbmcpOiBib29sZWFuIHsKICByZXR1cm4gdHlwZW9mIHMgPT09ICdzdHJpbmcnICYmIHMuc3Rh'
    'cnRzV2l0aCgnZGF0YTppbWFnZS8nKTsKfQoKLyogU3Vwb3J0ZSBzaW1wbGVzIGEgbWFya2Rvd246'
    'ICoqYm9sZCoqICsgcXVlYnJhcyBkZSBsaW5oYSAqLwpmdW5jdGlvbiByZW5kZXJJbmxpbmUodGV4'
    'dDogc3RyaW5nKTogUmVhY3QuUmVhY3ROb2RlW10gewogIGNvbnN0IHBhcnRzOiBSZWFjdC5SZWFj'
    'dE5vZGVbXSA9IFtdOwogIGNvbnN0IHJlZ2V4ID0gL1wqXCooW14qXSspXCpcKi9nOwogIGxldCBs'
    'YXN0ID0gMDsKICBsZXQgaWR4ID0gMDsKICBsZXQgbTogUmVnRXhwRXhlY0FycmF5IHwgbnVsbDsK'
    'ICB3aGlsZSAoKG0gPSByZWdleC5leGVjKHRleHQpKSAhPT0gbnVsbCkgewogICAgaWYgKG0uaW5k'
    'ZXggPiBsYXN0KSBwYXJ0cy5wdXNoKHRleHQuc2xpY2UobGFzdCwgbS5pbmRleCkpOwogICAgcGFy'
    'dHMucHVzaCg8c3Ryb25nIGtleT17aWR4Kyt9PnttWzFdfTwvc3Ryb25nPik7CiAgICBsYXN0ID0g'
    'cmVnZXgubGFzdEluZGV4OwogIH0KICBpZiAobGFzdCA8IHRleHQubGVuZ3RoKSBwYXJ0cy5wdXNo'
    'KHRleHQuc2xpY2UobGFzdCkpOwogIHJldHVybiBwYXJ0czsKfQoKZnVuY3Rpb24gTWVzc2FnZUNv'
    'bnRlbnQoeyBjb250ZW50IH06IHsgY29udGVudDogc3RyaW5nIH0pIHsKICBpZiAoaXNJbWFnZURh'
    'dGFVcmwoY29udGVudCkpIHsKICAgIHJldHVybiA8SW1hZ2VCdWJibGUgc3JjPXtjb250ZW50fSAv'
    'PjsKICB9CiAgY29uc3QgbGluZXMgPSBjb250ZW50LnNwbGl0KCdcbicpOwogIHJldHVybiAoCiAg'
    'ICA8PgogICAgICB7bGluZXMubWFwKChsaW5lLCBpKSA9PiAoCiAgICAgICAgPHNwYW4ga2V5PXtp'
    'fT4KICAgICAgICAgIHtyZW5kZXJJbmxpbmUobGluZSl9CiAgICAgICAgICB7aSA8IGxpbmVzLmxl'
    'bmd0aCAtIDEgJiYgPGJyIC8+fQogICAgICAgIDwvc3Bhbj4KICAgICAgKSl9CiAgICA8Lz4KICAp'
    'Owp9CgpmdW5jdGlvbiBJbWFnZUJ1YmJsZSh7IHNyYyB9OiB7IHNyYzogc3RyaW5nIH0pIHsKICBj'
    'b25zdCBmaWxlbmFtZSA9IGBwbGFudGEtJHtEYXRlLm5vdygpfS5wbmdgOwogIHJldHVybiAoCiAg'
    'ICA8ZGl2IHN0eWxlPXt7IGRpc3BsYXk6ICdmbGV4JywgZmxleERpcmVjdGlvbjogJ2NvbHVtbics'
    'IGdhcDogNiB9fT4KICAgICAgPGltZwogICAgICAgIHNyYz17c3JjfQogICAgICAgIGFsdD0iaW1h'
    'Z2VtIGFuZXhhZGEiCiAgICAgICAgc3R5bGU9e3sKICAgICAgICAgIG1heFdpZHRoOiAnMTAwJScs'
    'CiAgICAgICAgICBtYXhIZWlnaHQ6IDM2MCwKICAgICAgICAgIGJvcmRlclJhZGl1czogMTIsCiAg'
    'ICAgICAgICBkaXNwbGF5OiAnYmxvY2snLAogICAgICAgIH19CiAgICAgIC8+CiAgICAgIDxhCiAg'
    'ICAgICAgaHJlZj17c3JjfQogICAgICAgIGRvd25sb2FkPXtmaWxlbmFtZX0KICAgICAgICBzdHls'
    'ZT17ewogICAgICAgICAgZm9udFNpemU6IDExLAogICAgICAgICAgY29sb3I6ICdyZ2JhKDI1NSwy'
    'NTUsMjU1LDAuOSknLAogICAgICAgICAgdGV4dERlY29yYXRpb246ICd1bmRlcmxpbmUnLAogICAg'
    'ICAgICAgdGV4dEFsaWduOiAncmlnaHQnLAogICAgICAgICAgZm9udEZhbWlseTogJ3ZhcigtLWZv'
    'bnQtbW9ubyknLAogICAgICAgICAgbGV0dGVyU3BhY2luZzogJzAuMDRlbScsCiAgICAgICAgfX0K'
    'ICAgICAgPgogICAgICAgIOKshyBndWFyZGFyCiAgICAgIDwvYT4KICAgIDwvZGl2PgogICk7Cn0K'
    'Ci8qIOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
    'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
    'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
    'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgAogICBDT01QT05FTlQKICAg4pSA4pSA4pSA'
    '4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA'
    '4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA'
    '4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA'
    '4pSA4pSA4pSA4pSA4pSA4pSAICovCgpmdW5jdGlvbiBDaGF0SW5uZXIoKSB7CiAgY29uc3Qgcm91'
    'dGVyID0gdXNlUm91dGVyKCk7CiAgY29uc3QgcGFyYW1zID0gdXNlU2VhcmNoUGFyYW1zKCk7CiAg'
    'Y29uc3QgeyBzbmFwc2hvdCB9ID0gdXNlTGl2ZSgpOwogIGNvbnN0IHNuYXBzaG90UmVmID0gdXNl'
    'UmVmPExpdmVTbmFwc2hvdCB8IG51bGw+KG51bGwpOwogIHNuYXBzaG90UmVmLmN1cnJlbnQgPSBz'
    'bmFwc2hvdDsKCiAgY29uc3QgW21lc3NhZ2VzLCBzZXRNZXNzYWdlc10gPSB1c2VTdGF0ZTxNc2db'
    'XT4oW10pOwogIGNvbnN0IFtpbnB1dCwgc2V0SW5wdXRdID0gdXNlU3RhdGUoJycpOwogIGNvbnN0'
    'IFtzZW5kaW5nLCBzZXRTZW5kaW5nXSA9IHVzZVN0YXRlKGZhbHNlKTsKICBjb25zdCBzY3JvbGxS'
    'ZWYgPSB1c2VSZWY8SFRNTERpdkVsZW1lbnQ+KG51bGwpOwogIGNvbnN0IGhhbmRsZWRRdWVyeSA9'
    'IHVzZVJlZjxzdHJpbmcgfCBudWxsPihudWxsKTsKCiAgdXNlRWZmZWN0KCgpID0+IHsKICAgIHNl'
    'dE1lc3NhZ2VzKGxvYWRIaXN0b3J5KCkpOwogICAgLy8gQWNlaXRhciBpbWFnZW0gYW5leGFkYSB2'
    'aWEgc2Vzc2lvblN0b3JhZ2UKICAgIHRyeSB7CiAgICAgIGNvbnN0IHJhdyA9IHNlc3Npb25TdG9y'
    'YWdlLmdldEl0ZW0oQVRUQUNIX0tFWSk7CiAgICAgIGlmIChyYXcpIHsKICAgICAgICBjb25zdCBk'
    'YXRhID0gSlNPTi5wYXJzZShyYXcpOwogICAgICAgIHNlc3Npb25TdG9yYWdlLnJlbW92ZUl0ZW0o'
    'QVRUQUNIX0tFWSk7CiAgICAgICAgaWYgKGRhdGEgJiYgZGF0YS5kYXRhVXJsKSB7CiAgICAgICAg'
    'ICBjb25zdCBpbWdNc2c6IE1zZyA9IHsKICAgICAgICAgICAgcm9sZTogJ3VzZXInLAogICAgICAg'
    'ICAgICBjb250ZW50OiBkYXRhLmRhdGFVcmwsCiAgICAgICAgICAgIHRzOiBEYXRlLm5vdygpLAog'
    'ICAgICAgICAgfTsKICAgICAgICAgIHNldE1lc3NhZ2VzKChwcmV2KSA9PiB7CiAgICAgICAgICAg'
    'IGNvbnN0IG5leHQgPSBbLi4ucHJldiwgaW1nTXNnXTsKICAgICAgICAgICAgc2F2ZUhpc3Rvcnko'
    'bmV4dCk7CiAgICAgICAgICAgIHJldHVybiBuZXh0OwogICAgICAgICAgfSk7CiAgICAgICAgfQog'
    'ICAgICB9CiAgICB9IGNhdGNoIHt9CiAgfSwgW10pOwoKICB1c2VFZmZlY3QoKCkgPT4gewogICAg'
    'aWYgKHNjcm9sbFJlZi5jdXJyZW50KSB7CiAgICAgIHNjcm9sbFJlZi5jdXJyZW50LnNjcm9sbFRv'
    'cCA9IHNjcm9sbFJlZi5jdXJyZW50LnNjcm9sbEhlaWdodDsKICAgIH0KICB9LCBbbWVzc2FnZXNd'
    'KTsKCiAgdXNlRWZmZWN0KCgpID0+IHsKICAgIGNvbnN0IHEgPSBwYXJhbXM/LmdldCgncScpOwog'
    'ICAgaWYgKHEgJiYgaGFuZGxlZFF1ZXJ5LmN1cnJlbnQgIT09IHEpIHsKICAgICAgaGFuZGxlZFF1'
    'ZXJ5LmN1cnJlbnQgPSBxOwogICAgICBzZW5kKHEpOwogICAgICByb3V0ZXIucmVwbGFjZSgnL3Yy'
    'L2NoYXQnLCB7IHNjcm9sbDogZmFsc2UgfSk7CiAgICB9CiAgICAvLyBlc2xpbnQtZGlzYWJsZS1u'
    'ZXh0LWxpbmUgcmVhY3QtaG9va3MvZXhoYXVzdGl2ZS1kZXBzCiAgfSwgW3BhcmFtc10pOwoKICBj'
    'b25zdCBzZW5kID0gYXN5bmMgKHRleHQ/OiBzdHJpbmcpID0+IHsKICAgIGNvbnN0IGNvbnRlbnQg'
    'PSAodGV4dCA/PyBpbnB1dCkudHJpbSgpOwogICAgaWYgKCFjb250ZW50IHx8IHNlbmRpbmcpIHJl'
    'dHVybjsKCiAgICBjb25zdCB1c2VyTXNnOiBNc2cgPSB7IHJvbGU6ICd1c2VyJywgY29udGVudCwg'
    'dHM6IERhdGUubm93KCkgfTsKICAgIHNldE1lc3NhZ2VzKChtKSA9PiB7CiAgICAgIGNvbnN0IG5l'
    'eHQgPSBbLi4ubSwgdXNlck1zZ107CiAgICAgIHNhdmVIaXN0b3J5KG5leHQpOwogICAgICByZXR1'
    'cm4gbmV4dDsKICAgIH0pOwogICAgc2V0SW5wdXQoJycpOwogICAgc2V0U2VuZGluZyh0cnVlKTsK'
    'CiAgICAvLyDilZTilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDi'
    'lZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDi'
    'lZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDi'
    'lZDilZDilZDilZDilZcKICAgIC8vIOKVkSBJTlRFUkNFUFQ6IGNvb3JkZW5hZGFzIOKGkiByb3V0'
    'aW5nIGxvY2FsIGRldGVybWluw61zdGljbyAgIOKVkQogICAgLy8g4pWRIE5VTkNBICJzZW0gZGFk'
    'b3MiIHF1YW5kbyBow6EgY29vcmRzLiAgICAgICAgICAgICAgICAgICAgIOKVkQogICAgLy8g4pWa'
    '4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ'
    '4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ'
    '4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ'
    '4pWdCiAgICBjb25zdCBjb29yZHMgPSBkZXRlY3RDb29yZHMoY29udGVudCk7CiAgICBpZiAoY29v'
    'cmRzKSB7CiAgICAgIC8vIEVzcGVyYSAyNTBtcyBwYXJhIHBhcmVjZXIgImEgcGVuc2FyIiArIGVz'
    'cGVyYXIgcGVsbyBwcmltZWlybyB0aWNrIGRvIHVzZUxpdmUKICAgICAgYXdhaXQgbmV3IFByb21p'
    'c2UoKHIpID0+IHNldFRpbWVvdXQociwgMjUwKSk7CiAgICAgIGNvbnN0IHJlYyA9IHJlY29tbWVu'
    'ZENsdXN0ZXIoY29vcmRzLmxhdCwgY29vcmRzLmxuZywgc25hcHNob3RSZWYuY3VycmVudCk7CiAg'
    'ICAgIGNvbnN0IHJlcGx5ID0gZm9ybWF0UmVjb21tZW5kYXRpb24ocmVjKTsKICAgICAgY29uc3Qg'
    'YWlNc2c6IE1zZyA9IHsgcm9sZTogJ2Fzc2lzdGFudCcsIGNvbnRlbnQ6IHJlcGx5LCB0czogRGF0'
    'ZS5ub3coKSB9OwogICAgICBzZXRNZXNzYWdlcygobSkgPT4gewogICAgICAgIGNvbnN0IG5leHQg'
    'PSBbLi4ubSwgYWlNc2ddOwogICAgICAgIHNhdmVIaXN0b3J5KG5leHQpOwogICAgICAgIHJldHVy'
    'biBuZXh0OwogICAgICB9KTsKICAgICAgc2V0U2VuZGluZyhmYWxzZSk7CiAgICAgIHJldHVybjsK'
    'ICAgIH0KCiAgICAvLyBGbHV4byBub3JtYWwg4oCUIGNoYW1hciAvYXBpL3YxL2NoYXQKICAgIHRy'
    'eSB7CiAgICAgIGNvbnN0IHIgPSBhd2FpdCBmZXRjaChgJHtBUElfQkFTRX0vYXBpL3YxL2NoYXRg'
    'LCB7CiAgICAgICAgbWV0aG9kOiAnUE9TVCcsCiAgICAgICAgaGVhZGVyczogeyAnY29udGVudC10'
    'eXBlJzogJ2FwcGxpY2F0aW9uL2pzb24nIH0sCiAgICAgICAgYm9keTogSlNPTi5zdHJpbmdpZnko'
    'eyBtZXNzYWdlOiBjb250ZW50IH0pLAogICAgICB9KTsKICAgICAgbGV0IHJlcGx5ID0gJ0Rlc2N1'
    'bHBhLCBuw6NvIGNvbnNlZ3VpIHByb2Nlc3Nhci4nOwogICAgICBpZiAoci5vaykgewogICAgICAg'
    'IGNvbnN0IGogPSBhd2FpdCByLmpzb24oKTsKICAgICAgICByZXBseSA9CiAgICAgICAgICBqLnJl'
    'cGx5IHx8CiAgICAgICAgICBqLm1lc3NhZ2UgfHwKICAgICAgICAgIGoucmVzcG9uc2UgfHwKICAg'
    'ICAgICAgIGoudGV4dCB8fAogICAgICAgICAgSlNPTi5zdHJpbmdpZnkoaikuc2xpY2UoMCwgMjAw'
    'KTsKICAgICAgfSBlbHNlIHsKICAgICAgICByZXBseSA9IGBFcnJvIGRvIHNlcnZpZG9yICgke3Iu'
    'c3RhdHVzfSkuYDsKICAgICAgfQogICAgICBjb25zdCBhaU1zZzogTXNnID0geyByb2xlOiAnYXNz'
    'aXN0YW50JywgY29udGVudDogcmVwbHksIHRzOiBEYXRlLm5vdygpIH07CiAgICAgIHNldE1lc3Nh'
    'Z2VzKChtKSA9PiB7CiAgICAgICAgY29uc3QgbmV4dCA9IFsuLi5tLCBhaU1zZ107CiAgICAgICAg'
    'c2F2ZUhpc3RvcnkobmV4dCk7CiAgICAgICAgcmV0dXJuIG5leHQ7CiAgICAgIH0pOwogICAgfSBj'
    'YXRjaCB7CiAgICAgIGNvbnN0IGVyck1zZzogTXNnID0gewogICAgICAgIHJvbGU6ICdhc3Npc3Rh'
    'bnQnLAogICAgICAgIGNvbnRlbnQ6ICdQcm9ibGVtYSBkZSBsaWdhw6fDo28uIFZlcmlmaWNhIGEg'
    'cmVkZS4nLAogICAgICAgIHRzOiBEYXRlLm5vdygpLAogICAgICB9OwogICAgICBzZXRNZXNzYWdl'
    'cygobSkgPT4gewogICAgICAgIGNvbnN0IG5leHQgPSBbLi4ubSwgZXJyTXNnXTsKICAgICAgICBz'
    'YXZlSGlzdG9yeShuZXh0KTsKICAgICAgICByZXR1cm4gbmV4dDsKICAgICAgfSk7CiAgICB9IGZp'
    'bmFsbHkgewogICAgICBzZXRTZW5kaW5nKGZhbHNlKTsKICAgIH0KICB9OwoKICBjb25zdCBjbGVh'
    'ckhpc3RvcnkgPSAoKSA9PiB7CiAgICBpZiAoY29uZmlybSgnTGltcGFyIHRvZG8gbyBoaXN0w7Ny'
    'aWNvIGRlIGNvbnZlcnNhPycpKSB7CiAgICAgIHNldE1lc3NhZ2VzKFtdKTsKICAgICAgc2F2ZUhp'
    'c3RvcnkoW10pOwogICAgfQogIH07CgogIGNvbnN0IGFza0xvY2F0aW9uID0gKCkgPT4gewogICAg'
    'aWYgKCEoJ2dlb2xvY2F0aW9uJyBpbiBuYXZpZ2F0b3IpKSB7CiAgICAgIGFsZXJ0KCdHZW9sb2Nh'
    'bGl6YcOnw6NvIG7Do28gc3Vwb3J0YWRhIG5lc3RlIGJyb3dzZXIuJyk7CiAgICAgIHJldHVybjsK'
    'ICAgIH0KICAgIG5hdmlnYXRvci5nZW9sb2NhdGlvbi5nZXRDdXJyZW50UG9zaXRpb24oCiAgICAg'
    'IChwb3MpID0+IHsKICAgICAgICBjb25zdCB7IGxhdGl0dWRlLCBsb25naXR1ZGUgfSA9IHBvcy5j'
    'b29yZHM7CiAgICAgICAgc2VuZChgRXN0b3UgZW0gJHtsYXRpdHVkZS50b0ZpeGVkKDYpfSwgJHts'
    'b25naXR1ZGUudG9GaXhlZCg2KX0uIFF1YWwgYSBjYXNhLWRlLWJhbmhvIG1haXMgcHLDs3hpbWE/'
    'YCk7CiAgICAgIH0sCiAgICAgIChlcnIpID0+IGFsZXJ0KGBOw6NvIGNvbnNlZ3VpIG9idGVyIGxv'
    'Y2FsaXphw6fDo286ICR7ZXJyLm1lc3NhZ2V9YCksCiAgICAgIHsgdGltZW91dDogODAwMCwgZW5h'
    'YmxlSGlnaEFjY3VyYWN5OiB0cnVlIH0sCiAgICApOwogIH07CgogIHJldHVybiAoCiAgICA8ZGl2'
    'CiAgICAgIHN0eWxlPXt7CiAgICAgICAgcG9zaXRpb246ICdmaXhlZCcsCiAgICAgICAgdG9wOiAn'
    'dmFyKC0tdG9wYmFyLWgsIDcycHgpJywKICAgICAgICBsZWZ0OiAwLAogICAgICAgIHJpZ2h0OiAw'
    'LAogICAgICAgIGJvdHRvbTogMCwKICAgICAgICBkaXNwbGF5OiAnZmxleCcsCiAgICAgICAgZmxl'
    'eERpcmVjdGlvbjogJ2NvbHVtbicsCiAgICAgICAgYmFja2dyb3VuZDogJ3ZhcigtLWJnLCAjRkJG'
    'QUY3KScsCiAgICAgIH19CiAgICA+CiAgICAgIHsvKiBIZWFkZXIgZml4byAqL30KICAgICAgPGRp'
    'dgogICAgICAgIHN0eWxlPXt7CiAgICAgICAgICBmbGV4U2hyaW5rOiAwLAogICAgICAgICAgZGlz'
    'cGxheTogJ2ZsZXgnLAogICAgICAgICAganVzdGlmeUNvbnRlbnQ6ICdzcGFjZS1iZXR3ZWVuJywK'
    'ICAgICAgICAgIGFsaWduSXRlbXM6ICdjZW50ZXInLAogICAgICAgICAgZ2FwOiAxMiwKICAgICAg'
    'ICAgIHBhZGRpbmc6ICcxNHB4IGNsYW1wKDE2cHgsIDR2dywgNDBweCknLAogICAgICAgICAgYm9y'
    'ZGVyQm90dG9tOiAnMXB4IHNvbGlkIHZhcigtLWJvcmRlciknLAogICAgICAgICAgYmFja2dyb3Vu'
    'ZDogJ3ZhcigtLWJnLCAjRkJGQUY3KScsCiAgICAgICAgfX0KICAgICAgPgogICAgICAgIDxkaXY+'
    'CiAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT0ic2VjdGlvbi1sYWJlbCI+Q2hhdCDCtyBQbGFudGEg'
    'U21hcnQgSG9tZXM8L2Rpdj4KICAgICAgICAgIDxoMgogICAgICAgICAgICBzdHlsZT17ewogICAg'
    'ICAgICAgICAgIGZvbnRGYW1pbHk6ICd2YXIoLS1mb250LWRpc3BsYXkpJywKICAgICAgICAgICAg'
    'ICBmb250U2l6ZTogJ2NsYW1wKDIwcHgsIDN2dywgMjhweCknLAogICAgICAgICAgICAgIGZvbnRX'
    'ZWlnaHQ6IDUwMCwKICAgICAgICAgICAgICBsZXR0ZXJTcGFjaW5nOiAnLTAuMDNlbScsCiAgICAg'
    'ICAgICAgICAgbGluZUhlaWdodDogMSwKICAgICAgICAgICAgICBtYXJnaW5Ub3A6IDMsCiAgICAg'
    'ICAgICAgIH19CiAgICAgICAgICA+CiAgICAgICAgICAgIEFzayBQbGFudGEgYW55dGhpbmcKICAg'
    'ICAgICAgIDwvaDI+CiAgICAgICAgPC9kaXY+CiAgICAgICAge21lc3NhZ2VzLmxlbmd0aCA+IDAg'
    'JiYgKAogICAgICAgICAgPGJ1dHRvbgogICAgICAgICAgICBvbkNsaWNrPXtjbGVhckhpc3Rvcnl9'
    'CiAgICAgICAgICAgIHN0eWxlPXt7CiAgICAgICAgICAgICAgYmFja2dyb3VuZDogJ3RyYW5zcGFy'
    'ZW50JywKICAgICAgICAgICAgICBib3JkZXI6ICcxcHggc29saWQgdmFyKC0tYm9yZGVyLXN0cm9u'
    'ZyknLAogICAgICAgICAgICAgIGJvcmRlclJhZGl1czogOTk5LAogICAgICAgICAgICAgIHBhZGRp'
    'bmc6ICc2cHggMTRweCcsCiAgICAgICAgICAgICAgZm9udFNpemU6IDEyLAogICAgICAgICAgICAg'
    'IGNvbG9yOiAndmFyKC0tbXV0ZWQpJywKICAgICAgICAgICAgICBjdXJzb3I6ICdwb2ludGVyJywK'
    'ICAgICAgICAgICAgICBmbGV4U2hyaW5rOiAwLAogICAgICAgICAgICAgIGZvbnRGYW1pbHk6ICdp'
    'bmhlcml0JywKICAgICAgICAgICAgfX0KICAgICAgICAgID4KICAgICAgICAgICAgTGltcGFyCiAg'
    'ICAgICAgICA8L2J1dHRvbj4KICAgICAgICApfQogICAgICA8L2Rpdj4KCiAgICAgIHsvKiDDgXJl'
    'YSBkZSBtZW5zYWdlbnMg4oCUIHNjcm9sbCBJTlRFUk5PICh0aXBvIFdoYXRzQXBwKSAqL30KICAg'
    'ICAgPGRpdgogICAgICAgIHJlZj17c2Nyb2xsUmVmfQogICAgICAgIHN0eWxlPXt7CiAgICAgICAg'
    'ICBmbGV4OiAxLAogICAgICAgICAgbWluSGVpZ2h0OiAwLAogICAgICAgICAgb3ZlcmZsb3dZOiAn'
    'YXV0bycsCiAgICAgICAgICBwYWRkaW5nOiAnY2xhbXAoMTZweCwgM3Z3LCAyOHB4KSBjbGFtcCgx'
    'NnB4LCA0dncsIDQwcHgpJywKICAgICAgICAgIGRpc3BsYXk6ICdmbGV4JywKICAgICAgICAgIGZs'
    'ZXhEaXJlY3Rpb246ICdjb2x1bW4nLAogICAgICAgICAgZ2FwOiAxMiwKICAgICAgICB9fQogICAg'
    'ICA+CiAgICAgICAge21lc3NhZ2VzLmxlbmd0aCA9PT0gMCAmJiAoCiAgICAgICAgICA8ZGl2IHN0'
    'eWxlPXt7IGNvbG9yOiAndmFyKC0tbXV0ZWQpJywgbWF4V2lkdGg6IDU2MCB9fT4KICAgICAgICAg'
    'ICAgPHAgc3R5bGU9e3sgZm9udFNpemU6IDE2LCBsaW5lSGVpZ2h0OiAxLjU1LCBtYXJnaW5Cb3R0'
    'b206IDE4IH19PgogICAgICAgICAgICAgIFNvdSBvIGFzc2lzdGVudGUgZGEgUGxhbnRhLiBQZXJn'
    'dW50YS1tZSBzb2JyZSBvcyBjbHVzdGVycywKICAgICAgICAgICAgICBvY3VwYcOnw6NvLCBmaWxh'
    'cyDigJQgb3UgcGFydGlsaGEgYSB0dWEgbG9jYWxpemHDp8OjbyBwYXJhIGEKICAgICAgICAgICAg'
    'ICByZWNvbWVuZGHDp8OjbyBtYWlzIHLDoXBpZGEuCiAgICAgICAgICAgIDwvcD4KICAgICAgICAg'
    'ICAgPGRpdiBzdHlsZT17eyBkaXNwbGF5OiAnZmxleCcsIGZsZXhXcmFwOiAnd3JhcCcsIGdhcDog'
    'NiwgbWFyZ2luQm90dG9tOiAxMCB9fT4KICAgICAgICAgICAgICA8YnV0dG9uCiAgICAgICAgICAg'
    'ICAgICBvbkNsaWNrPXthc2tMb2NhdGlvbn0KICAgICAgICAgICAgICAgIHN0eWxlPXt7CiAgICAg'
    'ICAgICAgICAgICAgIGJhY2tncm91bmQ6ICd2YXIoLS1ncmVlbi1kYXJrLCAjMUIzQTIxKScsCiAg'
    'ICAgICAgICAgICAgICAgIGNvbG9yOiAnd2hpdGUnLAogICAgICAgICAgICAgICAgICBib3JkZXI6'
    'ICdub25lJywKICAgICAgICAgICAgICAgICAgYm9yZGVyUmFkaXVzOiA5OTksCiAgICAgICAgICAg'
    'ICAgICAgIHBhZGRpbmc6ICc4cHggMTZweCcsCiAgICAgICAgICAgICAgICAgIGZvbnRTaXplOiAx'
    'MywKICAgICAgICAgICAgICAgICAgZm9udFdlaWdodDogNjAwLAogICAgICAgICAgICAgICAgICBj'
    'dXJzb3I6ICdwb2ludGVyJywKICAgICAgICAgICAgICAgICAgZm9udEZhbWlseTogJ2luaGVyaXQn'
    'LAogICAgICAgICAgICAgICAgfX0KICAgICAgICAgICAgICA+CiAgICAgICAgICAgICAgICDwn5ON'
    'IE9uZGUgZXN0w6EgbyBXQyBtYWlzIHBlcnRvPwogICAgICAgICAgICAgIDwvYnV0dG9uPgogICAg'
    'ICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgPGRpdiBzdHlsZT17eyBkaXNwbGF5OiAnZmxleCcs'
    'IGZsZXhXcmFwOiAnd3JhcCcsIGdhcDogNiB9fT4KICAgICAgICAgICAgICB7WwogICAgICAgICAg'
    'ICAgICAgJ1F1YWwgbyBjbHVzdGVyIG1haXMgY2hlaW8gYWdvcmE/JywKICAgICAgICAgICAgICAg'
    'ICdRdWFudGFzIHBlc3NvYXMgaMOhIGFnb3JhIG5vIGZlc3RpdmFsPycsCiAgICAgICAgICAgICAg'
    'ICAnUXVhbmRvIMOpIGEgcHLDs3hpbWEgbGltcGV6YT8nLAogICAgICAgICAgICAgIF0ubWFwKChz'
    'KSA9PiAoCiAgICAgICAgICAgICAgICA8YnV0dG9uCiAgICAgICAgICAgICAgICAgIGtleT17c30K'
    'ICAgICAgICAgICAgICAgICAgb25DbGljaz17KCkgPT4gc2VuZChzKX0KICAgICAgICAgICAgICAg'
    'ICAgc3R5bGU9e3sKICAgICAgICAgICAgICAgICAgICBiYWNrZ3JvdW5kOiAnd2hpdGUnLAogICAg'
    'ICAgICAgICAgICAgICAgIGJvcmRlcjogJzFweCBzb2xpZCB2YXIoLS1ib3JkZXIpJywKICAgICAg'
    'ICAgICAgICAgICAgICBib3JkZXJSYWRpdXM6IDk5OSwKICAgICAgICAgICAgICAgICAgICBwYWRk'
    'aW5nOiAnN3B4IDEzcHgnLAogICAgICAgICAgICAgICAgICAgIGZvbnRTaXplOiAxMi41LAogICAg'
    'ICAgICAgICAgICAgICAgIGN1cnNvcjogJ3BvaW50ZXInLAogICAgICAgICAgICAgICAgICAgIGNv'
    'bG9yOiAndmFyKC0taW5rKScsCiAgICAgICAgICAgICAgICAgICAgZm9udEZhbWlseTogJ2luaGVy'
    'aXQnLAogICAgICAgICAgICAgICAgICB9fQogICAgICAgICAgICAgICAgPgogICAgICAgICAgICAg'
    'ICAgICB7c30KICAgICAgICAgICAgICAgIDwvYnV0dG9uPgogICAgICAgICAgICAgICkpfQogICAg'
    'ICAgICAgICA8L2Rpdj4KICAgICAgICAgIDwvZGl2PgogICAgICAgICl9CgogICAgICAgIHttZXNz'
    'YWdlcy5tYXAoKG0sIGkpID0+ICgKICAgICAgICAgIDxkaXYKICAgICAgICAgICAga2V5PXtpfQog'
    'ICAgICAgICAgICBzdHlsZT17ewogICAgICAgICAgICAgIGFsaWduU2VsZjogbS5yb2xlID09PSAn'
    'dXNlcicgPyAnZmxleC1lbmQnIDogJ2ZsZXgtc3RhcnQnLAogICAgICAgICAgICAgIGJhY2tncm91'
    'bmQ6IG0ucm9sZSA9PT0gJ3VzZXInID8gJ3ZhcigtLWluayknIDogJ3doaXRlJywKICAgICAgICAg'
    'ICAgICBjb2xvcjogbS5yb2xlID09PSAndXNlcicgPyAnd2hpdGUnIDogJ3ZhcigtLWluayknLAog'
    'ICAgICAgICAgICAgIHBhZGRpbmc6ICcxMXB4IDE1cHgnLAogICAgICAgICAgICAgIGJvcmRlclJh'
    'ZGl1czogMTYsCiAgICAgICAgICAgICAgbWF4V2lkdGg6ICc4NSUnLAogICAgICAgICAgICAgIGZv'
    'bnRTaXplOiAxNSwKICAgICAgICAgICAgICBsaW5lSGVpZ2h0OiAxLjU1LAogICAgICAgICAgICAg'
    'IGJvcmRlcjogbS5yb2xlID09PSAnYXNzaXN0YW50JyA/ICcxcHggc29saWQgdmFyKC0tYm9yZGVy'
    'KScgOiAnbm9uZScsCiAgICAgICAgICAgICAgYm94U2hhZG93OiBtLnJvbGUgPT09ICdhc3Npc3Rh'
    'bnQnID8gJ3ZhcigtLXNoYWRvdy1zbSknIDogJ25vbmUnLAogICAgICAgICAgICAgIHdvcmRCcmVh'
    'azogJ2JyZWFrLXdvcmQnLAogICAgICAgICAgICB9fQogICAgICAgICAgPgogICAgICAgICAgICA8'
    'TWVzc2FnZUNvbnRlbnQgY29udGVudD17bS5jb250ZW50fSAvPgogICAgICAgICAgPC9kaXY+CiAg'
    'ICAgICAgKSl9CiAgICAgICAge3NlbmRpbmcgJiYgKAogICAgICAgICAgPGRpdgogICAgICAgICAg'
    'ICBzdHlsZT17ewogICAgICAgICAgICAgIGFsaWduU2VsZjogJ2ZsZXgtc3RhcnQnLAogICAgICAg'
    'ICAgICAgIGJhY2tncm91bmQ6ICd3aGl0ZScsCiAgICAgICAgICAgICAgcGFkZGluZzogJzExcHgg'
    'MTVweCcsCiAgICAgICAgICAgICAgYm9yZGVyUmFkaXVzOiAxNiwKICAgICAgICAgICAgICBib3Jk'
    'ZXI6ICcxcHggc29saWQgdmFyKC0tYm9yZGVyKScsCiAgICAgICAgICAgICAgZm9udFNpemU6IDEz'
    'LAogICAgICAgICAgICAgIGNvbG9yOiAndmFyKC0tbXV0ZWQpJywKICAgICAgICAgICAgfX0KICAg'
    'ICAgICAgID4KICAgICAgICAgICAgPHNwYW4gc3R5bGU9e3sgYW5pbWF0aW9uOiAnZG90cyAxLjRz'
    'IGluZmluaXRlJyB9fT7il48g4pePIOKXjzwvc3Bhbj4KICAgICAgICAgIDwvZGl2PgogICAgICAg'
    'ICl9CiAgICAgIDwvZGl2PgoKICAgICAgey8qIElucHV0IHByw7NwcmlvIGZpeG8gbm8gZnVuZG8g'
    'KHRpcG8gV2hhdHNBcHApICovfQogICAgICA8ZGl2CiAgICAgICAgc3R5bGU9e3sKICAgICAgICAg'
    'IGZsZXhTaHJpbms6IDAsCiAgICAgICAgICBwYWRkaW5nOiAnY2xhbXAoMTBweCwgMnZ3LCAxNnB4'
    'KSBjbGFtcCgxNnB4LCA0dncsIDQwcHgpJywKICAgICAgICAgIGJvcmRlclRvcDogJzFweCBzb2xp'
    'ZCB2YXIoLS1ib3JkZXIpJywKICAgICAgICAgIGJhY2tncm91bmQ6ICd2YXIoLS1iZywgI0ZCRkFG'
    'NyknLAogICAgICAgIH19CiAgICAgID4KICAgICAgICA8ZGl2CiAgICAgICAgICBzdHlsZT17ewog'
    'ICAgICAgICAgICBkaXNwbGF5OiAnZmxleCcsCiAgICAgICAgICAgIGFsaWduSXRlbXM6ICdjZW50'
    'ZXInLAogICAgICAgICAgICBnYXA6IDQsCiAgICAgICAgICAgIG1heFdpZHRoOiA4MjAsCiAgICAg'
    'ICAgICAgIG1hcmdpbjogJzAgYXV0bycsCiAgICAgICAgICAgIGJhY2tncm91bmQ6ICd3aGl0ZScs'
    'CiAgICAgICAgICAgIGJvcmRlcjogJzFweCBzb2xpZCB2YXIoLS1ncmVlbi1kYXJrLCAjMUIzQTIx'
    'KScsCiAgICAgICAgICAgIGJvcmRlclJhZGl1czogOTk5LAogICAgICAgICAgICBwYWRkaW5nOiAn'
    'NnB4IDZweCA2cHggOHB4JywKICAgICAgICAgIH19CiAgICAgICAgPgogICAgICAgICAgPGJ1dHRv'
    'bgogICAgICAgICAgICB0eXBlPSJidXR0b24iCiAgICAgICAgICAgIG9uQ2xpY2s9e2Fza0xvY2F0'
    'aW9ufQogICAgICAgICAgICB0aXRsZT0iUGFydGlsaGFyIGxvY2FsaXphw6fDo28iCiAgICAgICAg'
    'ICAgIGFyaWEtbGFiZWw9IkxvY2FsaXphw6fDo28iCiAgICAgICAgICAgIHN0eWxlPXt7CiAgICAg'
    'ICAgICAgICAgYmFja2dyb3VuZDogJ3RyYW5zcGFyZW50JywKICAgICAgICAgICAgICBib3JkZXI6'
    'ICdub25lJywKICAgICAgICAgICAgICB3aWR0aDogMzgsCiAgICAgICAgICAgICAgaGVpZ2h0OiAz'
    'OCwKICAgICAgICAgICAgICBib3JkZXJSYWRpdXM6ICc1MCUnLAogICAgICAgICAgICAgIGN1cnNv'
    'cjogJ3BvaW50ZXInLAogICAgICAgICAgICAgIGRpc3BsYXk6ICdmbGV4JywKICAgICAgICAgICAg'
    'ICBhbGlnbkl0ZW1zOiAnY2VudGVyJywKICAgICAgICAgICAgICBqdXN0aWZ5Q29udGVudDogJ2Nl'
    'bnRlcicsCiAgICAgICAgICAgICAgZmxleFNocmluazogMCwKICAgICAgICAgICAgICBjb2xvcjog'
    'J3ZhcigtLWluayknLAogICAgICAgICAgICAgIGZvbnRTaXplOiAxOCwKICAgICAgICAgICAgfX0K'
    'ICAgICAgICAgID4KICAgICAgICAgICAg8J+TjQogICAgICAgICAgPC9idXR0b24+CiAgICAgICAg'
    'ICA8aW5wdXQKICAgICAgICAgICAgdHlwZT0idGV4dCIKICAgICAgICAgICAgdmFsdWU9e2lucHV0'
    'fQogICAgICAgICAgICBvbkNoYW5nZT17KGUpID0+IHNldElucHV0KGUudGFyZ2V0LnZhbHVlKX0K'
    'ICAgICAgICAgICAgb25LZXlEb3duPXsoZSkgPT4geyBpZiAoZS5rZXkgPT09ICdFbnRlcicpIHNl'
    'bmQoKTsgfX0KICAgICAgICAgICAgcGxhY2Vob2xkZXI9IlBlcmd1bnRhIMOgIFBsYW50YeKApiIK'
    'ICAgICAgICAgICAgc3R5bGU9e3sKICAgICAgICAgICAgICBmbGV4OiAxLAogICAgICAgICAgICAg'
    'IGJhY2tncm91bmQ6ICd0cmFuc3BhcmVudCcsCiAgICAgICAgICAgICAgYm9yZGVyOiAnbm9uZScs'
    'CiAgICAgICAgICAgICAgb3V0bGluZTogJ25vbmUnLAogICAgICAgICAgICAgIHBhZGRpbmc6ICcx'
    'MHB4IDZweCcsCiAgICAgICAgICAgICAgZm9udFNpemU6IDE1LjUsCiAgICAgICAgICAgICAgY29s'
    'b3I6ICd2YXIoLS1pbmspJywKICAgICAgICAgICAgICBtaW5XaWR0aDogMCwKICAgICAgICAgICAg'
    'ICBmb250RmFtaWx5OiAnaW5oZXJpdCcsCiAgICAgICAgICAgIH19CiAgICAgICAgICAvPgogICAg'
    'ICAgICAgPGJ1dHRvbgogICAgICAgICAgICBvbkNsaWNrPXsoKSA9PiBzZW5kKCl9CiAgICAgICAg'
    'ICAgIGRpc2FibGVkPXshaW5wdXQudHJpbSgpIHx8IHNlbmRpbmd9CiAgICAgICAgICAgIGFyaWEt'
    'bGFiZWw9IkVudmlhciIKICAgICAgICAgICAgc3R5bGU9e3sKICAgICAgICAgICAgICBiYWNrZ3Jv'
    'dW5kOiBpbnB1dC50cmltKCkgJiYgIXNlbmRpbmcgPyAndmFyKC0tZ3JlZW4tZGFyaywgIzFCM0Ey'
    'MSknIDogJyNFQkU5RTInLAogICAgICAgICAgICAgIGNvbG9yOiBpbnB1dC50cmltKCkgJiYgIXNl'
    'bmRpbmcgPyAnd2hpdGUnIDogJyNBMEEzOUEnLAogICAgICAgICAgICAgIGJvcmRlcjogJ25vbmUn'
    'LAogICAgICAgICAgICAgIGJvcmRlclJhZGl1czogJzUwJScsCiAgICAgICAgICAgICAgd2lkdGg6'
    'IDQwLAogICAgICAgICAgICAgIGhlaWdodDogNDAsCiAgICAgICAgICAgICAgY3Vyc29yOiBpbnB1'
    'dC50cmltKCkgJiYgIXNlbmRpbmcgPyAncG9pbnRlcicgOiAnZGVmYXVsdCcsCiAgICAgICAgICAg'
    'ICAgZGlzcGxheTogJ2ZsZXgnLAogICAgICAgICAgICAgIGFsaWduSXRlbXM6ICdjZW50ZXInLAog'
    'ICAgICAgICAgICAgIGp1c3RpZnlDb250ZW50OiAnY2VudGVyJywKICAgICAgICAgICAgICBmbGV4'
    'U2hyaW5rOiAwLAogICAgICAgICAgICAgIHRyYW5zaXRpb246ICdiYWNrZ3JvdW5kIDAuMTVzJywK'
    'ICAgICAgICAgICAgfX0KICAgICAgICAgID4KICAgICAgICAgICAgPHN2ZyB3aWR0aD0iMTYiIGhl'
    'aWdodD0iMTYiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgc3Ryb2tlPSJjdXJyZW50'
    'Q29sb3IiIHN0cm9rZVdpZHRoPSIyLjIiIHN0cm9rZUxpbmVjYXA9InJvdW5kIiBzdHJva2VMaW5l'
    'am9pbj0icm91bmQiPgogICAgICAgICAgICAgIDxsaW5lIHgxPSIxMiIgeTE9IjE5IiB4Mj0iMTIi'
    'IHkyPSI1IiAvPgogICAgICAgICAgICAgIDxwb2x5bGluZSBwb2ludHM9IjUgMTIgMTIgNSAxOSAx'
    'MiIgLz4KICAgICAgICAgICAgPC9zdmc+CiAgICAgICAgICA8L2J1dHRvbj4KICAgICAgICA8L2Rp'
    'dj4KICAgICAgPC9kaXY+CgogICAgICA8c3R5bGUganN4PntgCiAgICAgICAgQGtleWZyYW1lcyBk'
    'b3RzIHsKICAgICAgICAgIDAlLCAxMDAlIHsgb3BhY2l0eTogMC4zOyB9CiAgICAgICAgICA1MCUg'
    'eyBvcGFjaXR5OiAxOyB9CiAgICAgICAgfQogICAgICBgfTwvc3R5bGU+CiAgICA8L2Rpdj4KICAp'
    'Owp9CgpleHBvcnQgZGVmYXVsdCBmdW5jdGlvbiBDaGF0UGFnZSgpIHsKICByZXR1cm4gKAogICAg'
    'PFN1c3BlbnNlCiAgICAgIGZhbGxiYWNrPXsKICAgICAgICA8ZGl2IGNsYXNzTmFtZT0icGFnZSIg'
    'c3R5bGU9e3sgbWF4V2lkdGg6IDgyMCB9fT4KICAgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJzZWN0'
    'aW9uLWxhYmVsIj5DaGF0IMK3IGEgY2FycmVnYXLigKY8L2Rpdj4KICAgICAgICA8L2Rpdj4KICAg'
    'ICAgfQogICAgPgogICAgICA8Q2hhdElubmVyIC8+CiAgICA8L1N1c3BlbnNlPgogICk7Cn0K'
)

HELPER_B64 = 'ZGVmIF90cmltX3RvX2xhc3Rfc2VudGVuY2UodGV4dDogc3RyKSAtPiBzdHI6CiAgICAiIiJTZSBvIHRleHRvIHBhcmVjZSBjb3J0YWRvIGEgbWVpbyAobmFvIHRlcm1pbmEgZW0gcG9udHVhY2FvKSwgYXBhcmEKICAgIGF0ZSBhIHVsdGltYSBmcmFzZSBjb21wbGV0YS4gQmxpbmRhZ2VtIGNvbnRyYSByZXNwb3N0YXMgdHJ1bmNhZGFzLiIiIgogICAgaW1wb3J0IHJlIGFzIF9yZQogICAgdCA9ICh0ZXh0IG9yICIiKS5yc3RyaXAoKQogICAgaWYgbm90IHQ6CiAgICAgICAgcmV0dXJuIHQKICAgIGlmIHRbLTFdIGluICcuIT/igKYiKcK7JzoKICAgICAgICByZXR1cm4gdAogICAgbWF0Y2hlcyA9IGxpc3QoX3JlLmZpbmRpdGVyKHIiWy4hP+KApl0oPz1cc3wkKSIsIHQpKQogICAgaWYgbWF0Y2hlczoKICAgICAgICBjdXQgPSBtYXRjaGVzWy0xXS5lbmQoKQogICAgICAgIHRyaW1tZWQgPSB0WzpjdXRdLnJzdHJpcCgpCiAgICAgICAgaWYgbGVuKHRyaW1tZWQpID49IDIwOgogICAgICAgICAgICByZXR1cm4gdHJpbW1lZAogICAgcmV0dXJuIHQKCgo='
ESTRUTURA_B64 = 'RVNUUlVUVVJBOiByZXNwb3N0YXMgY2xhcmFzIGUgYmVtIG9yZ2FuaXphZGFzLCBlbSBwYXLDoWdyYWZvcyBjdXJ0b3MuIFF1YW5kbyBvIHRlbWEganVzdGlmaWNhLCBkZXNlbnZvbHZlIGF0w6kgfjQwMCBwYWxhdnJhcy4gVGVybWluYSBzZW1wcmUgbyByYWNpb2PDrW5pbyDigJQgbnVuY2EgY29ydGVzIHVtYSBpZGVpYSBhIG1laW8uCgo='


def run(cmd, cwd=None):
    print(f"$ {cmd}")
    r = subprocess.run(cmd, shell=True, cwd=cwd, capture_output=True, text=True)
    if r.stdout.strip(): print(r.stdout.rstrip())
    if r.stderr.strip(): print(r.stderr.rstrip(), file=sys.stderr)
    return r.returncode == 0


def patch_backend(root, stamp):
    f = root / "app" / "services" / "chat.py"
    if not f.exists():
        print("  WARN: app/services/chat.py nao encontrado")
        return False
    c = f.read_text()
    shutil.copy2(f, f.with_suffix(f".py.bak.v24.{stamp}"))
    changes = []

    helper = base64.b64decode(HELPER_B64).decode("utf-8")
    estrutura = base64.b64decode(ESTRUTURA_B64).decode("utf-8")

    # 1. Helper antes de _answer_via_gemini
    if "_trim_to_last_sentence" not in c:
        anchor = "def _answer_via_gemini("
        idx = c.find(anchor)
        if idx != -1:
            line_start = c.rfind("\n", 0, idx) + 1
            c = c[:line_start] + helper + c[line_start:]
            changes.append("helper _trim_to_last_sentence adicionado")
        else:
            changes.append("WARN: anchor _answer_via_gemini nao encontrado")
    else:
        changes.append("helper ja presente")

    # 2. Aplicar trim antes do retorno OK
    if "reply_text = _trim_to_last_sentence(reply_text)" not in c:
        a = "    _LAST_CALL_OK_TS = ts"
        if a in c:
            c = c.replace(a, "    reply_text = _trim_to_last_sentence(reply_text)\n" + a, 1)
            changes.append("trim aplicado antes do retorno")
        else:
            changes.append("WARN: nao consegui aplicar o trim")
    else:
        changes.append("trim ja aplicado")

    # 3. Estrutura no system prompt
    tom_anchor = "TOM: caloroso e esperto, como um amigo que conhece o recinto de cor."
    if tom_anchor in c and "ESTRUTURA:" not in c:
        c = c.replace(tom_anchor, estrutura + tom_anchor, 1)
        changes.append("system prompt: estrutura + ~400 palavras")
    elif "ESTRUTURA:" in c:
        changes.append("estrutura ja presente")
    else:
        changes.append("i anchor TOM nao encontrado")

    f.write_text(c)
    for ch in changes:
        mark = "WARN" if ch.startswith("WARN") else ("i" if ch.startswith("i ") else "OK")
        print(f"  [{mark}] {ch}")

    ok = run(f"python3 -m py_compile {f}", cwd=str(root))
    if not ok:
        print(f"  ERRO compile! restaura: cp {f}.bak.v24.{stamp} {f}")
        return False
    print("  OK chat.py compila")
    return True


def patch_searchbar(root, stamp):
    f = root / "frontend" / "components" / "v2" / "PlantaSearchBar.tsx"
    if not f.exists():
        print("  WARN: PlantaSearchBar.tsx nao encontrado")
        return False
    c = f.read_text()
    if "usePathname" in c and "/v2/chat" in c:
        print("  i searchbar ja esconde no /v2/chat")
        return True
    shutil.copy2(f, f.with_suffix(f".tsx.bak.v24.{stamp}"))

    if "import { useRouter } from 'next/navigation';" in c:
        c = c.replace(
            "import { useRouter } from 'next/navigation';",
            "import { useRouter, usePathname } from 'next/navigation';",
        )

    if "const router = useRouter();" in c and "const pathname = usePathname();" not in c:
        c = c.replace(
            "const router = useRouter();",
            "const router = useRouter();\n  const pathname = usePathname();",
            1,
        )

    m = re.search(r"\n  return \(\n    <div\n      style=\{\{\n        position: 'fixed',", c)
    if m:
        guard = "\n  // No /v2/chat o input proprio do chat substitui esta barra\n  if (pathname && pathname.startsWith('/v2/chat')) return null;\n"
        c = c[:m.start()] + guard + c[m.start():]
        print("  OK searchbar esconde-se no /v2/chat")
    else:
        print("  WARN: return principal da searchbar nao encontrado")

    f.write_text(c)
    return True


def main():
    root = Path.cwd()
    if not (root / "frontend").exists():
        print("ERRO: corre a partir de ~/planta_rock4")
        sys.exit(1)
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    print("=" * 68)
    print("  1. BACKEND — blindar Gemini (trim frase + estrutura)")
    print("=" * 68)
    patch_backend(root, stamp)

    print()
    print("=" * 68)
    print("  2. FRONTEND — chat estilo WhatsApp")
    print("=" * 68)
    chat = root / "frontend" / "app" / "v2" / "chat" / "page.tsx"
    if chat.exists():
        shutil.copy2(chat, chat.with_suffix(f".tsx.bak.v24.{stamp}"))
    d = base64.b64decode("".join(CHAT_PAGE_B64))
    chat.write_bytes(d)
    print(f"  OK chat/page.tsx v24 ({len(d)} B) — header fixo + scroll interno + input proprio")

    print()
    print("=" * 68)
    print("  3. FRONTEND — searchbar esconde no /v2/chat")
    print("=" * 68)
    patch_searchbar(root, stamp)

    print()
    print("=" * 68)
    print("  GIT COMMIT + PUSH")
    print("=" * 68)
    run("git add app/services/chat.py frontend/app/v2/chat/page.tsx frontend/components/v2/PlantaSearchBar.tsx", cwd=str(root))
    run('git commit -m "feat(v24): Gemini sem respostas truncadas + chat WhatsApp-style"', cwd=str(root))
    run("git push", cwd=str(root))

    print()
    print("  Aguarda ~90s (Vercel) + ~1-2min (Railway).")
    print()
    print("  Testa /v2/chat:")
    print("    1. A pagina NAO faz scroll — so a area de mensagens.")
    print("    2. Input proprio fixo no fundo, com 📍 e enviar.")
    print("    3. Pergunta longa -> resposta COMPLETA, nunca cortada a meio.")
    print("    4. Pergunta vaga -> recomenda + convida a localizacao.")


if __name__ == "__main__":
    main()
