#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
install_v21 — Chat com routing LOCAL DETERMINISTICO para coordenadas

PROBLEMA RESOLVIDO:
  O chat respondia "Sem dados disponiveis" quando o user mandava coords.
  Isto VIOLA o princípio core do PlantaOS (recomendar sempre o caminho mais leve).

SOLUCAO:
  Reescrita do /v2/chat/page.tsx para INTERCEPTAR mensagens com coords:
    1. Detecta padrao lat, lng via regex
    2. Calcula custo (walk + queue + congestion) para os 8 clusters
       usando posicoes fixas + useLive() snapshot ao vivo
    3. Responde com recomendacao + alternativa
    4. NUNCA chama Gemini para coords -> resposta determinística

POSICOES (em metros, relativas a Palco Mundo):
  wc-01: (-380, 120)   Entrada NW
  wc-02: (80, -30)     Junto ao palco
  wc-03: (-100, 80)    Central
  wc-04: (-200, 200)   Mid-elevado
  wc-05: (250, 180)    Elevado leste (unissex)
  wc-06: (-50, 250)    Central norte (unissex grande)
  wc-07: (-300, -80)   NW lockers
  wc-08: (350, 300)    Outer leste

VENUE_CENTROID: 38.7636°N, -9.0956°E

EXTRAS:
  - Botao verde "Onde esta o WC mais perto?" no welcome screen
  - Suporte simples a markdown (**bold** + quebras de linha)
  - ImageBubble com download (v20 preservado)
  - Suspense wrapper (v12b preservado)
  - sessionStorage para imagens (v20 preservado)
"""

import base64, os, shutil, subprocess, sys
from datetime import datetime
from pathlib import Path

os.environ["PATH"] = ":".join([
    "/usr/bin", "/bin", "/usr/sbin", "/sbin",
    "/usr/local/bin", "/opt/homebrew/bin",
    os.environ.get("PATH", ""),
])

CHAT_B64 = (
    'J3VzZSBjbGllbnQnOwoKaW1wb3J0IHsgU3VzcGVuc2UsIHVzZUVmZmVjdCwgdXNlUmVmLCB1c2VT'
    'dGF0ZSB9IGZyb20gJ3JlYWN0JzsKaW1wb3J0IHsgdXNlUm91dGVyLCB1c2VTZWFyY2hQYXJhbXMg'
    'fSBmcm9tICduZXh0L25hdmlnYXRpb24nOwppbXBvcnQgeyB1c2VMaXZlLCB0eXBlIExpdmVTbmFw'
    'c2hvdCB9IGZyb20gJ0AvY29tcG9uZW50cy92Mi9MaXZlQ29udGV4dCc7Cgpjb25zdCBBUElfQkFT'
    'RSA9IHByb2Nlc3MuZW52Lk5FWFRfUFVCTElDX0FQSV9CQVNFIHx8ICdodHRwczovL2FwaS5wbGFu'
    'dGFyb2NraW5yaW8uY29tJzsKY29uc3QgU1RPUkFHRV9LRVkgPSAncGxhbnRhLWNoYXQtaGlzdG9y'
    'eS12MSc7CmNvbnN0IEFUVEFDSF9LRVkgPSAncGxhbnRhLXBlbmRpbmctaW1hZ2UnOwoKaW50ZXJm'
    'YWNlIE1zZyB7CiAgcm9sZTogJ3VzZXInIHwgJ2Fzc2lzdGFudCc7CiAgY29udGVudDogc3RyaW5n'
    'OwogIHRzOiBudW1iZXI7Cn0KCi8qIOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
    'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
    'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
    'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgAogICBMT0NB'
    'TCBST1VUSU5HIOKAlCBkZXRlcm1pbsOtc3RpY28sIG51bmNhIGRlcGVuZGVudGUgZG8gTExNCiAg'
    'IOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
    'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
    'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
    'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgCAqLwoKLy8gQ2VudHJvaWQgYXByb3hpbWFkbyBk'
    'byBQYXJxdWUgVGVqbyAoTGlzYm9hKQpjb25zdCBWRU5VRV9DRU5UUk9JRCA9IHsgbGF0OiAzOC43'
    'NjM2LCBsbmc6IC05LjA5NTYgfTsKCi8vIENvbnZlcnPDo28gbWV0cm9zIOKGlCBncmF1cywgYmFz'
    'ZWFkYSBlbSBQYWxjbyBNdW5kbyBjb21vIG9yaWdlbQpjb25zdCBNRVRFUl9QRVJfREVHX0xBVCA9'
    'IDExMTMyMDsKY29uc3QgTUVURVJfUEVSX0RFR19MTkcgPSAxMTEzMjAgKiBNYXRoLmNvcygoVkVO'
    'VUVfQ0VOVFJPSUQubGF0ICogTWF0aC5QSSkgLyAxODApOwoKLy8gUG9zacOnw7VlcyBkb3MgOCBj'
    'bHVzdGVycyByZWxhdGl2YXMgYW8gUGFsY28gTXVuZG8gKGVtIG1ldHJvcykKY29uc3QgQ0xVU1RF'
    'UlM6IFJlY29yZDxzdHJpbmcsIHsgeF9tOiBudW1iZXI7IHlfbTogbnVtYmVyOyB6b25lOiBzdHJp'
    'bmcgfT4gPSB7CiAgJ3djLTAxJzogeyB4X206IC0zODAsIHlfbTogMTIwLCAgem9uZTogJ0VudHJh'
    'ZGEgTlcnIH0sCiAgJ3djLTAyJzogeyB4X206IDgwLCAgIHlfbTogLTMwLCAgem9uZTogJ0p1bnRv'
    'IGFvIHBhbGNvJyB9LAogICd3Yy0wMyc6IHsgeF9tOiAtMTAwLCB5X206IDgwLCAgIHpvbmU6ICdD'
    'ZW50cmFsJyB9LAogICd3Yy0wNCc6IHsgeF9tOiAtMjAwLCB5X206IDIwMCwgIHpvbmU6ICdFbGV2'
    'YWRvIG1pZCcgfSwKICAnd2MtMDUnOiB7IHhfbTogMjUwLCAgeV9tOiAxODAsICB6b25lOiAnRWxl'
    'dmFkbyBsZXN0ZSAodW5pc3NleCknIH0sCiAgJ3djLTA2JzogeyB4X206IC01MCwgIHlfbTogMjUw'
    'LCAgem9uZTogJ0NlbnRyYWwgbm9ydGUgKHVuaXNzZXggZ3JhbmRlKScgfSwKICAnd2MtMDcnOiB7'
    'IHhfbTogLTMwMCwgeV9tOiAtODAsICB6b25lOiAnTlcgwrcgbG9ja2VycycgfSwKICAnd2MtMDgn'
    'OiB7IHhfbTogMzUwLCAgeV9tOiAzMDAsICB6b25lOiAnT3V0ZXIgbGVzdGUnIH0sCn07Cgpjb25z'
    'dCBDT09SRFNfUkVHRVggPSAvKC0/XGR7MSwzfVwuXGR7Miw4fSlccyosXHMqKC0/XGR7MSwzfVwu'
    'XGR7Miw4fSkvOwoKZnVuY3Rpb24gZGV0ZWN0Q29vcmRzKHRleHQ6IHN0cmluZyk6IHsgbGF0OiBu'
    'dW1iZXI7IGxuZzogbnVtYmVyIH0gfCBudWxsIHsKICBjb25zdCBtID0gdGV4dC5tYXRjaChDT09S'
    'RFNfUkVHRVgpOwogIGlmICghbSkgcmV0dXJuIG51bGw7CiAgY29uc3QgbGF0ID0gcGFyc2VGbG9h'
    'dChtWzFdKTsKICBjb25zdCBsbmcgPSBwYXJzZUZsb2F0KG1bMl0pOwogIGlmIChOdW1iZXIuaXNO'
    'YU4obGF0KSB8fCBOdW1iZXIuaXNOYU4obG5nKSkgcmV0dXJuIG51bGw7CiAgaWYgKE1hdGguYWJz'
    'KGxhdCkgPiA5MCB8fCBNYXRoLmFicyhsbmcpID4gMTgwKSByZXR1cm4gbnVsbDsKICByZXR1cm4g'
    'eyBsYXQsIGxuZyB9Owp9CgpmdW5jdGlvbiBjbHVzdGVyUG9zKGNpZDogc3RyaW5nKTogeyBsYXQ6'
    'IG51bWJlcjsgbG5nOiBudW1iZXIgfSB7CiAgY29uc3QgYyA9IENMVVNURVJTW2NpZF07CiAgaWYg'
    'KCFjKSByZXR1cm4gVkVOVUVfQ0VOVFJPSUQ7CiAgcmV0dXJuIHsKICAgIGxhdDogVkVOVUVfQ0VO'
    'VFJPSUQubGF0ICsgYy55X20gLyBNRVRFUl9QRVJfREVHX0xBVCwKICAgIGxuZzogVkVOVUVfQ0VO'
    'VFJPSUQubG5nICsgYy54X20gLyBNRVRFUl9QRVJfREVHX0xORywKICB9Owp9CgpmdW5jdGlvbiBo'
    'YXZlcnNpbmUoYTogeyBsYXQ6IG51bWJlcjsgbG5nOiBudW1iZXIgfSwgYjogeyBsYXQ6IG51bWJl'
    'cjsgbG5nOiBudW1iZXIgfSk6IG51bWJlciB7CiAgY29uc3QgUiA9IDYzNzEwMDA7CiAgY29uc3Qg'
    'dG9SYWQgPSAoZDogbnVtYmVyKSA9PiAoZCAqIE1hdGguUEkpIC8gMTgwOwogIGNvbnN0IGRMYXQg'
    'PSB0b1JhZChiLmxhdCAtIGEubGF0KTsKICBjb25zdCBkTG5nID0gdG9SYWQoYi5sbmcgLSBhLmxu'
    'Zyk7CiAgY29uc3QgbGF0MSA9IHRvUmFkKGEubGF0KTsKICBjb25zdCBsYXQyID0gdG9SYWQoYi5s'
    'YXQpOwogIGNvbnN0IHggPQogICAgTWF0aC5zaW4oZExhdCAvIDIpICoqIDIgKwogICAgTWF0aC5j'
    'b3MobGF0MSkgKiBNYXRoLmNvcyhsYXQyKSAqIE1hdGguc2luKGRMbmcgLyAyKSAqKiAyOwogIHJl'
    'dHVybiAyICogUiAqIE1hdGguYXRhbjIoTWF0aC5zcXJ0KHgpLCBNYXRoLnNxcnQoMSAtIHgpKTsK'
    'fQoKaW50ZXJmYWNlIFJhbmtpbmcgewogIGNpZDogc3RyaW5nOwogIGRpc3RNZXRlcnM6IG51bWJl'
    'cjsKICB3YWxrU2Vjb25kczogbnVtYmVyOwogIG9jYzogbnVtYmVyOwogIGZpbGE6IG51bWJlcjsK'
    'ICB3YWl0U2VjOiBudW1iZXI7CiAgdG90YWxDb3N0OiBudW1iZXI7Cn0KCmZ1bmN0aW9uIHJlY29t'
    'bWVuZENsdXN0ZXIoCiAgdXNlckxhdDogbnVtYmVyLAogIHVzZXJMbmc6IG51bWJlciwKICBzbmFw'
    'c2hvdDogTGl2ZVNuYXBzaG90IHwgbnVsbCwKKTogeyBiZXN0OiBSYW5raW5nOyBhbHQ6IFJhbmtp'
    'bmcgfCBudWxsOyBpc091dHNpZGU6IGJvb2xlYW47IHZlbnVlRGlzdDogbnVtYmVyIH0gfCBudWxs'
    'IHsKICBjb25zdCB1c2VyID0geyBsYXQ6IHVzZXJMYXQsIGxuZzogdXNlckxuZyB9OwogIGNvbnN0'
    'IHZlbnVlRGlzdCA9IGhhdmVyc2luZSh1c2VyLCBWRU5VRV9DRU5UUk9JRCk7CiAgY29uc3QgaXNP'
    'dXRzaWRlID0gdmVudWVEaXN0ID4gODAwOyAvLyA+IDgwMG0gZG8gY2VudHJvaWQgPSBmb3JhIGRv'
    'IHZlbnVlCgogIGNvbnN0IHNvdXJjZUNsdXN0ZXJzID0gT2JqZWN0LmtleXMoQ0xVU1RFUlMpOwog'
    'IGNvbnN0IGxpdmVNYXAgPSBuZXcgTWFwKAogICAgKHNuYXBzaG90Py5jbHVzdGVycyA/PyBbXSku'
    'bWFwKChjKSA9PiBbYy5jbHVzdGVyX2lkLCBjXSksCiAgKTsKCiAgY29uc3QgcmFua2VkOiBSYW5r'
    'aW5nW10gPSBzb3VyY2VDbHVzdGVycwogICAgLm1hcCgoY2lkKSA9PiB7CiAgICAgIGNvbnN0IHBv'
    'cyA9IGNsdXN0ZXJQb3MoY2lkKTsKICAgICAgY29uc3QgZGlzdE1ldGVycyA9IGhhdmVyc2luZSh1'
    'c2VyLCBwb3MpOwogICAgICBjb25zdCB3YWxrU2Vjb25kcyA9IGRpc3RNZXRlcnMgLyAxLjQ7IC8v'
    'IH4xLjQgbS9zIG5vcm1hbCB3YWxraW5nCiAgICAgIGNvbnN0IGxpdmUgPSBsaXZlTWFwLmdldChj'
    'aWQpOwogICAgICBjb25zdCBvY2MgPSBsaXZlPy5wYXJhbXM/Lm9jdXBhY2FvX2luc3RhbnRhbmVh'
    'ID8/IDA7CiAgICAgIGNvbnN0IGZpbGEgPSBsaXZlPy5wYXJhbXM/LmZpbGFfYXR1YWwgPz8gMDsK'
    'ICAgICAgY29uc3Qgd2FpdFNlYyA9IChsaXZlPy5wYXJhbXM/LnRlbXBvX2VzcGVyYV9taW4gPz8g'
    'MCkgKiA2MDsKICAgICAgY29uc3QgY29uZ2VzdGlvblBlbmFsdHkgPSBvY2MgPj0gODAgPyA5MCA6'
    'IG9jYyA+PSA2MCA/IDI1IDogMDsKICAgICAgY29uc3QgdG90YWxDb3N0ID0gd2Fsa1NlY29uZHMg'
    'KyB3YWl0U2VjICsgY29uZ2VzdGlvblBlbmFsdHk7CiAgICAgIHJldHVybiB7IGNpZCwgZGlzdE1l'
    'dGVycywgd2Fsa1NlY29uZHMsIG9jYywgZmlsYSwgd2FpdFNlYywgdG90YWxDb3N0IH07CiAgICB9'
    'KQogICAgLnNvcnQoKGEsIGIpID0+IGEudG90YWxDb3N0IC0gYi50b3RhbENvc3QpOwoKICBpZiAo'
    'IXJhbmtlZC5sZW5ndGgpIHJldHVybiBudWxsOwogIHJldHVybiB7IGJlc3Q6IHJhbmtlZFswXSwg'
    'YWx0OiByYW5rZWRbMV0gfHwgbnVsbCwgaXNPdXRzaWRlLCB2ZW51ZURpc3QgfTsKfQoKZnVuY3Rp'
    'b24gZm10RGlzdChtOiBudW1iZXIpOiBzdHJpbmcgewogIGlmIChtIDwgMTAwMCkgcmV0dXJuIGAk'
    'e01hdGgucm91bmQobSl9IG1gOwogIGlmIChtIDwgMTAwMDApIHJldHVybiBgJHsobSAvIDEwMDAp'
    'LnRvRml4ZWQoMSl9IGttYDsKICByZXR1cm4gYCR7TWF0aC5yb3VuZChtIC8gMTAwMCl9IGttYDsK'
    'fQoKZnVuY3Rpb24gZm10V2Fsa01pbihzZWNvbmRzOiBudW1iZXIpOiBzdHJpbmcgewogIGNvbnN0'
    'IG0gPSBNYXRoLm1heCgxLCBNYXRoLnJvdW5kKHNlY29uZHMgLyA2MCkpOwogIHJldHVybiBgJHtt'
    'fSBtaW5gOwp9CgpmdW5jdGlvbiBmb3JtYXRSZWNvbW1lbmRhdGlvbigKICByZWM6IFJldHVyblR5'
    'cGU8dHlwZW9mIHJlY29tbWVuZENsdXN0ZXI+LAopOiBzdHJpbmcgewogIGlmICghcmVjKSB7CiAg'
    'ICByZXR1cm4gJ0FpbmRhIG7Do28gdGVuaG8gZGFkb3MgYW8gdml2by4gVGVudGEgZW0gcG91Y29z'
    'IHNlZ3VuZG9zLic7CiAgfQogIGNvbnN0IHsgYmVzdCwgYWx0LCBpc091dHNpZGUsIHZlbnVlRGlz'
    'dCB9ID0gcmVjOwogIGNvbnN0IGNpZFVwcGVyID0gYmVzdC5jaWQudG9VcHBlckNhc2UoKTsKICBj'
    'b25zdCB6b25lID0gQ0xVU1RFUlNbYmVzdC5jaWRdPy56b25lID8/ICcnOwogIGNvbnN0IG9jY0xh'
    'YmVsID0gYCR7TWF0aC5yb3VuZChiZXN0Lm9jYyl9JSBvY3VwYcOnw6NvYDsKICBjb25zdCBmaWxh'
    'TGFiZWwgPSBiZXN0LmZpbGEgPiAwID8gYCDCtyAke2Jlc3QuZmlsYX0gcGVzc29hcyBuYSBmaWxh'
    'YCA6ICcnOwoKICBsZXQgdHh0ID0gJyc7CiAgaWYgKGlzT3V0c2lkZSkgewogICAgdHh0ICs9IGBF'
    'c3TDoXMgYSAke2ZtdERpc3QodmVudWVEaXN0KX0gZG8gUGFycXVlIFRlam8uIFF1YW5kbyBjaGVn'
    'YXJlcyBhbyBmZXN0aXZhbCwgdmFpIGE6XG5cbmA7CiAgfQogIHR4dCArPSBgKioke2NpZFVwcGVy'
    'fSoqIMK3ICR7em9uZX1cbmA7CiAgdHh0ICs9IGAke2ZtdERpc3QoYmVzdC5kaXN0TWV0ZXJzKX0g'
    'wrcgfiR7Zm10V2Fsa01pbihiZXN0LndhbGtTZWNvbmRzKX0gYSBww6lcbmA7CiAgdHh0ICs9IGAk'
    'e29jY0xhYmVsfSR7ZmlsYUxhYmVsfWA7CiAgaWYgKGJlc3Qud2FpdFNlYyA+IDMwKSB0eHQgKz0g'
    'YCDCtyB+JHtNYXRoLnJvdW5kKGJlc3Qud2FpdFNlYyAvIDYwKX0gbWluIGVzcGVyYWA7CgogIGlm'
    'IChhbHQgJiYgYWx0LmNpZCAhPT0gYmVzdC5jaWQpIHsKICAgIGNvbnN0IGFsdFVwcGVyID0gYWx0'
    'LmNpZC50b1VwcGVyQ2FzZSgpOwogICAgdHh0ICs9IGBcblxuQWx0ZXJuYXRpdmE6ICoqJHthbHRV'
    'cHBlcn0qKiDigJQgJHtmbXRXYWxrTWluKGFsdC53YWxrU2Vjb25kcyl9IGEgcMOpLCAke01hdGgu'
    'cm91bmQoYWx0Lm9jYyl9JSBvY3VwYcOnw6NvLmA7CiAgfQogIHJldHVybiB0eHQ7Cn0KCi8qIOKU'
    'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
    'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
    'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
    'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgAogICBISVNUw5NSSUNPIExPQ0FMCiAgIOKUgOKUgOKU'
    'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
    'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
    'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
    'gOKUgOKUgOKUgOKUgOKUgOKUgCAqLwoKZnVuY3Rpb24gbG9hZEhpc3RvcnkoKTogTXNnW10gewog'
    'IGlmICh0eXBlb2Ygd2luZG93ID09PSAndW5kZWZpbmVkJykgcmV0dXJuIFtdOwogIHRyeSB7CiAg'
    'ICBjb25zdCByYXcgPSBsb2NhbFN0b3JhZ2UuZ2V0SXRlbShTVE9SQUdFX0tFWSk7CiAgICBpZiAo'
    'IXJhdykgcmV0dXJuIFtdOwogICAgY29uc3QgcGFyc2VkID0gSlNPTi5wYXJzZShyYXcpOwogICAg'
    'aWYgKEFycmF5LmlzQXJyYXkocGFyc2VkKSkgcmV0dXJuIHBhcnNlZDsKICAgIHJldHVybiBbXTsK'
    'ICB9IGNhdGNoIHsKICAgIHJldHVybiBbXTsKICB9Cn0KCmZ1bmN0aW9uIHNhdmVIaXN0b3J5KG1z'
    'Z3M6IE1zZ1tdKSB7CiAgaWYgKHR5cGVvZiB3aW5kb3cgPT09ICd1bmRlZmluZWQnKSByZXR1cm47'
    'CiAgdHJ5IHsKICAgIGxvY2FsU3RvcmFnZS5zZXRJdGVtKFNUT1JBR0VfS0VZLCBKU09OLnN0cmlu'
    'Z2lmeShtc2dzLnNsaWNlKC0yMDApKSk7CiAgfSBjYXRjaCB7fQp9CgpmdW5jdGlvbiBpc0ltYWdl'
    'RGF0YVVybChzOiBzdHJpbmcpOiBib29sZWFuIHsKICByZXR1cm4gdHlwZW9mIHMgPT09ICdzdHJp'
    'bmcnICYmIHMuc3RhcnRzV2l0aCgnZGF0YTppbWFnZS8nKTsKfQoKLyogU3Vwb3J0ZSBzaW1wbGVz'
    'IGEgbWFya2Rvd246ICoqYm9sZCoqICsgcXVlYnJhcyBkZSBsaW5oYSAqLwpmdW5jdGlvbiByZW5k'
    'ZXJJbmxpbmUodGV4dDogc3RyaW5nKTogUmVhY3QuUmVhY3ROb2RlW10gewogIGNvbnN0IHBhcnRz'
    'OiBSZWFjdC5SZWFjdE5vZGVbXSA9IFtdOwogIGNvbnN0IHJlZ2V4ID0gL1wqXCooW14qXSspXCpc'
    'Ki9nOwogIGxldCBsYXN0ID0gMDsKICBsZXQgaWR4ID0gMDsKICBsZXQgbTogUmVnRXhwRXhlY0Fy'
    'cmF5IHwgbnVsbDsKICB3aGlsZSAoKG0gPSByZWdleC5leGVjKHRleHQpKSAhPT0gbnVsbCkgewog'
    'ICAgaWYgKG0uaW5kZXggPiBsYXN0KSBwYXJ0cy5wdXNoKHRleHQuc2xpY2UobGFzdCwgbS5pbmRl'
    'eCkpOwogICAgcGFydHMucHVzaCg8c3Ryb25nIGtleT17aWR4Kyt9PnttWzFdfTwvc3Ryb25nPik7'
    'CiAgICBsYXN0ID0gcmVnZXgubGFzdEluZGV4OwogIH0KICBpZiAobGFzdCA8IHRleHQubGVuZ3Ro'
    'KSBwYXJ0cy5wdXNoKHRleHQuc2xpY2UobGFzdCkpOwogIHJldHVybiBwYXJ0czsKfQoKZnVuY3Rp'
    'b24gTWVzc2FnZUNvbnRlbnQoeyBjb250ZW50IH06IHsgY29udGVudDogc3RyaW5nIH0pIHsKICBp'
    'ZiAoaXNJbWFnZURhdGFVcmwoY29udGVudCkpIHsKICAgIHJldHVybiA8SW1hZ2VCdWJibGUgc3Jj'
    'PXtjb250ZW50fSAvPjsKICB9CiAgY29uc3QgbGluZXMgPSBjb250ZW50LnNwbGl0KCdcbicpOwog'
    'IHJldHVybiAoCiAgICA8PgogICAgICB7bGluZXMubWFwKChsaW5lLCBpKSA9PiAoCiAgICAgICAg'
    'PHNwYW4ga2V5PXtpfT4KICAgICAgICAgIHtyZW5kZXJJbmxpbmUobGluZSl9CiAgICAgICAgICB7'
    'aSA8IGxpbmVzLmxlbmd0aCAtIDEgJiYgPGJyIC8+fQogICAgICAgIDwvc3Bhbj4KICAgICAgKSl9'
    'CiAgICA8Lz4KICApOwp9CgpmdW5jdGlvbiBJbWFnZUJ1YmJsZSh7IHNyYyB9OiB7IHNyYzogc3Ry'
    'aW5nIH0pIHsKICBjb25zdCBmaWxlbmFtZSA9IGBwbGFudGEtJHtEYXRlLm5vdygpfS5wbmdgOwog'
    'IHJldHVybiAoCiAgICA8ZGl2IHN0eWxlPXt7IGRpc3BsYXk6ICdmbGV4JywgZmxleERpcmVjdGlv'
    'bjogJ2NvbHVtbicsIGdhcDogNiB9fT4KICAgICAgPGltZwogICAgICAgIHNyYz17c3JjfQogICAg'
    'ICAgIGFsdD0iaW1hZ2VtIGFuZXhhZGEiCiAgICAgICAgc3R5bGU9e3sKICAgICAgICAgIG1heFdp'
    'ZHRoOiAnMTAwJScsCiAgICAgICAgICBtYXhIZWlnaHQ6IDM2MCwKICAgICAgICAgIGJvcmRlclJh'
    'ZGl1czogMTIsCiAgICAgICAgICBkaXNwbGF5OiAnYmxvY2snLAogICAgICAgIH19CiAgICAgIC8+'
    'CiAgICAgIDxhCiAgICAgICAgaHJlZj17c3JjfQogICAgICAgIGRvd25sb2FkPXtmaWxlbmFtZX0K'
    'ICAgICAgICBzdHlsZT17ewogICAgICAgICAgZm9udFNpemU6IDExLAogICAgICAgICAgY29sb3I6'
    'ICdyZ2JhKDI1NSwyNTUsMjU1LDAuOSknLAogICAgICAgICAgdGV4dERlY29yYXRpb246ICd1bmRl'
    'cmxpbmUnLAogICAgICAgICAgdGV4dEFsaWduOiAncmlnaHQnLAogICAgICAgICAgZm9udEZhbWls'
    'eTogJ3ZhcigtLWZvbnQtbW9ubyknLAogICAgICAgICAgbGV0dGVyU3BhY2luZzogJzAuMDRlbScs'
    'CiAgICAgICAgfX0KICAgICAgPgogICAgICAgIOKshyBndWFyZGFyCiAgICAgIDwvYT4KICAgIDwv'
    'ZGl2PgogICk7Cn0KCi8qIOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
    'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
    'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
    'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgAogICBDT01QT05FTlQK'
    'ICAg4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA'
    '4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA'
    '4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA'
    '4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSAICovCgpmdW5jdGlvbiBDaGF0SW5uZXIoKSB7'
    'CiAgY29uc3Qgcm91dGVyID0gdXNlUm91dGVyKCk7CiAgY29uc3QgcGFyYW1zID0gdXNlU2VhcmNo'
    'UGFyYW1zKCk7CiAgY29uc3QgeyBzbmFwc2hvdCB9ID0gdXNlTGl2ZSgpOwogIGNvbnN0IHNuYXBz'
    'aG90UmVmID0gdXNlUmVmPExpdmVTbmFwc2hvdCB8IG51bGw+KG51bGwpOwogIHNuYXBzaG90UmVm'
    'LmN1cnJlbnQgPSBzbmFwc2hvdDsKCiAgY29uc3QgW21lc3NhZ2VzLCBzZXRNZXNzYWdlc10gPSB1'
    'c2VTdGF0ZTxNc2dbXT4oW10pOwogIGNvbnN0IFtpbnB1dCwgc2V0SW5wdXRdID0gdXNlU3RhdGUo'
    'JycpOwogIGNvbnN0IFtzZW5kaW5nLCBzZXRTZW5kaW5nXSA9IHVzZVN0YXRlKGZhbHNlKTsKICBj'
    'b25zdCBzY3JvbGxSZWYgPSB1c2VSZWY8SFRNTERpdkVsZW1lbnQ+KG51bGwpOwogIGNvbnN0IGhh'
    'bmRsZWRRdWVyeSA9IHVzZVJlZjxzdHJpbmcgfCBudWxsPihudWxsKTsKCiAgdXNlRWZmZWN0KCgp'
    'ID0+IHsKICAgIHNldE1lc3NhZ2VzKGxvYWRIaXN0b3J5KCkpOwogICAgLy8gQWNlaXRhciBpbWFn'
    'ZW0gYW5leGFkYSB2aWEgc2Vzc2lvblN0b3JhZ2UKICAgIHRyeSB7CiAgICAgIGNvbnN0IHJhdyA9'
    'IHNlc3Npb25TdG9yYWdlLmdldEl0ZW0oQVRUQUNIX0tFWSk7CiAgICAgIGlmIChyYXcpIHsKICAg'
    'ICAgICBjb25zdCBkYXRhID0gSlNPTi5wYXJzZShyYXcpOwogICAgICAgIHNlc3Npb25TdG9yYWdl'
    'LnJlbW92ZUl0ZW0oQVRUQUNIX0tFWSk7CiAgICAgICAgaWYgKGRhdGEgJiYgZGF0YS5kYXRhVXJs'
    'KSB7CiAgICAgICAgICBjb25zdCBpbWdNc2c6IE1zZyA9IHsKICAgICAgICAgICAgcm9sZTogJ3Vz'
    'ZXInLAogICAgICAgICAgICBjb250ZW50OiBkYXRhLmRhdGFVcmwsCiAgICAgICAgICAgIHRzOiBE'
    'YXRlLm5vdygpLAogICAgICAgICAgfTsKICAgICAgICAgIHNldE1lc3NhZ2VzKChwcmV2KSA9PiB7'
    'CiAgICAgICAgICAgIGNvbnN0IG5leHQgPSBbLi4ucHJldiwgaW1nTXNnXTsKICAgICAgICAgICAg'
    'c2F2ZUhpc3RvcnkobmV4dCk7CiAgICAgICAgICAgIHJldHVybiBuZXh0OwogICAgICAgICAgfSk7'
    'CiAgICAgICAgfQogICAgICB9CiAgICB9IGNhdGNoIHt9CiAgfSwgW10pOwoKICB1c2VFZmZlY3Qo'
    'KCkgPT4gewogICAgaWYgKHNjcm9sbFJlZi5jdXJyZW50KSB7CiAgICAgIHNjcm9sbFJlZi5jdXJy'
    'ZW50LnNjcm9sbFRvcCA9IHNjcm9sbFJlZi5jdXJyZW50LnNjcm9sbEhlaWdodDsKICAgIH0KICB9'
    'LCBbbWVzc2FnZXNdKTsKCiAgdXNlRWZmZWN0KCgpID0+IHsKICAgIGNvbnN0IHEgPSBwYXJhbXM/'
    'LmdldCgncScpOwogICAgaWYgKHEgJiYgaGFuZGxlZFF1ZXJ5LmN1cnJlbnQgIT09IHEpIHsKICAg'
    'ICAgaGFuZGxlZFF1ZXJ5LmN1cnJlbnQgPSBxOwogICAgICBzZW5kKHEpOwogICAgICByb3V0ZXIu'
    'cmVwbGFjZSgnL3YyL2NoYXQnLCB7IHNjcm9sbDogZmFsc2UgfSk7CiAgICB9CiAgICAvLyBlc2xp'
    'bnQtZGlzYWJsZS1uZXh0LWxpbmUgcmVhY3QtaG9va3MvZXhoYXVzdGl2ZS1kZXBzCiAgfSwgW3Bh'
    'cmFtc10pOwoKICBjb25zdCBzZW5kID0gYXN5bmMgKHRleHQ/OiBzdHJpbmcpID0+IHsKICAgIGNv'
    'bnN0IGNvbnRlbnQgPSAodGV4dCA/PyBpbnB1dCkudHJpbSgpOwogICAgaWYgKCFjb250ZW50IHx8'
    'IHNlbmRpbmcpIHJldHVybjsKCiAgICBjb25zdCB1c2VyTXNnOiBNc2cgPSB7IHJvbGU6ICd1c2Vy'
    'JywgY29udGVudCwgdHM6IERhdGUubm93KCkgfTsKICAgIHNldE1lc3NhZ2VzKChtKSA9PiB7CiAg'
    'ICAgIGNvbnN0IG5leHQgPSBbLi4ubSwgdXNlck1zZ107CiAgICAgIHNhdmVIaXN0b3J5KG5leHQp'
    'OwogICAgICByZXR1cm4gbmV4dDsKICAgIH0pOwogICAgc2V0SW5wdXQoJycpOwogICAgc2V0U2Vu'
    'ZGluZyh0cnVlKTsKCiAgICAvLyDilZTilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDi'
    'lZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDi'
    'lZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDi'
    'lZDilZDilZDilZDilZDilZDilZDilZDilZcKICAgIC8vIOKVkSBJTlRFUkNFUFQ6IGNvb3JkZW5h'
    'ZGFzIOKGkiByb3V0aW5nIGxvY2FsIGRldGVybWluw61zdGljbyAgIOKVkQogICAgLy8g4pWRIE5V'
    'TkNBICJzZW0gZGFkb3MiIHF1YW5kbyBow6EgY29vcmRzLiAgICAgICAgICAgICAgICAgICAgIOKV'
    'kQogICAgLy8g4pWa4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ'
    '4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ'
    '4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ'
    '4pWQ4pWQ4pWQ4pWQ4pWdCiAgICBjb25zdCBjb29yZHMgPSBkZXRlY3RDb29yZHMoY29udGVudCk7'
    'CiAgICBpZiAoY29vcmRzKSB7CiAgICAgIC8vIEVzcGVyYSAyNTBtcyBwYXJhIHBhcmVjZXIgImEg'
    'cGVuc2FyIiArIGVzcGVyYXIgcGVsbyBwcmltZWlybyB0aWNrIGRvIHVzZUxpdmUKICAgICAgYXdh'
    'aXQgbmV3IFByb21pc2UoKHIpID0+IHNldFRpbWVvdXQociwgMjUwKSk7CiAgICAgIGNvbnN0IHJl'
    'YyA9IHJlY29tbWVuZENsdXN0ZXIoY29vcmRzLmxhdCwgY29vcmRzLmxuZywgc25hcHNob3RSZWYu'
    'Y3VycmVudCk7CiAgICAgIGNvbnN0IHJlcGx5ID0gZm9ybWF0UmVjb21tZW5kYXRpb24ocmVjKTsK'
    'ICAgICAgY29uc3QgYWlNc2c6IE1zZyA9IHsgcm9sZTogJ2Fzc2lzdGFudCcsIGNvbnRlbnQ6IHJl'
    'cGx5LCB0czogRGF0ZS5ub3coKSB9OwogICAgICBzZXRNZXNzYWdlcygobSkgPT4gewogICAgICAg'
    'IGNvbnN0IG5leHQgPSBbLi4ubSwgYWlNc2ddOwogICAgICAgIHNhdmVIaXN0b3J5KG5leHQpOwog'
    'ICAgICAgIHJldHVybiBuZXh0OwogICAgICB9KTsKICAgICAgc2V0U2VuZGluZyhmYWxzZSk7CiAg'
    'ICAgIHJldHVybjsKICAgIH0KCiAgICAvLyBGbHV4byBub3JtYWwg4oCUIGNoYW1hciAvYXBpL3Yx'
    'L2NoYXQKICAgIHRyeSB7CiAgICAgIGNvbnN0IHIgPSBhd2FpdCBmZXRjaChgJHtBUElfQkFTRX0v'
    'YXBpL3YxL2NoYXRgLCB7CiAgICAgICAgbWV0aG9kOiAnUE9TVCcsCiAgICAgICAgaGVhZGVyczog'
    'eyAnY29udGVudC10eXBlJzogJ2FwcGxpY2F0aW9uL2pzb24nIH0sCiAgICAgICAgYm9keTogSlNP'
    'Ti5zdHJpbmdpZnkoeyBtZXNzYWdlOiBjb250ZW50IH0pLAogICAgICB9KTsKICAgICAgbGV0IHJl'
    'cGx5ID0gJ0Rlc2N1bHBhLCBuw6NvIGNvbnNlZ3VpIHByb2Nlc3Nhci4nOwogICAgICBpZiAoci5v'
    'aykgewogICAgICAgIGNvbnN0IGogPSBhd2FpdCByLmpzb24oKTsKICAgICAgICByZXBseSA9CiAg'
    'ICAgICAgICBqLnJlcGx5IHx8CiAgICAgICAgICBqLm1lc3NhZ2UgfHwKICAgICAgICAgIGoucmVz'
    'cG9uc2UgfHwKICAgICAgICAgIGoudGV4dCB8fAogICAgICAgICAgSlNPTi5zdHJpbmdpZnkoaiku'
    'c2xpY2UoMCwgMjAwKTsKICAgICAgfSBlbHNlIHsKICAgICAgICByZXBseSA9IGBFcnJvIGRvIHNl'
    'cnZpZG9yICgke3Iuc3RhdHVzfSkuYDsKICAgICAgfQogICAgICBjb25zdCBhaU1zZzogTXNnID0g'
    'eyByb2xlOiAnYXNzaXN0YW50JywgY29udGVudDogcmVwbHksIHRzOiBEYXRlLm5vdygpIH07CiAg'
    'ICAgIHNldE1lc3NhZ2VzKChtKSA9PiB7CiAgICAgICAgY29uc3QgbmV4dCA9IFsuLi5tLCBhaU1z'
    'Z107CiAgICAgICAgc2F2ZUhpc3RvcnkobmV4dCk7CiAgICAgICAgcmV0dXJuIG5leHQ7CiAgICAg'
    'IH0pOwogICAgfSBjYXRjaCB7CiAgICAgIGNvbnN0IGVyck1zZzogTXNnID0gewogICAgICAgIHJv'
    'bGU6ICdhc3Npc3RhbnQnLAogICAgICAgIGNvbnRlbnQ6ICdQcm9ibGVtYSBkZSBsaWdhw6fDo28u'
    'IFZlcmlmaWNhIGEgcmVkZS4nLAogICAgICAgIHRzOiBEYXRlLm5vdygpLAogICAgICB9OwogICAg'
    'ICBzZXRNZXNzYWdlcygobSkgPT4gewogICAgICAgIGNvbnN0IG5leHQgPSBbLi4ubSwgZXJyTXNn'
    'XTsKICAgICAgICBzYXZlSGlzdG9yeShuZXh0KTsKICAgICAgICByZXR1cm4gbmV4dDsKICAgICAg'
    'fSk7CiAgICB9IGZpbmFsbHkgewogICAgICBzZXRTZW5kaW5nKGZhbHNlKTsKICAgIH0KICB9OwoK'
    'ICBjb25zdCBjbGVhckhpc3RvcnkgPSAoKSA9PiB7CiAgICBpZiAoY29uZmlybSgnTGltcGFyIHRv'
    'ZG8gbyBoaXN0w7NyaWNvIGRlIGNvbnZlcnNhPycpKSB7CiAgICAgIHNldE1lc3NhZ2VzKFtdKTsK'
    'ICAgICAgc2F2ZUhpc3RvcnkoW10pOwogICAgfQogIH07CgogIGNvbnN0IGFza0xvY2F0aW9uID0g'
    'KCkgPT4gewogICAgaWYgKCEoJ2dlb2xvY2F0aW9uJyBpbiBuYXZpZ2F0b3IpKSB7CiAgICAgIGFs'
    'ZXJ0KCdHZW9sb2NhbGl6YcOnw6NvIG7Do28gc3Vwb3J0YWRhIG5lc3RlIGJyb3dzZXIuJyk7CiAg'
    'ICAgIHJldHVybjsKICAgIH0KICAgIG5hdmlnYXRvci5nZW9sb2NhdGlvbi5nZXRDdXJyZW50UG9z'
    'aXRpb24oCiAgICAgIChwb3MpID0+IHsKICAgICAgICBjb25zdCB7IGxhdGl0dWRlLCBsb25naXR1'
    'ZGUgfSA9IHBvcy5jb29yZHM7CiAgICAgICAgc2VuZChgRXN0b3UgZW0gJHtsYXRpdHVkZS50b0Zp'
    'eGVkKDYpfSwgJHtsb25naXR1ZGUudG9GaXhlZCg2KX0uIFF1YWwgYSBjYXNhLWRlLWJhbmhvIG1h'
    'aXMgcHLDs3hpbWE/YCk7CiAgICAgIH0sCiAgICAgIChlcnIpID0+IGFsZXJ0KGBOw6NvIGNvbnNl'
    'Z3VpIG9idGVyIGxvY2FsaXphw6fDo286ICR7ZXJyLm1lc3NhZ2V9YCksCiAgICAgIHsgdGltZW91'
    'dDogODAwMCwgZW5hYmxlSGlnaEFjY3VyYWN5OiB0cnVlIH0sCiAgICApOwogIH07CgogIHJldHVy'
    'biAoCiAgICA8ZGl2IGNsYXNzTmFtZT0icGFnZSIgc3R5bGU9e3sgbWF4V2lkdGg6IDgyMCwgcGFk'
    'ZGluZ0JvdHRvbTogMzIgfX0+CiAgICAgIDxkaXYKICAgICAgICBzdHlsZT17ewogICAgICAgICAg'
    'ZGlzcGxheTogJ2ZsZXgnLAogICAgICAgICAganVzdGlmeUNvbnRlbnQ6ICdzcGFjZS1iZXR3ZWVu'
    'JywKICAgICAgICAgIGFsaWduSXRlbXM6ICdmbGV4LWVuZCcsCiAgICAgICAgICBtYXJnaW5Cb3R0'
    'b206IDI0LAogICAgICAgICAgYm9yZGVyQm90dG9tOiAnMXB4IHNvbGlkIHZhcigtLWJvcmRlcikn'
    'LAogICAgICAgICAgcGFkZGluZ0JvdHRvbTogMTgsCiAgICAgICAgfX0KICAgICAgPgogICAgICAg'
    'IDxkaXY+CiAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT0ic2VjdGlvbi1sYWJlbCI+Q2hhdCDCtyBQ'
    'bGFudGEgU21hcnQgSG9tZXM8L2Rpdj4KICAgICAgICAgIDxoMgogICAgICAgICAgICBzdHlsZT17'
    'ewogICAgICAgICAgICAgIGZvbnRGYW1pbHk6ICd2YXIoLS1mb250LWRpc3BsYXkpJywKICAgICAg'
    'ICAgICAgICBmb250U2l6ZTogJ2NsYW1wKDI4cHgsIDR2dywgNDRweCknLAogICAgICAgICAgICAg'
    'IGZvbnRXZWlnaHQ6IDUwMCwKICAgICAgICAgICAgICBsZXR0ZXJTcGFjaW5nOiAnLTAuMDNlbScs'
    'CiAgICAgICAgICAgICAgbGluZUhlaWdodDogMSwKICAgICAgICAgICAgICBtYXJnaW5Ub3A6IDYs'
    'CiAgICAgICAgICAgIH19CiAgICAgICAgICA+CiAgICAgICAgICAgIEFzayBQbGFudGEgYW55dGhp'
    'bmcKICAgICAgICAgIDwvaDI+CiAgICAgICAgPC9kaXY+CiAgICAgICAge21lc3NhZ2VzLmxlbmd0'
    'aCA+IDAgJiYgKAogICAgICAgICAgPGJ1dHRvbgogICAgICAgICAgICBvbkNsaWNrPXtjbGVhckhp'
    'c3Rvcnl9CiAgICAgICAgICAgIHN0eWxlPXt7CiAgICAgICAgICAgICAgYmFja2dyb3VuZDogJ3Ry'
    'YW5zcGFyZW50JywKICAgICAgICAgICAgICBib3JkZXI6ICcxcHggc29saWQgdmFyKC0tYm9yZGVy'
    'LXN0cm9uZyknLAogICAgICAgICAgICAgIGJvcmRlclJhZGl1czogOTk5LAogICAgICAgICAgICAg'
    'IHBhZGRpbmc6ICc2cHggMTRweCcsCiAgICAgICAgICAgICAgZm9udFNpemU6IDEyLAogICAgICAg'
    'ICAgICAgIGNvbG9yOiAndmFyKC0tbXV0ZWQpJywKICAgICAgICAgICAgICBjdXJzb3I6ICdwb2lu'
    'dGVyJywKICAgICAgICAgICAgfX0KICAgICAgICAgID4KICAgICAgICAgICAgTGltcGFyIGhpc3TD'
    's3JpY28KICAgICAgICAgIDwvYnV0dG9uPgogICAgICAgICl9CiAgICAgIDwvZGl2PgoKICAgICAg'
    'e21lc3NhZ2VzLmxlbmd0aCA9PT0gMCAmJiAoCiAgICAgICAgPGRpdiBzdHlsZT17eyBwYWRkaW5n'
    'OiAnNDBweCAwIDIwcHgnLCBjb2xvcjogJ3ZhcigtLW11dGVkKScgfX0+CiAgICAgICAgICA8cCBz'
    'dHlsZT17eyBmb250U2l6ZTogMTcsIGxpbmVIZWlnaHQ6IDEuNTUsIG1heFdpZHRoOiA1NjAsIG1h'
    'cmdpbkJvdHRvbTogMTggfX0+CiAgICAgICAgICAgIFNvdSBvIGFzc2lzdGVudGUgZGEgUGxhbnRh'
    'LiBQZXJndW50YS1tZSBxdWFscXVlciBjb2lzYSBzb2JyZSBvcwogICAgICAgICAgICBjbHVzdGVy'
    'cywgb2N1cGHDp8Ojbywgb3Ugc2ltcGxlc21lbnRlIHBhcnRpbGhhIGEgdHVhIGxvY2FsaXphw6fD'
    'o28KICAgICAgICAgICAgcGFyYSBhIHJlY29tZW5kYcOnw6NvIG1haXMgcsOhcGlkYS4KICAgICAg'
    'ICAgIDwvcD4KICAgICAgICAgIDxkaXYgc3R5bGU9e3sgZGlzcGxheTogJ2ZsZXgnLCBmbGV4V3Jh'
    'cDogJ3dyYXAnLCBnYXA6IDYsIG1hcmdpbkJvdHRvbTogMTIgfX0+CiAgICAgICAgICAgIDxidXR0'
    'b24KICAgICAgICAgICAgICBvbkNsaWNrPXthc2tMb2NhdGlvbn0KICAgICAgICAgICAgICBzdHls'
    'ZT17ewogICAgICAgICAgICAgICAgYmFja2dyb3VuZDogJ3ZhcigtLWdyZWVuLWRhcmssICMxQjNB'
    'MjEpJywKICAgICAgICAgICAgICAgIGNvbG9yOiAnd2hpdGUnLAogICAgICAgICAgICAgICAgYm9y'
    'ZGVyOiAnbm9uZScsCiAgICAgICAgICAgICAgICBib3JkZXJSYWRpdXM6IDk5OSwKICAgICAgICAg'
    'ICAgICAgIHBhZGRpbmc6ICc4cHggMTZweCcsCiAgICAgICAgICAgICAgICBmb250U2l6ZTogMTMs'
    'CiAgICAgICAgICAgICAgICBmb250V2VpZ2h0OiA2MDAsCiAgICAgICAgICAgICAgICBjdXJzb3I6'
    'ICdwb2ludGVyJywKICAgICAgICAgICAgICAgIGZvbnRGYW1pbHk6ICdpbmhlcml0JywKICAgICAg'
    'ICAgICAgICAgIGRpc3BsYXk6ICdpbmxpbmUtZmxleCcsCiAgICAgICAgICAgICAgICBhbGlnbkl0'
    'ZW1zOiAnY2VudGVyJywKICAgICAgICAgICAgICAgIGdhcDogNiwKICAgICAgICAgICAgICB9fQog'
    'ICAgICAgICAgICA+CiAgICAgICAgICAgICAg8J+TjSBPbmRlIGVzdMOhIG8gV0MgbWFpcyBwZXJ0'
    'bz8KICAgICAgICAgICAgPC9idXR0b24+CiAgICAgICAgICA8L2Rpdj4KICAgICAgICAgIDxkaXYg'
    'c3R5bGU9e3sgZGlzcGxheTogJ2ZsZXgnLCBmbGV4V3JhcDogJ3dyYXAnLCBnYXA6IDYgfX0+CiAg'
    'ICAgICAgICAgIHtbCiAgICAgICAgICAgICAgJ1F1YWwgbyBjbHVzdGVyIG1haXMgY2hlaW8gYWdv'
    'cmE/JywKICAgICAgICAgICAgICAnUXVlbSBlc3TDoSBhIGxpbXBhciBvIFdDLTA0PycsCiAgICAg'
    'ICAgICAgICAgJ1F1YW5kbyDDqSBhIHByw7N4aW1hIGxpbXBlemE/JywKICAgICAgICAgICAgICAn'
    'UXVhbnRhcyBwZXNzb2FzIGjDoSBhZ29yYSBubyBmZXN0aXZhbD8nLAogICAgICAgICAgICBdLm1h'
    'cCgocykgPT4gKAogICAgICAgICAgICAgIDxidXR0b24KICAgICAgICAgICAgICAgIGtleT17c30K'
    'ICAgICAgICAgICAgICAgIG9uQ2xpY2s9eygpID0+IHNlbmQocyl9CiAgICAgICAgICAgICAgICBz'
    'dHlsZT17ewogICAgICAgICAgICAgICAgICBiYWNrZ3JvdW5kOiAndmFyKC0tYmctc29mdCknLAog'
    'ICAgICAgICAgICAgICAgICBib3JkZXI6ICcxcHggc29saWQgdmFyKC0tYm9yZGVyKScsCiAgICAg'
    'ICAgICAgICAgICAgIGJvcmRlclJhZGl1czogOTk5LAogICAgICAgICAgICAgICAgICBwYWRkaW5n'
    'OiAnN3B4IDEzcHgnLAogICAgICAgICAgICAgICAgICBmb250U2l6ZTogMTIuNSwKICAgICAgICAg'
    'ICAgICAgICAgY3Vyc29yOiAncG9pbnRlcicsCiAgICAgICAgICAgICAgICAgIGNvbG9yOiAndmFy'
    'KC0taW5rKScsCiAgICAgICAgICAgICAgICAgIGZvbnRGYW1pbHk6ICdpbmhlcml0JywKICAgICAg'
    'ICAgICAgICAgIH19CiAgICAgICAgICAgICAgPgogICAgICAgICAgICAgICAge3N9CiAgICAgICAg'
    'ICAgICAgPC9idXR0b24+CiAgICAgICAgICAgICkpfQogICAgICAgICAgPC9kaXY+CiAgICAgICAg'
    'PC9kaXY+CiAgICAgICl9CgogICAgICA8ZGl2CiAgICAgICAgcmVmPXtzY3JvbGxSZWZ9CiAgICAg'
    'ICAgc3R5bGU9e3sKICAgICAgICAgIGRpc3BsYXk6ICdmbGV4JywKICAgICAgICAgIGZsZXhEaXJl'
    'Y3Rpb246ICdjb2x1bW4nLAogICAgICAgICAgZ2FwOiAxMiwKICAgICAgICAgIG1hcmdpbkJvdHRv'
    'bTogMjQsCiAgICAgICAgICBtYXhIZWlnaHQ6ICdjYWxjKDEwMHZoIC0gMzYwcHgpJywKICAgICAg'
    'ICAgIG92ZXJmbG93WTogJ2F1dG8nLAogICAgICAgIH19CiAgICAgID4KICAgICAgICB7bWVzc2Fn'
    'ZXMubWFwKChtLCBpKSA9PiAoCiAgICAgICAgICA8ZGl2CiAgICAgICAgICAgIGtleT17aX0KICAg'
    'ICAgICAgICAgc3R5bGU9e3sKICAgICAgICAgICAgICBhbGlnblNlbGY6IG0ucm9sZSA9PT0gJ3Vz'
    'ZXInID8gJ2ZsZXgtZW5kJyA6ICdmbGV4LXN0YXJ0JywKICAgICAgICAgICAgICBiYWNrZ3JvdW5k'
    'OiBtLnJvbGUgPT09ICd1c2VyJyA/ICd2YXIoLS1pbmspJyA6ICd3aGl0ZScsCiAgICAgICAgICAg'
    'ICAgY29sb3I6IG0ucm9sZSA9PT0gJ3VzZXInID8gJ3doaXRlJyA6ICd2YXIoLS1pbmspJywKICAg'
    'ICAgICAgICAgICBwYWRkaW5nOiAnMTJweCAxNnB4JywKICAgICAgICAgICAgICBib3JkZXJSYWRp'
    'dXM6IDE2LAogICAgICAgICAgICAgIG1heFdpZHRoOiAnODUlJywKICAgICAgICAgICAgICBmb250'
    'U2l6ZTogMTUsCiAgICAgICAgICAgICAgbGluZUhlaWdodDogMS41NSwKICAgICAgICAgICAgICBi'
    'b3JkZXI6IG0ucm9sZSA9PT0gJ2Fzc2lzdGFudCcgPyAnMXB4IHNvbGlkIHZhcigtLWJvcmRlcikn'
    'IDogJ25vbmUnLAogICAgICAgICAgICAgIGJveFNoYWRvdzogbS5yb2xlID09PSAnYXNzaXN0YW50'
    'JyA/ICd2YXIoLS1zaGFkb3ctc20pJyA6ICdub25lJywKICAgICAgICAgICAgICB3b3JkQnJlYWs6'
    'ICdicmVhay13b3JkJywKICAgICAgICAgICAgfX0KICAgICAgICAgID4KICAgICAgICAgICAgPE1l'
    'c3NhZ2VDb250ZW50IGNvbnRlbnQ9e20uY29udGVudH0gLz4KICAgICAgICAgIDwvZGl2PgogICAg'
    'ICAgICkpfQogICAgICAgIHtzZW5kaW5nICYmICgKICAgICAgICAgIDxkaXYKICAgICAgICAgICAg'
    'c3R5bGU9e3sKICAgICAgICAgICAgICBhbGlnblNlbGY6ICdmbGV4LXN0YXJ0JywKICAgICAgICAg'
    'ICAgICBiYWNrZ3JvdW5kOiAnd2hpdGUnLAogICAgICAgICAgICAgIHBhZGRpbmc6ICcxMnB4IDE2'
    'cHgnLAogICAgICAgICAgICAgIGJvcmRlclJhZGl1czogMTYsCiAgICAgICAgICAgICAgYm9yZGVy'
    'OiAnMXB4IHNvbGlkIHZhcigtLWJvcmRlciknLAogICAgICAgICAgICAgIGZvbnRTaXplOiAxMywK'
    'ICAgICAgICAgICAgICBjb2xvcjogJ3ZhcigtLW11dGVkKScsCiAgICAgICAgICAgIH19CiAgICAg'
    'ICAgICA+CiAgICAgICAgICAgIDxzcGFuIHN0eWxlPXt7IGFuaW1hdGlvbjogJ2RvdHMgMS40cyBp'
    'bmZpbml0ZScgfX0+4pePIOKXjyDil488L3NwYW4+CiAgICAgICAgICA8L2Rpdj4KICAgICAgICAp'
    'fQogICAgICA8L2Rpdj4KCiAgICAgIDxzdHlsZSBqc3g+e2AKICAgICAgICBAa2V5ZnJhbWVzIGRv'
    'dHMgewogICAgICAgICAgMCUsIDEwMCUgeyBvcGFjaXR5OiAwLjM7IH0KICAgICAgICAgIDUwJSB7'
    'IG9wYWNpdHk6IDE7IH0KICAgICAgICB9CiAgICAgIGB9PC9zdHlsZT4KICAgIDwvZGl2PgogICk7'
    'Cn0KCmV4cG9ydCBkZWZhdWx0IGZ1bmN0aW9uIENoYXRQYWdlKCkgewogIHJldHVybiAoCiAgICA8'
    'U3VzcGVuc2UKICAgICAgZmFsbGJhY2s9ewogICAgICAgIDxkaXYgY2xhc3NOYW1lPSJwYWdlIiBz'
    'dHlsZT17eyBtYXhXaWR0aDogODIwIH19PgogICAgICAgICAgPGRpdiBjbGFzc05hbWU9InNlY3Rp'
    'b24tbGFiZWwiPkNoYXQgwrcgYSBjYXJyZWdhcuKApjwvZGl2PgogICAgICAgIDwvZGl2PgogICAg'
    'ICB9CiAgICA+CiAgICAgIDxDaGF0SW5uZXIgLz4KICAgIDwvU3VzcGVuc2U+CiAgKTsKfQo='
)


def run(cmd, cwd=None):
    print(f"$ {cmd}")
    r = subprocess.run(cmd, shell=True, cwd=cwd, capture_output=True, text=True)
    if r.stdout.strip(): print(r.stdout.rstrip())
    if r.stderr.strip(): print(r.stderr.rstrip(), file=sys.stderr)
    return r.returncode == 0


def main():
    root = Path.cwd()
    if not (root / "frontend").exists():
        print("ERRO: corre a partir de ~/planta_rock4")
        sys.exit(1)
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    chat = root / "frontend" / "app" / "v2" / "chat" / "page.tsx"
    if chat.exists():
        shutil.copy2(chat, chat.with_suffix(f".tsx.bak.v21.{stamp}"))
    d = base64.b64decode("".join(CHAT_B64))
    chat.write_bytes(d)
    print(f"  OK chat/page.tsx v21 ({len(d)} B) — routing LOCAL para coords")

    run("git add frontend/app/v2/chat/page.tsx", cwd=str(root))
    run('git commit -m "fix(v21): chat com routing LOCAL determinístico para coords (nunca mais Sem dados)"', cwd=str(root))
    run("git push", cwd=str(root))

    print()
    print("=" * 68)
    print("  PRONTO")
    print("=" * 68)
    print()
    print("  Aguarda ~90s e CMD+SHIFT+R em janela anonima.")
    print()
    print("  Teste:")
    print("    1. /v2/chat")
    print("    2. Clica em '📍 Onde está o WC mais perto?'")
    print("    3. Permite geolocalização")
    print("    4. Recebes resposta IMEDIATA com:")
    print("       - Cluster recomendado (em **bold**)")
    print("       - Distancia em metros / km")
    print("       - Tempo a pe")
    print("       - Ocupacao e fila actual")
    print("       - Alternativa")
    print()
    print("  Se estás em Porto/Famalicao (41.17, -8.63), o chat diz:")
    print("    'Estás a ~280 km do Parque Tejo. Quando chegares ao festival,")
    print("     vai a WC-XX, ~Xmin a pé...'")
    print()
    print("  Nunca mais ouvirás 'Sem dados disponíveis'.")


if __name__ == "__main__":
    main()
