#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
PlantaOS install_v8 — CAMINHO B · Inteligência mostrável + frontend operacional

Adiciona:
  Backend (2 ficheiros novos):
    - app/services/forecast.py
    - app/routers/forecast.py  → GET /api/v1/forecast/cluster/{id}

  Frontend (3 ficheiros novos + 2 patches):
    - app/v2/cleaning/page.tsx   → dashboard limpeza com botões
    - app/v2/incidents/page.tsx  → lista + formulário criar/resolver
    - components/v2/WeatherWidget.tsx  → widget tempo compacto
    - lib/v2-api.ts (APPEND)     → 11 tipos + 8 funções API novas
    - components/v2/TopBar.tsx (PATCH) → add WeatherWidget + 2 links nav
"""

import base64
import os
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path

os.environ["PATH"] = ":".join([
    "/usr/bin", "/bin", "/usr/sbin", "/sbin",
    "/usr/local/bin", "/opt/homebrew/bin",
    os.environ.get("PATH", ""),
])

FILES = {
    'frontend/app/v2/cleaning/page.tsx': (
        'J3VzZSBjbGllbnQnOwoKaW1wb3J0IHsgdXNlRWZmZWN0LCB1c2VTdGF0ZSB9IGZyb20gJ3JlYWN0'
        'JzsKaW1wb3J0IHsgYXBpLCB0eXBlIENsZWFuaW5nQ2x1c3RlclN0YXR1cyB9IGZyb20gJ0AvbGli'
        'L3YyLWFwaSc7Cgpjb25zdCBSRUZSRVNIX01TID0gMzBfMDAwOwoKY29uc3QgU1RBVFVTX0NPTE9S'
        'UzogUmVjb3JkPHN0cmluZywgeyBiZzogc3RyaW5nOyBpbms6IHN0cmluZzsgbGFiZWw6IHN0cmlu'
        'ZyB9PiA9IHsKICBjbGVhbjogeyBiZzogJyNFOEYxRUEnLCBpbms6ICcjMUIzQTIxJywgbGFiZWw6'
        'ICdMaW1wbycgfSwKICBpbl9wcm9ncmVzczogeyBiZzogJyNGRkY3RTAnLCBpbms6ICcjN0E1QTAw'
        'JywgbGFiZWw6ICdBIGxpbXBhcicgfSwKICBuZWVkc19jbGVhbmluZzogeyBiZzogJyNGREVDREMn'
        'LCBpbms6ICcjQTg1RDAwJywgbGFiZWw6ICdBIGFndWFyZGFyJyB9LAogIHVyZ2VudDogeyBiZzog'
        'JyNGOEQ5QzQnLCBpbms6ICcjQzI1QTFBJywgbGFiZWw6ICdVcmdlbnRlJyB9LAp9OwoKZnVuY3Rp'
        'b24gZm10TWludXRlcyhtOiBudW1iZXIgfCBudWxsIHwgdW5kZWZpbmVkKTogc3RyaW5nIHsKICBp'
        'ZiAobSA9PT0gbnVsbCB8fCBtID09PSB1bmRlZmluZWQpIHJldHVybiAnc2VtIHJlZ2lzdG8nOwog'
        'IGlmIChtIDwgNjApIHJldHVybiBgJHttfSBtaW5gOwogIGNvbnN0IGggPSBNYXRoLmZsb29yKG0g'
        'LyA2MCk7CiAgY29uc3QgcmVtID0gbSAlIDYwOwogIHJldHVybiByZW0gPT09IDAgPyBgJHtofWhg'
        'IDogYCR7aH1oICR7cmVtfW1gOwp9CgpleHBvcnQgZGVmYXVsdCBmdW5jdGlvbiBDbGVhbmluZ1Bh'
        'Z2UoKSB7CiAgY29uc3QgW2NsdXN0ZXJzLCBzZXRDbHVzdGVyc10gPSB1c2VTdGF0ZTxDbGVhbmlu'
        'Z0NsdXN0ZXJTdGF0dXNbXT4oW10pOwogIGNvbnN0IFtsb2FkaW5nLCBzZXRMb2FkaW5nXSA9IHVz'
        'ZVN0YXRlKHRydWUpOwogIGNvbnN0IFtlcnJvciwgc2V0RXJyb3JdID0gdXNlU3RhdGU8c3RyaW5n'
        'IHwgbnVsbD4obnVsbCk7CiAgY29uc3QgW21hcmtpbmcsIHNldE1hcmtpbmddID0gdXNlU3RhdGU8'
        'c3RyaW5nIHwgbnVsbD4obnVsbCk7CiAgY29uc3QgW2xhc3RVcGRhdGUsIHNldExhc3RVcGRhdGVd'
        'ID0gdXNlU3RhdGU8RGF0ZSB8IG51bGw+KG51bGwpOwoKICBjb25zdCBmZXRjaFNjaGVkdWxlID0g'
        'YXN5bmMgKCkgPT4gewogICAgdHJ5IHsKICAgICAgY29uc3QgZGF0YSA9IGF3YWl0IGFwaS5jbGVh'
        'bmluZ1NjaGVkdWxlKCk7CiAgICAgIHNldENsdXN0ZXJzKGRhdGEuY2x1c3RlcnMpOwogICAgICBz'
        'ZXRFcnJvcihudWxsKTsKICAgICAgc2V0TGFzdFVwZGF0ZShuZXcgRGF0ZSgpKTsKICAgIH0gY2F0'
        'Y2ggKGVycikgewogICAgICBzZXRFcnJvcihlcnIgaW5zdGFuY2VvZiBFcnJvciA/IGVyci5tZXNz'
        'YWdlIDogJ2Vycm8nKTsKICAgIH0gZmluYWxseSB7CiAgICAgIHNldExvYWRpbmcoZmFsc2UpOwog'
        'ICAgfQogIH07CgogIHVzZUVmZmVjdCgoKSA9PiB7CiAgICBmZXRjaFNjaGVkdWxlKCk7CiAgICBj'
        'b25zdCBpdiA9IHNldEludGVydmFsKGZldGNoU2NoZWR1bGUsIFJFRlJFU0hfTVMpOwogICAgcmV0'
        'dXJuICgpID0+IGNsZWFySW50ZXJ2YWwoaXYpOwogIH0sIFtdKTsKCiAgY29uc3QgbWFya0NsZWFu'
        'ID0gYXN5bmMgKGNsdXN0ZXJJZDogc3RyaW5nKSA9PiB7CiAgICBzZXRNYXJraW5nKGNsdXN0ZXJJ'
        'ZCk7CiAgICB0cnkgewogICAgICBhd2FpdCBhcGkuY2xlYW5pbmdNYXJrRG9uZSh7CiAgICAgICAg'
        'Y2x1c3Rlcl9pZDogY2x1c3RlcklkLAogICAgICAgIHRlYW06ICdFcXVpcGEgQScsCiAgICAgICAg'
        'b3BlcmF0b3I6ICdPcGVyYWRvcicsCiAgICAgICAgbm90ZXM6IG51bGwsCiAgICAgIH0pOwogICAg'
        'ICBhd2FpdCBmZXRjaFNjaGVkdWxlKCk7CiAgICB9IGNhdGNoIChlcnIpIHsKICAgICAgc2V0RXJy'
        'b3IoZXJyIGluc3RhbmNlb2YgRXJyb3IgPyBlcnIubWVzc2FnZSA6ICdlcnJvJyk7CiAgICB9IGZp'
        'bmFsbHkgewogICAgICBzZXRNYXJraW5nKG51bGwpOwogICAgfQogIH07CgogIGNvbnN0IGNsZWFu'
        'Q291bnQgPSBjbHVzdGVycy5maWx0ZXIoKGMpID0+IGMuc3RhdHVzID09PSAnY2xlYW4nKS5sZW5n'
        'dGg7CiAgY29uc3QgdXJnZW50Q291bnQgPSBjbHVzdGVycy5maWx0ZXIoKGMpID0+IGMuc3RhdHVz'
        'ID09PSAndXJnZW50JykubGVuZ3RoOwogIGNvbnN0IG5lZWRzQ291bnQgPSBjbHVzdGVycy5maWx0'
        'ZXIoKGMpID0+IGMuc3RhdHVzID09PSAnbmVlZHNfY2xlYW5pbmcnKS5sZW5ndGg7CgogIHJldHVy'
        'biAoCiAgICA8ZGl2IHN0eWxlPXt7IHBhZGRpbmc6ICc0MHB4IDMycHggNDhweCcsIG1heFdpZHRo'
        'OiAxMjgwLCBtYXJnaW46ICcwIGF1dG8nIH19PgogICAgICA8ZGl2IHN0eWxlPXt7IG1hcmdpbkJv'
        'dHRvbTogMjggfX0+CiAgICAgICAgPGRpdiBjbGFzc05hbWU9InNlY3Rpb24tbGFiZWwiPk9wZXJh'
        'w6fDtWVzIMK3IGxpbXBlemEgZG9zIDggY2x1c3RlcnM8L2Rpdj4KICAgICAgICA8aDEKICAgICAg'
        'ICAgIGNsYXNzTmFtZT0ic2VyaWYiCiAgICAgICAgICBzdHlsZT17ewogICAgICAgICAgICBmb250'
        'U2l6ZTogJ2NsYW1wKDI4cHgsIDR2dywgNDRweCknLAogICAgICAgICAgICBmb250V2VpZ2h0OiA1'
        'MDAsCiAgICAgICAgICAgIGNvbG9yOiAndmFyKC0tY29sb3ItaW5rKScsCiAgICAgICAgICAgIGxp'
        'bmVIZWlnaHQ6IDEuMSwKICAgICAgICAgICAgbWFyZ2luQm90dG9tOiA4LAogICAgICAgICAgfX0K'
        'ICAgICAgICA+CiAgICAgICAgICBFc3RhZG8gZGUgbGltcGV6YQogICAgICAgIDwvaDE+CiAgICAg'
        'ICAgPHAgc3R5bGU9e3sgY29sb3I6ICd2YXIoLS1jb2xvci1tdXRlZCknLCBmb250U2l6ZTogMTQs'
        'IGxpbmVIZWlnaHQ6IDEuNiB9fT4KICAgICAgICAgIExpbXBvIG5vcyDDumx0aW1vcyA5MCBtaW4g'
        'wrcgQSBhZ3VhcmRhciBlbnRyZSA5MOKAkzE4MCBtaW4gwrcgVXJnZW50ZSBhY2ltYSBkZSAxODAg'
        'bWluLnsnICd9CiAgICAgICAgICB7bGFzdFVwZGF0ZSAmJiAoCiAgICAgICAgICAgIDxzcGFuIGNs'
        'YXNzTmFtZT0ibW9ubyIgc3R5bGU9e3sgZm9udFNpemU6IDExIH19PgogICAgICAgICAgICAgIGFj'
        'dHVhbGl6YWRvIHtsYXN0VXBkYXRlLnRvTG9jYWxlVGltZVN0cmluZygncHQtUFQnKX0KICAgICAg'
        'ICAgICAgPC9zcGFuPgogICAgICAgICAgKX0KICAgICAgICA8L3A+CiAgICAgIDwvZGl2PgoKICAg'
        'ICAgey8qIEtQSXMgKi99CiAgICAgIDxkaXYKICAgICAgICBzdHlsZT17ewogICAgICAgICAgZGlz'
        'cGxheTogJ2dyaWQnLAogICAgICAgICAgZ3JpZFRlbXBsYXRlQ29sdW1uczogJ3JlcGVhdChhdXRv'
        'LWZpdCwgbWlubWF4KDE0MHB4LCAxZnIpKScsCiAgICAgICAgICBnYXA6IDEyLAogICAgICAgICAg'
        'bWFyZ2luQm90dG9tOiAyNCwKICAgICAgICB9fQogICAgICA+CiAgICAgICAgPEtwaVRpbGUgbGFi'
        'ZWw9IkxpbXBvcyIgdmFsdWU9e2NsZWFuQ291bnR9IHRvdGFsPXs4fSBjb2xvcj0iIzFCM0EyMSIg'
        'Lz4KICAgICAgICA8S3BpVGlsZSBsYWJlbD0iQSBhZ3VhcmRhciIgdmFsdWU9e25lZWRzQ291bnR9'
        'IHRvdGFsPXs4fSBjb2xvcj0iI0E4NUQwMCIgLz4KICAgICAgICA8S3BpVGlsZSBsYWJlbD0iVXJn'
        'ZW50ZXMiIHZhbHVlPXt1cmdlbnRDb3VudH0gdG90YWw9ezh9IGNvbG9yPSIjQzI1QTFBIiAvPgog'
        'ICAgICA8L2Rpdj4KCiAgICAgIHtlcnJvciAmJiAoCiAgICAgICAgPGRpdgogICAgICAgICAgc3R5'
        'bGU9e3sKICAgICAgICAgICAgcGFkZGluZzogMTIsCiAgICAgICAgICAgIGJhY2tncm91bmQ6ICcj'
        'RkRFQ0RDJywKICAgICAgICAgICAgY29sb3I6ICcjQzI1QTFBJywKICAgICAgICAgICAgYm9yZGVy'
        'UmFkaXVzOiA4LAogICAgICAgICAgICBtYXJnaW5Cb3R0b206IDE2LAogICAgICAgICAgICBmb250'
        'U2l6ZTogMTMsCiAgICAgICAgICB9fQogICAgICAgID4KICAgICAgICAgIHtlcnJvcn0KICAgICAg'
        'ICA8L2Rpdj4KICAgICAgKX0KCiAgICAgIHtsb2FkaW5nICYmIGNsdXN0ZXJzLmxlbmd0aCA9PT0g'
        'MCAmJiAoCiAgICAgICAgPGRpdiBzdHlsZT17eyBjb2xvcjogJ3ZhcigtLWNvbG9yLW11dGVkKScs'
        'IHBhZGRpbmc6IDI0IH19PkEgY2FycmVnYXLigKY8L2Rpdj4KICAgICAgKX0KCiAgICAgIHsvKiBH'
        'cmlkIGRlIGNsdXN0ZXJzICovfQogICAgICA8ZGl2CiAgICAgICAgc3R5bGU9e3sKICAgICAgICAg'
        'IGRpc3BsYXk6ICdncmlkJywKICAgICAgICAgIGdyaWRUZW1wbGF0ZUNvbHVtbnM6ICdyZXBlYXQo'
        'YXV0by1maXQsIG1pbm1heCgyODBweCwgMWZyKSknLAogICAgICAgICAgZ2FwOiAxNiwKICAgICAg'
        'ICB9fQogICAgICA+CiAgICAgICAge2NsdXN0ZXJzLm1hcCgoYykgPT4gewogICAgICAgICAgY29u'
        'c3Qgc3R5ID0gU1RBVFVTX0NPTE9SU1tjLnN0YXR1c10gfHwgU1RBVFVTX0NPTE9SUy5uZWVkc19j'
        'bGVhbmluZzsKICAgICAgICAgIHJldHVybiAoCiAgICAgICAgICAgIDxkaXYKICAgICAgICAgICAg'
        'ICBrZXk9e2MuY2x1c3Rlcl9pZH0KICAgICAgICAgICAgICBzdHlsZT17ewogICAgICAgICAgICAg'
        'ICAgYmFja2dyb3VuZDogJ3ZhcigtLWNhcmQsIHdoaXRlKScsCiAgICAgICAgICAgICAgICBib3Jk'
        'ZXI6ICcxcHggc29saWQgdmFyKC0tY29sb3ItYm9yZGVyKScsCiAgICAgICAgICAgICAgICBib3Jk'
        'ZXJSYWRpdXM6IDEyLAogICAgICAgICAgICAgICAgcGFkZGluZzogMjAsCiAgICAgICAgICAgICAg'
        'ICBkaXNwbGF5OiAnZmxleCcsCiAgICAgICAgICAgICAgICBmbGV4RGlyZWN0aW9uOiAnY29sdW1u'
        'JywKICAgICAgICAgICAgICAgIGdhcDogMTIsCiAgICAgICAgICAgICAgfX0KICAgICAgICAgICAg'
        'PgogICAgICAgICAgICAgIDxkaXYgc3R5bGU9e3sgZGlzcGxheTogJ2ZsZXgnLCBqdXN0aWZ5Q29u'
        'dGVudDogJ3NwYWNlLWJldHdlZW4nLCBhbGlnbkl0ZW1zOiAnZmxleC1zdGFydCcgfX0+CiAgICAg'
        'ICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICA8ZGl2CiAgICAgICAgICAgICAgICAg'
        'ICAgY2xhc3NOYW1lPSJtb25vIgogICAgICAgICAgICAgICAgICAgIHN0eWxlPXt7CiAgICAgICAg'
        'ICAgICAgICAgICAgICBmb250U2l6ZTogMTEsCiAgICAgICAgICAgICAgICAgICAgICBjb2xvcjog'
        'J3ZhcigtLWNvbG9yLW11dGVkKScsCiAgICAgICAgICAgICAgICAgICAgICBsZXR0ZXJTcGFjaW5n'
        'OiAnMC4wOGVtJywKICAgICAgICAgICAgICAgICAgICAgIHRleHRUcmFuc2Zvcm06ICd1cHBlcmNh'
        'c2UnLAogICAgICAgICAgICAgICAgICAgICAgbWFyZ2luQm90dG9tOiA0LAogICAgICAgICAgICAg'
        'ICAgICAgIH19CiAgICAgICAgICAgICAgICAgID4KICAgICAgICAgICAgICAgICAgICBDbHVzdGVy'
        'CiAgICAgICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICAgICAgICA8ZGl2CiAgICAgICAg'
        'ICAgICAgICAgICAgY2xhc3NOYW1lPSJzZXJpZiIKICAgICAgICAgICAgICAgICAgICBzdHlsZT17'
        'eyBmb250U2l6ZTogMjQsIGZvbnRXZWlnaHQ6IDUwMCwgY29sb3I6ICd2YXIoLS1jb2xvci1pbmsp'
        'JyB9fQogICAgICAgICAgICAgICAgICA+CiAgICAgICAgICAgICAgICAgICAge2MuY2x1c3Rlcl9p'
        'ZH0KICAgICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICAgICA8L2Rpdj4KICAgICAg'
        'ICAgICAgICAgIDxzcGFuCiAgICAgICAgICAgICAgICAgIHN0eWxlPXt7CiAgICAgICAgICAgICAg'
        'ICAgICAgYmFja2dyb3VuZDogc3R5LmJnLAogICAgICAgICAgICAgICAgICAgIGNvbG9yOiBzdHku'
        'aW5rLAogICAgICAgICAgICAgICAgICAgIHBhZGRpbmc6ICc0cHggMTBweCcsCiAgICAgICAgICAg'
        'ICAgICAgICAgYm9yZGVyUmFkaXVzOiA5OTksCiAgICAgICAgICAgICAgICAgICAgZm9udFNpemU6'
        'IDExLAogICAgICAgICAgICAgICAgICAgIGZvbnRXZWlnaHQ6IDYwMCwKICAgICAgICAgICAgICAg'
        'ICAgICBsZXR0ZXJTcGFjaW5nOiAnMC4wNWVtJywKICAgICAgICAgICAgICAgICAgICB0ZXh0VHJh'
        'bnNmb3JtOiAndXBwZXJjYXNlJywKICAgICAgICAgICAgICAgICAgfX0KICAgICAgICAgICAgICAg'
        'ID4KICAgICAgICAgICAgICAgICAge3N0eS5sYWJlbH0KICAgICAgICAgICAgICAgIDwvc3Bhbj4K'
        'ICAgICAgICAgICAgICA8L2Rpdj4KCiAgICAgICAgICAgICAgPGRpdiBzdHlsZT17eyBkaXNwbGF5'
        'OiAnZ3JpZCcsIGdhcDogNiwgZm9udFNpemU6IDEzLCBjb2xvcjogJ3ZhcigtLWNvbG9yLW11dGVk'
        'KScgfX0+CiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICA8c3BhbiBzdHls'
        'ZT17eyBjb2xvcjogJ3ZhcigtLWNvbG9yLWluayknLCBmb250V2VpZ2h0OiA1MDAgfX0+CiAgICAg'
        'ICAgICAgICAgICAgICAgSMOhIHtmbXRNaW51dGVzKGMubWludXRlc19zaW5jZV9jbGVhbil9CiAg'
        'ICAgICAgICAgICAgICAgIDwvc3Bhbj57JyAnfQogICAgICAgICAgICAgICAgICBkZXNkZSBhIMO6'
        'bHRpbWEgbGltcGV6YQogICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICAgICB7Yy5s'
        'YXN0X3RlYW0gJiYgKAogICAgICAgICAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT0ibW9ubyIgc3R5'
        'bGU9e3sgZm9udFNpemU6IDExIH19PgogICAgICAgICAgICAgICAgICAgIHtjLmxhc3RfdGVhbX0K'
        'ICAgICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICAgICApfQogICAgICAgICAgICAg'
        'ICAge2MubmV4dF9zY2hlZHVsZWRfZm9yICYmICgKICAgICAgICAgICAgICAgICAgPGRpdiBzdHls'
        'ZT17eyBmb250U2l6ZTogMTIgfX0+CiAgICAgICAgICAgICAgICAgICAgUHLDs3hpbWE6eycgJ30K'
        'ICAgICAgICAgICAgICAgICAgICB7bmV3IERhdGUoYy5uZXh0X3NjaGVkdWxlZF9mb3IpLnRvTG9j'
        'YWxlU3RyaW5nKCdwdC1QVCcsIHsKICAgICAgICAgICAgICAgICAgICAgIGRheTogJzItZGlnaXQn'
        'LAogICAgICAgICAgICAgICAgICAgICAgbW9udGg6ICcyLWRpZ2l0JywKICAgICAgICAgICAgICAg'
        'ICAgICAgIGhvdXI6ICcyLWRpZ2l0JywKICAgICAgICAgICAgICAgICAgICAgIG1pbnV0ZTogJzIt'
        'ZGlnaXQnLAogICAgICAgICAgICAgICAgICAgIH0pfQogICAgICAgICAgICAgICAgICA8L2Rpdj4K'
        'ICAgICAgICAgICAgICAgICl9CiAgICAgICAgICAgICAgPC9kaXY+CgogICAgICAgICAgICAgIDxi'
        'dXR0b24KICAgICAgICAgICAgICAgIG9uQ2xpY2s9eygpID0+IG1hcmtDbGVhbihjLmNsdXN0ZXJf'
        'aWQpfQogICAgICAgICAgICAgICAgZGlzYWJsZWQ9e21hcmtpbmcgPT09IGMuY2x1c3Rlcl9pZH0K'
        'ICAgICAgICAgICAgICAgIHN0eWxlPXt7CiAgICAgICAgICAgICAgICAgIG1hcmdpblRvcDogNCwK'
        'ICAgICAgICAgICAgICAgICAgYmFja2dyb3VuZDogYy5zdGF0dXMgPT09ICdjbGVhbicgPyAndmFy'
        'KC0tY29sb3ItYm9yZGVyKScgOiAndmFyKC0tY29sb3Itc3VjY2VzcywgIzFCM0EyMSknLAogICAg'
        'ICAgICAgICAgICAgICBjb2xvcjogYy5zdGF0dXMgPT09ICdjbGVhbicgPyAndmFyKC0tY29sb3It'
        'bXV0ZWQpJyA6ICd3aGl0ZScsCiAgICAgICAgICAgICAgICAgIGJvcmRlcjogJ25vbmUnLAogICAg'
        'ICAgICAgICAgICAgICBib3JkZXJSYWRpdXM6IDgsCiAgICAgICAgICAgICAgICAgIHBhZGRpbmc6'
        'ICcxMHB4IDE2cHgnLAogICAgICAgICAgICAgICAgICBmb250U2l6ZTogMTMsCiAgICAgICAgICAg'
        'ICAgICAgIGZvbnRXZWlnaHQ6IDYwMCwKICAgICAgICAgICAgICAgICAgY3Vyc29yOiBtYXJraW5n'
        'ID09PSBjLmNsdXN0ZXJfaWQgPyAnd2FpdCcgOiAncG9pbnRlcicsCiAgICAgICAgICAgICAgICAg'
        'IG9wYWNpdHk6IG1hcmtpbmcgPT09IGMuY2x1c3Rlcl9pZCA/IDAuNSA6IDEsCiAgICAgICAgICAg'
        'ICAgICAgIHRyYW5zaXRpb246ICdhbGwgMC4xNXMnLAogICAgICAgICAgICAgICAgfX0KICAgICAg'
        'ICAgICAgICA+CiAgICAgICAgICAgICAgICB7bWFya2luZyA9PT0gYy5jbHVzdGVyX2lkID8gJ0Eg'
        'cmVnaXN0YXLigKYnIDogJ01hcmNhciBjb21vIGxpbXBvJ30KICAgICAgICAgICAgICA8L2J1dHRv'
        'bj4KICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICApOwogICAgICAgIH0pfQogICAgICA8L2Rp'
        'dj4KICAgIDwvZGl2PgogICk7Cn0KCmZ1bmN0aW9uIEtwaVRpbGUoewogIGxhYmVsLAogIHZhbHVl'
        'LAogIHRvdGFsLAogIGNvbG9yLAp9OiB7CiAgbGFiZWw6IHN0cmluZzsKICB2YWx1ZTogbnVtYmVy'
        'OwogIHRvdGFsOiBudW1iZXI7CiAgY29sb3I6IHN0cmluZzsKfSkgewogIHJldHVybiAoCiAgICA8'
        'ZGl2CiAgICAgIHN0eWxlPXt7CiAgICAgICAgYmFja2dyb3VuZDogJ3ZhcigtLWNhcmQsIHdoaXRl'
        'KScsCiAgICAgICAgYm9yZGVyOiAnMXB4IHNvbGlkIHZhcigtLWNvbG9yLWJvcmRlciknLAogICAg'
        'ICAgIGJvcmRlclJhZGl1czogMTAsCiAgICAgICAgcGFkZGluZzogMTYsCiAgICAgIH19CiAgICA+'
        'CiAgICAgIDxkaXYKICAgICAgICBjbGFzc05hbWU9Im1vbm8iCiAgICAgICAgc3R5bGU9e3sKICAg'
        'ICAgICAgIGZvbnRTaXplOiAxMCwKICAgICAgICAgIGNvbG9yOiAndmFyKC0tY29sb3ItbXV0ZWQp'
        'JywKICAgICAgICAgIGxldHRlclNwYWNpbmc6ICcwLjA4ZW0nLAogICAgICAgICAgdGV4dFRyYW5z'
        'Zm9ybTogJ3VwcGVyY2FzZScsCiAgICAgICAgICBtYXJnaW5Cb3R0b206IDYsCiAgICAgICAgfX0K'
        'ICAgICAgPgogICAgICAgIHtsYWJlbH0KICAgICAgPC9kaXY+CiAgICAgIDxkaXYKICAgICAgICBz'
        'dHlsZT17ewogICAgICAgICAgZGlzcGxheTogJ2ZsZXgnLAogICAgICAgICAgYWxpZ25JdGVtczog'
        'J2Jhc2VsaW5lJywKICAgICAgICAgIGdhcDogNiwKICAgICAgICAgIGNvbG9yLAogICAgICAgIH19'
        'CiAgICAgID4KICAgICAgICA8c3BhbiBjbGFzc05hbWU9InNlcmlmIiBzdHlsZT17eyBmb250U2l6'
        'ZTogMjgsIGZvbnRXZWlnaHQ6IDUwMCwgbGluZUhlaWdodDogMSB9fT4KICAgICAgICAgIHt2YWx1'
        'ZX0KICAgICAgICA8L3NwYW4+CiAgICAgICAgPHNwYW4gY2xhc3NOYW1lPSJtb25vIiBzdHlsZT17'
        'eyBmb250U2l6ZTogMTIsIGNvbG9yOiAndmFyKC0tY29sb3ItbXV0ZWQpJyB9fT4KICAgICAgICAg'
        'IC8ge3RvdGFsfQogICAgICAgIDwvc3Bhbj4KICAgICAgPC9kaXY+CiAgICA8L2Rpdj4KICApOwp9'
        'Cg=='
    ),
    'frontend/app/v2/incidents/page.tsx': (
        'J3VzZSBjbGllbnQnOwoKaW1wb3J0IHsgdXNlRWZmZWN0LCB1c2VNZW1vLCB1c2VTdGF0ZSB9IGZy'
        'b20gJ3JlYWN0JzsKaW1wb3J0IHsKICBhcGksCiAgdHlwZSBJbmNpZGVudEVudHJ5LAogIHR5cGUg'
        'SW5jaWRlbnRTZXZlcml0eSwKICB0eXBlIEluY2lkZW50Q2F0ZWdvcnksCn0gZnJvbSAnQC9saWIv'
        'djItYXBpJzsKCmNvbnN0IFJFRlJFU0hfTVMgPSAyMF8wMDA7Cgpjb25zdCBTRVZFUklUWV9DT0xP'
        'UlM6IFJlY29yZDxJbmNpZGVudFNldmVyaXR5LCB7IGJnOiBzdHJpbmc7IGluazogc3RyaW5nIH0+'
        'ID0gewogIGluZm86IHsgYmc6ICcjRThGMUVBJywgaW5rOiAnIzFCM0EyMScgfSwKICB3YXJuaW5n'
        'OiB7IGJnOiAnI0ZGRjdFMCcsIGluazogJyM3QTVBMDAnIH0sCiAgY3JpdGljYWw6IHsgYmc6ICcj'
        'RjhEOUM0JywgaW5rOiAnI0MyNUExQScgfSwKfTsKCmNvbnN0IFNFVkVSSVRZX0xBQkVMOiBSZWNv'
        'cmQ8SW5jaWRlbnRTZXZlcml0eSwgc3RyaW5nPiA9IHsKICBpbmZvOiAnSW5mbycsCiAgd2Fybmlu'
        'ZzogJ0F2aXNvJywKICBjcml0aWNhbDogJ0Nyw610aWNvJywKfTsKCmNvbnN0IENBVEVHT1JZX0xB'
        'QkVMOiBSZWNvcmQ8SW5jaWRlbnRDYXRlZ29yeSwgc3RyaW5nPiA9IHsKICBtZWRpY2FsOiAnTcOp'
        'ZGljbycsCiAgY3Jvd2Q6ICdNdWx0aWTDo28nLAogIHNhZmV0eTogJ1NlZ3VyYW7Dp2EnLAogIGh5'
        'Z2llbmU6ICdIaWdpZW5lJywKICB0ZWNobmljYWw6ICdUw6ljbmljbycsCiAgb3RoZXI6ICdPdXRy'
        'bycsCn07Cgpjb25zdCBDTFVTVEVSUyA9IFsnV0MtMDEnLCAnV0MtMDInLCAnV0MtMDMnLCAnV0Mt'
        'MDQnLCAnV0MtMDUnLCAnV0MtMDYnLCAnV0MtMDcnLCAnV0MtMDgnXTsKCmV4cG9ydCBkZWZhdWx0'
        'IGZ1bmN0aW9uIEluY2lkZW50c1BhZ2UoKSB7CiAgY29uc3QgW2luY2lkZW50cywgc2V0SW5jaWRl'
        'bnRzXSA9IHVzZVN0YXRlPEluY2lkZW50RW50cnlbXT4oW10pOwogIGNvbnN0IFtvcGVuX2NvdW50'
        'LCBzZXRPcGVuQ291bnRdID0gdXNlU3RhdGUoMCk7CiAgY29uc3QgW2NyaXRpY2FsX2NvdW50LCBz'
        'ZXRDcml0aWNhbENvdW50XSA9IHVzZVN0YXRlKDApOwogIGNvbnN0IFtmaWx0ZXJTZXZlcml0eSwg'
        'c2V0RmlsdGVyU2V2ZXJpdHldID0gdXNlU3RhdGU8c3RyaW5nPignJyk7CiAgY29uc3QgW2ZpbHRl'
        'ck9wZW5Pbmx5LCBzZXRGaWx0ZXJPcGVuT25seV0gPSB1c2VTdGF0ZShmYWxzZSk7CiAgY29uc3Qg'
        'W2xvYWRpbmcsIHNldExvYWRpbmddID0gdXNlU3RhdGUodHJ1ZSk7CiAgY29uc3QgW2Vycm9yLCBz'
        'ZXRFcnJvcl0gPSB1c2VTdGF0ZTxzdHJpbmcgfCBudWxsPihudWxsKTsKICBjb25zdCBbc2hvd0Zv'
        'cm0sIHNldFNob3dGb3JtXSA9IHVzZVN0YXRlKGZhbHNlKTsKICBjb25zdCBbc3VibWl0dGluZywg'
        'c2V0U3VibWl0dGluZ10gPSB1c2VTdGF0ZShmYWxzZSk7CiAgY29uc3QgW3Jlc29sdmluZywgc2V0'
        'UmVzb2x2aW5nXSA9IHVzZVN0YXRlPG51bWJlciB8IG51bGw+KG51bGwpOwoKICBjb25zdCBbZm9y'
        'bSwgc2V0Rm9ybV0gPSB1c2VTdGF0ZTx7CiAgICBjbHVzdGVyX2lkOiBzdHJpbmc7CiAgICBzZXZl'
        'cml0eTogSW5jaWRlbnRTZXZlcml0eTsKICAgIGNhdGVnb3J5OiBJbmNpZGVudENhdGVnb3J5Owog'
        'ICAgbm90ZTogc3RyaW5nOwogICAgcmVwb3J0ZWRfYnk6IHN0cmluZzsKICB9Pih7CiAgICBjbHVz'
        'dGVyX2lkOiAnV0MtMDEnLAogICAgc2V2ZXJpdHk6ICd3YXJuaW5nJywKICAgIGNhdGVnb3J5OiAn'
        'aHlnaWVuZScsCiAgICBub3RlOiAnJywKICAgIHJlcG9ydGVkX2J5OiAnJywKICB9KTsKCiAgY29u'
        'c3QgZmV0Y2hMaXN0ID0gYXN5bmMgKCkgPT4gewogICAgdHJ5IHsKICAgICAgY29uc3QgZGF0YSA9'
        'IGF3YWl0IGFwaS5pbmNpZGVudHNMaXN0KHsKICAgICAgICBzZXZlcml0eTogZmlsdGVyU2V2ZXJp'
        'dHkgfHwgdW5kZWZpbmVkLAogICAgICAgIG9wZW5fb25seTogZmlsdGVyT3Blbk9ubHksCiAgICAg'
        'ICAgbGltaXQ6IDEwMCwKICAgICAgfSk7CiAgICAgIHNldEluY2lkZW50cyhkYXRhLmluY2lkZW50'
        'cyk7CiAgICAgIHNldE9wZW5Db3VudChkYXRhLm9wZW5fY291bnQpOwogICAgICBzZXRDcml0aWNh'
        'bENvdW50KGRhdGEuY3JpdGljYWxfY291bnQpOwogICAgICBzZXRFcnJvcihudWxsKTsKICAgIH0g'
        'Y2F0Y2ggKGVycikgewogICAgICBzZXRFcnJvcihlcnIgaW5zdGFuY2VvZiBFcnJvciA/IGVyci5t'
        'ZXNzYWdlIDogJ2Vycm8nKTsKICAgIH0gZmluYWxseSB7CiAgICAgIHNldExvYWRpbmcoZmFsc2Up'
        'OwogICAgfQogIH07CgogIHVzZUVmZmVjdCgoKSA9PiB7CiAgICBmZXRjaExpc3QoKTsKICAgIGNv'
        'bnN0IGl2ID0gc2V0SW50ZXJ2YWwoZmV0Y2hMaXN0LCBSRUZSRVNIX01TKTsKICAgIHJldHVybiAo'
        'KSA9PiBjbGVhckludGVydmFsKGl2KTsKICB9LCBbZmlsdGVyU2V2ZXJpdHksIGZpbHRlck9wZW5P'
        'bmx5XSk7CgogIGNvbnN0IHN1Ym1pdCA9IGFzeW5jIChlOiBSZWFjdC5Gb3JtRXZlbnQpID0+IHsK'
        'ICAgIGUucHJldmVudERlZmF1bHQoKTsKICAgIGlmICghZm9ybS5ub3RlLnRyaW0oKSkgcmV0dXJu'
        'OwogICAgc2V0U3VibWl0dGluZyh0cnVlKTsKICAgIHRyeSB7CiAgICAgIGF3YWl0IGFwaS5pbmNp'
        'ZGVudENyZWF0ZSh7CiAgICAgICAgY2x1c3Rlcl9pZDogZm9ybS5jbHVzdGVyX2lkIHx8IG51bGws'
        'CiAgICAgICAgc2V2ZXJpdHk6IGZvcm0uc2V2ZXJpdHksCiAgICAgICAgY2F0ZWdvcnk6IGZvcm0u'
        'Y2F0ZWdvcnksCiAgICAgICAgbm90ZTogZm9ybS5ub3RlLAogICAgICAgIHJlcG9ydGVkX2J5OiBm'
        'b3JtLnJlcG9ydGVkX2J5IHx8IG51bGwsCiAgICAgIH0pOwogICAgICBzZXRGb3JtKHsKICAgICAg'
        'ICBjbHVzdGVyX2lkOiAnV0MtMDEnLAogICAgICAgIHNldmVyaXR5OiAnd2FybmluZycsCiAgICAg'
        'ICAgY2F0ZWdvcnk6ICdoeWdpZW5lJywKICAgICAgICBub3RlOiAnJywKICAgICAgICByZXBvcnRl'
        'ZF9ieTogJycsCiAgICAgIH0pOwogICAgICBzZXRTaG93Rm9ybShmYWxzZSk7CiAgICAgIGF3YWl0'
        'IGZldGNoTGlzdCgpOwogICAgfSBjYXRjaCAoZXJyKSB7CiAgICAgIHNldEVycm9yKGVyciBpbnN0'
        'YW5jZW9mIEVycm9yID8gZXJyLm1lc3NhZ2UgOiAnZXJybycpOwogICAgfSBmaW5hbGx5IHsKICAg'
        'ICAgc2V0U3VibWl0dGluZyhmYWxzZSk7CiAgICB9CiAgfTsKCiAgY29uc3QgcmVzb2x2ZSA9IGFz'
        'eW5jIChpZDogbnVtYmVyKSA9PiB7CiAgICBzZXRSZXNvbHZpbmcoaWQpOwogICAgdHJ5IHsKICAg'
        'ICAgYXdhaXQgYXBpLmluY2lkZW50UmVzb2x2ZShpZCwgewogICAgICAgIHJlc29sdmVkX2J5OiAn'
        'T3BlcmHDp8O1ZXMnLAogICAgICAgIHJlc29sdXRpb25fbm90ZTogbnVsbCwKICAgICAgfSk7CiAg'
        'ICAgIGF3YWl0IGZldGNoTGlzdCgpOwogICAgfSBjYXRjaCAoZXJyKSB7CiAgICAgIHNldEVycm9y'
        'KGVyciBpbnN0YW5jZW9mIEVycm9yID8gZXJyLm1lc3NhZ2UgOiAnZXJybycpOwogICAgfSBmaW5h'
        'bGx5IHsKICAgICAgc2V0UmVzb2x2aW5nKG51bGwpOwogICAgfQogIH07CgogIHJldHVybiAoCiAg'
        'ICA8ZGl2IHN0eWxlPXt7IHBhZGRpbmc6ICc0MHB4IDMycHggNDhweCcsIG1heFdpZHRoOiAxMjgw'
        'LCBtYXJnaW46ICcwIGF1dG8nIH19PgogICAgICA8ZGl2IHN0eWxlPXt7IG1hcmdpbkJvdHRvbTog'
        'MjggfX0+CiAgICAgICAgPGRpdiBjbGFzc05hbWU9InNlY3Rpb24tbGFiZWwiPk9wZXJhw6fDtWVz'
        'IMK3IHJlZ2lzdG8gZGUgaW5jaWRlbnRlczwvZGl2PgogICAgICAgIDxoMQogICAgICAgICAgY2xh'
        'c3NOYW1lPSJzZXJpZiIKICAgICAgICAgIHN0eWxlPXt7CiAgICAgICAgICAgIGZvbnRTaXplOiAn'
        'Y2xhbXAoMjhweCwgNHZ3LCA0NHB4KScsCiAgICAgICAgICAgIGZvbnRXZWlnaHQ6IDUwMCwKICAg'
        'ICAgICAgICAgY29sb3I6ICd2YXIoLS1jb2xvci1pbmspJywKICAgICAgICAgICAgbGluZUhlaWdo'
        'dDogMS4xLAogICAgICAgICAgICBtYXJnaW5Cb3R0b206IDgsCiAgICAgICAgICB9fQogICAgICAg'
        'ID4KICAgICAgICAgIEluY2lkZW50ZXMKICAgICAgICA8L2gxPgogICAgICAgIDxwIHN0eWxlPXt7'
        'IGNvbG9yOiAndmFyKC0tY29sb3ItbXV0ZWQpJywgZm9udFNpemU6IDE0LCBsaW5lSGVpZ2h0OiAx'
        'LjYgfX0+CiAgICAgICAgICBSZWdpc3RvIGRlIHR1ZG8gbyBxdWUgYWNvbnRlY2Ugbm8gdGVycmVu'
        'byDCtyA2IGNhdGVnb3JpYXMgwrcgMyBuw612ZWlzIGRlIHNldmVyaWRhZGUKICAgICAgICA8L3A+'
        'CiAgICAgIDwvZGl2PgoKICAgICAgey8qIEtQSXMgKyBhY8Onw7VlcyAqL30KICAgICAgPGRpdgog'
        'ICAgICAgIHN0eWxlPXt7CiAgICAgICAgICBkaXNwbGF5OiAnZ3JpZCcsCiAgICAgICAgICBncmlk'
        'VGVtcGxhdGVDb2x1bW5zOiAncmVwZWF0KGF1dG8tZml0LCBtaW5tYXgoMTQwcHgsIDFmcikpIGF1'
        'dG8nLAogICAgICAgICAgZ2FwOiAxMiwKICAgICAgICAgIG1hcmdpbkJvdHRvbTogMjQsCiAgICAg'
        'ICAgICBhbGlnbkl0ZW1zOiAnc3RyZXRjaCcsCiAgICAgICAgfX0KICAgICAgPgogICAgICAgIDxL'
        'cGkgbGFiZWw9IlRvdGFsIiB2YWx1ZT17aW5jaWRlbnRzLmxlbmd0aH0gY29sb3I9IiMxQTFBMUEi'
        'IC8+CiAgICAgICAgPEtwaSBsYWJlbD0iQWJlcnRvcyIgdmFsdWU9e29wZW5fY291bnR9IGNvbG9y'
        'PSIjQTg1RDAwIiAvPgogICAgICAgIDxLcGkgbGFiZWw9IkNyw610aWNvcyIgdmFsdWU9e2NyaXRp'
        'Y2FsX2NvdW50fSBjb2xvcj0iI0MyNUExQSIgLz4KICAgICAgICA8YnV0dG9uCiAgICAgICAgICBv'
        'bkNsaWNrPXsoKSA9PiBzZXRTaG93Rm9ybSgodikgPT4gIXYpfQogICAgICAgICAgc3R5bGU9e3sK'
        'ICAgICAgICAgICAgYmFja2dyb3VuZDogc2hvd0Zvcm0gPyAndmFyKC0tY29sb3ItYm9yZGVyKScg'
        'OiAndmFyKC0tY29sb3Itc3VjY2VzcywgIzFCM0EyMSknLAogICAgICAgICAgICBjb2xvcjogc2hv'
        'd0Zvcm0gPyAndmFyKC0tY29sb3ItbXV0ZWQpJyA6ICd3aGl0ZScsCiAgICAgICAgICAgIGJvcmRl'
        'cjogJ25vbmUnLAogICAgICAgICAgICBib3JkZXJSYWRpdXM6IDEwLAogICAgICAgICAgICBwYWRk'
        'aW5nOiAnMCAyNHB4JywKICAgICAgICAgICAgZm9udFNpemU6IDEzLAogICAgICAgICAgICBmb250'
        'V2VpZ2h0OiA2MDAsCiAgICAgICAgICAgIGN1cnNvcjogJ3BvaW50ZXInLAogICAgICAgICAgICB3'
        'aGl0ZVNwYWNlOiAnbm93cmFwJywKICAgICAgICAgIH19CiAgICAgICAgPgogICAgICAgICAge3No'
        'b3dGb3JtID8gJ0NhbmNlbGFyJyA6ICcrIFJlcG9ydGFyJ30KICAgICAgICA8L2J1dHRvbj4KICAg'
        'ICAgPC9kaXY+CgogICAgICB7LyogRm9ybXVsw6FyaW8gKi99CiAgICAgIHtzaG93Rm9ybSAmJiAo'
        'CiAgICAgICAgPGZvcm0KICAgICAgICAgIG9uU3VibWl0PXtzdWJtaXR9CiAgICAgICAgICBzdHls'
        'ZT17ewogICAgICAgICAgICBiYWNrZ3JvdW5kOiAndmFyKC0tY2FyZCwgd2hpdGUpJywKICAgICAg'
        'ICAgICAgYm9yZGVyOiAnMXB4IHNvbGlkIHZhcigtLWNvbG9yLWJvcmRlciknLAogICAgICAgICAg'
        'ICBib3JkZXJSYWRpdXM6IDEyLAogICAgICAgICAgICBwYWRkaW5nOiAyMCwKICAgICAgICAgICAg'
        'bWFyZ2luQm90dG9tOiAyNCwKICAgICAgICAgICAgZGlzcGxheTogJ2dyaWQnLAogICAgICAgICAg'
        'ICBncmlkVGVtcGxhdGVDb2x1bW5zOiAncmVwZWF0KGF1dG8tZml0LCBtaW5tYXgoMTgwcHgsIDFm'
        'cikpJywKICAgICAgICAgICAgZ2FwOiAxMiwKICAgICAgICAgIH19CiAgICAgICAgPgogICAgICAg'
        'ICAgPEZpZWxkIGxhYmVsPSJDbHVzdGVyIj4KICAgICAgICAgICAgPHNlbGVjdAogICAgICAgICAg'
        'ICAgIHZhbHVlPXtmb3JtLmNsdXN0ZXJfaWR9CiAgICAgICAgICAgICAgb25DaGFuZ2U9eyhlKSA9'
        'PiBzZXRGb3JtKHsgLi4uZm9ybSwgY2x1c3Rlcl9pZDogZS50YXJnZXQudmFsdWUgfSl9CiAgICAg'
        'ICAgICAgICAgc3R5bGU9e2lucHV0U3R5bGV9CiAgICAgICAgICAgID4KICAgICAgICAgICAgICB7'
        'Q0xVU1RFUlMubWFwKChjKSA9PiAoCiAgICAgICAgICAgICAgICA8b3B0aW9uIGtleT17Y30gdmFs'
        'dWU9e2N9PgogICAgICAgICAgICAgICAgICB7Y30KICAgICAgICAgICAgICAgIDwvb3B0aW9uPgog'
        'ICAgICAgICAgICAgICkpfQogICAgICAgICAgICA8L3NlbGVjdD4KICAgICAgICAgIDwvRmllbGQ+'
        'CiAgICAgICAgICA8RmllbGQgbGFiZWw9IlNldmVyaWRhZGUiPgogICAgICAgICAgICA8c2VsZWN0'
        'CiAgICAgICAgICAgICAgdmFsdWU9e2Zvcm0uc2V2ZXJpdHl9CiAgICAgICAgICAgICAgb25DaGFu'
        'Z2U9eyhlKSA9PgogICAgICAgICAgICAgICAgc2V0Rm9ybSh7IC4uLmZvcm0sIHNldmVyaXR5OiBl'
        'LnRhcmdldC52YWx1ZSBhcyBJbmNpZGVudFNldmVyaXR5IH0pCiAgICAgICAgICAgICAgfQogICAg'
        'ICAgICAgICAgIHN0eWxlPXtpbnB1dFN0eWxlfQogICAgICAgICAgICA+CiAgICAgICAgICAgICAg'
        'eyhbJ2luZm8nLCAnd2FybmluZycsICdjcml0aWNhbCddIGFzIEluY2lkZW50U2V2ZXJpdHlbXSku'
        'bWFwKChzKSA9PiAoCiAgICAgICAgICAgICAgICA8b3B0aW9uIGtleT17c30gdmFsdWU9e3N9Pgog'
        'ICAgICAgICAgICAgICAgICB7U0VWRVJJVFlfTEFCRUxbc119CiAgICAgICAgICAgICAgICA8L29w'
        'dGlvbj4KICAgICAgICAgICAgICApKX0KICAgICAgICAgICAgPC9zZWxlY3Q+CiAgICAgICAgICA8'
        'L0ZpZWxkPgogICAgICAgICAgPEZpZWxkIGxhYmVsPSJDYXRlZ29yaWEiPgogICAgICAgICAgICA8'
        'c2VsZWN0CiAgICAgICAgICAgICAgdmFsdWU9e2Zvcm0uY2F0ZWdvcnl9CiAgICAgICAgICAgICAg'
        'b25DaGFuZ2U9eyhlKSA9PgogICAgICAgICAgICAgICAgc2V0Rm9ybSh7IC4uLmZvcm0sIGNhdGVn'
        'b3J5OiBlLnRhcmdldC52YWx1ZSBhcyBJbmNpZGVudENhdGVnb3J5IH0pCiAgICAgICAgICAgICAg'
        'fQogICAgICAgICAgICAgIHN0eWxlPXtpbnB1dFN0eWxlfQogICAgICAgICAgICA+CiAgICAgICAg'
        'ICAgICAgeyhPYmplY3Qua2V5cyhDQVRFR09SWV9MQUJFTCkgYXMgSW5jaWRlbnRDYXRlZ29yeVtd'
        'KS5tYXAoKGMpID0+ICgKICAgICAgICAgICAgICAgIDxvcHRpb24ga2V5PXtjfSB2YWx1ZT17Y30+'
        'CiAgICAgICAgICAgICAgICAgIHtDQVRFR09SWV9MQUJFTFtjXX0KICAgICAgICAgICAgICAgIDwv'
        'b3B0aW9uPgogICAgICAgICAgICAgICkpfQogICAgICAgICAgICA8L3NlbGVjdD4KICAgICAgICAg'
        'IDwvRmllbGQ+CiAgICAgICAgICA8RmllbGQgbGFiZWw9IlF1ZW0gcmVwb3J0YSI+CiAgICAgICAg'
        'ICAgIDxpbnB1dAogICAgICAgICAgICAgIHR5cGU9InRleHQiCiAgICAgICAgICAgICAgdmFsdWU9'
        'e2Zvcm0ucmVwb3J0ZWRfYnl9CiAgICAgICAgICAgICAgb25DaGFuZ2U9eyhlKSA9PiBzZXRGb3Jt'
        'KHsgLi4uZm9ybSwgcmVwb3J0ZWRfYnk6IGUudGFyZ2V0LnZhbHVlIH0pfQogICAgICAgICAgICAg'
        'IHBsYWNlaG9sZGVyPSJub21lIC8gZnVuw6fDo28iCiAgICAgICAgICAgICAgc3R5bGU9e2lucHV0'
        'U3R5bGV9CiAgICAgICAgICAgIC8+CiAgICAgICAgICA8L0ZpZWxkPgogICAgICAgICAgPEZpZWxk'
        'IGxhYmVsPSJEZXNjcmnDp8OjbyIgZnVsbD4KICAgICAgICAgICAgPHRleHRhcmVhCiAgICAgICAg'
        'ICAgICAgdmFsdWU9e2Zvcm0ubm90ZX0KICAgICAgICAgICAgICBvbkNoYW5nZT17KGUpID0+IHNl'
        'dEZvcm0oeyAuLi5mb3JtLCBub3RlOiBlLnRhcmdldC52YWx1ZSB9KX0KICAgICAgICAgICAgICBy'
        'b3dzPXsyfQogICAgICAgICAgICAgIHJlcXVpcmVkCiAgICAgICAgICAgICAgcGxhY2Vob2xkZXI9'
        'Ik8gcXVlIGFjb250ZWNldSwgb25kZSwgcXVhbmRv4oCmIgogICAgICAgICAgICAgIHN0eWxlPXt7'
        'IC4uLmlucHV0U3R5bGUsIGZvbnRGYW1pbHk6ICdpbmhlcml0JywgcmVzaXplOiAndmVydGljYWwn'
        'IH19CiAgICAgICAgICAgIC8+CiAgICAgICAgICA8L0ZpZWxkPgogICAgICAgICAgPGRpdiBzdHls'
        'ZT17eyBncmlkQ29sdW1uOiAnMSAvIC0xJywgZGlzcGxheTogJ2ZsZXgnLCBqdXN0aWZ5Q29udGVu'
        'dDogJ2ZsZXgtZW5kJyB9fT4KICAgICAgICAgICAgPGJ1dHRvbgogICAgICAgICAgICAgIHR5cGU9'
        'InN1Ym1pdCIKICAgICAgICAgICAgICBkaXNhYmxlZD17c3VibWl0dGluZyB8fCAhZm9ybS5ub3Rl'
        'LnRyaW0oKX0KICAgICAgICAgICAgICBzdHlsZT17ewogICAgICAgICAgICAgICAgYmFja2dyb3Vu'
        'ZDogJ3ZhcigtLWNvbG9yLXN1Y2Nlc3MsICMxQjNBMjEpJywKICAgICAgICAgICAgICAgIGNvbG9y'
        'OiAnd2hpdGUnLAogICAgICAgICAgICAgICAgYm9yZGVyOiAnbm9uZScsCiAgICAgICAgICAgICAg'
        'ICBib3JkZXJSYWRpdXM6IDgsCiAgICAgICAgICAgICAgICBwYWRkaW5nOiAnMTBweCAyNHB4JywK'
        'ICAgICAgICAgICAgICAgIGZvbnRTaXplOiAxMywKICAgICAgICAgICAgICAgIGZvbnRXZWlnaHQ6'
        'IDYwMCwKICAgICAgICAgICAgICAgIGN1cnNvcjogc3VibWl0dGluZyA/ICd3YWl0JyA6ICdwb2lu'
        'dGVyJywKICAgICAgICAgICAgICAgIG9wYWNpdHk6IHN1Ym1pdHRpbmcgfHwgIWZvcm0ubm90ZS50'
        'cmltKCkgPyAwLjUgOiAxLAogICAgICAgICAgICAgIH19CiAgICAgICAgICAgID4KICAgICAgICAg'
        'ICAgICB7c3VibWl0dGluZyA/ICdBIHJlZ2lzdGFy4oCmJyA6ICdSZWdpc3RhciBpbmNpZGVudGUn'
        'fQogICAgICAgICAgICA8L2J1dHRvbj4KICAgICAgICAgIDwvZGl2PgogICAgICAgIDwvZm9ybT4K'
        'ICAgICAgKX0KCiAgICAgIHsvKiBGaWx0cm9zICovfQogICAgICA8ZGl2IHN0eWxlPXt7IGRpc3Bs'
        'YXk6ICdmbGV4JywgZ2FwOiAxMiwgbWFyZ2luQm90dG9tOiAxNiwgYWxpZ25JdGVtczogJ2NlbnRl'
        'cicsIGZsZXhXcmFwOiAnd3JhcCcgfX0+CiAgICAgICAgPHNwYW4gc3R5bGU9e3sgZm9udFNpemU6'
        'IDEyLCBjb2xvcjogJ3ZhcigtLWNvbG9yLW11dGVkKScgfX0+RmlsdHJvczo8L3NwYW4+CiAgICAg'
        'ICAgPHNlbGVjdAogICAgICAgICAgdmFsdWU9e2ZpbHRlclNldmVyaXR5fQogICAgICAgICAgb25D'
        'aGFuZ2U9eyhlKSA9PiBzZXRGaWx0ZXJTZXZlcml0eShlLnRhcmdldC52YWx1ZSl9CiAgICAgICAg'
        'ICBzdHlsZT17eyAuLi5pbnB1dFN0eWxlLCB3aWR0aDogJ2F1dG8nIH19CiAgICAgICAgPgogICAg'
        'ICAgICAgPG9wdGlvbiB2YWx1ZT0iIj5Ub2RhIGEgc2V2ZXJpZGFkZTwvb3B0aW9uPgogICAgICAg'
        'ICAgPG9wdGlvbiB2YWx1ZT0iY3JpdGljYWwiPkFwZW5hcyBjcsOtdGljb3M8L29wdGlvbj4KICAg'
        'ICAgICAgIDxvcHRpb24gdmFsdWU9Indhcm5pbmciPkFwZW5hcyBhdmlzb3M8L29wdGlvbj4KICAg'
        'ICAgICAgIDxvcHRpb24gdmFsdWU9ImluZm8iPkFwZW5hcyBpbmZvPC9vcHRpb24+CiAgICAgICAg'
        'PC9zZWxlY3Q+CiAgICAgICAgPGxhYmVsIHN0eWxlPXt7IGRpc3BsYXk6ICdpbmxpbmUtZmxleCcs'
        'IGFsaWduSXRlbXM6ICdjZW50ZXInLCBnYXA6IDYsIGZvbnRTaXplOiAxMyB9fT4KICAgICAgICAg'
        'IDxpbnB1dAogICAgICAgICAgICB0eXBlPSJjaGVja2JveCIKICAgICAgICAgICAgY2hlY2tlZD17'
        'ZmlsdGVyT3Blbk9ubHl9CiAgICAgICAgICAgIG9uQ2hhbmdlPXsoZSkgPT4gc2V0RmlsdGVyT3Bl'
        'bk9ubHkoZS50YXJnZXQuY2hlY2tlZCl9CiAgICAgICAgICAvPgogICAgICAgICAgc8OzIGFiZXJ0'
        'b3MKICAgICAgICA8L2xhYmVsPgogICAgICA8L2Rpdj4KCiAgICAgIHtlcnJvciAmJiAoCiAgICAg'
        'ICAgPGRpdgogICAgICAgICAgc3R5bGU9e3sKICAgICAgICAgICAgcGFkZGluZzogMTIsCiAgICAg'
        'ICAgICAgIGJhY2tncm91bmQ6ICcjRkRFQ0RDJywKICAgICAgICAgICAgY29sb3I6ICcjQzI1QTFB'
        'JywKICAgICAgICAgICAgYm9yZGVyUmFkaXVzOiA4LAogICAgICAgICAgICBtYXJnaW5Cb3R0b206'
        'IDE2LAogICAgICAgICAgICBmb250U2l6ZTogMTMsCiAgICAgICAgICB9fQogICAgICAgID4KICAg'
        'ICAgICAgIHtlcnJvcn0KICAgICAgICA8L2Rpdj4KICAgICAgKX0KCiAgICAgIHsvKiBMaXN0YSAq'
        'L30KICAgICAge2xvYWRpbmcgJiYgaW5jaWRlbnRzLmxlbmd0aCA9PT0gMCAmJiAoCiAgICAgICAg'
        'PGRpdiBzdHlsZT17eyBjb2xvcjogJ3ZhcigtLWNvbG9yLW11dGVkKScsIHBhZGRpbmc6IDI0IH19'
        'PkEgY2FycmVnYXLigKY8L2Rpdj4KICAgICAgKX0KCiAgICAgIHshbG9hZGluZyAmJiBpbmNpZGVu'
        'dHMubGVuZ3RoID09PSAwICYmICgKICAgICAgICA8ZGl2CiAgICAgICAgICBzdHlsZT17ewogICAg'
        'ICAgICAgICBwYWRkaW5nOiAzMiwKICAgICAgICAgICAgdGV4dEFsaWduOiAnY2VudGVyJywKICAg'
        'ICAgICAgICAgY29sb3I6ICd2YXIoLS1jb2xvci1tdXRlZCknLAogICAgICAgICAgICBiYWNrZ3Jv'
        'dW5kOiAndmFyKC0tY2FyZCwgd2hpdGUpJywKICAgICAgICAgICAgYm9yZGVyOiAnMXB4IHNvbGlk'
        'IHZhcigtLWNvbG9yLWJvcmRlciknLAogICAgICAgICAgICBib3JkZXJSYWRpdXM6IDEyLAogICAg'
        'ICAgICAgfX0KICAgICAgICA+CiAgICAgICAgICBTZW0gaW5jaWRlbnRlcyByZWdpc3RhZG9zLgog'
        'ICAgICAgIDwvZGl2PgogICAgICApfQoKICAgICAgPGRpdiBzdHlsZT17eyBkaXNwbGF5OiAnZ3Jp'
        'ZCcsIGdhcDogMTAgfX0+CiAgICAgICAge2luY2lkZW50cy5tYXAoKGkpID0+IHsKICAgICAgICAg'
        'IGNvbnN0IHNldiA9IFNFVkVSSVRZX0NPTE9SU1tpLnNldmVyaXR5XTsKICAgICAgICAgIHJldHVy'
        'biAoCiAgICAgICAgICAgIDxkaXYKICAgICAgICAgICAgICBrZXk9e2kuaWR9CiAgICAgICAgICAg'
        'ICAgc3R5bGU9e3sKICAgICAgICAgICAgICAgIGJhY2tncm91bmQ6ICd2YXIoLS1jYXJkLCB3aGl0'
        'ZSknLAogICAgICAgICAgICAgICAgYm9yZGVyOiAnMXB4IHNvbGlkIHZhcigtLWNvbG9yLWJvcmRl'
        'ciknLAogICAgICAgICAgICAgICAgYm9yZGVyTGVmdDogYDRweCBzb2xpZCAke3Nldi5pbmt9YCwK'
        'ICAgICAgICAgICAgICAgIGJvcmRlclJhZGl1czogMTAsCiAgICAgICAgICAgICAgICBwYWRkaW5n'
        'OiAxNiwKICAgICAgICAgICAgICAgIGRpc3BsYXk6ICdncmlkJywKICAgICAgICAgICAgICAgIGdy'
        'aWRUZW1wbGF0ZUNvbHVtbnM6ICcxZnIgYXV0bycsCiAgICAgICAgICAgICAgICBnYXA6IDEyLAog'
        'ICAgICAgICAgICAgICAgb3BhY2l0eTogaS5yZXNvbHZlZCA/IDAuNTUgOiAxLAogICAgICAgICAg'
        'ICAgIH19CiAgICAgICAgICAgID4KICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAg'
        'PGRpdiBzdHlsZT17eyBkaXNwbGF5OiAnZmxleCcsIGdhcDogOCwgYWxpZ25JdGVtczogJ2NlbnRl'
        'cicsIG1hcmdpbkJvdHRvbTogNiB9fT4KICAgICAgICAgICAgICAgICAgPHNwYW4KICAgICAgICAg'
        'ICAgICAgICAgICBzdHlsZT17ewogICAgICAgICAgICAgICAgICAgICAgYmFja2dyb3VuZDogc2V2'
        'LmJnLAogICAgICAgICAgICAgICAgICAgICAgY29sb3I6IHNldi5pbmssCiAgICAgICAgICAgICAg'
        'ICAgICAgICBwYWRkaW5nOiAnMnB4IDhweCcsCiAgICAgICAgICAgICAgICAgICAgICBib3JkZXJS'
        'YWRpdXM6IDk5OSwKICAgICAgICAgICAgICAgICAgICAgIGZvbnRTaXplOiAxMCwKICAgICAgICAg'
        'ICAgICAgICAgICAgIGZvbnRXZWlnaHQ6IDcwMCwKICAgICAgICAgICAgICAgICAgICAgIGxldHRl'
        'clNwYWNpbmc6ICcwLjA4ZW0nLAogICAgICAgICAgICAgICAgICAgICAgdGV4dFRyYW5zZm9ybTog'
        'J3VwcGVyY2FzZScsCiAgICAgICAgICAgICAgICAgICAgfX0KICAgICAgICAgICAgICAgICAgPgog'
        'ICAgICAgICAgICAgICAgICAgIHtTRVZFUklUWV9MQUJFTFtpLnNldmVyaXR5XX0KICAgICAgICAg'
        'ICAgICAgICAgPC9zcGFuPgogICAgICAgICAgICAgICAgICA8c3BhbgogICAgICAgICAgICAgICAg'
        'ICAgIGNsYXNzTmFtZT0ibW9ubyIKICAgICAgICAgICAgICAgICAgICBzdHlsZT17eyBmb250U2l6'
        'ZTogMTEsIGNvbG9yOiAndmFyKC0tY29sb3ItbXV0ZWQpJyB9fQogICAgICAgICAgICAgICAgICA+'
        'CiAgICAgICAgICAgICAgICAgICAge2kuY2x1c3Rlcl9pZCB8fCAn4oCUJ30gwrcge0NBVEVHT1JZ'
        'X0xBQkVMW2kuY2F0ZWdvcnldfQogICAgICAgICAgICAgICAgICA8L3NwYW4+CiAgICAgICAgICAg'
        'ICAgICAgIHtpLnJlc29sdmVkICYmICgKICAgICAgICAgICAgICAgICAgICA8c3BhbgogICAgICAg'
        'ICAgICAgICAgICAgICAgc3R5bGU9e3sKICAgICAgICAgICAgICAgICAgICAgICAgZm9udFNpemU6'
        'IDEwLAogICAgICAgICAgICAgICAgICAgICAgICBjb2xvcjogJyMxQjNBMjEnLAogICAgICAgICAg'
        'ICAgICAgICAgICAgICBiYWNrZ3JvdW5kOiAnI0U4RjFFQScsCiAgICAgICAgICAgICAgICAgICAg'
        'ICAgIHBhZGRpbmc6ICcycHggOHB4JywKICAgICAgICAgICAgICAgICAgICAgICAgYm9yZGVyUmFk'
        'aXVzOiA5OTksCiAgICAgICAgICAgICAgICAgICAgICAgIGZvbnRXZWlnaHQ6IDYwMCwKICAgICAg'
        'ICAgICAgICAgICAgICAgIH19CiAgICAgICAgICAgICAgICAgICAgPgogICAgICAgICAgICAgICAg'
        'ICAgICAgUkVTT0xWSURPCiAgICAgICAgICAgICAgICAgICAgPC9zcGFuPgogICAgICAgICAgICAg'
        'ICAgICApfQogICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICAgICA8ZGl2IHN0eWxl'
        'PXt7IGZvbnRTaXplOiAxNCwgY29sb3I6ICd2YXIoLS1jb2xvci1pbmspJywgbGluZUhlaWdodDog'
        'MS41IH19PgogICAgICAgICAgICAgICAgICB7aS5ub3RlfQogICAgICAgICAgICAgICAgPC9kaXY+'
        'CiAgICAgICAgICAgICAgICA8ZGl2CiAgICAgICAgICAgICAgICAgIGNsYXNzTmFtZT0ibW9ubyIK'
        'ICAgICAgICAgICAgICAgICAgc3R5bGU9e3sgZm9udFNpemU6IDExLCBjb2xvcjogJ3ZhcigtLWNv'
        'bG9yLW11dGVkKScsIG1hcmdpblRvcDogNiB9fQogICAgICAgICAgICAgICAgPgogICAgICAgICAg'
        'ICAgICAgICB7bmV3IERhdGUoaS5vY2N1cnJlZF9hdCkudG9Mb2NhbGVTdHJpbmcoJ3B0LVBUJywg'
        'ewogICAgICAgICAgICAgICAgICAgIGRheTogJzItZGlnaXQnLAogICAgICAgICAgICAgICAgICAg'
        'IG1vbnRoOiAnMi1kaWdpdCcsCiAgICAgICAgICAgICAgICAgICAgaG91cjogJzItZGlnaXQnLAog'
        'ICAgICAgICAgICAgICAgICAgIG1pbnV0ZTogJzItZGlnaXQnLAogICAgICAgICAgICAgICAgICB9'
        'KX0KICAgICAgICAgICAgICAgICAge2kucmVwb3J0ZWRfYnkgPyBgIMK3ICR7aS5yZXBvcnRlZF9i'
        'eX1gIDogJyd9CiAgICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgICA8L2Rpdj4KICAg'
        'ICAgICAgICAgICB7IWkucmVzb2x2ZWQgJiYgKAogICAgICAgICAgICAgICAgPGJ1dHRvbgogICAg'
        'ICAgICAgICAgICAgICBvbkNsaWNrPXsoKSA9PiByZXNvbHZlKGkuaWQpfQogICAgICAgICAgICAg'
        'ICAgICBkaXNhYmxlZD17cmVzb2x2aW5nID09PSBpLmlkfQogICAgICAgICAgICAgICAgICBzdHls'
        'ZT17ewogICAgICAgICAgICAgICAgICAgIGJhY2tncm91bmQ6ICd0cmFuc3BhcmVudCcsCiAgICAg'
        'ICAgICAgICAgICAgICAgY29sb3I6ICd2YXIoLS1jb2xvci1zdWNjZXNzLCAjMUIzQTIxKScsCiAg'
        'ICAgICAgICAgICAgICAgICAgYm9yZGVyOiAnMXB4IHNvbGlkIHZhcigtLWNvbG9yLXN1Y2Nlc3Ms'
        'ICMxQjNBMjEpJywKICAgICAgICAgICAgICAgICAgICBib3JkZXJSYWRpdXM6IDgsCiAgICAgICAg'
        'ICAgICAgICAgICAgcGFkZGluZzogJzZweCAxNHB4JywKICAgICAgICAgICAgICAgICAgICBmb250'
        'U2l6ZTogMTIsCiAgICAgICAgICAgICAgICAgICAgZm9udFdlaWdodDogNjAwLAogICAgICAgICAg'
        'ICAgICAgICAgIGN1cnNvcjogJ3BvaW50ZXInLAogICAgICAgICAgICAgICAgICAgIHdoaXRlU3Bh'
        'Y2U6ICdub3dyYXAnLAogICAgICAgICAgICAgICAgICAgIGFsaWduU2VsZjogJ2ZsZXgtc3RhcnQn'
        'LAogICAgICAgICAgICAgICAgICB9fQogICAgICAgICAgICAgICAgPgogICAgICAgICAgICAgICAg'
        'ICB7cmVzb2x2aW5nID09PSBpLmlkID8gJ+KApicgOiAnUmVzb2x2ZXInfQogICAgICAgICAgICAg'
        'ICAgPC9idXR0b24+CiAgICAgICAgICAgICAgKX0KICAgICAgICAgICAgPC9kaXY+CiAgICAgICAg'
        'ICApOwogICAgICAgIH0pfQogICAgICA8L2Rpdj4KICAgIDwvZGl2PgogICk7Cn0KCmNvbnN0IGlu'
        'cHV0U3R5bGU6IFJlYWN0LkNTU1Byb3BlcnRpZXMgPSB7CiAgd2lkdGg6ICcxMDAlJywKICBwYWRk'
        'aW5nOiAnOHB4IDEwcHgnLAogIGZvbnRTaXplOiAxMywKICBib3JkZXI6ICcxcHggc29saWQgdmFy'
        'KC0tY29sb3ItYm9yZGVyKScsCiAgYm9yZGVyUmFkaXVzOiA2LAogIGJhY2tncm91bmQ6ICd3aGl0'
        'ZScsCiAgY29sb3I6ICd2YXIoLS1jb2xvci1pbmspJywKfTsKCmZ1bmN0aW9uIEZpZWxkKHsKICBs'
        'YWJlbCwKICBjaGlsZHJlbiwKICBmdWxsLAp9OiB7CiAgbGFiZWw6IHN0cmluZzsKICBjaGlsZHJl'
        'bjogUmVhY3QuUmVhY3ROb2RlOwogIGZ1bGw/OiBib29sZWFuOwp9KSB7CiAgcmV0dXJuICgKICAg'
        'IDxkaXYgc3R5bGU9e3sgZ3JpZENvbHVtbjogZnVsbCA/ICcxIC8gLTEnIDogdW5kZWZpbmVkIH19'
        'PgogICAgICA8bGFiZWwKICAgICAgICBzdHlsZT17ewogICAgICAgICAgZGlzcGxheTogJ2Jsb2Nr'
        'JywKICAgICAgICAgIGZvbnRTaXplOiAxMSwKICAgICAgICAgIGNvbG9yOiAndmFyKC0tY29sb3It'
        'bXV0ZWQpJywKICAgICAgICAgIG1hcmdpbkJvdHRvbTogNCwKICAgICAgICAgIGZvbnRXZWlnaHQ6'
        'IDUwMCwKICAgICAgICAgIGxldHRlclNwYWNpbmc6ICcwLjA0ZW0nLAogICAgICAgICAgdGV4dFRy'
        'YW5zZm9ybTogJ3VwcGVyY2FzZScsCiAgICAgICAgfX0KICAgICAgPgogICAgICAgIHtsYWJlbH0K'
        'ICAgICAgPC9sYWJlbD4KICAgICAge2NoaWxkcmVufQogICAgPC9kaXY+CiAgKTsKfQoKZnVuY3Rp'
        'b24gS3BpKHsgbGFiZWwsIHZhbHVlLCBjb2xvciB9OiB7IGxhYmVsOiBzdHJpbmc7IHZhbHVlOiBu'
        'dW1iZXI7IGNvbG9yOiBzdHJpbmcgfSkgewogIHJldHVybiAoCiAgICA8ZGl2CiAgICAgIHN0eWxl'
        'PXt7CiAgICAgICAgYmFja2dyb3VuZDogJ3ZhcigtLWNhcmQsIHdoaXRlKScsCiAgICAgICAgYm9y'
        'ZGVyOiAnMXB4IHNvbGlkIHZhcigtLWNvbG9yLWJvcmRlciknLAogICAgICAgIGJvcmRlclJhZGl1'
        'czogMTAsCiAgICAgICAgcGFkZGluZzogMTQsCiAgICAgIH19CiAgICA+CiAgICAgIDxkaXYKICAg'
        'ICAgICBjbGFzc05hbWU9Im1vbm8iCiAgICAgICAgc3R5bGU9e3sKICAgICAgICAgIGZvbnRTaXpl'
        'OiAxMCwKICAgICAgICAgIGNvbG9yOiAndmFyKC0tY29sb3ItbXV0ZWQpJywKICAgICAgICAgIGxl'
        'dHRlclNwYWNpbmc6ICcwLjA4ZW0nLAogICAgICAgICAgdGV4dFRyYW5zZm9ybTogJ3VwcGVyY2Fz'
        'ZScsCiAgICAgICAgICBtYXJnaW5Cb3R0b206IDQsCiAgICAgICAgfX0KICAgICAgPgogICAgICAg'
        'IHtsYWJlbH0KICAgICAgPC9kaXY+CiAgICAgIDxkaXYgY2xhc3NOYW1lPSJzZXJpZiIgc3R5bGU9'
        'e3sgZm9udFNpemU6IDI2LCBmb250V2VpZ2h0OiA1MDAsIGNvbG9yLCBsaW5lSGVpZ2h0OiAxIH19'
        'PgogICAgICAgIHt2YWx1ZX0KICAgICAgPC9kaXY+CiAgICA8L2Rpdj4KICApOwp9Cg=='
    ),
    'frontend/components/v2/WeatherWidget.tsx': (
        'J3VzZSBjbGllbnQnOwoKaW1wb3J0IHsgdXNlRWZmZWN0LCB1c2VTdGF0ZSB9IGZyb20gJ3JlYWN0'
        'JzsKaW1wb3J0IHsgYXBpLCB0eXBlIFdlYXRoZXJOb3cgfSBmcm9tICdAL2xpYi92Mi1hcGknOwoK'
        'Y29uc3QgUkVGUkVTSF9NUyA9IDEwICogNjAgKiAxMDAwOyAvLyAxMCBtaW4g4oCUIGFsaW5oYWRv'
        'IGNvbSBjYWNoZSBkbyBiYWNrZW5kCgpmdW5jdGlvbiBpY29uRm9yKGNvZGU6IG51bWJlcik6IHN0'
        'cmluZyB7CiAgaWYgKGNvZGUgPT09IDAgfHwgY29kZSA9PT0gMSkgcmV0dXJuICfimIAnOwogIGlm'
        'IChjb2RlID09PSAyKSByZXR1cm4gJ+KbhSc7CiAgaWYgKGNvZGUgPT09IDMpIHJldHVybiAn4piB'
        'JzsKICBpZiAoY29kZSA+PSA0NSAmJiBjb2RlIDw9IDQ4KSByZXR1cm4gJ/CfjKsnOwogIGlmIChj'
        'b2RlID49IDUxICYmIGNvZGUgPD0gNjcpIHJldHVybiAn8J+Mpyc7CiAgaWYgKGNvZGUgPj0gNzEg'
        'JiYgY29kZSA8PSA3NykgcmV0dXJuICfinYQnOwogIGlmIChjb2RlID49IDgwICYmIGNvZGUgPD0g'
        'ODIpIHJldHVybiAn8J+Mpic7CiAgaWYgKGNvZGUgPj0gOTUpIHJldHVybiAn4puIJzsKICByZXR1'
        'cm4gJ8K3JzsKfQoKZXhwb3J0IGRlZmF1bHQgZnVuY3Rpb24gV2VhdGhlcldpZGdldCgpIHsKICBj'
        'b25zdCBbdywgc2V0V10gPSB1c2VTdGF0ZTxXZWF0aGVyTm93IHwgbnVsbD4obnVsbCk7CgogIHVz'
        'ZUVmZmVjdCgoKSA9PiB7CiAgICBjb25zdCBmZXRjaCA9IGFzeW5jICgpID0+IHsKICAgICAgdHJ5'
        'IHsKICAgICAgICBjb25zdCBkYXRhID0gYXdhaXQgYXBpLndlYXRoZXJOb3coKTsKICAgICAgICBz'
        'ZXRXKGRhdGEpOwogICAgICB9IGNhdGNoIHsKICAgICAgICAvLyBzaWxlbmNpb3NvIOKAlCBtZXRl'
        'byDDqSBuaWNlLXRvLWhhdmUKICAgICAgfQogICAgfTsKICAgIGZldGNoKCk7CiAgICBjb25zdCBp'
        'diA9IHNldEludGVydmFsKGZldGNoLCBSRUZSRVNIX01TKTsKICAgIHJldHVybiAoKSA9PiBjbGVh'
        'ckludGVydmFsKGl2KTsKICB9LCBbXSk7CgogIGlmICghdykgcmV0dXJuIG51bGw7CgogIHJldHVy'
        'biAoCiAgICA8c3BhbgogICAgICB0aXRsZT17YCR7dy53ZWF0aGVyX2xhYmVsfSDCtyB2ZW50byAk'
        'e3cud2luZF9rbWgudG9GaXhlZCgwKX0ga20vaCDCtyBodW1pZGFkZSAke3cuaHVtaWRpdHlfcGN0'
        'LnRvRml4ZWQoMCl9JSDCtyAke3cubG9jYXRpb259YH0KICAgICAgc3R5bGU9e3sKICAgICAgICBk'
        'aXNwbGF5OiAnaW5saW5lLWZsZXgnLAogICAgICAgIGFsaWduSXRlbXM6ICdjZW50ZXInLAogICAg'
        'ICAgIGdhcDogNiwKICAgICAgICBmb250U2l6ZTogMTIsCiAgICAgICAgY29sb3I6ICd2YXIoLS1j'
        'b2xvci1tdXRlZCknLAogICAgICAgIHBhZGRpbmc6ICc0cHggMTBweCcsCiAgICAgICAgYmFja2dy'
        'b3VuZDogJ3ZhcigtLWNvbG9yLXN1cmZhY2UsICNGQUZBRjcpJywKICAgICAgICBib3JkZXI6ICcx'
        'cHggc29saWQgdmFyKC0tY29sb3ItYm9yZGVyKScsCiAgICAgICAgYm9yZGVyUmFkaXVzOiA5OTks'
        'CiAgICAgIH19CiAgICA+CiAgICAgIDxzcGFuIHN0eWxlPXt7IGZvbnRTaXplOiAxNCB9fT57aWNv'
        'bkZvcih3LndlYXRoZXJfY29kZSl9PC9zcGFuPgogICAgICA8c3BhbiBzdHlsZT17eyBmb250V2Vp'
        'Z2h0OiA2MDAsIGNvbG9yOiAndmFyKC0tY29sb3ItaW5rKScgfX0+CiAgICAgICAge3cudGVtcGVy'
        'YXR1cmVfYy50b0ZpeGVkKDApfcKwQwogICAgICA8L3NwYW4+CiAgICAgIDxzcGFuIHN0eWxlPXt7'
        'IGZvbnRTaXplOiAxMCwgb3BhY2l0eTogMC43IH19Pnt3LndlYXRoZXJfbGFiZWx9PC9zcGFuPgog'
        'ICAgPC9zcGFuPgogICk7Cn0K'
    ),
    'app/services/forecast.py': (
        'IiIiClBsYW50YU9TIMK3IEZvcmVjYXN0IHNlcnZpY2UKPT09PT09PT09PT09PT09PT09PT09PT09'
        'PT09PQpQcm9qZWN0YSBvY3VwYcOnw6NvIGEgMzAgbWluIMOgIGZyZW50ZSBiYXNlYWRvIGVtOgog'
        'IC0gVGVuZMOqbmNpYSByZWNlbnRlIChzbG9wZSBkYXMgw7psdGltYXMgYW1vc3RyYXMgc2ltdWxh'
        'ZGFzKQogIC0gU2hvdyBzY2hlZHVsZSAoc3VyZ2UgfjMuOMOXIG5vcyAyNSBtaW4gZGVwb2lzIGRl'
        'IGZpbSBkZSBzaG93KQoKU2VtIE1MLiBEZXRlcm1pbsOtc3RpY28uIFNlbXByZSBkZXZvbHZlIHVt'
        'IG7Dum1lcm8uCiIiIgpmcm9tIF9fZnV0dXJlX18gaW1wb3J0IGFubm90YXRpb25zCgpmcm9tIGRh'
        'dGFjbGFzc2VzIGltcG9ydCBkYXRhY2xhc3MKZnJvbSBkYXRldGltZSBpbXBvcnQgZGF0ZXRpbWUs'
        'IHRpbWV6b25lLCB0aW1lZGVsdGEKZnJvbSB0eXBpbmcgaW1wb3J0IE9wdGlvbmFsCgojIENsdXN0'
        'ZXIgY2FwIChsdWdhcmVzIHRvdGFpcyBwb3IgY2x1c3RlciwgZG8gWExTWCBvZmljaWFsKQpDTFVT'
        'VEVSX0NBUEFDSVRZOiBkaWN0W3N0ciwgaW50XSA9IHsKICAgICJXQy0wMSI6IDEzNSwKICAgICJX'
        'Qy0wMiI6IDEyNiwKICAgICJXQy0wMyI6IDEwMiwKICAgICJXQy0wNCI6IDE1MCwKICAgICJXQy0w'
        'NSI6IDEzMywKICAgICJXQy0wNiI6IDIwOCwKICAgICJXQy0wNyI6IDEzOCwKICAgICJXQy0wOCI6'
        'IDE0NSwKfQoKIyBRdWFudG8gY2FkYSBjbHVzdGVyIGFwYW5oYSBkZSBzdXJnZSBww7NzLXNob3cs'
        'IGVtICUgZG8gZGVsdGEKIyBXQy0wNiBhYnNvcnZlIH44OCUgZGFzIHJlZGlyZWPDp8O1ZXMsIGRh'
        'w60gZXN0ZXMgcGVzb3MKU1VSR0VfV0VJR0hUOiBkaWN0W3N0ciwgZmxvYXRdID0gewogICAgIldD'
        'LTAxIjogMC4wNSwKICAgICJXQy0wMiI6IDAuMDQsCiAgICAiV0MtMDMiOiAwLjA1LAogICAgIldD'
        'LTA0IjogMC4wNiwKICAgICJXQy0wNSI6IDAuMDgsCiAgICAiV0MtMDYiOiAwLjUwLCAgICMgYWJz'
        'b3J2ZSBhIG1haW9yaWEgZG8gc3VyZ2UKICAgICJXQy0wNyI6IDAuMTUsCiAgICAiV0MtMDgiOiAw'
        'LjA3LAp9CgpTVVJHRV9GQUNUT1IgPSAzLjgKU1VSR0VfRFVSQVRJT05fTUlOID0gMjUKCgpAZGF0'
        'YWNsYXNzCmNsYXNzIEZvcmVjYXN0UG9pbnQ6CiAgICBtaW51dGVzX2FoZWFkOiBpbnQKICAgIG9j'
        'dXBhY2FvX3BjdDogZmxvYXQKICAgIGNvbmZpZGVuY2U6IGZsb2F0ICAjIDAtMQogICAgc3VyZ2Vf'
        'YWN0aXZlOiBib29sCgoKQGRhdGFjbGFzcwpjbGFzcyBDbHVzdGVyRm9yZWNhc3Q6CiAgICBjbHVz'
        'dGVyX2lkOiBzdHIKICAgIGhvcml6b25fbWluOiBpbnQKICAgIGN1cnJlbnRfb2N1cGFjYW9fcGN0'
        'OiBmbG9hdAogICAgcG9pbnRzOiBsaXN0W0ZvcmVjYXN0UG9pbnRdCiAgICBwZWFrX29jdXBhY2Fv'
        'X3BjdDogZmxvYXQKICAgIHBlYWtfYXRfbWluOiBpbnQKICAgIG5vdGVzOiBsaXN0W3N0cl0KCgpk'
        'ZWYgcHJvamVjdCgKICAgIGNsdXN0ZXJfaWQ6IHN0ciwKICAgIGN1cnJlbnRfcGN0OiBmbG9hdCwK'
        'ICAgIHRyZW5kX3Nsb3BlX3Blcl9taW46IGZsb2F0ID0gMC4wLAogICAgbWludXRlc190b19zaG93'
        'X2VuZDogT3B0aW9uYWxbaW50XSA9IE5vbmUsCiAgICBob3Jpem9uX21pbjogaW50ID0gMzAsCikg'
        'LT4gQ2x1c3RlckZvcmVjYXN0OgogICAgIiIiUHJvamVjdGEgYSBjdXJ2YSBkZSBvY3VwYcOnw6Nv'
        'LiIiIgogICAgbm90ZXM6IGxpc3Rbc3RyXSA9IFtdCiAgICBwb2ludHM6IGxpc3RbRm9yZWNhc3RQ'
        'b2ludF0gPSBbXQogICAgc3VyZ2Vfd2VpZ2h0ID0gU1VSR0VfV0VJR0hULmdldChjbHVzdGVyX2lk'
        'LCAwLjEpCgogICAgcGVha19wY3QgPSBjdXJyZW50X3BjdAogICAgcGVha19taW4gPSAwCgogICAg'
        'Zm9yIG0gaW4gKDUsIDEwLCAxNSwgMjAsIDI1LCAzMCk6CiAgICAgICAgaWYgbSA+IGhvcml6b25f'
        'bWluOgogICAgICAgICAgICBicmVhawogICAgICAgICMgVGVuZMOqbmNpYSBsaW5lYXIKICAgICAg'
        'ICBiYXNlID0gY3VycmVudF9wY3QgKyB0cmVuZF9zbG9wZV9wZXJfbWluICogbQogICAgICAgICMg'
        'U3VyZ2UgY29udHJpYnVpw6fDo28KICAgICAgICBzdXJnZV9hY3RpdmUgPSBGYWxzZQogICAgICAg'
        'IHN1cmdlX2FkZCA9IDAuMAogICAgICAgIGlmIG1pbnV0ZXNfdG9fc2hvd19lbmQgaXMgbm90IE5v'
        'bmU6CiAgICAgICAgICAgICMgU2UgbyBzaG93IGFjYWJhIGRlbnRybyBkZSBbLTUsICsyNV0gbWlu'
        'IGVtIHJlbGHDp8OjbyBhICdtJywgc3VyZ2UgZXN0w6EgYWN0aXZvCiAgICAgICAgICAgIHRfYWZ0'
        'ZXJfZW5kID0gbSAtIG1pbnV0ZXNfdG9fc2hvd19lbmQKICAgICAgICAgICAgaWYgMCA8PSB0X2Fm'
        'dGVyX2VuZCA8PSBTVVJHRV9EVVJBVElPTl9NSU46CiAgICAgICAgICAgICAgICBzdXJnZV9hY3Rp'
        'dmUgPSBUcnVlCiAgICAgICAgICAgICAgICAjIFN1cmdlIGludGVuc2lmaWNhIG5vcyBwcmltZWly'
        'b3MgMTAgbWluLCBkZWNhaSBkZXBvaXMKICAgICAgICAgICAgICAgIGludGVuc2l0eSA9IDEuMCAt'
        'ICh0X2FmdGVyX2VuZCAvIFNVUkdFX0RVUkFUSU9OX01JTikKICAgICAgICAgICAgICAgIHN1cmdl'
        'X2FkZCA9IHN1cmdlX3dlaWdodCAqIChTVVJHRV9GQUNUT1IgLSAxLjApICogMTAwLjAgKiBpbnRl'
        'bnNpdHkKICAgICAgICBwcm9qID0gbWF4KDAuMCwgbWluKDEwMC4wLCBiYXNlICsgc3VyZ2VfYWRk'
        'KSkKICAgICAgICAjIENvbmZpYW7Dp2EgZGVjcmVzY2UgY29tIGhvcml6b250ZQogICAgICAgIGNv'
        'bmYgPSBtYXgoMC4zLCAwLjkgLSAwLjAyICogbSkKICAgICAgICBwb2ludHMuYXBwZW5kKAogICAg'
        'ICAgICAgICBGb3JlY2FzdFBvaW50KAogICAgICAgICAgICAgICAgbWludXRlc19haGVhZD1tLAog'
        'ICAgICAgICAgICAgICAgb2N1cGFjYW9fcGN0PXJvdW5kKHByb2osIDEpLAogICAgICAgICAgICAg'
        'ICAgY29uZmlkZW5jZT1yb3VuZChjb25mLCAyKSwKICAgICAgICAgICAgICAgIHN1cmdlX2FjdGl2'
        'ZT1zdXJnZV9hY3RpdmUsCiAgICAgICAgICAgICkKICAgICAgICApCiAgICAgICAgaWYgcHJvaiA+'
        'IHBlYWtfcGN0OgogICAgICAgICAgICBwZWFrX3BjdCA9IHByb2oKICAgICAgICAgICAgcGVha19t'
        'aW4gPSBtCgogICAgaWYgbWludXRlc190b19zaG93X2VuZCBpcyBub3QgTm9uZSBhbmQgMCA8IG1p'
        'bnV0ZXNfdG9fc2hvd19lbmQgPD0gaG9yaXpvbl9taW46CiAgICAgICAgbm90ZXMuYXBwZW5kKAog'
        'ICAgICAgICAgICBmIlNob3cgdGVybWluYSBkYXF1aSBhIHttaW51dGVzX3RvX3Nob3dfZW5kfSBt'
        'aW4gwrcgc3VyZ2UgcHJldmlzdG8iCiAgICAgICAgKQogICAgaWYgcGVha19wY3QgPiA4NToKICAg'
        'ICAgICBub3Rlcy5hcHBlbmQoZiJQaWNvIHByZXZpc3RvOiB7cGVha19wY3Q6LjBmfSUgYW9zIHtw'
        'ZWFrX21pbn0gbWluIikKCiAgICByZXR1cm4gQ2x1c3RlckZvcmVjYXN0KAogICAgICAgIGNsdXN0'
        'ZXJfaWQ9Y2x1c3Rlcl9pZCwKICAgICAgICBob3Jpem9uX21pbj1ob3Jpem9uX21pbiwKICAgICAg'
        'ICBjdXJyZW50X29jdXBhY2FvX3BjdD1yb3VuZChjdXJyZW50X3BjdCwgMSksCiAgICAgICAgcG9p'
        'bnRzPXBvaW50cywKICAgICAgICBwZWFrX29jdXBhY2FvX3BjdD1yb3VuZChwZWFrX3BjdCwgMSks'
        'CiAgICAgICAgcGVha19hdF9taW49cGVha19taW4sCiAgICAgICAgbm90ZXM9bm90ZXMsCiAgICAp'
        'Cg=='
    ),
    'app/routers/forecast.py': (
        'IiIiClBsYW50YU9TIMK3IEZvcmVjYXN0IHJvdXRlcgo9PT09PT09PT09PT09PT09PT09PT09PT09'
        'PT0KR0VUIC9hcGkvdjEvZm9yZWNhc3QvY2x1c3Rlci97Y2x1c3Rlcl9pZH0/aG9yaXpvbl9taW49'
        'MzAKIiIiCmZyb20gX19mdXR1cmVfXyBpbXBvcnQgYW5ub3RhdGlvbnMKCmZyb20gZGF0ZXRpbWUg'
        'aW1wb3J0IGRhdGV0aW1lLCB0aW1lem9uZQpmcm9tIHR5cGluZyBpbXBvcnQgT3B0aW9uYWwKCmZy'
        'b20gZmFzdGFwaSBpbXBvcnQgQVBJUm91dGVyLCBIVFRQRXhjZXB0aW9uLCBRdWVyeQpmcm9tIHB5'
        'ZGFudGljIGltcG9ydCBCYXNlTW9kZWwKCmZyb20gYXBwLnNlcnZpY2VzIGltcG9ydCBmb3JlY2Fz'
        'dCBhcyBmY19zZXJ2aWNlCmZyb20gYXBwLnNlcnZpY2VzLnN0YXRlIGltcG9ydCBnZXRfY3VycmVu'
        'dF9zdGF0ZQpmcm9tIGFwcC5zZXJ2aWNlcy5zaW11bGF0aW9uIGltcG9ydCBzaW11bGF0ZV90aWNr'
        'ICAjIG5vcWEg4oCUIHVzYWRvIGluZGlyZWN0YW1lbnRlCgpyb3V0ZXIgPSBBUElSb3V0ZXIocHJl'
        'Zml4PSIvYXBpL3YxL2ZvcmVjYXN0IiwgdGFncz1bImZvcmVjYXN0Il0pCgoKY2xhc3MgRm9yZWNh'
        'c3RQb2ludE91dChCYXNlTW9kZWwpOgogICAgbWludXRlc19haGVhZDogaW50CiAgICBvY3VwYWNh'
        'b19wY3Q6IGZsb2F0CiAgICBjb25maWRlbmNlOiBmbG9hdAogICAgc3VyZ2VfYWN0aXZlOiBib29s'
        'CgoKY2xhc3MgRm9yZWNhc3RSZXNwb25zZShCYXNlTW9kZWwpOgogICAgY2x1c3Rlcl9pZDogc3Ry'
        'CiAgICBob3Jpem9uX21pbjogaW50CiAgICBjdXJyZW50X29jdXBhY2FvX3BjdDogZmxvYXQKICAg'
        'IHBvaW50czogbGlzdFtGb3JlY2FzdFBvaW50T3V0XQogICAgcGVha19vY3VwYWNhb19wY3Q6IGZs'
        'b2F0CiAgICBwZWFrX2F0X21pbjogaW50CiAgICBub3RlczogbGlzdFtzdHJdCiAgICBnZW5lcmF0'
        'ZWRfYXQ6IGRhdGV0aW1lCgoKZGVmIF9taW51dGVzX3RvX25leHRfc2hvd19lbmQoKSAtPiBPcHRp'
        'b25hbFtpbnRdOgogICAgIiIiU3R1YiBtaW5pbWFsIOKAlCBzZW0gYWNlc3NvIGFvIHNob3cgc2No'
        'ZWR1bGUgcmV0b3JuYSBOb25lLgogICAgTyBhdXRvX3RpY2sgZG8gc3VyZ2VfcHJlZGljdG9yIChD'
        'YW1pbmhvIEIgcGFydGUgMikgZmFyw6EgZXN0YSBsw7NnaWNhCiAgICBlbSBiYWNrZ3JvdW5kIGNv'
        'bSBhY2Vzc28gYW8gc2hvd3Mgcm91dGVyLiIiIgogICAgcmV0dXJuIE5vbmUKCgpAcm91dGVyLmdl'
        'dCgiL2NsdXN0ZXIve2NsdXN0ZXJfaWR9IiwgcmVzcG9uc2VfbW9kZWw9Rm9yZWNhc3RSZXNwb25z'
        'ZSkKYXN5bmMgZGVmIGNsdXN0ZXJfZm9yZWNhc3QoCiAgICBjbHVzdGVyX2lkOiBzdHIsCiAgICBo'
        'b3Jpem9uX21pbjogaW50ID0gUXVlcnkoMzAsIGdlPTUsIGxlPTYwKSwKKToKICAgICIiIlByb2pl'
        'Y3RhIGEgb2N1cGHDp8OjbyBkbyBjbHVzdGVyIHBhcmEgb3MgcHLDs3hpbW9zIG1pbnV0b3MuIiIi'
        'CiAgICB0cnk6CiAgICAgICAgc3RhdGUgPSBhd2FpdCBnZXRfY3VycmVudF9zdGF0ZSgpCiAgICBl'
        'eGNlcHQgRXhjZXB0aW9uIGFzIGU6CiAgICAgICAgcmFpc2UgSFRUUEV4Y2VwdGlvbig1MDAsIGRl'
        'dGFpbD1mIk7Do28gY29uc2VndWkgbGVyIGVzdGFkbyBhY3R1YWw6IHtlfSIpCgogICAgIyBFbmNv'
        'bnRyYSBvY3VwYcOnw6NvIGFjdHVhbCBhZ3JlZ2FkYSBwb3IgY2x1c3RlcgogICAgc2VjdGlvbnMg'
        'PSBnZXRhdHRyKHN0YXRlLCAic2VjdGlvbnMiLCBOb25lKSBvciBbXQogICAgY2x1c3Rlcl9wY3Rz'
        'OiBsaXN0W2Zsb2F0XSA9IFtdCiAgICBmb3IgcyBpbiBzZWN0aW9uczoKICAgICAgICBzaWQgPSBn'
        'ZXRhdHRyKHMsICJzZWN0aW9uX2lkIiwgIiIpCiAgICAgICAgaWYgc2lkLnN0YXJ0c3dpdGgoY2x1'
        'c3Rlcl9pZCk6CiAgICAgICAgICAgIHBjdCA9IGdldGF0dHIocywgIm9jdXBhY2FvX3BjdCIsIDAu'
        'MCkKICAgICAgICAgICAgY2x1c3Rlcl9wY3RzLmFwcGVuZChmbG9hdChwY3QpKQoKICAgIGlmIG5v'
        'dCBjbHVzdGVyX3BjdHM6CiAgICAgICAgcmFpc2UgSFRUUEV4Y2VwdGlvbig0MDQsIGRldGFpbD1m'
        'IkNsdXN0ZXIge2NsdXN0ZXJfaWR9IG7Do28gZW5jb250cmFkbyIpCgogICAgY3VycmVudF9wY3Qg'
        'PSBzdW0oY2x1c3Rlcl9wY3RzKSAvIGxlbihjbHVzdGVyX3BjdHMpCgogICAgIyBTbG9wZSBjb25z'
        'ZXJ2YWRvciDigJQgMCBwb3IgZGVmZWl0byAoc2VtIGhpc3TDs3JpY28gZW0gbWVtw7NyaWEgYWlu'
        'ZGEpCiAgICBzbG9wZSA9IDAuMAoKICAgIGZvcmVjYXN0ID0gZmNfc2VydmljZS5wcm9qZWN0KAog'
        'ICAgICAgIGNsdXN0ZXJfaWQ9Y2x1c3Rlcl9pZCwKICAgICAgICBjdXJyZW50X3BjdD1jdXJyZW50'
        'X3BjdCwKICAgICAgICB0cmVuZF9zbG9wZV9wZXJfbWluPXNsb3BlLAogICAgICAgIG1pbnV0ZXNf'
        'dG9fc2hvd19lbmQ9X21pbnV0ZXNfdG9fbmV4dF9zaG93X2VuZCgpLAogICAgICAgIGhvcml6b25f'
        'bWluPWhvcml6b25fbWluLAogICAgKQoKICAgIHJldHVybiBGb3JlY2FzdFJlc3BvbnNlKAogICAg'
        'ICAgIGNsdXN0ZXJfaWQ9Zm9yZWNhc3QuY2x1c3Rlcl9pZCwKICAgICAgICBob3Jpem9uX21pbj1m'
        'b3JlY2FzdC5ob3Jpem9uX21pbiwKICAgICAgICBjdXJyZW50X29jdXBhY2FvX3BjdD1mb3JlY2Fz'
        'dC5jdXJyZW50X29jdXBhY2FvX3BjdCwKICAgICAgICBwb2ludHM9WwogICAgICAgICAgICBGb3Jl'
        'Y2FzdFBvaW50T3V0KAogICAgICAgICAgICAgICAgbWludXRlc19haGVhZD1wLm1pbnV0ZXNfYWhl'
        'YWQsCiAgICAgICAgICAgICAgICBvY3VwYWNhb19wY3Q9cC5vY3VwYWNhb19wY3QsCiAgICAgICAg'
        'ICAgICAgICBjb25maWRlbmNlPXAuY29uZmlkZW5jZSwKICAgICAgICAgICAgICAgIHN1cmdlX2Fj'
        'dGl2ZT1wLnN1cmdlX2FjdGl2ZSwKICAgICAgICAgICAgKQogICAgICAgICAgICBmb3IgcCBpbiBm'
        'b3JlY2FzdC5wb2ludHMKICAgICAgICBdLAogICAgICAgIHBlYWtfb2N1cGFjYW9fcGN0PWZvcmVj'
        'YXN0LnBlYWtfb2N1cGFjYW9fcGN0LAogICAgICAgIHBlYWtfYXRfbWluPWZvcmVjYXN0LnBlYWtf'
        'YXRfbWluLAogICAgICAgIG5vdGVzPWZvcmVjYXN0Lm5vdGVzLAogICAgICAgIGdlbmVyYXRlZF9h'
        'dD1kYXRldGltZS5ub3codGltZXpvbmUudXRjKSwKICAgICkK'
    ),
}

V2_API_APPEND_B64 = (
    'Ci8vIOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKV'
    'kOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKV'
    'kOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKV'
    'kOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkAovLyB2OCDCtyBPUEVSQUNJT05B'
    'TCDigJQgY2xlYW5pbmcgwrcgc3RhZmYgwrcgaW5jaWRlbnRzIMK3IHdlYXRoZXIgwrcgZm9yZWNh'
    'c3QKLy8g4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ'
    '4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ'
    '4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ'
    '4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQCgpleHBvcnQgdHlwZSBDbGVh'
    'bmluZ1N0YXR1cyA9ICdjbGVhbicgfCAnaW5fcHJvZ3Jlc3MnIHwgJ25lZWRzX2NsZWFuaW5nJyB8'
    'ICd1cmdlbnQnOwoKZXhwb3J0IGludGVyZmFjZSBDbGVhbmluZ0NsdXN0ZXJTdGF0dXMgewogIGNs'
    'dXN0ZXJfaWQ6IHN0cmluZzsKICBzdGF0dXM6IENsZWFuaW5nU3RhdHVzOwogIGxhc3RfY2xlYW5l'
    'ZF9hdDogc3RyaW5nIHwgbnVsbDsKICBuZXh0X3NjaGVkdWxlZF9mb3I6IHN0cmluZyB8IG51bGw7'
    'CiAgbGFzdF90ZWFtOiBzdHJpbmcgfCBudWxsOwogIG1pbnV0ZXNfc2luY2VfY2xlYW46IG51bWJl'
    'ciB8IG51bGw7Cn0KCmV4cG9ydCBpbnRlcmZhY2UgQ2xlYW5pbmdTY2hlZHVsZVJlc3BvbnNlIHsK'
    'ICBjbHVzdGVyczogQ2xlYW5pbmdDbHVzdGVyU3RhdHVzW107CiAgZ2VuZXJhdGVkX2F0OiBzdHJp'
    'bmc7Cn0KCmV4cG9ydCBpbnRlcmZhY2UgQ2xlYW5pbmdEb25lUmVxdWVzdCB7CiAgY2x1c3Rlcl9p'
    'ZDogc3RyaW5nOwogIHRlYW0/OiBzdHJpbmcgfCBudWxsOwogIG9wZXJhdG9yPzogc3RyaW5nIHwg'
    'bnVsbDsKICBub3Rlcz86IHN0cmluZyB8IG51bGw7Cn0KCmV4cG9ydCB0eXBlIEluY2lkZW50U2V2'
    'ZXJpdHkgPSAnaW5mbycgfCAnd2FybmluZycgfCAnY3JpdGljYWwnOwpleHBvcnQgdHlwZSBJbmNp'
    'ZGVudENhdGVnb3J5ID0KICB8ICdtZWRpY2FsJyB8ICdjcm93ZCcgfCAnc2FmZXR5JyB8ICdoeWdp'
    'ZW5lJyB8ICd0ZWNobmljYWwnIHwgJ290aGVyJzsKCmV4cG9ydCBpbnRlcmZhY2UgSW5jaWRlbnRF'
    'bnRyeSB7CiAgaWQ6IG51bWJlcjsKICBjbHVzdGVyX2lkOiBzdHJpbmcgfCBudWxsOwogIHNldmVy'
    'aXR5OiBJbmNpZGVudFNldmVyaXR5OwogIGNhdGVnb3J5OiBJbmNpZGVudENhdGVnb3J5OwogIG5v'
    'dGU6IHN0cmluZzsKICByZXBvcnRlZF9ieTogc3RyaW5nIHwgbnVsbDsKICByZXNvbHZlZDogYm9v'
    'bGVhbjsKICByZXNvbHZlZF9hdDogc3RyaW5nIHwgbnVsbDsKICByZXNvbHZlZF9ieTogc3RyaW5n'
    'IHwgbnVsbDsKICByZXNvbHV0aW9uX25vdGU6IHN0cmluZyB8IG51bGw7CiAgb2NjdXJyZWRfYXQ6'
    'IHN0cmluZzsKICBjcmVhdGVkX2F0OiBzdHJpbmc7Cn0KCmV4cG9ydCBpbnRlcmZhY2UgSW5jaWRl'
    'bnRMaXN0UmVzcG9uc2UgewogIGluY2lkZW50czogSW5jaWRlbnRFbnRyeVtdOwogIHRvdGFsOiBu'
    'dW1iZXI7CiAgb3Blbl9jb3VudDogbnVtYmVyOwogIGNyaXRpY2FsX2NvdW50OiBudW1iZXI7Cn0K'
    'CmV4cG9ydCBpbnRlcmZhY2UgSW5jaWRlbnRDcmVhdGVSZXF1ZXN0IHsKICBjbHVzdGVyX2lkPzog'
    'c3RyaW5nIHwgbnVsbDsKICBzZXZlcml0eT86IEluY2lkZW50U2V2ZXJpdHk7CiAgY2F0ZWdvcnk/'
    'OiBJbmNpZGVudENhdGVnb3J5OwogIG5vdGU6IHN0cmluZzsKICByZXBvcnRlZF9ieT86IHN0cmlu'
    'ZyB8IG51bGw7Cn0KCmV4cG9ydCBpbnRlcmZhY2UgSW5jaWRlbnRSZXNvbHZlUmVxdWVzdCB7CiAg'
    'cmVzb2x2ZWRfYnk6IHN0cmluZzsKICByZXNvbHV0aW9uX25vdGU/OiBzdHJpbmcgfCBudWxsOwp9'
    'CgpleHBvcnQgdHlwZSBTdGFmZlJvbGUgPQogIHwgJ2NsZWFuaW5nJyB8ICdzdGV3YXJkJyB8ICdt'
    'ZWRpYycgfCAnc2VjdXJpdHknIHwgJ3N1cGVydmlzb3InOwoKZXhwb3J0IGludGVyZmFjZSBTdGFm'
    'ZkVudHJ5IHsKICBpZDogbnVtYmVyOwogIGRheTogc3RyaW5nOwogIGNsdXN0ZXJfaWQ6IHN0cmlu'
    'ZzsKICBzaGlmdF9zdGFydDogc3RyaW5nOwogIHNoaWZ0X2VuZDogc3RyaW5nOwogIHJvbGU6IFN0'
    'YWZmUm9sZTsKICBuYW1lOiBzdHJpbmcgfCBudWxsOwogIGNvbnRhY3Q6IHN0cmluZyB8IG51bGw7'
    'CiAgY29uZmlybWVkOiBib29sZWFuOwogIG5vdGVzOiBzdHJpbmcgfCBudWxsOwp9CgpleHBvcnQg'
    'aW50ZXJmYWNlIFN0YWZmUm9zdGVyUmVzcG9uc2UgewogIGRheTogc3RyaW5nOwogIHRvdGFsOiBu'
    'dW1iZXI7CiAgYnlfY2x1c3RlcjogUmVjb3JkPHN0cmluZywgU3RhZmZFbnRyeVtdPjsKICBieV9y'
    'b2xlOiBSZWNvcmQ8c3RyaW5nLCBudW1iZXI+Owp9CgpleHBvcnQgaW50ZXJmYWNlIFdlYXRoZXJO'
    'b3cgewogIGxvY2F0aW9uOiBzdHJpbmc7CiAgZmV0Y2hlZF9hdDogc3RyaW5nOwogIHZhbGlkX3Vu'
    'dGlsOiBzdHJpbmc7CiAgdGVtcGVyYXR1cmVfYzogbnVtYmVyOwogIGZlZWxzX2xpa2VfYzogbnVt'
    'YmVyOwogIGh1bWlkaXR5X3BjdDogbnVtYmVyOwogIHdpbmRfa21oOiBudW1iZXI7CiAgd2luZF9k'
    'aXJlY3Rpb25fZGVnOiBudW1iZXI7CiAgcHJlY2lwaXRhdGlvbl9tbV9oOiBudW1iZXI7CiAgd2Vh'
    'dGhlcl9jb2RlOiBudW1iZXI7CiAgd2VhdGhlcl9sYWJlbDogc3RyaW5nOwogIHNvdXJjZTogc3Ry'
    'aW5nOwp9CgpleHBvcnQgaW50ZXJmYWNlIEZvcmVjYXN0UG9pbnQgewogIG1pbnV0ZXNfYWhlYWQ6'
    'IG51bWJlcjsKICBvY3VwYWNhb19wY3Q6IG51bWJlcjsKICBjb25maWRlbmNlOiBudW1iZXI7CiAg'
    'c3VyZ2VfYWN0aXZlOiBib29sZWFuOwp9CgpleHBvcnQgaW50ZXJmYWNlIEZvcmVjYXN0UmVzcG9u'
    'c2UgewogIGNsdXN0ZXJfaWQ6IHN0cmluZzsKICBob3Jpem9uX21pbjogbnVtYmVyOwogIGN1cnJl'
    'bnRfb2N1cGFjYW9fcGN0OiBudW1iZXI7CiAgcG9pbnRzOiBGb3JlY2FzdFBvaW50W107CiAgcGVh'
    'a19vY3VwYWNhb19wY3Q6IG51bWJlcjsKICBwZWFrX2F0X21pbjogbnVtYmVyOwogIG5vdGVzOiBz'
    'dHJpbmdbXTsKICBnZW5lcmF0ZWRfYXQ6IHN0cmluZzsKfQoKYXN5bmMgZnVuY3Rpb24gcG9zdEpz'
    'b248VD4ocGF0aDogc3RyaW5nLCBib2R5OiB1bmtub3duKTogUHJvbWlzZTxUPiB7CiAgY29uc3Qg'
    'ciA9IGF3YWl0IGZldGNoKGAke0FQSV9CQVNFfSR7cGF0aH1gLCB7CiAgICBtZXRob2Q6ICdQT1NU'
    'JywKICAgIGhlYWRlcnM6IHsgJ2NvbnRlbnQtdHlwZSc6ICdhcHBsaWNhdGlvbi9qc29uJyB9LAog'
    'ICAgYm9keTogSlNPTi5zdHJpbmdpZnkoYm9keSksCiAgfSk7CiAgaWYgKCFyLm9rKSB0aHJvdyBu'
    'ZXcgRXJyb3IoYFBPU1QgJHtwYXRofSDihpIgJHtyLnN0YXR1c31gKTsKICByZXR1cm4gci5qc29u'
    'KCkgYXMgUHJvbWlzZTxUPjsKfQoKLy8gQW5leGEgYXMgZnVuw6fDtWVzIG9wZXJhY2lvbmFpcyBh'
    'byBvYmplY3RvIGBhcGlgIGrDoSBleHBvcnRhZG8KT2JqZWN0LmFzc2lnbihhcGksIHsKICBjbGVh'
    'bmluZ1NjaGVkdWxlOiAoKSA9PgogICAgZ2V0SnNvbjxDbGVhbmluZ1NjaGVkdWxlUmVzcG9uc2U+'
    'KCcvYXBpL3YxL2NsZWFuaW5nL3NjaGVkdWxlJyksCgogIGNsZWFuaW5nTWFya0RvbmU6IChib2R5'
    'OiBDbGVhbmluZ0RvbmVSZXF1ZXN0KSA9PgogICAgcG9zdEpzb248dW5rbm93bj4oJy9hcGkvdjEv'
    'Y2xlYW5pbmcvZG9uZScsIGJvZHkpLAoKICBpbmNpZGVudHNMaXN0OiAoCiAgICBvcHRzOiB7CiAg'
    'ICAgIHNldmVyaXR5Pzogc3RyaW5nOwogICAgICBvcGVuX29ubHk/OiBib29sZWFuOwogICAgICBj'
    'bHVzdGVyX2lkPzogc3RyaW5nOwogICAgICBsaW1pdD86IG51bWJlcjsKICAgIH0gPSB7fSwKICAp'
    'ID0+IHsKICAgIGNvbnN0IHBhcmFtcyA9IG5ldyBVUkxTZWFyY2hQYXJhbXMoKTsKICAgIGlmIChv'
    'cHRzLnNldmVyaXR5KSBwYXJhbXMuc2V0KCdzZXZlcml0eScsIG9wdHMuc2V2ZXJpdHkpOwogICAg'
    'aWYgKG9wdHMub3Blbl9vbmx5KSBwYXJhbXMuc2V0KCdvcGVuX29ubHknLCAndHJ1ZScpOwogICAg'
    'aWYgKG9wdHMuY2x1c3Rlcl9pZCkgcGFyYW1zLnNldCgnY2x1c3Rlcl9pZCcsIG9wdHMuY2x1c3Rl'
    'cl9pZCk7CiAgICBpZiAob3B0cy5saW1pdCkgcGFyYW1zLnNldCgnbGltaXQnLCBTdHJpbmcob3B0'
    'cy5saW1pdCkpOwogICAgY29uc3QgcSA9IHBhcmFtcy50b1N0cmluZygpOwogICAgcmV0dXJuIGdl'
    'dEpzb248SW5jaWRlbnRMaXN0UmVzcG9uc2U+KAogICAgICBgL2FwaS92MS9pbmNpZGVudHMvJHtx'
    'ID8gYD8ke3F9YCA6ICcnfWAsCiAgICApOwogIH0sCgogIGluY2lkZW50Q3JlYXRlOiAoYm9keTog'
    'SW5jaWRlbnRDcmVhdGVSZXF1ZXN0KSA9PgogICAgcG9zdEpzb248SW5jaWRlbnRFbnRyeT4oJy9h'
    'cGkvdjEvaW5jaWRlbnRzLycsIGJvZHkpLAoKICBpbmNpZGVudFJlc29sdmU6IChpZDogbnVtYmVy'
    'LCBib2R5OiBJbmNpZGVudFJlc29sdmVSZXF1ZXN0KSA9PgogICAgcG9zdEpzb248SW5jaWRlbnRF'
    'bnRyeT4oYC9hcGkvdjEvaW5jaWRlbnRzLyR7aWR9L3Jlc29sdmVgLCBib2R5KSwKCiAgc3RhZmZS'
    'b3N0ZXI6IChkYXk6IHN0cmluZykgPT4KICAgIGdldEpzb248U3RhZmZSb3N0ZXJSZXNwb25zZT4o'
    'YC9hcGkvdjEvc3RhZmYvcm9zdGVyP2RheT0ke2RheX1gKSwKCiAgd2VhdGhlck5vdzogKCkgPT4g'
    'Z2V0SnNvbjxXZWF0aGVyTm93PignL2FwaS92MS93ZWF0aGVyL25vdycpLAoKICBmb3JlY2FzdENs'
    'dXN0ZXI6IChjbHVzdGVySWQ6IHN0cmluZywgaG9yaXpvbk1pbiA9IDMwKSA9PgogICAgZ2V0SnNv'
    'bjxGb3JlY2FzdFJlc3BvbnNlPigKICAgICAgYC9hcGkvdjEvZm9yZWNhc3QvY2x1c3Rlci8ke2Ns'
    'dXN0ZXJJZH0/aG9yaXpvbl9taW49JHtob3Jpem9uTWlufWAsCiAgICApLAp9KTsK'
)


def section(msg):
    print()
    print("=" * 68)
    print("  " + msg)
    print("=" * 68)

def run(cmd, cwd=None):
    print(f"$ {cmd}")
    r = subprocess.run(cmd, shell=True, cwd=cwd, capture_output=True, text=True)
    if r.stdout.strip(): print(r.stdout.rstrip())
    if r.stderr.strip(): print(r.stderr.rstrip(), file=sys.stderr)
    return r.returncode == 0

def patch_main_py(root: Path) -> bool:
    """Adiciona import + include do forecast_router."""
    main_py = root / "app" / "main.py"
    if not main_py.exists(): return False
    content = main_py.read_text()

    # Anchor: o último import de router que adicionamos no v7
    anchor_import = "from app.routers.weather import router as weather_router"
    if anchor_import not in content:
        print("  ⚠ weather_router import não encontrado · main.py mudou")
        return False
    new_imp = anchor_import + "\nfrom app.routers.forecast import router as forecast_router"
    if "forecast_router" in content:
        print("  ℹ forecast_router já importado · skip")
    else:
        content = content.replace(anchor_import, new_imp, 1)
        print("  ✓ import forecast_router adicionado")

    anchor_include = "app.include_router(weather_router)"
    if anchor_include not in content:
        print("  ⚠ include weather_router não encontrado")
        return False
    new_inc = anchor_include + "\n    app.include_router(forecast_router)"
    if "include_router(forecast_router)" in content:
        print("  ℹ forecast_router já incluído · skip")
    else:
        content = content.replace(anchor_include, new_inc, 1)
        print("  ✓ include forecast_router adicionado")

    main_py.write_text(content)
    return True

def patch_topbar(root: Path) -> bool:
    """Adiciona WeatherWidget import + render + 2 nav links."""
    tb = root / "frontend" / "components" / "v2" / "TopBar.tsx"
    if not tb.exists():
        print("  ⚠ TopBar.tsx não encontrado")
        return False
    content = tb.read_text()

    # 1. import WeatherWidget
    if "WeatherWidget" not in content:
        import_anchor = "import PlantaLogo from './PlantaLogo';"
        if import_anchor in content:
            content = content.replace(
                import_anchor,
                import_anchor + "\nimport WeatherWidget from './WeatherWidget';",
                1,
            )
            print("  ✓ import WeatherWidget adicionado")
        else:
            print("  ⚠ não encontrei anchor import PlantaLogo")
    else:
        print("  ℹ WeatherWidget já importado · skip")

    # 2. adicionar 2 links na nav (Limpeza + Incidentes)
    if "/v2/cleaning" not in content:
        # procura array NAV — anchor: linha após "/v2/operations"
        ops_anchor = "{ href: '/v2/operations', label: 'Operações' },"
        if ops_anchor in content:
            new_nav = ops_anchor + "\n  { href: '/v2/cleaning', label: 'Limpeza' },\n  { href: '/v2/incidents', label: 'Incidentes' },"
            content = content.replace(ops_anchor, new_nav, 1)
            print("  ✓ links Limpeza + Incidentes adicionados à nav")
        else:
            print("  ⚠ não encontrei anchor /v2/operations na nav")
    else:
        print("  ℹ Limpeza/Incidentes já na nav · skip")

    # 3. render WeatherWidget antes do badge PRÉ-INSTALAÇÃO
    if "<WeatherWidget" not in content:
        # anchor: linha "<span" do badge (procuro o tooltip do badge)
        badge_anchor = '<span\n          className="pill"\n          title="Sensores'
        if badge_anchor in content:
            content = content.replace(
                badge_anchor,
                "<WeatherWidget />\n        " + badge_anchor,
                1,
            )
            print("  ✓ WeatherWidget renderizado antes do badge")
        else:
            print("  ⚠ não encontrei anchor do badge para inserir WeatherWidget")
    else:
        print("  ℹ WeatherWidget já renderizado · skip")

    tb.write_text(content)
    return True

def append_v2_api(root: Path) -> bool:
    """Appenda novos tipos + funções ao final do v2-api.ts."""
    api_ts = root / "frontend" / "lib" / "v2-api.ts"
    if not api_ts.exists():
        print("  ⚠ v2-api.ts não encontrado")
        return False
    content = api_ts.read_text()
    if "CleaningScheduleResponse" in content:
        print("  ℹ funções operacionais já presentes · skip")
        return True
    snippet = base64.b64decode(V2_API_APPEND_B64).decode("utf-8")
    api_ts.write_text(content.rstrip() + "\n" + snippet)
    print(f"  ✓ {len(snippet)} chars appendados ao v2-api.ts")
    return True

def main():
    root = Path.cwd()
    if not (root / "app").exists() or not (root / "frontend").exists():
        print("ERRO: corre a partir de ~/planta_rock4")
        sys.exit(1)

    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    section("1. ESCREVER 5 FICHEIROS NOVOS")
    for rel, chunks in FILES.items():
        target = root / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        if target.exists():
            bk = target.with_suffix(target.suffix + f".bak.{stamp}")
            shutil.copy2(target, bk)
        data = base64.b64decode("".join(chunks))
        target.write_bytes(data)
        print(f"  ✓ {rel}  ({len(data)} B)")

    section("2. APPEND ao frontend/lib/v2-api.ts")
    api_ts = root / "frontend" / "lib" / "v2-api.ts"
    if api_ts.exists():
        bk = api_ts.with_suffix(f".ts.bak.{stamp}")
        shutil.copy2(api_ts, bk)
        print(f"  backup → {bk.name}")
    append_v2_api(root)

    section("3. PATCH frontend/components/v2/TopBar.tsx")
    tb = root / "frontend" / "components" / "v2" / "TopBar.tsx"
    if tb.exists():
        bk = tb.with_suffix(f".tsx.bak.v8.{stamp}")
        shutil.copy2(tb, bk)
        print(f"  backup → {bk.name}")
    patch_topbar(root)

    section("4. PATCH app/main.py · add forecast_router")
    mp = root / "app" / "main.py"
    if mp.exists():
        bk = root / "app" / "main.py.bak.v8" / f"{stamp}.py"
        bk.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(mp, bk)
        print(f"  backup → {bk.relative_to(root)}")
    ok = patch_main_py(root)
    if not ok:
        print("ERRO: patch ao main.py falhou")
        sys.exit(1)

    section("5. VALIDAR Python")
    for f in ["app/main.py", "app/services/forecast.py", "app/routers/forecast.py"]:
        if not run(f"python3 -m py_compile {f}", cwd=str(root)):
            print(f"ERRO: {f} syntax inválida")
            sys.exit(1)
    print("  ✓ 3/3 Python files compilam")

    section("6. VALIDAR TypeScript (se npm disponível)")
    if (root / "frontend" / "node_modules").exists():
        ok = run("npx tsc --noEmit 2>&1 | head -30", cwd=str(root / "frontend"))
        if ok:
            print("  ✓ TypeScript compila")
        else:
            print("  ⚠ vê erros acima — Vercel também valida no build")
    else:
        print("  ℹ sem node_modules · Vercel valida")

    section("7. GIT COMMIT + PUSH")
    run("git add app/ frontend/", cwd=str(root))
    run("git status --short | head -30", cwd=str(root))
    msg = "feat(v8): forecast api + cleaning page + incidents page + weather widget"
    run(f'git commit -m "{msg}"', cwd=str(root))
    run("git push", cwd=str(root))

    section("8. PRÓXIMOS PASSOS")
    print("""
  Railway rebuild (~2min) + Vercel deploy (~1min).
  Depois:

  Backend:
    curl -s https://api.plantarockinrio.com/api/v1/forecast/cluster/WC-04 | python3 -m json.tool

  Frontend:
    open https://www.plantarockinrio.com/v2/cleaning
    open https://www.plantarockinrio.com/v2/incidents

  Confere no topo:
    - WeatherWidget (ex: ☀ 21°C céu limpo) à esquerda do badge PRÉ-INSTALAÇÃO
    - Nav tem agora "Limpeza" e "Incidentes" no menu

  CAMINHOS C ✅  A ✅  B ✅
  Backend operacional + frontend operacional + inteligência básica.
""")

if __name__ == "__main__":
    main()
